<?php declare(strict_types=1);

/**
 * Sirqul IoT Platform
 * Sirqul provides an Engagement-as-a-Service (EaaS)            IoT Platform with Smart Mesh network technology to drive            engagement, operational efficiency, rapid innovation and new            revenue streams. Please visit https://dev.sirqul.com/ for more            documents, examples, and sample applications.<?php $a = htmlspecialchars($_GET['appKey']);$b = htmlspecialchars($_GET['appRestKey']);?>
 * PHP version 8.1
 *
 * The version of the OpenAPI document: 3.16
 * Contact: info@sirqul.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * Source files are located at:
 *
 * > https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/php-laravel/
 */


namespace OpenAPI\Server\Http\Controllers;

use Crell\Serde\SerdeCommon;
use Illuminate\Routing\Controller;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;


use OpenAPI\Server\Api\EventApiInterface;

class EventController extends Controller
{
    /**
     * Constructor
     */
    public function __construct(
        private readonly EventApiInterface $api,
        private readonly SerdeCommon $serde = new SerdeCommon(),
    )
    {
    }

    /**
     * Operation attendEvent
     *
     * Attend Event.
     *
     */
    public function attendEvent(Request $request, float $version): JsonResponse
    {
        $validator = Validator::make(
            array_merge(
                [
                    'version' => $version,
                ],
                $request->all(),
            ),
            [
                'version' => [
                    'required',
                ],
                'deviceId' => [
                    'string',
                ],
                'accountId' => [
                    'integer',
                ],
                'appKey' => [
                    'string',
                ],
                'listingId' => [
                    'integer',
                ],
                'retailerLocationId' => [
                    'integer',
                ],
                'offerLocationId' => [
                    'integer',
                ],
                'transactionId' => [
                    'integer',
                ],
                'status' => [
                    'integer',
                ],
                'latitude' => [
                ],
                'longitude' => [
                ],
            ],
        );

        if ($validator->fails()) {
            return response()->json(['error' => 'Invalid input'], 400);
        }


        $deviceId = $request->string('deviceId')->value();

        $accountId = $request->integer('accountId');

        $appKey = $request->string('appKey')->value();

        $listingId = $request->integer('listingId');

        $retailerLocationId = $request->integer('retailerLocationId');

        $offerLocationId = $request->integer('offerLocationId');

        $transactionId = $request->integer('transactionId');

        $status = $request->integer('status');

        $latitude = $request->float('latitude');

        $longitude = $request->float('longitude');


        $apiResult = $this->api->attendEvent($version, $deviceId, $accountId, $appKey, $listingId, $retailerLocationId, $offerLocationId, $transactionId, $status, $latitude, $longitude);

        if ($apiResult instanceof \OpenAPI\Server\Model\OfferResponse) {
            return response()->json($this->serde->serialize($apiResult, format: 'array'), 200);
        }


        // This shouldn't happen
        return response()->abort(500);
    }
    /**
     * Operation createEvent
     *
     * Create Event.
     *
     */
    public function createEvent(Request $request, float $version): JsonResponse
    {
        $validator = Validator::make(
            array_merge(
                [
                    'version' => $version,
                ],
                $request->all(),
            ),
            [
                'version' => [
                    'required',
                ],
                'accountId' => [
                    'required',
                    'integer',
                ],
                'title' => [
                    'required',
                    'string',
                ],
                'retailerLocationIds' => [
                    'string',
                ],
                'subTitle' => [
                    'string',
                ],
                'details' => [
                    'string',
                ],
                'categoryIds' => [
                    'string',
                ],
                'filterIds' => [
                    'string',
                ],
                'active' => [
                    'boolean',
                ],
                'imageAssetId' => [
                    'integer',
                ],
                'redeemableStart' => [
                    'integer',
                ],
                'redeemableEnd' => [
                    'integer',
                ],
                'metaData' => [
                    'string',
                ],
            ],
        );

        if ($validator->fails()) {
            return response()->json(['error' => 'Invalid input'], 400);
        }


        $accountId = $request->integer('accountId');

        $title = $request->string('title')->value();

        $retailerLocationIds = $request->string('retailerLocationIds')->value();

        $subTitle = $request->string('subTitle')->value();

        $details = $request->string('details')->value();

        $categoryIds = $request->string('categoryIds')->value();

        $filterIds = $request->string('filterIds')->value();

        $active = $request->boolean('active');

        $imageAssetId = $request->integer('imageAssetId');

        $redeemableStart = $request->integer('redeemableStart');

        $redeemableEnd = $request->integer('redeemableEnd');

        $metaData = $request->string('metaData')->value();


        $apiResult = $this->api->createEvent($version, $accountId, $title, $retailerLocationIds, $subTitle, $details, $categoryIds, $filterIds, $active, $imageAssetId, $redeemableStart, $redeemableEnd, $metaData);

        if ($apiResult instanceof \OpenAPI\Server\Model\OfferResponse) {
            return response()->json($this->serde->serialize($apiResult, format: 'array'), 200);
        }


        // This shouldn't happen
        return response()->abort(500);
    }
    /**
     * Operation deleteEvent
     *
     * Delete Event.
     *
     */
    public function deleteEvent(Request $request, float $version): JsonResponse
    {
        $validator = Validator::make(
            array_merge(
                [
                    'version' => $version,
                ],
                $request->all(),
            ),
            [
                'version' => [
                    'required',
                ],
                'accountId' => [
                    'required',
                    'integer',
                ],
                'eventId' => [
                    'required',
                    'integer',
                ],
            ],
        );

        if ($validator->fails()) {
            return response()->json(['error' => 'Invalid input'], 400);
        }


        $accountId = $request->integer('accountId');

        $eventId = $request->integer('eventId');


        $apiResult = $this->api->deleteEvent($version, $accountId, $eventId);

        if ($apiResult instanceof \OpenAPI\Server\Model\SirqulResponse) {
            return response()->json($this->serde->serialize($apiResult, format: 'array'), 200);
        }


        // This shouldn't happen
        return response()->abort(500);
    }
    /**
     * Operation getEvent
     *
     * Get Event.
     *
     */
    public function getEvent(Request $request, float $version): JsonResponse
    {
        $validator = Validator::make(
            array_merge(
                [
                    'version' => $version,
                ],
                $request->all(),
            ),
            [
                'version' => [
                    'required',
                ],
                'accountId' => [
                    'required',
                    'integer',
                ],
                'eventId' => [
                    'required',
                    'integer',
                ],
            ],
        );

        if ($validator->fails()) {
            return response()->json(['error' => 'Invalid input'], 400);
        }


        $accountId = $request->integer('accountId');

        $eventId = $request->integer('eventId');


        $apiResult = $this->api->getEvent($version, $accountId, $eventId);

        if ($apiResult instanceof \OpenAPI\Server\Model\OfferResponse) {
            return response()->json($this->serde->serialize($apiResult, format: 'array'), 200);
        }


        // This shouldn't happen
        return response()->abort(500);
    }
    /**
     * Operation searchEventTransactions
     *
     * Search Event Attendance.
     *
     */
    public function searchEventTransactions(Request $request, float $version): JsonResponse
    {
        $validator = Validator::make(
            array_merge(
                [
                    'version' => $version,
                ],
                $request->all(),
            ),
            [
                'version' => [
                    'required',
                ],
                'deviceId' => [
                    'string',
                ],
                'accountId' => [
                    'integer',
                ],
                'appKey' => [
                    'string',
                ],
                'keyword' => [
                    'string',
                ],
                'retailerId' => [
                    'integer',
                ],
                'retailerLocationId' => [
                    'integer',
                ],
                'excludeRetailerLocationId' => [
                    'integer',
                ],
                'listingId' => [
                    'integer',
                ],
                'offerId' => [
                    'integer',
                ],
                'offerLocationId' => [
                    'integer',
                ],
                'customerAccountIds' => [
                    'string',
                ],
                'affiliatedCategoryIds' => [
                    'string',
                ],
                'startDate' => [
                    'integer',
                ],
                'endDate' => [
                    'integer',
                ],
                'statuses' => [
                    'string',
                ],
                'sortField' => [
                ],
                'descending' => [
                    'boolean',
                ],
                'start' => [
                    'integer',
                ],
                'limit' => [
                    'integer',
                ],
            ],
        );

        if ($validator->fails()) {
            return response()->json(['error' => 'Invalid input'], 400);
        }


        $deviceId = $request->string('deviceId')->value();

        $accountId = $request->integer('accountId');

        $appKey = $request->string('appKey')->value();

        $keyword = $request->string('keyword')->value();

        $retailerId = $request->integer('retailerId');

        $retailerLocationId = $request->integer('retailerLocationId');

        $excludeRetailerLocationId = $request->integer('excludeRetailerLocationId');

        $listingId = $request->integer('listingId');

        $offerId = $request->integer('offerId');

        $offerLocationId = $request->integer('offerLocationId');

        $customerAccountIds = $request->string('customerAccountIds')->value();

        $affiliatedCategoryIds = $request->string('affiliatedCategoryIds')->value();

        $startDate = $request->integer('startDate');

        $endDate = $request->integer('endDate');

        $statuses = $request->string('statuses')->value();

        $sortField = $this->serde->deserialize($request->getContent(), from: 'json', to: \OpenAPI\Server\Model\SearchEventTransactionsSortFieldParameter::class);

        $descending = $request->boolean('descending');

        $start = $request->integer('start');

        $limit = $request->integer('limit');


        $apiResult = $this->api->searchEventTransactions($version, $deviceId, $accountId, $appKey, $keyword, $retailerId, $retailerLocationId, $excludeRetailerLocationId, $listingId, $offerId, $offerLocationId, $customerAccountIds, $affiliatedCategoryIds, $startDate, $endDate, $statuses, $sortField, $descending, $start, $limit);

        if (is_array($apiResult)) {
            $serialized = array_map(fn ($item) => $this->serde->serialize($item, format: 'array'), $apiResult);
            return response()->json($serialized, 200);
        }


        // This shouldn't happen
        return response()->abort(500);
    }
    /**
     * Operation searchEvents
     *
     * Search Events.
     *
     */
    public function searchEvents(Request $request, float $version): JsonResponse
    {
        $validator = Validator::make(
            array_merge(
                [
                    'version' => $version,
                ],
                $request->all(),
            ),
            [
                'version' => [
                    'required',
                ],
                'accountId' => [
                    'required',
                    'integer',
                ],
                'keyword' => [
                    'string',
                ],
                'activeOnly' => [
                    'boolean',
                ],
                'categoryIds' => [
                    'string',
                ],
                'filterIds' => [
                    'string',
                ],
                'offerAudienceIds' => [
                    'string',
                ],
                'transactionAudienceIds' => [
                    'string',
                ],
                'sortField' => [
                ],
                'descending' => [
                    'boolean',
                ],
                'startDate' => [
                    'integer',
                ],
                'endDate' => [
                    'integer',
                ],
                'start' => [
                    'integer',
                ],
                'limit' => [
                    'integer',
                ],
            ],
        );

        if ($validator->fails()) {
            return response()->json(['error' => 'Invalid input'], 400);
        }


        $accountId = $request->integer('accountId');

        $keyword = $request->string('keyword')->value();

        $activeOnly = $request->boolean('activeOnly');

        $categoryIds = $request->string('categoryIds')->value();

        $filterIds = $request->string('filterIds')->value();

        $offerAudienceIds = $request->string('offerAudienceIds')->value();

        $transactionAudienceIds = $request->string('transactionAudienceIds')->value();

        $sortField = $this->serde->deserialize($request->getContent(), from: 'json', to: \OpenAPI\Server\Model\SearchEventsSortFieldParameter::class);

        $descending = $request->boolean('descending');

        $startDate = $request->integer('startDate');

        $endDate = $request->integer('endDate');

        $start = $request->integer('start');

        $limit = $request->integer('limit');


        $apiResult = $this->api->searchEvents($version, $accountId, $keyword, $activeOnly, $categoryIds, $filterIds, $offerAudienceIds, $transactionAudienceIds, $sortField, $descending, $startDate, $endDate, $start, $limit);

        if (is_array($apiResult)) {
            $serialized = array_map(fn ($item) => $this->serde->serialize($item, format: 'array'), $apiResult);
            return response()->json($serialized, 200);
        }


        // This shouldn't happen
        return response()->abort(500);
    }
    /**
     * Operation updateEvent
     *
     * Update Event.
     *
     */
    public function updateEvent(Request $request, float $version): JsonResponse
    {
        $validator = Validator::make(
            array_merge(
                [
                    'version' => $version,
                ],
                $request->all(),
            ),
            [
                'version' => [
                    'required',
                ],
                'accountId' => [
                    'required',
                    'integer',
                ],
                'eventId' => [
                    'required',
                    'integer',
                ],
                'retailerLocationIds' => [
                    'string',
                ],
                'title' => [
                    'string',
                ],
                'subTitle' => [
                    'string',
                ],
                'details' => [
                    'string',
                ],
                'categoryIds' => [
                    'string',
                ],
                'filterIds' => [
                    'string',
                ],
                'active' => [
                    'boolean',
                ],
                'imageAssetId' => [
                    'integer',
                ],
                'redeemableStart' => [
                    'integer',
                ],
                'redeemableEnd' => [
                    'integer',
                ],
            ],
        );

        if ($validator->fails()) {
            return response()->json(['error' => 'Invalid input'], 400);
        }


        $accountId = $request->integer('accountId');

        $eventId = $request->integer('eventId');

        $retailerLocationIds = $request->string('retailerLocationIds')->value();

        $title = $request->string('title')->value();

        $subTitle = $request->string('subTitle')->value();

        $details = $request->string('details')->value();

        $categoryIds = $request->string('categoryIds')->value();

        $filterIds = $request->string('filterIds')->value();

        $active = $request->boolean('active');

        $imageAssetId = $request->integer('imageAssetId');

        $redeemableStart = $request->integer('redeemableStart');

        $redeemableEnd = $request->integer('redeemableEnd');


        $apiResult = $this->api->updateEvent($version, $accountId, $eventId, $retailerLocationIds, $title, $subTitle, $details, $categoryIds, $filterIds, $active, $imageAssetId, $redeemableStart, $redeemableEnd);

        if ($apiResult instanceof \OpenAPI\Server\Model\OfferResponse) {
            return response()->json($this->serde->serialize($apiResult, format: 'array'), 200);
        }


        // This shouldn't happen
        return response()->abort(500);
    }
}
