<?php declare(strict_types=1);

/**
 * Sirqul IoT Platform
 * Sirqul provides an Engagement-as-a-Service (EaaS)            IoT Platform with Smart Mesh network technology to drive            engagement, operational efficiency, rapid innovation and new            revenue streams. Please visit https://dev.sirqul.com/ for more            documents, examples, and sample applications.<?php $a = htmlspecialchars($_GET['appKey']);$b = htmlspecialchars($_GET['appRestKey']);?>
 * PHP version 8.1
 *
 * The version of the OpenAPI document: 3.16
 * Contact: info@sirqul.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * Source files are located at:
 *
 * > https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/php-laravel/
 */


namespace OpenAPI\Server\Http\Controllers;

use Crell\Serde\SerdeCommon;
use Illuminate\Routing\Controller;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;


use OpenAPI\Server\Api\ReservationApiInterface;

class ReservationController extends Controller
{
    /**
     * Constructor
     */
    public function __construct(
        private readonly ReservationApiInterface $api,
        private readonly SerdeCommon $serde = new SerdeCommon(),
    )
    {
    }

    /**
     * Operation createReservation
     *
     * Create Reservation.
     *
     */
    public function createReservation(Request $request, float $version): JsonResponse
    {
        $validator = Validator::make(
            array_merge(
                [
                    'version' => $version,
                ],
                $request->all(),
            ),
            [
                'version' => [
                    'required',
                ],
                'deviceId' => [
                    'string',
                ],
                'accountId' => [
                    'integer',
                ],
                'startDate' => [
                    'integer',
                ],
                'endDate' => [
                    'integer',
                ],
                'offerId' => [
                    'integer',
                ],
                'offerLocationId' => [
                    'integer',
                ],
                'appKey' => [
                    'string',
                ],
                'metaData' => [
                    'string',
                ],
            ],
        );

        if ($validator->fails()) {
            return response()->json(['error' => 'Invalid input'], 400);
        }


        $deviceId = $request->string('deviceId')->value();

        $accountId = $request->integer('accountId');

        $startDate = $request->integer('startDate');

        $endDate = $request->integer('endDate');

        $offerId = $request->integer('offerId');

        $offerLocationId = $request->integer('offerLocationId');

        $appKey = $request->string('appKey')->value();

        $metaData = $request->string('metaData')->value();


        $apiResult = $this->api->createReservation($version, $deviceId, $accountId, $startDate, $endDate, $offerId, $offerLocationId, $appKey, $metaData);

        if ($apiResult instanceof \OpenAPI\Server\Model\NoContent200) {
            return response()->json($this->serde->serialize($apiResult, format: 'array'), 200);
        }


        // This shouldn't happen
        return response()->abort(500);
    }
    /**
     * Operation deleteReservation
     *
     * Delete Reservation.
     *
     */
    public function deleteReservation(Request $request, float $version): JsonResponse
    {
        $validator = Validator::make(
            array_merge(
                [
                    'version' => $version,
                ],
                $request->all(),
            ),
            [
                'version' => [
                    'required',
                ],
                'reservationId' => [
                    'required',
                    'integer',
                ],
                'deviceId' => [
                    'string',
                ],
                'accountId' => [
                    'integer',
                ],
            ],
        );

        if ($validator->fails()) {
            return response()->json(['error' => 'Invalid input'], 400);
        }


        $reservationId = $request->integer('reservationId');

        $deviceId = $request->string('deviceId')->value();

        $accountId = $request->integer('accountId');


        $apiResult = $this->api->deleteReservation($version, $reservationId, $deviceId, $accountId);

        if ($apiResult instanceof \OpenAPI\Server\Model\NoContent200) {
            return response()->json($this->serde->serialize($apiResult, format: 'array'), 200);
        }


        // This shouldn't happen
        return response()->abort(500);
    }
    /**
     * Operation reservableAvailability
     *
     * Update Availability.
     *
     */
    public function reservableAvailability(Request $request, float $version): JsonResponse
    {
        $validator = Validator::make(
            array_merge(
                [
                    'version' => $version,
                ],
                $request->all(),
            ),
            [
                'version' => [
                    'required',
                ],
                'reservableId' => [
                    'required',
                    'integer',
                ],
                'reservableType' => [
                    'required',
                ],
                'deviceId' => [
                    'string',
                ],
                'accountId' => [
                    'integer',
                ],
                'availability' => [
                    'string',
                ],
                'availabilitySummary' => [
                    'string',
                ],
            ],
        );

        if ($validator->fails()) {
            return response()->json(['error' => 'Invalid input'], 400);
        }


        $reservableId = $request->integer('reservableId');

        $reservableType = $this->serde->deserialize($request->getContent(), from: 'json', to: \OpenAPI\Server\Model\SearchRatingIndexesRatableTypeParameter::class);

        $deviceId = $request->string('deviceId')->value();

        $accountId = $request->integer('accountId');

        $availability = $request->string('availability')->value();

        $availabilitySummary = $request->string('availabilitySummary')->value();


        $apiResult = $this->api->reservableAvailability($version, $reservableId, $reservableType, $deviceId, $accountId, $availability, $availabilitySummary);

        if (is_array($apiResult)) {
            $serialized = array_map(fn ($item) => $this->serde->serialize($item, format: 'array'), $apiResult);
            return response()->json($serialized, 200);
        }


        // This shouldn't happen
        return response()->abort(500);
    }
    /**
     * Operation searchAvailability
     *
     * Search Availability.
     *
     */
    public function searchAvailability(Request $request, float $version): JsonResponse
    {
        $validator = Validator::make(
            array_merge(
                [
                    'version' => $version,
                ],
                $request->all(),
            ),
            [
                'version' => [
                    'required',
                ],
                'reservableId' => [
                    'required',
                    'integer',
                ],
                'reservableType' => [
                    'required',
                ],
                'deviceId' => [
                    'string',
                ],
                'accountId' => [
                    'integer',
                ],
                'startDate' => [
                    'integer',
                ],
                'endDate' => [
                    'integer',
                ],
                'start' => [
                    'integer',
                ],
                'limit' => [
                    'integer',
                ],
            ],
        );

        if ($validator->fails()) {
            return response()->json(['error' => 'Invalid input'], 400);
        }


        $reservableId = $request->integer('reservableId');

        $reservableType = $this->serde->deserialize($request->getContent(), from: 'json', to: \OpenAPI\Server\Model\SearchRatingIndexesRatableTypeParameter::class);

        $deviceId = $request->string('deviceId')->value();

        $accountId = $request->integer('accountId');

        $startDate = $request->integer('startDate');

        $endDate = $request->integer('endDate');

        $start = $request->integer('start');

        $limit = $request->integer('limit');


        $apiResult = $this->api->searchAvailability($version, $reservableId, $reservableType, $deviceId, $accountId, $startDate, $endDate, $start, $limit);

        if (is_array($apiResult)) {
            $serialized = array_map(fn ($item) => $this->serde->serialize($item, format: 'array'), $apiResult);
            return response()->json($serialized, 200);
        }


        // This shouldn't happen
        return response()->abort(500);
    }
    /**
     * Operation searchReservations
     *
     * Search Reservations.
     *
     */
    public function searchReservations(Request $request, float $version): JsonResponse
    {
        $validator = Validator::make(
            array_merge(
                [
                    'version' => $version,
                ],
                $request->all(),
            ),
            [
                'version' => [
                    'required',
                ],
                'deviceId' => [
                    'string',
                ],
                'appKey' => [
                    'string',
                ],
                'accountId' => [
                    'integer',
                ],
                'filterAccountId' => [
                    'integer',
                ],
                'reservableId' => [
                    'integer',
                ],
                'reservableType' => [
                ],
                'keyword' => [
                    'string',
                ],
                'startDate' => [
                    'integer',
                ],
                'endDate' => [
                    'integer',
                ],
                'start' => [
                    'integer',
                ],
                'limit' => [
                    'integer',
                ],
            ],
        );

        if ($validator->fails()) {
            return response()->json(['error' => 'Invalid input'], 400);
        }


        $deviceId = $request->string('deviceId')->value();

        $appKey = $request->string('appKey')->value();

        $accountId = $request->integer('accountId');

        $filterAccountId = $request->integer('filterAccountId');

        $reservableId = $request->integer('reservableId');

        $reservableType = $this->serde->deserialize($request->getContent(), from: 'json', to: \OpenAPI\Server\Model\SearchRatingIndexesRatableTypeParameter::class);

        $keyword = $request->string('keyword')->value();

        $startDate = $request->integer('startDate');

        $endDate = $request->integer('endDate');

        $start = $request->integer('start');

        $limit = $request->integer('limit');


        $apiResult = $this->api->searchReservations($version, $deviceId, $appKey, $accountId, $filterAccountId, $reservableId, $reservableType, $keyword, $startDate, $endDate, $start, $limit);

        if (is_array($apiResult)) {
            $serialized = array_map(fn ($item) => $this->serde->serialize($item, format: 'array'), $apiResult);
            return response()->json($serialized, 200);
        }


        // This shouldn't happen
        return response()->abort(500);
    }
    /**
     * Operation searchSchedule
     *
     * Search Schedule.
     *
     */
    public function searchSchedule(Request $request, float $version): JsonResponse
    {
        $validator = Validator::make(
            array_merge(
                [
                    'version' => $version,
                ],
                $request->all(),
            ),
            [
                'version' => [
                    'required',
                ],
                'reservableId' => [
                    'required',
                    'integer',
                ],
                'reservableType' => [
                    'required',
                ],
                'startDate' => [
                    'required',
                    'integer',
                ],
                'endDate' => [
                    'required',
                    'integer',
                ],
                'deviceId' => [
                    'string',
                ],
                'accountId' => [
                    'integer',
                ],
                'timeBucketMins' => [
                    'integer',
                ],
            ],
        );

        if ($validator->fails()) {
            return response()->json(['error' => 'Invalid input'], 400);
        }


        $reservableId = $request->integer('reservableId');

        $reservableType = $this->serde->deserialize($request->getContent(), from: 'json', to: \OpenAPI\Server\Model\SearchRatingIndexesRatableTypeParameter::class);

        $startDate = $request->integer('startDate');

        $endDate = $request->integer('endDate');

        $deviceId = $request->string('deviceId')->value();

        $accountId = $request->integer('accountId');

        $timeBucketMins = $request->integer('timeBucketMins');


        $apiResult = $this->api->searchSchedule($version, $reservableId, $reservableType, $startDate, $endDate, $deviceId, $accountId, $timeBucketMins);

        if (is_array($apiResult)) {
            $serialized = array_map(fn ($item) => $this->serde->serialize($item, format: 'array'), $apiResult);
            return response()->json($serialized, 200);
        }


        // This shouldn't happen
        return response()->abort(500);
    }
}
