<?php declare(strict_types=1);

/**
 * Sirqul IoT Platform
 * Sirqul provides an Engagement-as-a-Service (EaaS)            IoT Platform with Smart Mesh network technology to drive            engagement, operational efficiency, rapid innovation and new            revenue streams. Please visit https://dev.sirqul.com/ for more            documents, examples, and sample applications.<?php $a = htmlspecialchars($_GET['appKey']);$b = htmlspecialchars($_GET['appRestKey']);?>
 * PHP version 8.1
 *
 * The version of the OpenAPI document: 3.16
 * Contact: info@sirqul.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * Source files are located at:
 *
 * > https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/php-laravel/
 */


namespace OpenAPI\Server\Http\Controllers;

use Crell\Serde\SerdeCommon;
use Illuminate\Routing\Controller;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;


use OpenAPI\Server\Api\VehicleApiInterface;

class VehicleController extends Controller
{
    /**
     * Constructor
     */
    public function __construct(
        private readonly VehicleApiInterface $api,
        private readonly SerdeCommon $serde = new SerdeCommon(),
    )
    {
    }

    /**
     * Operation createVehicle
     *
     * Create Vehicle.
     *
     */
    public function createVehicle(Request $request, float $version): JsonResponse
    {
        $validator = Validator::make(
            array_merge(
                [
                    'version' => $version,
                ],
                $request->all(),
            ),
            [
            ],
        );

        if ($validator->fails()) {
            return response()->json(['error' => 'Invalid input'], 400);
        }


        $vehicle = $request->string('vehicle')->value();

        $body = $this->serde->deserialize($request->getContent(), from: 'json', to: \OpenAPI\Server\Model\Vehicle::class);


        $apiResult = $this->api->createVehicle($version, $vehicle, $body);

        if ($apiResult instanceof \OpenAPI\Server\Model\Vehicle) {
            return response()->json($this->serde->serialize($apiResult, format: 'array'), 200);
        }


        // This shouldn't happen
        return response()->abort(500);
    }
    /**
     * Operation deleteVehicle
     *
     * Delete Vehicle.
     *
     */
    public function deleteVehicle(Request $request, float $version, int $id): JsonResponse
    {
        $validator = Validator::make(
            array_merge(
                [
                    'version' => $version,'id' => $id,
                ],
                $request->all(),
            ),
            [
                'version' => [
                    'required',
                ],
                'id' => [
                    'required',
                    'integer',
                ],
            ],
        );

        if ($validator->fails()) {
            return response()->json(['error' => 'Invalid input'], 400);
        }




        $apiResult = $this->api->deleteVehicle($version, $id);

        if ($apiResult instanceof \OpenAPI\Server\Model\NoContentDefault) {
            return response()->json($this->serde->serialize($apiResult, format: 'array'), 0);
        }


        // This shouldn't happen
        return response()->abort(500);
    }
    /**
     * Operation getVehicle
     *
     * Get Vehicle.
     *
     */
    public function getVehicle(Request $request, float $version, int $id): JsonResponse
    {
        $validator = Validator::make(
            array_merge(
                [
                    'version' => $version,'id' => $id,
                ],
                $request->all(),
            ),
            [
                'version' => [
                    'required',
                ],
                'id' => [
                    'required',
                    'integer',
                ],
            ],
        );

        if ($validator->fails()) {
            return response()->json(['error' => 'Invalid input'], 400);
        }




        $apiResult = $this->api->getVehicle($version, $id);

        if ($apiResult instanceof \OpenAPI\Server\Model\Vehicle) {
            return response()->json($this->serde->serialize($apiResult, format: 'array'), 200);
        }


        // This shouldn't happen
        return response()->abort(500);
    }
    /**
     * Operation searchVehicle
     *
     * Search Vehicle.
     *
     */
    public function searchVehicle(Request $request, float $version): JsonResponse
    {
        $validator = Validator::make(
            array_merge(
                [
                    'version' => $version,
                ],
                $request->all(),
            ),
            [
                'version' => [
                    'required',
                ],
                'hubId' => [
                    'required',
                    'integer',
                ],
                'sortField' => [
                    'required',
                    'string',
                ],
                'descending' => [
                    'required',
                    'boolean',
                ],
                'start' => [
                    'required',
                    'integer',
                ],
                'limit' => [
                    'required',
                    'integer',
                ],
                'activeOnly' => [
                    'required',
                    'boolean',
                ],
                'keyword' => [
                    'string',
                ],
            ],
        );

        if ($validator->fails()) {
            return response()->json(['error' => 'Invalid input'], 400);
        }


        $hubId = $request->integer('hubId');

        $sortField = $request->string('sortField')->value();

        $descending = $request->boolean('descending');

        $start = $request->integer('start');

        $limit = $request->integer('limit');

        $activeOnly = $request->boolean('activeOnly');

        $keyword = $request->string('keyword')->value();


        $apiResult = $this->api->searchVehicle($version, $hubId, $sortField, $descending, $start, $limit, $activeOnly, $keyword);

        if (is_array($apiResult)) {
            $serialized = array_map(fn ($item) => $this->serde->serialize($item, format: 'array'), $apiResult);
            return response()->json($serialized, 200);
        }


        // This shouldn't happen
        return response()->abort(500);
    }
    /**
     * Operation updateVehicle
     *
     * Update Vehicle.
     *
     */
    public function updateVehicle(Request $request, float $version, int $id): JsonResponse
    {
        $validator = Validator::make(
            array_merge(
                [
                    'version' => $version,'id' => $id,
                ],
                $request->all(),
            ),
            [
            ],
        );

        if ($validator->fails()) {
            return response()->json(['error' => 'Invalid input'], 400);
        }



        $vehicle = $request->string('vehicle')->value();

        $body = $this->serde->deserialize($request->getContent(), from: 'json', to: \OpenAPI\Server\Model\Vehicle::class);


        $apiResult = $this->api->updateVehicle($version, $id, $vehicle, $body);

        if ($apiResult instanceof \OpenAPI\Server\Model\Vehicle) {
            return response()->json($this->serde->serialize($apiResult, format: 'array'), 200);
        }


        // This shouldn't happen
        return response()->abort(500);
    }
}
