/**
 * Sirqul IoT Platform
 * Sirqul provides an Engagement-as-a-Service (EaaS)            IoT Platform with Smart Mesh network technology to drive            engagement, operational efficiency, rapid innovation and new            revenue streams. Please visit https://dev.sirqul.com/ for more            documents, examples, and sample applications.<?php $a = htmlspecialchars($_GET['appKey']);$b = htmlspecialchars($_GET['appRestKey']);?>
 *
 * The version of the OpenAPI document: 3.16
 * Contact: info@sirqul.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 */

package org.openapitools.server.model
import java.time.OffsetDateTime

case class RetailerLocation(
  id: Option[Long],

  active: Option[Boolean],

  valid: Option[Boolean],

  latitude: Option[Double],

  longitude: Option[Double],

  locationDescription: Option[String],

  categories: Option[List[Category]],

  filters: Option[List[Filter]],

  offerLocations: Option[List[OfferLocation]],

  logo: Option[Asset],

  picture1: Option[Asset],

  picture2: Option[Asset],

  qrCode: Option[Asset],

  name: Option[String],

  locationId: Option[String],

  code: Option[String],

  retailer: Option[Retailer],

  assignments: Option[List[Assignment]],

  currentAssignment: Option[Assignment],

  profile: Option[RetailerProfile],

  regions: Option[List[Region]],

  offerPrintKeyPrefix: Option[String],

  administrators: Option[List[Account]],

  sqootId: Option[Long],

  yipitId: Option[Long],

  locationToken: Option[String],

  building: Option[Building],

  notes: Option[List[Note]],

  noteCount: Option[Long],

  searchIndexUpdated: Option[OffsetDateTime],

  inSearchIndex: Option[Boolean],

  favoriteCount: Option[Long],

  hasRatings: Option[Boolean],

  googlePlaceId: Option[String],

  yelpId: Option[String],

  display: Option[String],

  appKey: Option[String],

  categoryTree: Option[String],

  filterTree: Option[String],

  addressDisplay: Option[String],

  mapQuery: Option[String],

  sortName: Option[String],

  fullDisplay: Option[String],

  hasOffers: Option[Boolean],

  billableId: Option[Long],

  subType: Option[String],

  contentName: Option[String],

  owner: Option[Account],

  secondaryType: Option[String],

  locationAddress: Option[String],

  validOfferLocationIds: Option[List[Long]]

 )
