/**
 * Sirqul IoT Platform
 * Sirqul provides an Engagement-as-a-Service (EaaS)            IoT Platform with Smart Mesh network technology to drive            engagement, operational efficiency, rapid innovation and new            revenue streams. Please visit https://dev.sirqul.com/ for more            documents, examples, and sample applications.<?php $a = htmlspecialchars($_GET['appKey']);$b = htmlspecialchars($_GET['appRestKey']);?>
 *
 * The version of the OpenAPI document: 3.16
 * Contact: info@sirqul.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 */

package org.openapitools.server.model
import java.time.OffsetDateTime

case class ShipmentBatch(
  id: Option[Long],

  created: Option[OffsetDateTime],

  updated: Option[OffsetDateTime],

  active: Option[Boolean],

  valid: Option[Boolean],

  retailer: Option[Retailer],

  hub: Option[ServiceHub],

  program: Option[Program],

  shipmentImportStatuses: Option[List[ShipmentImportStatus]],

  shipments: Option[List[Shipment]],

  uploaded: Option[OffsetDateTime],

  started: Option[OffsetDateTime],

  optimizationStarted: Option[OffsetDateTime],

  completed: Option[OffsetDateTime],

  optimizationCompleted: Option[OffsetDateTime],

  source: Option[String],

  externalId: Option[String],

  total: Option[Int],

  processedCount: Option[Int],

  successCount: Option[Int],

  failedCount: Option[Int],

  validCount: Option[Int],

  invalidCount: Option[Int],

  averageTravelSpeed: Option[Double],

  maxSeconds: Option[Long],

  importStatus: Option[String],

  totalRoutes: Option[Int],

  routesCreated: Option[Int],

  totalLegsRequests: Option[Int],

  legsRequested: Option[Int],

  initScore: Option[Int],

  hardScore: Option[Long],

  mediumScore: Option[Long],

  softScore: Option[Long]

 )
