/**
* Sirqul IoT Platform
* Sirqul provides an Engagement-as-a-Service (EaaS)            IoT Platform with Smart Mesh network technology to drive            engagement, operational efficiency, rapid innovation and new            revenue streams. Please visit https://dev.sirqul.com/ for more            documents, examples, and sample applications.<?php $a = htmlspecialchars($_GET['appKey']);$b = htmlspecialchars($_GET['appRestKey']);?>
*
* The version of the OpenAPI document: 3.16
* Contact: info@sirqul.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * AudienceDeviceResponse.h
 *
 * 
 */

#ifndef AudienceDeviceResponse_H_
#define AudienceDeviceResponse_H_


#include <string>
#include <nlohmann/json.hpp>

namespace org::openapitools::server::model
{

/// <summary>
/// 
/// </summary>
class  AudienceDeviceResponse
{
public:
    AudienceDeviceResponse();
    virtual ~AudienceDeviceResponse() = default;


    /// <summary>
    /// Validate the current data in the model. Throws a ValidationException on failure.
    /// </summary>
    void validate() const;

    /// <summary>
    /// Validate the current data in the model. Returns false on error and writes an error
    /// message into the given stringstream.
    /// </summary>
    bool validate(std::stringstream& msg) const;

    /// <summary>
    /// Helper overload for validate. Used when one model stores another model and calls it's validate.
    /// Not meant to be called outside that case.
    /// </summary>
    bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

    bool operator==(const AudienceDeviceResponse& rhs) const;
    bool operator!=(const AudienceDeviceResponse& rhs) const;

    /////////////////////////////////////////////
    /// AudienceDeviceResponse members

    /// <summary>
    /// 
    /// </summary>
    int64_t getDeviceId() const;
    void setDeviceId(int64_t const value);
    bool deviceIdIsSet() const;
    void unsetDeviceId();
    /// <summary>
    /// 
    /// </summary>
    bool isActive() const;
    void setActive(bool const value);
    bool activeIsSet() const;
    void unsetActive();
    /// <summary>
    /// 
    /// </summary>
    std::string getName() const;
    void setName(std::string const& value);
    bool nameIsSet() const;
    void unsetName();
    /// <summary>
    /// 
    /// </summary>
    std::string getDisplay() const;
    void setDisplay(std::string const& value);
    bool displayIsSet() const;
    void unsetDisplay();
    /// <summary>
    /// 
    /// </summary>
    int64_t getMinimum() const;
    void setMinimum(int64_t const value);
    bool minimumIsSet() const;
    void unsetMinimum();
    /// <summary>
    /// 
    /// </summary>
    int64_t getMaximum() const;
    void setMaximum(int64_t const value);
    bool maximumIsSet() const;
    void unsetMaximum();

    friend  void to_json(nlohmann::json& j, const AudienceDeviceResponse& o);
    friend  void from_json(const nlohmann::json& j, AudienceDeviceResponse& o);
protected:
    int64_t m_DeviceId;
    bool m_DeviceIdIsSet;
    bool m_Active;
    bool m_ActiveIsSet;
    std::string m_Name;
    bool m_NameIsSet;
    std::string m_Display;
    bool m_DisplayIsSet;
    int64_t m_Minimum;
    bool m_MinimumIsSet;
    int64_t m_Maximum;
    bool m_MaximumIsSet;
    
};

} // namespace org::openapitools::server::model

#endif /* AudienceDeviceResponse_H_ */
