/**
* Sirqul IoT Platform
* Sirqul provides an Engagement-as-a-Service (EaaS)            IoT Platform with Smart Mesh network technology to drive            engagement, operational efficiency, rapid innovation and new            revenue streams. Please visit https://dev.sirqul.com/ for more            documents, examples, and sample applications.<?php $a = htmlspecialchars($_GET['appKey']);$b = htmlspecialchars($_GET['appRestKey']);?>
*
* The version of the OpenAPI document: 3.16
* Contact: info@sirqul.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "AudienceDevice.h"
#include "Helpers.h"

#include <sstream>

namespace org::openapitools::server::model
{

AudienceDevice::AudienceDevice()
{
    m_Id = 0L;
    m_IdIsSet = false;
    m_Active = false;
    m_ActiveIsSet = false;
    m_Valid = false;
    m_ValidIsSet = false;
    m_Name = "";
    m_NameIsSet = false;
    m_Minimum = 0L;
    m_MinimumIsSet = false;
    m_Maximum = 0L;
    m_MaximumIsSet = false;
    
}

void AudienceDevice::validate() const
{
    std::stringstream msg;
    if (!validate(msg))
    {
        throw org::openapitools::server::helpers::ValidationException(msg.str());
    }
}

bool AudienceDevice::validate(std::stringstream& msg) const
{
    return validate(msg, "");
}

bool AudienceDevice::validate(std::stringstream& msg, const std::string& pathPrefix) const
{
    bool success = true;
    const std::string _pathPrefix = pathPrefix.empty() ? "AudienceDevice" : pathPrefix;

                            
    return success;
}

bool AudienceDevice::operator==(const AudienceDevice& rhs) const
{
    return
    
    
    
    ((!idIsSet() && !rhs.idIsSet()) || (idIsSet() && rhs.idIsSet() && getId() == rhs.getId())) &&
    
    
    ((!activeIsSet() && !rhs.activeIsSet()) || (activeIsSet() && rhs.activeIsSet() && isActive() == rhs.isActive())) &&
    
    
    ((!validIsSet() && !rhs.validIsSet()) || (validIsSet() && rhs.validIsSet() && isValid() == rhs.isValid())) &&
    
    
    ((!nameIsSet() && !rhs.nameIsSet()) || (nameIsSet() && rhs.nameIsSet() && getName() == rhs.getName())) &&
    
    
    ((!minimumIsSet() && !rhs.minimumIsSet()) || (minimumIsSet() && rhs.minimumIsSet() && getMinimum() == rhs.getMinimum())) &&
    
    
    ((!maximumIsSet() && !rhs.maximumIsSet()) || (maximumIsSet() && rhs.maximumIsSet() && getMaximum() == rhs.getMaximum()))
    
    ;
}

bool AudienceDevice::operator!=(const AudienceDevice& rhs) const
{
    return !(*this == rhs);
}

void to_json(nlohmann::json& j, const AudienceDevice& o)
{
    j = nlohmann::json::object();
    if(o.idIsSet())
        j["id"] = o.m_Id;
    if(o.activeIsSet())
        j["active"] = o.m_Active;
    if(o.validIsSet())
        j["valid"] = o.m_Valid;
    if(o.nameIsSet())
        j["name"] = o.m_Name;
    if(o.minimumIsSet())
        j["minimum"] = o.m_Minimum;
    if(o.maximumIsSet())
        j["maximum"] = o.m_Maximum;
    
}

void from_json(const nlohmann::json& j, AudienceDevice& o)
{
    if(j.find("id") != j.end())
    {
        j.at("id").get_to(o.m_Id);
        o.m_IdIsSet = true;
    } 
    if(j.find("active") != j.end())
    {
        j.at("active").get_to(o.m_Active);
        o.m_ActiveIsSet = true;
    } 
    if(j.find("valid") != j.end())
    {
        j.at("valid").get_to(o.m_Valid);
        o.m_ValidIsSet = true;
    } 
    if(j.find("name") != j.end())
    {
        j.at("name").get_to(o.m_Name);
        o.m_NameIsSet = true;
    } 
    if(j.find("minimum") != j.end())
    {
        j.at("minimum").get_to(o.m_Minimum);
        o.m_MinimumIsSet = true;
    } 
    if(j.find("maximum") != j.end())
    {
        j.at("maximum").get_to(o.m_Maximum);
        o.m_MaximumIsSet = true;
    } 
    
}

int64_t AudienceDevice::getId() const
{
    return m_Id;
}
void AudienceDevice::setId(int64_t const value)
{
    m_Id = value;
    m_IdIsSet = true;
}
bool AudienceDevice::idIsSet() const
{
    return m_IdIsSet;
}
void AudienceDevice::unsetId()
{
    m_IdIsSet = false;
}
bool AudienceDevice::isActive() const
{
    return m_Active;
}
void AudienceDevice::setActive(bool const value)
{
    m_Active = value;
    m_ActiveIsSet = true;
}
bool AudienceDevice::activeIsSet() const
{
    return m_ActiveIsSet;
}
void AudienceDevice::unsetActive()
{
    m_ActiveIsSet = false;
}
bool AudienceDevice::isValid() const
{
    return m_Valid;
}
void AudienceDevice::setValid(bool const value)
{
    m_Valid = value;
    m_ValidIsSet = true;
}
bool AudienceDevice::validIsSet() const
{
    return m_ValidIsSet;
}
void AudienceDevice::unsetValid()
{
    m_ValidIsSet = false;
}
std::string AudienceDevice::getName() const
{
    return m_Name;
}
void AudienceDevice::setName(std::string const& value)
{
    m_Name = value;
    m_NameIsSet = true;
}
bool AudienceDevice::nameIsSet() const
{
    return m_NameIsSet;
}
void AudienceDevice::unsetName()
{
    m_NameIsSet = false;
}
int64_t AudienceDevice::getMinimum() const
{
    return m_Minimum;
}
void AudienceDevice::setMinimum(int64_t const value)
{
    m_Minimum = value;
    m_MinimumIsSet = true;
}
bool AudienceDevice::minimumIsSet() const
{
    return m_MinimumIsSet;
}
void AudienceDevice::unsetMinimum()
{
    m_MinimumIsSet = false;
}
int64_t AudienceDevice::getMaximum() const
{
    return m_Maximum;
}
void AudienceDevice::setMaximum(int64_t const value)
{
    m_Maximum = value;
    m_MaximumIsSet = true;
}
bool AudienceDevice::maximumIsSet() const
{
    return m_MaximumIsSet;
}
void AudienceDevice::unsetMaximum()
{
    m_MaximumIsSet = false;
}


} // namespace org::openapitools::server::model

