/**
* Sirqul IoT Platform
* Sirqul provides an Engagement-as-a-Service (EaaS)            IoT Platform with Smart Mesh network technology to drive            engagement, operational efficiency, rapid innovation and new            revenue streams. Please visit https://dev.sirqul.com/ for more            documents, examples, and sample applications.<?php $a = htmlspecialchars($_GET['appKey']);$b = htmlspecialchars($_GET['appRestKey']);?>
*
* The version of the OpenAPI document: 3.16
* Contact: info@sirqul.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * EventAttendanceResponse.h
 *
 * 
 */

#ifndef EventAttendanceResponse_H_
#define EventAttendanceResponse_H_


#include "OfferShortResponse.h"
#include "AccountShortResponse.h"
#include <vector>
#include "CategoryResponse.h"
#include <nlohmann/json.hpp>

namespace org::openapitools::server::model
{

/// <summary>
/// 
/// </summary>
class  EventAttendanceResponse
{
public:
    EventAttendanceResponse();
    virtual ~EventAttendanceResponse() = default;


    /// <summary>
    /// Validate the current data in the model. Throws a ValidationException on failure.
    /// </summary>
    void validate() const;

    /// <summary>
    /// Validate the current data in the model. Returns false on error and writes an error
    /// message into the given stringstream.
    /// </summary>
    bool validate(std::stringstream& msg) const;

    /// <summary>
    /// Helper overload for validate. Used when one model stores another model and calls it's validate.
    /// Not meant to be called outside that case.
    /// </summary>
    bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

    bool operator==(const EventAttendanceResponse& rhs) const;
    bool operator!=(const EventAttendanceResponse& rhs) const;

    /////////////////////////////////////////////
    /// EventAttendanceResponse members

    /// <summary>
    /// 
    /// </summary>
    org::openapitools::server::model::OfferShortResponse getEvent() const;
    void setEvent(org::openapitools::server::model::OfferShortResponse const& value);
    bool eventIsSet() const;
    void unsetEvent();
    /// <summary>
    /// 
    /// </summary>
    std::vector<org::openapitools::server::model::CategoryResponse> getAffiliatedCategories() const;
    void setAffiliatedCategories(std::vector<org::openapitools::server::model::CategoryResponse> const& value);
    bool affiliatedCategoriesIsSet() const;
    void unsetAffiliatedCategories();
    /// <summary>
    /// 
    /// </summary>
    org::openapitools::server::model::AccountShortResponse getAttendee() const;
    void setAttendee(org::openapitools::server::model::AccountShortResponse const& value);
    bool attendeeIsSet() const;
    void unsetAttendee();
    /// <summary>
    /// 
    /// </summary>
    bool isRFriend() const;
    void setRFriend(bool const value);
    bool rFriendIsSet() const;
    void unsetr_friend();

    friend  void to_json(nlohmann::json& j, const EventAttendanceResponse& o);
    friend  void from_json(const nlohmann::json& j, EventAttendanceResponse& o);
protected:
    org::openapitools::server::model::OfferShortResponse m_Event;
    bool m_EventIsSet;
    std::vector<org::openapitools::server::model::CategoryResponse> m_AffiliatedCategories;
    bool m_AffiliatedCategoriesIsSet;
    org::openapitools::server::model::AccountShortResponse m_Attendee;
    bool m_AttendeeIsSet;
    bool m_r_friend;
    bool m_r_friendIsSet;
    
};

} // namespace org::openapitools::server::model

#endif /* EventAttendanceResponse_H_ */
