/**
* Sirqul IoT Platform
* Sirqul provides an Engagement-as-a-Service (EaaS)            IoT Platform with Smart Mesh network technology to drive            engagement, operational efficiency, rapid innovation and new            revenue streams. Please visit https://dev.sirqul.com/ for more            documents, examples, and sample applications.<?php $a = htmlspecialchars($_GET['appKey']);$b = htmlspecialchars($_GET['appRestKey']);?>
*
* The version of the OpenAPI document: 3.16
* Contact: info@sirqul.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "Interval.h"
#include "Helpers.h"

#include <sstream>

namespace org::openapitools::server::model
{

Interval::Interval()
{
    m_End = "";
    m_EndIsSet = false;
    m_Start = "";
    m_StartIsSet = false;
    m_ChronologyIsSet = false;
    m_StartMillis = 0L;
    m_StartMillisIsSet = false;
    m_EndMillis = 0L;
    m_EndMillisIsSet = false;
    m_BeforeNow = false;
    m_BeforeNowIsSet = false;
    m_AfterNow = false;
    m_AfterNowIsSet = false;
    
}

void Interval::validate() const
{
    std::stringstream msg;
    if (!validate(msg))
    {
        throw org::openapitools::server::helpers::ValidationException(msg.str());
    }
}

bool Interval::validate(std::stringstream& msg) const
{
    return validate(msg, "");
}

bool Interval::validate(std::stringstream& msg, const std::string& pathPrefix) const
{
    bool success = true;
    const std::string _pathPrefix = pathPrefix.empty() ? "Interval" : pathPrefix;

                                
    return success;
}

bool Interval::operator==(const Interval& rhs) const
{
    return
    
    
    
    ((!endIsSet() && !rhs.endIsSet()) || (endIsSet() && rhs.endIsSet() && getEnd() == rhs.getEnd())) &&
    
    
    ((!startIsSet() && !rhs.startIsSet()) || (startIsSet() && rhs.startIsSet() && getStart() == rhs.getStart())) &&
    
    
    ((!chronologyIsSet() && !rhs.chronologyIsSet()) || (chronologyIsSet() && rhs.chronologyIsSet() && getChronology() == rhs.getChronology())) &&
    
    
    ((!startMillisIsSet() && !rhs.startMillisIsSet()) || (startMillisIsSet() && rhs.startMillisIsSet() && getStartMillis() == rhs.getStartMillis())) &&
    
    
    ((!endMillisIsSet() && !rhs.endMillisIsSet()) || (endMillisIsSet() && rhs.endMillisIsSet() && getEndMillis() == rhs.getEndMillis())) &&
    
    
    ((!beforeNowIsSet() && !rhs.beforeNowIsSet()) || (beforeNowIsSet() && rhs.beforeNowIsSet() && isBeforeNow() == rhs.isBeforeNow())) &&
    
    
    ((!afterNowIsSet() && !rhs.afterNowIsSet()) || (afterNowIsSet() && rhs.afterNowIsSet() && isAfterNow() == rhs.isAfterNow()))
    
    ;
}

bool Interval::operator!=(const Interval& rhs) const
{
    return !(*this == rhs);
}

void to_json(nlohmann::json& j, const Interval& o)
{
    j = nlohmann::json::object();
    if(o.endIsSet())
        j["end"] = o.m_End;
    if(o.startIsSet())
        j["start"] = o.m_Start;
    if(o.chronologyIsSet())
        j["chronology"] = o.m_Chronology;
    if(o.startMillisIsSet())
        j["startMillis"] = o.m_StartMillis;
    if(o.endMillisIsSet())
        j["endMillis"] = o.m_EndMillis;
    if(o.beforeNowIsSet())
        j["beforeNow"] = o.m_BeforeNow;
    if(o.afterNowIsSet())
        j["afterNow"] = o.m_AfterNow;
    
}

void from_json(const nlohmann::json& j, Interval& o)
{
    if(j.find("end") != j.end())
    {
        j.at("end").get_to(o.m_End);
        o.m_EndIsSet = true;
    } 
    if(j.find("start") != j.end())
    {
        j.at("start").get_to(o.m_Start);
        o.m_StartIsSet = true;
    } 
    if(j.find("chronology") != j.end())
    {
        j.at("chronology").get_to(o.m_Chronology);
        o.m_ChronologyIsSet = true;
    } 
    if(j.find("startMillis") != j.end())
    {
        j.at("startMillis").get_to(o.m_StartMillis);
        o.m_StartMillisIsSet = true;
    } 
    if(j.find("endMillis") != j.end())
    {
        j.at("endMillis").get_to(o.m_EndMillis);
        o.m_EndMillisIsSet = true;
    } 
    if(j.find("beforeNow") != j.end())
    {
        j.at("beforeNow").get_to(o.m_BeforeNow);
        o.m_BeforeNowIsSet = true;
    } 
    if(j.find("afterNow") != j.end())
    {
        j.at("afterNow").get_to(o.m_AfterNow);
        o.m_AfterNowIsSet = true;
    } 
    
}

std::string Interval::getEnd() const
{
    return m_End;
}
void Interval::setEnd(std::string const& value)
{
    m_End = value;
    m_EndIsSet = true;
}
bool Interval::endIsSet() const
{
    return m_EndIsSet;
}
void Interval::unsetEnd()
{
    m_EndIsSet = false;
}
std::string Interval::getStart() const
{
    return m_Start;
}
void Interval::setStart(std::string const& value)
{
    m_Start = value;
    m_StartIsSet = true;
}
bool Interval::startIsSet() const
{
    return m_StartIsSet;
}
void Interval::unsetStart()
{
    m_StartIsSet = false;
}
org::openapitools::server::model::Chronology Interval::getChronology() const
{
    return m_Chronology;
}
void Interval::setChronology(org::openapitools::server::model::Chronology const& value)
{
    m_Chronology = value;
    m_ChronologyIsSet = true;
}
bool Interval::chronologyIsSet() const
{
    return m_ChronologyIsSet;
}
void Interval::unsetChronology()
{
    m_ChronologyIsSet = false;
}
int64_t Interval::getStartMillis() const
{
    return m_StartMillis;
}
void Interval::setStartMillis(int64_t const value)
{
    m_StartMillis = value;
    m_StartMillisIsSet = true;
}
bool Interval::startMillisIsSet() const
{
    return m_StartMillisIsSet;
}
void Interval::unsetStartMillis()
{
    m_StartMillisIsSet = false;
}
int64_t Interval::getEndMillis() const
{
    return m_EndMillis;
}
void Interval::setEndMillis(int64_t const value)
{
    m_EndMillis = value;
    m_EndMillisIsSet = true;
}
bool Interval::endMillisIsSet() const
{
    return m_EndMillisIsSet;
}
void Interval::unsetEndMillis()
{
    m_EndMillisIsSet = false;
}
bool Interval::isBeforeNow() const
{
    return m_BeforeNow;
}
void Interval::setBeforeNow(bool const value)
{
    m_BeforeNow = value;
    m_BeforeNowIsSet = true;
}
bool Interval::beforeNowIsSet() const
{
    return m_BeforeNowIsSet;
}
void Interval::unsetBeforeNow()
{
    m_BeforeNowIsSet = false;
}
bool Interval::isAfterNow() const
{
    return m_AfterNow;
}
void Interval::setAfterNow(bool const value)
{
    m_AfterNow = value;
    m_AfterNowIsSet = true;
}
bool Interval::afterNowIsSet() const
{
    return m_AfterNowIsSet;
}
void Interval::unsetAfterNow()
{
    m_AfterNowIsSet = false;
}


} // namespace org::openapitools::server::model

