/**
* Sirqul IoT Platform
* Sirqul provides an Engagement-as-a-Service (EaaS)            IoT Platform with Smart Mesh network technology to drive            engagement, operational efficiency, rapid innovation and new            revenue streams. Please visit https://dev.sirqul.com/ for more            documents, examples, and sample applications.<?php $a = htmlspecialchars($_GET['appKey']);$b = htmlspecialchars($_GET['appRestKey']);?>
*
* The version of the OpenAPI document: 3.16
* Contact: info@sirqul.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * Location.h
 *
 * 
 */

#ifndef Location_H_
#define Location_H_


#include "ServiceHub.h"
#include "Territory.h"
#include "Program.h"
#include "CellCarrier.h"
#include "Address.h"
#include "YayOrNay.h"
#include <string>
#include "Asset.h"
#include "Note.h"
#include <vector>
#include <nlohmann/json.hpp>

namespace org::openapitools::server::model
{

/// <summary>
/// 
/// </summary>
class  Location
{
public:
    Location();
    virtual ~Location() = default;


    /// <summary>
    /// Validate the current data in the model. Throws a ValidationException on failure.
    /// </summary>
    void validate() const;

    /// <summary>
    /// Validate the current data in the model. Returns false on error and writes an error
    /// message into the given stringstream.
    /// </summary>
    bool validate(std::stringstream& msg) const;

    /// <summary>
    /// Helper overload for validate. Used when one model stores another model and calls it's validate.
    /// Not meant to be called outside that case.
    /// </summary>
    bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

    bool operator==(const Location& rhs) const;
    bool operator!=(const Location& rhs) const;

    /////////////////////////////////////////////
    /// Location members

    /// <summary>
    /// 
    /// </summary>
    int64_t getId() const;
    void setId(int64_t const value);
    bool idIsSet() const;
    void unsetId();
    /// <summary>
    /// 
    /// </summary>
    bool isActive() const;
    void setActive(bool const value);
    bool activeIsSet() const;
    void unsetActive();
    /// <summary>
    /// 
    /// </summary>
    bool isValid() const;
    void setValid(bool const value);
    bool validIsSet() const;
    void unsetValid();
    /// <summary>
    /// 
    /// </summary>
    double getLatitude() const;
    void setLatitude(double const value);
    bool latitudeIsSet() const;
    void unsetLatitude();
    /// <summary>
    /// 
    /// </summary>
    double getLongitude() const;
    void setLongitude(double const value);
    bool longitudeIsSet() const;
    void unsetLongitude();
    /// <summary>
    /// 
    /// </summary>
    std::string getLocationDescription() const;
    void setLocationDescription(std::string const& value);
    bool locationDescriptionIsSet() const;
    void unsetLocationDescription();
    /// <summary>
    /// 
    /// </summary>
    std::string getName() const;
    void setName(std::string const& value);
    bool nameIsSet() const;
    void unsetName();
    /// <summary>
    /// 
    /// </summary>
    org::openapitools::server::model::Territory getTerritory() const;
    void setTerritory(org::openapitools::server::model::Territory const& value);
    bool territoryIsSet() const;
    void unsetTerritory();
    /// <summary>
    /// 
    /// </summary>
    org::openapitools::server::model::ServiceHub getHub() const;
    void setHub(org::openapitools::server::model::ServiceHub const& value);
    bool hubIsSet() const;
    void unsetHub();
    /// <summary>
    /// 
    /// </summary>
    org::openapitools::server::model::Asset getPicture() const;
    void setPicture(org::openapitools::server::model::Asset const& value);
    bool pictureIsSet() const;
    void unsetPicture();
    /// <summary>
    /// 
    /// </summary>
    std::vector<org::openapitools::server::model::Note> getNotes() const;
    void setNotes(std::vector<org::openapitools::server::model::Note> const& value);
    bool notesIsSet() const;
    void unsetNotes();
    /// <summary>
    /// 
    /// </summary>
    int64_t getNoteCount() const;
    void setNoteCount(int64_t const value);
    bool noteCountIsSet() const;
    void unsetNoteCount();
    /// <summary>
    /// 
    /// </summary>
    std::string getHomePhone() const;
    void setHomePhone(std::string const& value);
    bool homePhoneIsSet() const;
    void unsetHomePhone();
    /// <summary>
    /// 
    /// </summary>
    std::string getCellPhone() const;
    void setCellPhone(std::string const& value);
    bool cellPhoneIsSet() const;
    void unsetCellPhone();
    /// <summary>
    /// 
    /// </summary>
    org::openapitools::server::model::CellCarrier getCellCarrier() const;
    void setCellCarrier(org::openapitools::server::model::CellCarrier const& value);
    bool cellCarrierIsSet() const;
    void unsetCellCarrier();
    /// <summary>
    /// 
    /// </summary>
    std::string getBusinessPhone() const;
    void setBusinessPhone(std::string const& value);
    bool businessPhoneIsSet() const;
    void unsetBusinessPhone();
    /// <summary>
    /// 
    /// </summary>
    std::string getBusinessPhoneExt() const;
    void setBusinessPhoneExt(std::string const& value);
    bool businessPhoneExtIsSet() const;
    void unsetBusinessPhoneExt();
    /// <summary>
    /// 
    /// </summary>
    std::string getFaxNumber() const;
    void setFaxNumber(std::string const& value);
    bool faxNumberIsSet() const;
    void unsetFaxNumber();
    /// <summary>
    /// 
    /// </summary>
    std::string getTimeZone() const;
    void setTimeZone(std::string const& value);
    bool timeZoneIsSet() const;
    void unsetTimeZone();
    /// <summary>
    /// 
    /// </summary>
    std::string getUtcOffset() const;
    void setUtcOffset(std::string const& value);
    bool utcOffsetIsSet() const;
    void unsetUtcOffset();
    /// <summary>
    /// 
    /// </summary>
    std::string getCode501c3() const;
    void setCode501c3(std::string const& value);
    bool code501c3IsSet() const;
    void unsetCode501c3();
    /// <summary>
    /// 
    /// </summary>
    std::string getEmailAddress() const;
    void setEmailAddress(std::string const& value);
    bool emailAddressIsSet() const;
    void unsetEmailAddress();
    /// <summary>
    /// 
    /// </summary>
    org::openapitools::server::model::Address getAddress() const;
    void setAddress(org::openapitools::server::model::Address const& value);
    bool addressIsSet() const;
    void unsetAddress();
    /// <summary>
    /// 
    /// </summary>
    std::string getWeb() const;
    void setWeb(std::string const& value);
    bool webIsSet() const;
    void unsetWeb();
    /// <summary>
    /// 
    /// </summary>
    org::openapitools::server::model::Program getProgram() const;
    void setProgram(org::openapitools::server::model::Program const& value);
    bool programIsSet() const;
    void unsetProgram();
    /// <summary>
    /// 
    /// </summary>
    std::string getVisibility() const;
    void setVisibility(std::string const& value);
    bool visibilityIsSet() const;
    void unsetVisibility();
    /// <summary>
    /// 
    /// </summary>
    std::string getGroupingId() const;
    void setGroupingId(std::string const& value);
    bool groupingIdIsSet() const;
    void unsetGroupingId();
    /// <summary>
    /// 
    /// </summary>
    bool isDestination() const;
    void setDestination(bool const value);
    bool destinationIsSet() const;
    void unsetDestination();
    /// <summary>
    /// 
    /// </summary>
    int64_t getDockingTime() const;
    void setDockingTime(int64_t const value);
    bool dockingTimeIsSet() const;
    void unsetDockingTime();
    /// <summary>
    /// 
    /// </summary>
    int64_t getUsageCount() const;
    void setUsageCount(int64_t const value);
    bool usageCountIsSet() const;
    void unsetUsageCount();
    /// <summary>
    /// 
    /// </summary>
    std::string getTimeFramesAllowed() const;
    void setTimeFramesAllowed(std::string const& value);
    bool timeFramesAllowedIsSet() const;
    void unsetTimeFramesAllowed();
    /// <summary>
    /// 
    /// </summary>
    std::vector<org::openapitools::server::model::YayOrNay> getLikes() const;
    void setLikes(std::vector<org::openapitools::server::model::YayOrNay> const& value);
    bool likesIsSet() const;
    void unsetLikes();
    /// <summary>
    /// 
    /// </summary>
    int64_t getLikeCount() const;
    void setLikeCount(int64_t const value);
    bool likeCountIsSet() const;
    void unsetLikeCount();
    /// <summary>
    /// 
    /// </summary>
    int64_t getDislikeCount() const;
    void setDislikeCount(int64_t const value);
    bool dislikeCountIsSet() const;
    void unsetDislikeCount();
    /// <summary>
    /// 
    /// </summary>
    std::string getOwnerDisplay() const;
    void setOwnerDisplay(std::string const& value);
    bool ownerDisplayIsSet() const;
    void unsetOwnerDisplay();
    /// <summary>
    /// 
    /// </summary>
    std::string getContentName() const;
    void setContentName(std::string const& value);
    bool contentNameIsSet() const;
    void unsetContentName();

    friend  void to_json(nlohmann::json& j, const Location& o);
    friend  void from_json(const nlohmann::json& j, Location& o);
protected:
    int64_t m_Id;
    bool m_IdIsSet;
    bool m_Active;
    bool m_ActiveIsSet;
    bool m_Valid;
    bool m_ValidIsSet;
    double m_Latitude;
    bool m_LatitudeIsSet;
    double m_Longitude;
    bool m_LongitudeIsSet;
    std::string m_LocationDescription;
    bool m_LocationDescriptionIsSet;
    std::string m_Name;
    bool m_NameIsSet;
    org::openapitools::server::model::Territory m_Territory;
    bool m_TerritoryIsSet;
    org::openapitools::server::model::ServiceHub m_Hub;
    bool m_HubIsSet;
    org::openapitools::server::model::Asset m_Picture;
    bool m_PictureIsSet;
    std::vector<org::openapitools::server::model::Note> m_Notes;
    bool m_NotesIsSet;
    int64_t m_NoteCount;
    bool m_NoteCountIsSet;
    std::string m_HomePhone;
    bool m_HomePhoneIsSet;
    std::string m_CellPhone;
    bool m_CellPhoneIsSet;
    org::openapitools::server::model::CellCarrier m_CellCarrier;
    bool m_CellCarrierIsSet;
    std::string m_BusinessPhone;
    bool m_BusinessPhoneIsSet;
    std::string m_BusinessPhoneExt;
    bool m_BusinessPhoneExtIsSet;
    std::string m_FaxNumber;
    bool m_FaxNumberIsSet;
    std::string m_TimeZone;
    bool m_TimeZoneIsSet;
    std::string m_UtcOffset;
    bool m_UtcOffsetIsSet;
    std::string m_Code501c3;
    bool m_Code501c3IsSet;
    std::string m_EmailAddress;
    bool m_EmailAddressIsSet;
    org::openapitools::server::model::Address m_Address;
    bool m_AddressIsSet;
    std::string m_Web;
    bool m_WebIsSet;
    org::openapitools::server::model::Program m_Program;
    bool m_ProgramIsSet;
    std::string m_Visibility;
    bool m_VisibilityIsSet;
    std::string m_GroupingId;
    bool m_GroupingIdIsSet;
    bool m_Destination;
    bool m_DestinationIsSet;
    int64_t m_DockingTime;
    bool m_DockingTimeIsSet;
    int64_t m_UsageCount;
    bool m_UsageCountIsSet;
    std::string m_TimeFramesAllowed;
    bool m_TimeFramesAllowedIsSet;
    std::vector<org::openapitools::server::model::YayOrNay> m_Likes;
    bool m_LikesIsSet;
    int64_t m_LikeCount;
    bool m_LikeCountIsSet;
    int64_t m_DislikeCount;
    bool m_DislikeCountIsSet;
    std::string m_OwnerDisplay;
    bool m_OwnerDisplayIsSet;
    std::string m_ContentName;
    bool m_ContentNameIsSet;
    
};

} // namespace org::openapitools::server::model

#endif /* Location_H_ */
