/**
* Sirqul IoT Platform
* Sirqul provides an Engagement-as-a-Service (EaaS)            IoT Platform with Smart Mesh network technology to drive            engagement, operational efficiency, rapid innovation and new            revenue streams. Please visit https://dev.sirqul.com/ for more            documents, examples, and sample applications.<?php $a = htmlspecialchars($_GET['appKey']);$b = htmlspecialchars($_GET['appRestKey']);?>
*
* The version of the OpenAPI document: 3.16
* Contact: info@sirqul.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "PaymentTypesResponse.h"
#include "Helpers.h"

#include <sstream>

namespace org::openapitools::server::model
{

PaymentTypesResponse::PaymentTypesResponse()
{
    m_Valid = false;
    m_ValidIsSet = false;
    m_Message = "";
    m_MessageIsSet = false;
    m_Version = 0.0;
    m_VersionIsSet = false;
    m_SerializeNulls = false;
    m_SerializeNullsIsSet = false;
    m_StartTimeLog = 0L;
    m_StartTimeLogIsSet = false;
    m_ErrorCode = "";
    m_ErrorCodeIsSet = false;
    m_RequestIsSet = false;
    m_CreditCardOnFile = false;
    m_CreditCardOnFileIsSet = false;
    m_CreditCardNumber = "";
    m_CreditCardNumberIsSet = false;
    m_CreditCardExpirationMonth = "";
    m_CreditCardExpirationMonthIsSet = false;
    m_CreditCardExpirationYear = "";
    m_CreditCardExpirationYearIsSet = false;
    m_PointsOnFile = false;
    m_PointsOnFileIsSet = false;
    m_PointsAmount = 0.0;
    m_PointsAmountIsSet = false;
    m_AccountIsSet = false;
    m_FirstName = "";
    m_FirstNameIsSet = false;
    m_LastName = "";
    m_LastNameIsSet = false;
    m_Address = "";
    m_AddressIsSet = false;
    m_City = "";
    m_CityIsSet = false;
    m_State = "";
    m_StateIsSet = false;
    m_PostalCode = "";
    m_PostalCodeIsSet = false;
    m_Phone = "";
    m_PhoneIsSet = false;
    m_Provider = "";
    m_ProviderIsSet = false;
    m_PaymentMethodId = 0L;
    m_PaymentMethodIdIsSet = false;
    m_Validated = false;
    m_ValidatedIsSet = false;
    m_AccountNumber = "";
    m_AccountNumberIsSet = false;
    m_BankName = "";
    m_BankNameIsSet = false;
    m_RoutingNumber = "";
    m_RoutingNumberIsSet = false;
    m_IsDefaultPaymentMethod = false;
    m_IsDefaultPaymentMethodIsSet = false;
    m_AccountName = "";
    m_AccountNameIsSet = false;
    m_PaymentMethodNickname = "";
    m_PaymentMethodNicknameIsSet = false;
    m_TaxId = "";
    m_TaxIdIsSet = false;
    m_Returning = "";
    m_ReturningIsSet = false;
    
}

void PaymentTypesResponse::validate() const
{
    std::stringstream msg;
    if (!validate(msg))
    {
        throw org::openapitools::server::helpers::ValidationException(msg.str());
    }
}

bool PaymentTypesResponse::validate(std::stringstream& msg) const
{
    return validate(msg, "");
}

bool PaymentTypesResponse::validate(std::stringstream& msg, const std::string& pathPrefix) const
{
    bool success = true;
    const std::string _pathPrefix = pathPrefix.empty() ? "PaymentTypesResponse" : pathPrefix;

                                 
    if (requestIsSet())
    {
        const std::vector<org::openapitools::server::model::NameStringValueResponse>& value = m_Request;
        const std::string currentValuePath = _pathPrefix + ".request";
                
        
        { // Recursive validation of array elements
            const std::string oldValuePath = currentValuePath;
            int i = 0;
            for (const org::openapitools::server::model::NameStringValueResponse& value : value)
            { 
                const std::string currentValuePath = oldValuePath + "[" + std::to_string(i) + "]";
                        
        success = value.validate(msg, currentValuePath + ".request") && success;
 
                i++;
            }
        }

    }
                                                                                                        
    return success;
}

bool PaymentTypesResponse::operator==(const PaymentTypesResponse& rhs) const
{
    return
    
    
    
    ((!validIsSet() && !rhs.validIsSet()) || (validIsSet() && rhs.validIsSet() && isValid() == rhs.isValid())) &&
    
    
    ((!messageIsSet() && !rhs.messageIsSet()) || (messageIsSet() && rhs.messageIsSet() && getMessage() == rhs.getMessage())) &&
    
    
    ((!versionIsSet() && !rhs.versionIsSet()) || (versionIsSet() && rhs.versionIsSet() && getVersion() == rhs.getVersion())) &&
    
    
    ((!serializeNullsIsSet() && !rhs.serializeNullsIsSet()) || (serializeNullsIsSet() && rhs.serializeNullsIsSet() && isSerializeNulls() == rhs.isSerializeNulls())) &&
    
    
    ((!startTimeLogIsSet() && !rhs.startTimeLogIsSet()) || (startTimeLogIsSet() && rhs.startTimeLogIsSet() && getStartTimeLog() == rhs.getStartTimeLog())) &&
    
    
    ((!errorCodeIsSet() && !rhs.errorCodeIsSet()) || (errorCodeIsSet() && rhs.errorCodeIsSet() && getErrorCode() == rhs.getErrorCode())) &&
    
    
    ((!requestIsSet() && !rhs.requestIsSet()) || (requestIsSet() && rhs.requestIsSet() && getRequest() == rhs.getRequest())) &&
    
    
    ((!creditCardOnFileIsSet() && !rhs.creditCardOnFileIsSet()) || (creditCardOnFileIsSet() && rhs.creditCardOnFileIsSet() && isCreditCardOnFile() == rhs.isCreditCardOnFile())) &&
    
    
    ((!creditCardNumberIsSet() && !rhs.creditCardNumberIsSet()) || (creditCardNumberIsSet() && rhs.creditCardNumberIsSet() && getCreditCardNumber() == rhs.getCreditCardNumber())) &&
    
    
    ((!creditCardExpirationMonthIsSet() && !rhs.creditCardExpirationMonthIsSet()) || (creditCardExpirationMonthIsSet() && rhs.creditCardExpirationMonthIsSet() && getCreditCardExpirationMonth() == rhs.getCreditCardExpirationMonth())) &&
    
    
    ((!creditCardExpirationYearIsSet() && !rhs.creditCardExpirationYearIsSet()) || (creditCardExpirationYearIsSet() && rhs.creditCardExpirationYearIsSet() && getCreditCardExpirationYear() == rhs.getCreditCardExpirationYear())) &&
    
    
    ((!pointsOnFileIsSet() && !rhs.pointsOnFileIsSet()) || (pointsOnFileIsSet() && rhs.pointsOnFileIsSet() && isPointsOnFile() == rhs.isPointsOnFile())) &&
    
    
    ((!pointsAmountIsSet() && !rhs.pointsAmountIsSet()) || (pointsAmountIsSet() && rhs.pointsAmountIsSet() && getPointsAmount() == rhs.getPointsAmount())) &&
    
    
    ((!accountIsSet() && !rhs.accountIsSet()) || (accountIsSet() && rhs.accountIsSet() && getAccount() == rhs.getAccount())) &&
    
    
    ((!firstNameIsSet() && !rhs.firstNameIsSet()) || (firstNameIsSet() && rhs.firstNameIsSet() && getFirstName() == rhs.getFirstName())) &&
    
    
    ((!lastNameIsSet() && !rhs.lastNameIsSet()) || (lastNameIsSet() && rhs.lastNameIsSet() && getLastName() == rhs.getLastName())) &&
    
    
    ((!addressIsSet() && !rhs.addressIsSet()) || (addressIsSet() && rhs.addressIsSet() && getAddress() == rhs.getAddress())) &&
    
    
    ((!cityIsSet() && !rhs.cityIsSet()) || (cityIsSet() && rhs.cityIsSet() && getCity() == rhs.getCity())) &&
    
    
    ((!stateIsSet() && !rhs.stateIsSet()) || (stateIsSet() && rhs.stateIsSet() && getState() == rhs.getState())) &&
    
    
    ((!postalCodeIsSet() && !rhs.postalCodeIsSet()) || (postalCodeIsSet() && rhs.postalCodeIsSet() && getPostalCode() == rhs.getPostalCode())) &&
    
    
    ((!phoneIsSet() && !rhs.phoneIsSet()) || (phoneIsSet() && rhs.phoneIsSet() && getPhone() == rhs.getPhone())) &&
    
    
    ((!providerIsSet() && !rhs.providerIsSet()) || (providerIsSet() && rhs.providerIsSet() && getProvider() == rhs.getProvider())) &&
    
    
    ((!paymentMethodIdIsSet() && !rhs.paymentMethodIdIsSet()) || (paymentMethodIdIsSet() && rhs.paymentMethodIdIsSet() && getPaymentMethodId() == rhs.getPaymentMethodId())) &&
    
    
    ((!validatedIsSet() && !rhs.validatedIsSet()) || (validatedIsSet() && rhs.validatedIsSet() && isValidated() == rhs.isValidated())) &&
    
    
    ((!accountNumberIsSet() && !rhs.accountNumberIsSet()) || (accountNumberIsSet() && rhs.accountNumberIsSet() && getAccountNumber() == rhs.getAccountNumber())) &&
    
    
    ((!bankNameIsSet() && !rhs.bankNameIsSet()) || (bankNameIsSet() && rhs.bankNameIsSet() && getBankName() == rhs.getBankName())) &&
    
    
    ((!routingNumberIsSet() && !rhs.routingNumberIsSet()) || (routingNumberIsSet() && rhs.routingNumberIsSet() && getRoutingNumber() == rhs.getRoutingNumber())) &&
    
    
    ((!isDefaultPaymentMethodIsSet() && !rhs.isDefaultPaymentMethodIsSet()) || (isDefaultPaymentMethodIsSet() && rhs.isDefaultPaymentMethodIsSet() && isIsDefaultPaymentMethod() == rhs.isIsDefaultPaymentMethod())) &&
    
    
    ((!accountNameIsSet() && !rhs.accountNameIsSet()) || (accountNameIsSet() && rhs.accountNameIsSet() && getAccountName() == rhs.getAccountName())) &&
    
    
    ((!paymentMethodNicknameIsSet() && !rhs.paymentMethodNicknameIsSet()) || (paymentMethodNicknameIsSet() && rhs.paymentMethodNicknameIsSet() && getPaymentMethodNickname() == rhs.getPaymentMethodNickname())) &&
    
    
    ((!taxIdIsSet() && !rhs.taxIdIsSet()) || (taxIdIsSet() && rhs.taxIdIsSet() && getTaxId() == rhs.getTaxId())) &&
    
    
    ((!returningIsSet() && !rhs.returningIsSet()) || (returningIsSet() && rhs.returningIsSet() && getReturning() == rhs.getReturning()))
    
    ;
}

bool PaymentTypesResponse::operator!=(const PaymentTypesResponse& rhs) const
{
    return !(*this == rhs);
}

void to_json(nlohmann::json& j, const PaymentTypesResponse& o)
{
    j = nlohmann::json::object();
    if(o.validIsSet())
        j["valid"] = o.m_Valid;
    if(o.messageIsSet())
        j["message"] = o.m_Message;
    if(o.versionIsSet())
        j["version"] = o.m_Version;
    if(o.serializeNullsIsSet())
        j["serializeNulls"] = o.m_SerializeNulls;
    if(o.startTimeLogIsSet())
        j["startTimeLog"] = o.m_StartTimeLog;
    if(o.errorCodeIsSet())
        j["errorCode"] = o.m_ErrorCode;
    if(o.requestIsSet() || !o.m_Request.empty())
        j["request"] = o.m_Request;
    if(o.creditCardOnFileIsSet())
        j["creditCardOnFile"] = o.m_CreditCardOnFile;
    if(o.creditCardNumberIsSet())
        j["creditCardNumber"] = o.m_CreditCardNumber;
    if(o.creditCardExpirationMonthIsSet())
        j["creditCardExpirationMonth"] = o.m_CreditCardExpirationMonth;
    if(o.creditCardExpirationYearIsSet())
        j["creditCardExpirationYear"] = o.m_CreditCardExpirationYear;
    if(o.pointsOnFileIsSet())
        j["pointsOnFile"] = o.m_PointsOnFile;
    if(o.pointsAmountIsSet())
        j["pointsAmount"] = o.m_PointsAmount;
    if(o.accountIsSet())
        j["account"] = o.m_Account;
    if(o.firstNameIsSet())
        j["firstName"] = o.m_FirstName;
    if(o.lastNameIsSet())
        j["lastName"] = o.m_LastName;
    if(o.addressIsSet())
        j["address"] = o.m_Address;
    if(o.cityIsSet())
        j["city"] = o.m_City;
    if(o.stateIsSet())
        j["state"] = o.m_State;
    if(o.postalCodeIsSet())
        j["postalCode"] = o.m_PostalCode;
    if(o.phoneIsSet())
        j["phone"] = o.m_Phone;
    if(o.providerIsSet())
        j["provider"] = o.m_Provider;
    if(o.paymentMethodIdIsSet())
        j["paymentMethodId"] = o.m_PaymentMethodId;
    if(o.validatedIsSet())
        j["validated"] = o.m_Validated;
    if(o.accountNumberIsSet())
        j["accountNumber"] = o.m_AccountNumber;
    if(o.bankNameIsSet())
        j["bankName"] = o.m_BankName;
    if(o.routingNumberIsSet())
        j["routingNumber"] = o.m_RoutingNumber;
    if(o.isDefaultPaymentMethodIsSet())
        j["isDefaultPaymentMethod"] = o.m_IsDefaultPaymentMethod;
    if(o.accountNameIsSet())
        j["accountName"] = o.m_AccountName;
    if(o.paymentMethodNicknameIsSet())
        j["paymentMethodNickname"] = o.m_PaymentMethodNickname;
    if(o.taxIdIsSet())
        j["taxId"] = o.m_TaxId;
    if(o.returningIsSet())
        j["returning"] = o.m_Returning;
    
}

void from_json(const nlohmann::json& j, PaymentTypesResponse& o)
{
    if(j.find("valid") != j.end())
    {
        j.at("valid").get_to(o.m_Valid);
        o.m_ValidIsSet = true;
    } 
    if(j.find("message") != j.end())
    {
        j.at("message").get_to(o.m_Message);
        o.m_MessageIsSet = true;
    } 
    if(j.find("version") != j.end())
    {
        j.at("version").get_to(o.m_Version);
        o.m_VersionIsSet = true;
    } 
    if(j.find("serializeNulls") != j.end())
    {
        j.at("serializeNulls").get_to(o.m_SerializeNulls);
        o.m_SerializeNullsIsSet = true;
    } 
    if(j.find("startTimeLog") != j.end())
    {
        j.at("startTimeLog").get_to(o.m_StartTimeLog);
        o.m_StartTimeLogIsSet = true;
    } 
    if(j.find("errorCode") != j.end())
    {
        j.at("errorCode").get_to(o.m_ErrorCode);
        o.m_ErrorCodeIsSet = true;
    } 
    if(j.find("request") != j.end())
    {
        j.at("request").get_to(o.m_Request);
        o.m_RequestIsSet = true;
    } 
    if(j.find("creditCardOnFile") != j.end())
    {
        j.at("creditCardOnFile").get_to(o.m_CreditCardOnFile);
        o.m_CreditCardOnFileIsSet = true;
    } 
    if(j.find("creditCardNumber") != j.end())
    {
        j.at("creditCardNumber").get_to(o.m_CreditCardNumber);
        o.m_CreditCardNumberIsSet = true;
    } 
    if(j.find("creditCardExpirationMonth") != j.end())
    {
        j.at("creditCardExpirationMonth").get_to(o.m_CreditCardExpirationMonth);
        o.m_CreditCardExpirationMonthIsSet = true;
    } 
    if(j.find("creditCardExpirationYear") != j.end())
    {
        j.at("creditCardExpirationYear").get_to(o.m_CreditCardExpirationYear);
        o.m_CreditCardExpirationYearIsSet = true;
    } 
    if(j.find("pointsOnFile") != j.end())
    {
        j.at("pointsOnFile").get_to(o.m_PointsOnFile);
        o.m_PointsOnFileIsSet = true;
    } 
    if(j.find("pointsAmount") != j.end())
    {
        j.at("pointsAmount").get_to(o.m_PointsAmount);
        o.m_PointsAmountIsSet = true;
    } 
    if(j.find("account") != j.end())
    {
        j.at("account").get_to(o.m_Account);
        o.m_AccountIsSet = true;
    } 
    if(j.find("firstName") != j.end())
    {
        j.at("firstName").get_to(o.m_FirstName);
        o.m_FirstNameIsSet = true;
    } 
    if(j.find("lastName") != j.end())
    {
        j.at("lastName").get_to(o.m_LastName);
        o.m_LastNameIsSet = true;
    } 
    if(j.find("address") != j.end())
    {
        j.at("address").get_to(o.m_Address);
        o.m_AddressIsSet = true;
    } 
    if(j.find("city") != j.end())
    {
        j.at("city").get_to(o.m_City);
        o.m_CityIsSet = true;
    } 
    if(j.find("state") != j.end())
    {
        j.at("state").get_to(o.m_State);
        o.m_StateIsSet = true;
    } 
    if(j.find("postalCode") != j.end())
    {
        j.at("postalCode").get_to(o.m_PostalCode);
        o.m_PostalCodeIsSet = true;
    } 
    if(j.find("phone") != j.end())
    {
        j.at("phone").get_to(o.m_Phone);
        o.m_PhoneIsSet = true;
    } 
    if(j.find("provider") != j.end())
    {
        j.at("provider").get_to(o.m_Provider);
        o.m_ProviderIsSet = true;
    } 
    if(j.find("paymentMethodId") != j.end())
    {
        j.at("paymentMethodId").get_to(o.m_PaymentMethodId);
        o.m_PaymentMethodIdIsSet = true;
    } 
    if(j.find("validated") != j.end())
    {
        j.at("validated").get_to(o.m_Validated);
        o.m_ValidatedIsSet = true;
    } 
    if(j.find("accountNumber") != j.end())
    {
        j.at("accountNumber").get_to(o.m_AccountNumber);
        o.m_AccountNumberIsSet = true;
    } 
    if(j.find("bankName") != j.end())
    {
        j.at("bankName").get_to(o.m_BankName);
        o.m_BankNameIsSet = true;
    } 
    if(j.find("routingNumber") != j.end())
    {
        j.at("routingNumber").get_to(o.m_RoutingNumber);
        o.m_RoutingNumberIsSet = true;
    } 
    if(j.find("isDefaultPaymentMethod") != j.end())
    {
        j.at("isDefaultPaymentMethod").get_to(o.m_IsDefaultPaymentMethod);
        o.m_IsDefaultPaymentMethodIsSet = true;
    } 
    if(j.find("accountName") != j.end())
    {
        j.at("accountName").get_to(o.m_AccountName);
        o.m_AccountNameIsSet = true;
    } 
    if(j.find("paymentMethodNickname") != j.end())
    {
        j.at("paymentMethodNickname").get_to(o.m_PaymentMethodNickname);
        o.m_PaymentMethodNicknameIsSet = true;
    } 
    if(j.find("taxId") != j.end())
    {
        j.at("taxId").get_to(o.m_TaxId);
        o.m_TaxIdIsSet = true;
    } 
    if(j.find("returning") != j.end())
    {
        j.at("returning").get_to(o.m_Returning);
        o.m_ReturningIsSet = true;
    } 
    
}

bool PaymentTypesResponse::isValid() const
{
    return m_Valid;
}
void PaymentTypesResponse::setValid(bool const value)
{
    m_Valid = value;
    m_ValidIsSet = true;
}
bool PaymentTypesResponse::validIsSet() const
{
    return m_ValidIsSet;
}
void PaymentTypesResponse::unsetValid()
{
    m_ValidIsSet = false;
}
std::string PaymentTypesResponse::getMessage() const
{
    return m_Message;
}
void PaymentTypesResponse::setMessage(std::string const& value)
{
    m_Message = value;
    m_MessageIsSet = true;
}
bool PaymentTypesResponse::messageIsSet() const
{
    return m_MessageIsSet;
}
void PaymentTypesResponse::unsetMessage()
{
    m_MessageIsSet = false;
}
double PaymentTypesResponse::getVersion() const
{
    return m_Version;
}
void PaymentTypesResponse::setVersion(double const value)
{
    m_Version = value;
    m_VersionIsSet = true;
}
bool PaymentTypesResponse::versionIsSet() const
{
    return m_VersionIsSet;
}
void PaymentTypesResponse::unsetVersion()
{
    m_VersionIsSet = false;
}
bool PaymentTypesResponse::isSerializeNulls() const
{
    return m_SerializeNulls;
}
void PaymentTypesResponse::setSerializeNulls(bool const value)
{
    m_SerializeNulls = value;
    m_SerializeNullsIsSet = true;
}
bool PaymentTypesResponse::serializeNullsIsSet() const
{
    return m_SerializeNullsIsSet;
}
void PaymentTypesResponse::unsetSerializeNulls()
{
    m_SerializeNullsIsSet = false;
}
int64_t PaymentTypesResponse::getStartTimeLog() const
{
    return m_StartTimeLog;
}
void PaymentTypesResponse::setStartTimeLog(int64_t const value)
{
    m_StartTimeLog = value;
    m_StartTimeLogIsSet = true;
}
bool PaymentTypesResponse::startTimeLogIsSet() const
{
    return m_StartTimeLogIsSet;
}
void PaymentTypesResponse::unsetStartTimeLog()
{
    m_StartTimeLogIsSet = false;
}
std::string PaymentTypesResponse::getErrorCode() const
{
    return m_ErrorCode;
}
void PaymentTypesResponse::setErrorCode(std::string const& value)
{
    m_ErrorCode = value;
    m_ErrorCodeIsSet = true;
}
bool PaymentTypesResponse::errorCodeIsSet() const
{
    return m_ErrorCodeIsSet;
}
void PaymentTypesResponse::unsetErrorCode()
{
    m_ErrorCodeIsSet = false;
}
std::vector<org::openapitools::server::model::NameStringValueResponse> PaymentTypesResponse::getRequest() const
{
    return m_Request;
}
void PaymentTypesResponse::setRequest(std::vector<org::openapitools::server::model::NameStringValueResponse> const& value)
{
    m_Request = value;
    m_RequestIsSet = true;
}
bool PaymentTypesResponse::requestIsSet() const
{
    return m_RequestIsSet;
}
void PaymentTypesResponse::unsetRequest()
{
    m_RequestIsSet = false;
}
bool PaymentTypesResponse::isCreditCardOnFile() const
{
    return m_CreditCardOnFile;
}
void PaymentTypesResponse::setCreditCardOnFile(bool const value)
{
    m_CreditCardOnFile = value;
    m_CreditCardOnFileIsSet = true;
}
bool PaymentTypesResponse::creditCardOnFileIsSet() const
{
    return m_CreditCardOnFileIsSet;
}
void PaymentTypesResponse::unsetCreditCardOnFile()
{
    m_CreditCardOnFileIsSet = false;
}
std::string PaymentTypesResponse::getCreditCardNumber() const
{
    return m_CreditCardNumber;
}
void PaymentTypesResponse::setCreditCardNumber(std::string const& value)
{
    m_CreditCardNumber = value;
    m_CreditCardNumberIsSet = true;
}
bool PaymentTypesResponse::creditCardNumberIsSet() const
{
    return m_CreditCardNumberIsSet;
}
void PaymentTypesResponse::unsetCreditCardNumber()
{
    m_CreditCardNumberIsSet = false;
}
std::string PaymentTypesResponse::getCreditCardExpirationMonth() const
{
    return m_CreditCardExpirationMonth;
}
void PaymentTypesResponse::setCreditCardExpirationMonth(std::string const& value)
{
    m_CreditCardExpirationMonth = value;
    m_CreditCardExpirationMonthIsSet = true;
}
bool PaymentTypesResponse::creditCardExpirationMonthIsSet() const
{
    return m_CreditCardExpirationMonthIsSet;
}
void PaymentTypesResponse::unsetCreditCardExpirationMonth()
{
    m_CreditCardExpirationMonthIsSet = false;
}
std::string PaymentTypesResponse::getCreditCardExpirationYear() const
{
    return m_CreditCardExpirationYear;
}
void PaymentTypesResponse::setCreditCardExpirationYear(std::string const& value)
{
    m_CreditCardExpirationYear = value;
    m_CreditCardExpirationYearIsSet = true;
}
bool PaymentTypesResponse::creditCardExpirationYearIsSet() const
{
    return m_CreditCardExpirationYearIsSet;
}
void PaymentTypesResponse::unsetCreditCardExpirationYear()
{
    m_CreditCardExpirationYearIsSet = false;
}
bool PaymentTypesResponse::isPointsOnFile() const
{
    return m_PointsOnFile;
}
void PaymentTypesResponse::setPointsOnFile(bool const value)
{
    m_PointsOnFile = value;
    m_PointsOnFileIsSet = true;
}
bool PaymentTypesResponse::pointsOnFileIsSet() const
{
    return m_PointsOnFileIsSet;
}
void PaymentTypesResponse::unsetPointsOnFile()
{
    m_PointsOnFileIsSet = false;
}
double PaymentTypesResponse::getPointsAmount() const
{
    return m_PointsAmount;
}
void PaymentTypesResponse::setPointsAmount(double const value)
{
    m_PointsAmount = value;
    m_PointsAmountIsSet = true;
}
bool PaymentTypesResponse::pointsAmountIsSet() const
{
    return m_PointsAmountIsSet;
}
void PaymentTypesResponse::unsetPointsAmount()
{
    m_PointsAmountIsSet = false;
}
org::openapitools::server::model::AccountShortResponse PaymentTypesResponse::getAccount() const
{
    return m_Account;
}
void PaymentTypesResponse::setAccount(org::openapitools::server::model::AccountShortResponse const& value)
{
    m_Account = value;
    m_AccountIsSet = true;
}
bool PaymentTypesResponse::accountIsSet() const
{
    return m_AccountIsSet;
}
void PaymentTypesResponse::unsetAccount()
{
    m_AccountIsSet = false;
}
std::string PaymentTypesResponse::getFirstName() const
{
    return m_FirstName;
}
void PaymentTypesResponse::setFirstName(std::string const& value)
{
    m_FirstName = value;
    m_FirstNameIsSet = true;
}
bool PaymentTypesResponse::firstNameIsSet() const
{
    return m_FirstNameIsSet;
}
void PaymentTypesResponse::unsetFirstName()
{
    m_FirstNameIsSet = false;
}
std::string PaymentTypesResponse::getLastName() const
{
    return m_LastName;
}
void PaymentTypesResponse::setLastName(std::string const& value)
{
    m_LastName = value;
    m_LastNameIsSet = true;
}
bool PaymentTypesResponse::lastNameIsSet() const
{
    return m_LastNameIsSet;
}
void PaymentTypesResponse::unsetLastName()
{
    m_LastNameIsSet = false;
}
std::string PaymentTypesResponse::getAddress() const
{
    return m_Address;
}
void PaymentTypesResponse::setAddress(std::string const& value)
{
    m_Address = value;
    m_AddressIsSet = true;
}
bool PaymentTypesResponse::addressIsSet() const
{
    return m_AddressIsSet;
}
void PaymentTypesResponse::unsetAddress()
{
    m_AddressIsSet = false;
}
std::string PaymentTypesResponse::getCity() const
{
    return m_City;
}
void PaymentTypesResponse::setCity(std::string const& value)
{
    m_City = value;
    m_CityIsSet = true;
}
bool PaymentTypesResponse::cityIsSet() const
{
    return m_CityIsSet;
}
void PaymentTypesResponse::unsetCity()
{
    m_CityIsSet = false;
}
std::string PaymentTypesResponse::getState() const
{
    return m_State;
}
void PaymentTypesResponse::setState(std::string const& value)
{
    m_State = value;
    m_StateIsSet = true;
}
bool PaymentTypesResponse::stateIsSet() const
{
    return m_StateIsSet;
}
void PaymentTypesResponse::unsetState()
{
    m_StateIsSet = false;
}
std::string PaymentTypesResponse::getPostalCode() const
{
    return m_PostalCode;
}
void PaymentTypesResponse::setPostalCode(std::string const& value)
{
    m_PostalCode = value;
    m_PostalCodeIsSet = true;
}
bool PaymentTypesResponse::postalCodeIsSet() const
{
    return m_PostalCodeIsSet;
}
void PaymentTypesResponse::unsetPostalCode()
{
    m_PostalCodeIsSet = false;
}
std::string PaymentTypesResponse::getPhone() const
{
    return m_Phone;
}
void PaymentTypesResponse::setPhone(std::string const& value)
{
    m_Phone = value;
    m_PhoneIsSet = true;
}
bool PaymentTypesResponse::phoneIsSet() const
{
    return m_PhoneIsSet;
}
void PaymentTypesResponse::unsetPhone()
{
    m_PhoneIsSet = false;
}
std::string PaymentTypesResponse::getProvider() const
{
    return m_Provider;
}
void PaymentTypesResponse::setProvider(std::string const& value)
{
    m_Provider = value;
    m_ProviderIsSet = true;
}
bool PaymentTypesResponse::providerIsSet() const
{
    return m_ProviderIsSet;
}
void PaymentTypesResponse::unsetProvider()
{
    m_ProviderIsSet = false;
}
int64_t PaymentTypesResponse::getPaymentMethodId() const
{
    return m_PaymentMethodId;
}
void PaymentTypesResponse::setPaymentMethodId(int64_t const value)
{
    m_PaymentMethodId = value;
    m_PaymentMethodIdIsSet = true;
}
bool PaymentTypesResponse::paymentMethodIdIsSet() const
{
    return m_PaymentMethodIdIsSet;
}
void PaymentTypesResponse::unsetPaymentMethodId()
{
    m_PaymentMethodIdIsSet = false;
}
bool PaymentTypesResponse::isValidated() const
{
    return m_Validated;
}
void PaymentTypesResponse::setValidated(bool const value)
{
    m_Validated = value;
    m_ValidatedIsSet = true;
}
bool PaymentTypesResponse::validatedIsSet() const
{
    return m_ValidatedIsSet;
}
void PaymentTypesResponse::unsetValidated()
{
    m_ValidatedIsSet = false;
}
std::string PaymentTypesResponse::getAccountNumber() const
{
    return m_AccountNumber;
}
void PaymentTypesResponse::setAccountNumber(std::string const& value)
{
    m_AccountNumber = value;
    m_AccountNumberIsSet = true;
}
bool PaymentTypesResponse::accountNumberIsSet() const
{
    return m_AccountNumberIsSet;
}
void PaymentTypesResponse::unsetAccountNumber()
{
    m_AccountNumberIsSet = false;
}
std::string PaymentTypesResponse::getBankName() const
{
    return m_BankName;
}
void PaymentTypesResponse::setBankName(std::string const& value)
{
    m_BankName = value;
    m_BankNameIsSet = true;
}
bool PaymentTypesResponse::bankNameIsSet() const
{
    return m_BankNameIsSet;
}
void PaymentTypesResponse::unsetBankName()
{
    m_BankNameIsSet = false;
}
std::string PaymentTypesResponse::getRoutingNumber() const
{
    return m_RoutingNumber;
}
void PaymentTypesResponse::setRoutingNumber(std::string const& value)
{
    m_RoutingNumber = value;
    m_RoutingNumberIsSet = true;
}
bool PaymentTypesResponse::routingNumberIsSet() const
{
    return m_RoutingNumberIsSet;
}
void PaymentTypesResponse::unsetRoutingNumber()
{
    m_RoutingNumberIsSet = false;
}
bool PaymentTypesResponse::isIsDefaultPaymentMethod() const
{
    return m_IsDefaultPaymentMethod;
}
void PaymentTypesResponse::setIsDefaultPaymentMethod(bool const value)
{
    m_IsDefaultPaymentMethod = value;
    m_IsDefaultPaymentMethodIsSet = true;
}
bool PaymentTypesResponse::isDefaultPaymentMethodIsSet() const
{
    return m_IsDefaultPaymentMethodIsSet;
}
void PaymentTypesResponse::unsetIsDefaultPaymentMethod()
{
    m_IsDefaultPaymentMethodIsSet = false;
}
std::string PaymentTypesResponse::getAccountName() const
{
    return m_AccountName;
}
void PaymentTypesResponse::setAccountName(std::string const& value)
{
    m_AccountName = value;
    m_AccountNameIsSet = true;
}
bool PaymentTypesResponse::accountNameIsSet() const
{
    return m_AccountNameIsSet;
}
void PaymentTypesResponse::unsetAccountName()
{
    m_AccountNameIsSet = false;
}
std::string PaymentTypesResponse::getPaymentMethodNickname() const
{
    return m_PaymentMethodNickname;
}
void PaymentTypesResponse::setPaymentMethodNickname(std::string const& value)
{
    m_PaymentMethodNickname = value;
    m_PaymentMethodNicknameIsSet = true;
}
bool PaymentTypesResponse::paymentMethodNicknameIsSet() const
{
    return m_PaymentMethodNicknameIsSet;
}
void PaymentTypesResponse::unsetPaymentMethodNickname()
{
    m_PaymentMethodNicknameIsSet = false;
}
std::string PaymentTypesResponse::getTaxId() const
{
    return m_TaxId;
}
void PaymentTypesResponse::setTaxId(std::string const& value)
{
    m_TaxId = value;
    m_TaxIdIsSet = true;
}
bool PaymentTypesResponse::taxIdIsSet() const
{
    return m_TaxIdIsSet;
}
void PaymentTypesResponse::unsetTaxId()
{
    m_TaxIdIsSet = false;
}
std::string PaymentTypesResponse::getReturning() const
{
    return m_Returning;
}
void PaymentTypesResponse::setReturning(std::string const& value)
{
    m_Returning = value;
    m_ReturningIsSet = true;
}
bool PaymentTypesResponse::returningIsSet() const
{
    return m_ReturningIsSet;
}
void PaymentTypesResponse::unsetReturning()
{
    m_ReturningIsSet = false;
}


} // namespace org::openapitools::server::model

