/**
* Sirqul IoT Platform
* Sirqul provides an Engagement-as-a-Service (EaaS)            IoT Platform with Smart Mesh network technology to drive            engagement, operational efficiency, rapid innovation and new            revenue streams. Please visit https://dev.sirqul.com/ for more            documents, examples, and sample applications.<?php $a = htmlspecialchars($_GET['appKey']);$b = htmlspecialchars($_GET['appRestKey']);?>
*
* The version of the OpenAPI document: 3.16
* Contact: info@sirqul.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * QuestionResponse.h
 *
 * 
 */

#ifndef QuestionResponse_H_
#define QuestionResponse_H_


#include "AnswerResponse.h"
#include "ScoreListResponse.h"
#include "TicketListResponse.h"
#include <string>
#include "AccountShortResponse.h"
#include <vector>
#include "AssetShortResponse.h"
#include <nlohmann/json.hpp>

namespace org::openapitools::server::model
{

/// <summary>
/// 
/// </summary>
class  QuestionResponse
{
public:
    QuestionResponse();
    virtual ~QuestionResponse() = default;


    /// <summary>
    /// Validate the current data in the model. Throws a ValidationException on failure.
    /// </summary>
    void validate() const;

    /// <summary>
    /// Validate the current data in the model. Returns false on error and writes an error
    /// message into the given stringstream.
    /// </summary>
    bool validate(std::stringstream& msg) const;

    /// <summary>
    /// Helper overload for validate. Used when one model stores another model and calls it's validate.
    /// Not meant to be called outside that case.
    /// </summary>
    bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

    bool operator==(const QuestionResponse& rhs) const;
    bool operator!=(const QuestionResponse& rhs) const;

    /////////////////////////////////////////////
    /// QuestionResponse members

    /// <summary>
    /// 
    /// </summary>
    int64_t getId() const;
    void setId(int64_t const value);
    bool idIsSet() const;
    void unsetId();
    /// <summary>
    /// 
    /// </summary>
    std::string getQuestion() const;
    void setQuestion(std::string const& value);
    bool questionIsSet() const;
    void unsetQuestion();
    /// <summary>
    /// 
    /// </summary>
    org::openapitools::server::model::AssetShortResponse getImage() const;
    void setImage(org::openapitools::server::model::AssetShortResponse const& value);
    bool imageIsSet() const;
    void unsetImage();
    /// <summary>
    /// 
    /// </summary>
    std::string getVideoURL() const;
    void setVideoURL(std::string const& value);
    bool videoURLIsSet() const;
    void unsetVideoURL();
    /// <summary>
    /// 
    /// </summary>
    bool isActive() const;
    void setActive(bool const value);
    bool activeIsSet() const;
    void unsetActive();
    /// <summary>
    /// 
    /// </summary>
    std::vector<org::openapitools::server::model::AnswerResponse> getAnswers() const;
    void setAnswers(std::vector<org::openapitools::server::model::AnswerResponse> const& value);
    bool answersIsSet() const;
    void unsetAnswers();
    /// <summary>
    /// 
    /// </summary>
    org::openapitools::server::model::ScoreListResponse getScores() const;
    void setScores(org::openapitools::server::model::ScoreListResponse const& value);
    bool scoresIsSet() const;
    void unsetScores();
    /// <summary>
    /// 
    /// </summary>
    org::openapitools::server::model::TicketListResponse getTickets() const;
    void setTickets(org::openapitools::server::model::TicketListResponse const& value);
    bool ticketsIsSet() const;
    void unsetTickets();
    /// <summary>
    /// 
    /// </summary>
    org::openapitools::server::model::AccountShortResponse getOwner() const;
    void setOwner(org::openapitools::server::model::AccountShortResponse const& value);
    bool ownerIsSet() const;
    void unsetOwner();
    /// <summary>
    /// 
    /// </summary>
    org::openapitools::server::model::AssetShortResponse getIcon() const;
    void setIcon(org::openapitools::server::model::AssetShortResponse const& value);
    bool iconIsSet() const;
    void unsetIcon();
    /// <summary>
    /// 
    /// </summary>
    std::string getAuthorOverride() const;
    void setAuthorOverride(std::string const& value);
    bool authorOverrideIsSet() const;
    void unsetAuthorOverride();
    /// <summary>
    /// 
    /// </summary>
    int64_t getUpdatedDate() const;
    void setUpdatedDate(int64_t const value);
    bool updatedDateIsSet() const;
    void unsetUpdatedDate();
    /// <summary>
    /// 
    /// </summary>
    int64_t getStartDate() const;
    void setStartDate(int64_t const value);
    bool startDateIsSet() const;
    void unsetStartDate();
    /// <summary>
    /// 
    /// </summary>
    int64_t getEndDate() const;
    void setEndDate(int64_t const value);
    bool endDateIsSet() const;
    void unsetEndDate();
    /// <summary>
    /// 
    /// </summary>
    int64_t getCreatedDate() const;
    void setCreatedDate(int64_t const value);
    bool createdDateIsSet() const;
    void unsetCreatedDate();
    /// <summary>
    /// 
    /// </summary>
    std::string getTags() const;
    void setTags(std::string const& value);
    bool tagsIsSet() const;
    void unsetTags();
    /// <summary>
    /// 
    /// </summary>
    bool isAllocateTickets() const;
    void setAllocateTickets(bool const value);
    bool allocateTicketsIsSet() const;
    void unsetAllocateTickets();
    /// <summary>
    /// 
    /// </summary>
    std::string getTicketType() const;
    void setTicketType(std::string const& value);
    bool ticketTypeIsSet() const;
    void unsetTicketType();
    /// <summary>
    /// 
    /// </summary>
    int64_t getTicketCount() const;
    void setTicketCount(int64_t const value);
    bool ticketCountIsSet() const;
    void unsetTicketCount();
    /// <summary>
    /// 
    /// </summary>
    int64_t getPoints() const;
    void setPoints(int64_t const value);
    bool pointsIsSet() const;
    void unsetPoints();

    friend  void to_json(nlohmann::json& j, const QuestionResponse& o);
    friend  void from_json(const nlohmann::json& j, QuestionResponse& o);
protected:
    int64_t m_Id;
    bool m_IdIsSet;
    std::string m_Question;
    bool m_QuestionIsSet;
    org::openapitools::server::model::AssetShortResponse m_Image;
    bool m_ImageIsSet;
    std::string m_VideoURL;
    bool m_VideoURLIsSet;
    bool m_Active;
    bool m_ActiveIsSet;
    std::vector<org::openapitools::server::model::AnswerResponse> m_Answers;
    bool m_AnswersIsSet;
    org::openapitools::server::model::ScoreListResponse m_Scores;
    bool m_ScoresIsSet;
    org::openapitools::server::model::TicketListResponse m_Tickets;
    bool m_TicketsIsSet;
    org::openapitools::server::model::AccountShortResponse m_Owner;
    bool m_OwnerIsSet;
    org::openapitools::server::model::AssetShortResponse m_Icon;
    bool m_IconIsSet;
    std::string m_AuthorOverride;
    bool m_AuthorOverrideIsSet;
    int64_t m_UpdatedDate;
    bool m_UpdatedDateIsSet;
    int64_t m_StartDate;
    bool m_StartDateIsSet;
    int64_t m_EndDate;
    bool m_EndDateIsSet;
    int64_t m_CreatedDate;
    bool m_CreatedDateIsSet;
    std::string m_Tags;
    bool m_TagsIsSet;
    bool m_AllocateTickets;
    bool m_AllocateTicketsIsSet;
    std::string m_TicketType;
    bool m_TicketTypeIsSet;
    int64_t m_TicketCount;
    bool m_TicketCountIsSet;
    int64_t m_Points;
    bool m_PointsIsSet;
    
};

} // namespace org::openapitools::server::model

#endif /* QuestionResponse_H_ */
