/**
* Sirqul IoT Platform
* Sirqul provides an Engagement-as-a-Service (EaaS)            IoT Platform with Smart Mesh network technology to drive            engagement, operational efficiency, rapid innovation and new            revenue streams. Please visit https://dev.sirqul.com/ for more            documents, examples, and sample applications.<?php $a = htmlspecialchars($_GET['appKey']);$b = htmlspecialchars($_GET['appRestKey']);?>
*
* The version of the OpenAPI document: 3.16
* Contact: info@sirqul.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * WordzWordResponse.h
 *
 * 
 */

#ifndef WordzWordResponse_H_
#define WordzWordResponse_H_


#include "ScoreListResponse.h"
#include <string>
#include "AssetShortResponse.h"
#include <nlohmann/json.hpp>

namespace org::openapitools::server::model
{

/// <summary>
/// 
/// </summary>
class  WordzWordResponse
{
public:
    WordzWordResponse();
    virtual ~WordzWordResponse() = default;


    /// <summary>
    /// Validate the current data in the model. Throws a ValidationException on failure.
    /// </summary>
    void validate() const;

    /// <summary>
    /// Validate the current data in the model. Returns false on error and writes an error
    /// message into the given stringstream.
    /// </summary>
    bool validate(std::stringstream& msg) const;

    /// <summary>
    /// Helper overload for validate. Used when one model stores another model and calls it's validate.
    /// Not meant to be called outside that case.
    /// </summary>
    bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

    bool operator==(const WordzWordResponse& rhs) const;
    bool operator!=(const WordzWordResponse& rhs) const;

    /////////////////////////////////////////////
    /// WordzWordResponse members

    /// <summary>
    /// 
    /// </summary>
    int64_t getId() const;
    void setId(int64_t const value);
    bool idIsSet() const;
    void unsetId();
    /// <summary>
    /// 
    /// </summary>
    std::string getWord() const;
    void setWord(std::string const& value);
    bool wordIsSet() const;
    void unsetWord();
    /// <summary>
    /// 
    /// </summary>
    std::string getDefinition() const;
    void setDefinition(std::string const& value);
    bool definitionIsSet() const;
    void unsetDefinition();
    /// <summary>
    /// 
    /// </summary>
    org::openapitools::server::model::ScoreListResponse getScores() const;
    void setScores(org::openapitools::server::model::ScoreListResponse const& value);
    bool scoresIsSet() const;
    void unsetScores();
    /// <summary>
    /// 
    /// </summary>
    org::openapitools::server::model::AssetShortResponse getIcon() const;
    void setIcon(org::openapitools::server::model::AssetShortResponse const& value);
    bool iconIsSet() const;
    void unsetIcon();
    /// <summary>
    /// 
    /// </summary>
    org::openapitools::server::model::AssetShortResponse getImage() const;
    void setImage(org::openapitools::server::model::AssetShortResponse const& value);
    bool imageIsSet() const;
    void unsetImage();
    /// <summary>
    /// 
    /// </summary>
    std::string getAuthorOverride() const;
    void setAuthorOverride(std::string const& value);
    bool authorOverrideIsSet() const;
    void unsetAuthorOverride();
    /// <summary>
    /// 
    /// </summary>
    int64_t getUpdatedDate() const;
    void setUpdatedDate(int64_t const value);
    bool updatedDateIsSet() const;
    void unsetUpdatedDate();
    /// <summary>
    /// 
    /// </summary>
    int64_t getStartDate() const;
    void setStartDate(int64_t const value);
    bool startDateIsSet() const;
    void unsetStartDate();
    /// <summary>
    /// 
    /// </summary>
    int64_t getEndDate() const;
    void setEndDate(int64_t const value);
    bool endDateIsSet() const;
    void unsetEndDate();
    /// <summary>
    /// 
    /// </summary>
    int64_t getCreatedDate() const;
    void setCreatedDate(int64_t const value);
    bool createdDateIsSet() const;
    void unsetCreatedDate();
    /// <summary>
    /// 
    /// </summary>
    bool isActive() const;
    void setActive(bool const value);
    bool activeIsSet() const;
    void unsetActive();
    /// <summary>
    /// 
    /// </summary>
    bool isAllocateTickets() const;
    void setAllocateTickets(bool const value);
    bool allocateTicketsIsSet() const;
    void unsetAllocateTickets();
    /// <summary>
    /// 
    /// </summary>
    std::string getTicketType() const;
    void setTicketType(std::string const& value);
    bool ticketTypeIsSet() const;
    void unsetTicketType();
    /// <summary>
    /// 
    /// </summary>
    int64_t getTicketCount() const;
    void setTicketCount(int64_t const value);
    bool ticketCountIsSet() const;
    void unsetTicketCount();
    /// <summary>
    /// 
    /// </summary>
    int64_t getPoints() const;
    void setPoints(int64_t const value);
    bool pointsIsSet() const;
    void unsetPoints();

    friend  void to_json(nlohmann::json& j, const WordzWordResponse& o);
    friend  void from_json(const nlohmann::json& j, WordzWordResponse& o);
protected:
    int64_t m_Id;
    bool m_IdIsSet;
    std::string m_Word;
    bool m_WordIsSet;
    std::string m_Definition;
    bool m_DefinitionIsSet;
    org::openapitools::server::model::ScoreListResponse m_Scores;
    bool m_ScoresIsSet;
    org::openapitools::server::model::AssetShortResponse m_Icon;
    bool m_IconIsSet;
    org::openapitools::server::model::AssetShortResponse m_Image;
    bool m_ImageIsSet;
    std::string m_AuthorOverride;
    bool m_AuthorOverrideIsSet;
    int64_t m_UpdatedDate;
    bool m_UpdatedDateIsSet;
    int64_t m_StartDate;
    bool m_StartDateIsSet;
    int64_t m_EndDate;
    bool m_EndDateIsSet;
    int64_t m_CreatedDate;
    bool m_CreatedDateIsSet;
    bool m_Active;
    bool m_ActiveIsSet;
    bool m_AllocateTickets;
    bool m_AllocateTicketsIsSet;
    std::string m_TicketType;
    bool m_TicketTypeIsSet;
    int64_t m_TicketCount;
    bool m_TicketCountIsSet;
    int64_t m_Points;
    bool m_PointsIsSet;
    
};

} // namespace org::openapitools::server::model

#endif /* WordzWordResponse_H_ */
