# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model import Model
from openapi_server import util


class PreferredLocationResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, owner_id: int=None, on_date: str=None, on_date_milli: int=None, hour: int=None, latitude: float=None, longitude: float=None, distance: float=None, duration: int=None, start_step_id: int=None, end_step_id: int=None):
        """PreferredLocationResponse - a model defined in OpenAPI

        :param owner_id: The owner_id of this PreferredLocationResponse.
        :param on_date: The on_date of this PreferredLocationResponse.
        :param on_date_milli: The on_date_milli of this PreferredLocationResponse.
        :param hour: The hour of this PreferredLocationResponse.
        :param latitude: The latitude of this PreferredLocationResponse.
        :param longitude: The longitude of this PreferredLocationResponse.
        :param distance: The distance of this PreferredLocationResponse.
        :param duration: The duration of this PreferredLocationResponse.
        :param start_step_id: The start_step_id of this PreferredLocationResponse.
        :param end_step_id: The end_step_id of this PreferredLocationResponse.
        """
        self.openapi_types = {
            'owner_id': int,
            'on_date': str,
            'on_date_milli': int,
            'hour': int,
            'latitude': float,
            'longitude': float,
            'distance': float,
            'duration': int,
            'start_step_id': int,
            'end_step_id': int
        }

        self.attribute_map = {
            'owner_id': 'ownerId',
            'on_date': 'onDate',
            'on_date_milli': 'onDateMilli',
            'hour': 'hour',
            'latitude': 'latitude',
            'longitude': 'longitude',
            'distance': 'distance',
            'duration': 'duration',
            'start_step_id': 'startStepId',
            'end_step_id': 'endStepId'
        }

        self._owner_id = owner_id
        self._on_date = on_date
        self._on_date_milli = on_date_milli
        self._hour = hour
        self._latitude = latitude
        self._longitude = longitude
        self._distance = distance
        self._duration = duration
        self._start_step_id = start_step_id
        self._end_step_id = end_step_id

    @classmethod
    def from_dict(cls, dikt: dict) -> 'PreferredLocationResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The PreferredLocationResponse of this PreferredLocationResponse.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def owner_id(self):
        """Gets the owner_id of this PreferredLocationResponse.


        :return: The owner_id of this PreferredLocationResponse.
        :rtype: int
        """
        return self._owner_id

    @owner_id.setter
    def owner_id(self, owner_id):
        """Sets the owner_id of this PreferredLocationResponse.


        :param owner_id: The owner_id of this PreferredLocationResponse.
        :type owner_id: int
        """

        self._owner_id = owner_id

    @property
    def on_date(self):
        """Gets the on_date of this PreferredLocationResponse.


        :return: The on_date of this PreferredLocationResponse.
        :rtype: str
        """
        return self._on_date

    @on_date.setter
    def on_date(self, on_date):
        """Sets the on_date of this PreferredLocationResponse.


        :param on_date: The on_date of this PreferredLocationResponse.
        :type on_date: str
        """

        self._on_date = on_date

    @property
    def on_date_milli(self):
        """Gets the on_date_milli of this PreferredLocationResponse.


        :return: The on_date_milli of this PreferredLocationResponse.
        :rtype: int
        """
        return self._on_date_milli

    @on_date_milli.setter
    def on_date_milli(self, on_date_milli):
        """Sets the on_date_milli of this PreferredLocationResponse.


        :param on_date_milli: The on_date_milli of this PreferredLocationResponse.
        :type on_date_milli: int
        """

        self._on_date_milli = on_date_milli

    @property
    def hour(self):
        """Gets the hour of this PreferredLocationResponse.


        :return: The hour of this PreferredLocationResponse.
        :rtype: int
        """
        return self._hour

    @hour.setter
    def hour(self, hour):
        """Sets the hour of this PreferredLocationResponse.


        :param hour: The hour of this PreferredLocationResponse.
        :type hour: int
        """

        self._hour = hour

    @property
    def latitude(self):
        """Gets the latitude of this PreferredLocationResponse.


        :return: The latitude of this PreferredLocationResponse.
        :rtype: float
        """
        return self._latitude

    @latitude.setter
    def latitude(self, latitude):
        """Sets the latitude of this PreferredLocationResponse.


        :param latitude: The latitude of this PreferredLocationResponse.
        :type latitude: float
        """

        self._latitude = latitude

    @property
    def longitude(self):
        """Gets the longitude of this PreferredLocationResponse.


        :return: The longitude of this PreferredLocationResponse.
        :rtype: float
        """
        return self._longitude

    @longitude.setter
    def longitude(self, longitude):
        """Sets the longitude of this PreferredLocationResponse.


        :param longitude: The longitude of this PreferredLocationResponse.
        :type longitude: float
        """

        self._longitude = longitude

    @property
    def distance(self):
        """Gets the distance of this PreferredLocationResponse.


        :return: The distance of this PreferredLocationResponse.
        :rtype: float
        """
        return self._distance

    @distance.setter
    def distance(self, distance):
        """Sets the distance of this PreferredLocationResponse.


        :param distance: The distance of this PreferredLocationResponse.
        :type distance: float
        """

        self._distance = distance

    @property
    def duration(self):
        """Gets the duration of this PreferredLocationResponse.


        :return: The duration of this PreferredLocationResponse.
        :rtype: int
        """
        return self._duration

    @duration.setter
    def duration(self, duration):
        """Sets the duration of this PreferredLocationResponse.


        :param duration: The duration of this PreferredLocationResponse.
        :type duration: int
        """

        self._duration = duration

    @property
    def start_step_id(self):
        """Gets the start_step_id of this PreferredLocationResponse.


        :return: The start_step_id of this PreferredLocationResponse.
        :rtype: int
        """
        return self._start_step_id

    @start_step_id.setter
    def start_step_id(self, start_step_id):
        """Sets the start_step_id of this PreferredLocationResponse.


        :param start_step_id: The start_step_id of this PreferredLocationResponse.
        :type start_step_id: int
        """

        self._start_step_id = start_step_id

    @property
    def end_step_id(self):
        """Gets the end_step_id of this PreferredLocationResponse.


        :return: The end_step_id of this PreferredLocationResponse.
        :rtype: int
        """
        return self._end_step_id

    @end_step_id.setter
    def end_step_id(self, end_step_id):
        """Sets the end_step_id of this PreferredLocationResponse.


        :param end_step_id: The end_step_id of this PreferredLocationResponse.
        :type end_step_id: int
        """

        self._end_step_id = end_step_id
