/**
* Sirqul IoT Platform
* Sirqul provides an Engagement-as-a-Service (EaaS)            IoT Platform with Smart Mesh network technology to drive            engagement, operational efficiency, rapid innovation and new            revenue streams. Please visit https://dev.sirqul.com/ for more            documents, examples, and sample applications.<?php $a = htmlspecialchars($_GET['appKey']);$b = htmlspecialchars($_GET['appRestKey']);?>
*
* The version of the OpenAPI document: 3.16
* Contact: info@sirqul.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

#include "TriggerApi.h"
#include "Helpers.h"

namespace org::openapitools::server::api
{

using namespace org::openapitools::server::helpers;
using namespace org::openapitools::server::model;

const std::string TriggerApi::base = "";

TriggerApi::TriggerApi(const std::shared_ptr<Pistache::Rest::Router>& rtr)
    : ApiBase(rtr)
{}

void TriggerApi::init() {
    setupRoutes();
}

void TriggerApi::setupRoutes() {
    using namespace Pistache::Rest;

    Routes::Post(*router, base + "/api/:version/trigger/create", Routes::bind(&TriggerApi::create_trigger_handler, this));
    Routes::Post(*router, base + "/api/:version/trigger/delete", Routes::bind(&TriggerApi::delete_trigger_handler, this));
    Routes::Get(*router, base + "/api/:version/trigger/get", Routes::bind(&TriggerApi::get_trigger_handler, this));
    Routes::Get(*router, base + "/api/:version/trigger/search", Routes::bind(&TriggerApi::search_triggers_handler, this));
    Routes::Post(*router, base + "/api/:version/trigger/update", Routes::bind(&TriggerApi::update_trigger_handler, this));

    // Default handler, called when a route is not found
    router->addCustomHandler(Routes::bind(&TriggerApi::trigger_api_default_handler, this));
}

void TriggerApi::handleParsingException(const std::exception& ex, Pistache::Http::ResponseWriter &response) const noexcept {
    std::pair<Pistache::Http::Code, std::string> codeAndError = handleParsingException(ex);
    response.send(codeAndError.first, codeAndError.second);
}

std::pair<Pistache::Http::Code, std::string> TriggerApi::handleParsingException(const std::exception& ex) const noexcept {
    try {
        throw;
    } catch (nlohmann::detail::exception &e) {
        return std::make_pair(Pistache::Http::Code::Bad_Request, e.what());
    } catch (org::openapitools::server::helpers::ValidationException &e) {
        return std::make_pair(Pistache::Http::Code::Bad_Request, e.what());
    } catch (std::exception &e) {
        return std::make_pair(Pistache::Http::Code::Internal_Server_Error, e.what());
    }
}

void TriggerApi::handleOperationException(const std::exception& ex, Pistache::Http::ResponseWriter &response) const noexcept {
    std::pair<Pistache::Http::Code, std::string> codeAndError = handleOperationException(ex);
    response.send(codeAndError.first, codeAndError.second);
}

std::pair<Pistache::Http::Code, std::string> TriggerApi::handleOperationException(const std::exception& ex) const noexcept {
    return std::make_pair(Pistache::Http::Code::Internal_Server_Error, ex.what());
}

void TriggerApi::create_trigger_handler(const Pistache::Rest::Request& request, Pistache::Http::ResponseWriter response) {
    try {

        // Getting the path params
        auto version = request.param(":version").as<double>();
        
        
        // Getting the query params
        auto accountIdQuery = request.query().get("accountId");
        std::optional<int64_t> accountId;
        if (accountIdQuery.has_value()) {
            int64_t valueQuery_instance;
            if (fromStringValue(accountIdQuery.value(), valueQuery_instance)) {
                accountId = valueQuery_instance;
            }
        }
        auto nameQuery = request.query().get("name");
        std::optional<std::string> name;
        if (nameQuery.has_value()) {
            std::string valueQuery_instance;
            if (fromStringValue(nameQuery.value(), valueQuery_instance)) {
                name = valueQuery_instance;
            }
        }
        auto appKeyQuery = request.query().get("appKey");
        std::optional<std::string> appKey;
        if (appKeyQuery.has_value()) {
            std::string valueQuery_instance;
            if (fromStringValue(appKeyQuery.value(), valueQuery_instance)) {
                appKey = valueQuery_instance;
            }
        }
        auto groupingIdQuery = request.query().get("groupingId");
        std::optional<std::string> groupingId;
        if (groupingIdQuery.has_value()) {
            std::string valueQuery_instance;
            if (fromStringValue(groupingIdQuery.value(), valueQuery_instance)) {
                groupingId = valueQuery_instance;
            }
        }
        auto endpointURLQuery = request.query().get("endpointURL");
        std::optional<std::string> endpointURL;
        if (endpointURLQuery.has_value()) {
            std::string valueQuery_instance;
            if (fromStringValue(endpointURLQuery.value(), valueQuery_instance)) {
                endpointURL = valueQuery_instance;
            }
        }
        auto payloadQuery = request.query().get("payload");
        std::optional<std::string> payload;
        if (payloadQuery.has_value()) {
            std::string valueQuery_instance;
            if (fromStringValue(payloadQuery.value(), valueQuery_instance)) {
                payload = valueQuery_instance;
            }
        }
        auto scheduledDateQuery = request.query().get("scheduledDate");
        std::optional<int64_t> scheduledDate;
        if (scheduledDateQuery.has_value()) {
            int64_t valueQuery_instance;
            if (fromStringValue(scheduledDateQuery.value(), valueQuery_instance)) {
                scheduledDate = valueQuery_instance;
            }
        }
        auto startDateQuery = request.query().get("startDate");
        std::optional<int64_t> startDate;
        if (startDateQuery.has_value()) {
            int64_t valueQuery_instance;
            if (fromStringValue(startDateQuery.value(), valueQuery_instance)) {
                startDate = valueQuery_instance;
            }
        }
        auto endDateQuery = request.query().get("endDate");
        std::optional<int64_t> endDate;
        if (endDateQuery.has_value()) {
            int64_t valueQuery_instance;
            if (fromStringValue(endDateQuery.value(), valueQuery_instance)) {
                endDate = valueQuery_instance;
            }
        }
        auto cronExpressionQuery = request.query().get("cronExpression");
        std::optional<std::string> cronExpression;
        if (cronExpressionQuery.has_value()) {
            std::string valueQuery_instance;
            if (fromStringValue(cronExpressionQuery.value(), valueQuery_instance)) {
                cronExpression = valueQuery_instance;
            }
        }
        auto conditionalInputQuery = request.query().get("conditionalInput");
        std::optional<std::string> conditionalInput;
        if (conditionalInputQuery.has_value()) {
            std::string valueQuery_instance;
            if (fromStringValue(conditionalInputQuery.value(), valueQuery_instance)) {
                conditionalInput = valueQuery_instance;
            }
        }
        auto visibilityQuery = request.query().get("visibility");
        std::optional<std::string> visibility;
        if (visibilityQuery.has_value()) {
            std::string valueQuery_instance;
            if (fromStringValue(visibilityQuery.value(), valueQuery_instance)) {
                visibility = valueQuery_instance;
            }
        }
        auto activeQuery = request.query().get("active");
        std::optional<bool> active;
        if (activeQuery.has_value()) {
            bool valueQuery_instance;
            if (fromStringValue(activeQuery.value(), valueQuery_instance)) {
                active = valueQuery_instance;
            }
        }
    


        try {





            this->create_trigger(version, accountId, name, appKey, groupingId, endpointURL, payload, scheduledDate, startDate, endDate, cronExpression, conditionalInput, visibility, active, response);
            } catch (Pistache::Http::HttpError &e) {
                response.send(static_cast<Pistache::Http::Code>(e.code()), e.what());
                return;
            } catch (std::exception &e) {
                this->handleOperationException(e, response);
                return;
            }

    } catch (std::exception &e) {
        response.send(Pistache::Http::Code::Internal_Server_Error, e.what());
    }


}

void TriggerApi::delete_trigger_handler(const Pistache::Rest::Request& request, Pistache::Http::ResponseWriter response) {
    try {

        // Getting the path params
        auto version = request.param(":version").as<double>();
        
        
        // Getting the query params
        auto accountIdQuery = request.query().get("accountId");
        std::optional<int64_t> accountId;
        if (accountIdQuery.has_value()) {
            int64_t valueQuery_instance;
            if (fromStringValue(accountIdQuery.value(), valueQuery_instance)) {
                accountId = valueQuery_instance;
            }
        }
        auto triggerIdQuery = request.query().get("triggerId");
        std::optional<int64_t> triggerId;
        if (triggerIdQuery.has_value()) {
            int64_t valueQuery_instance;
            if (fromStringValue(triggerIdQuery.value(), valueQuery_instance)) {
                triggerId = valueQuery_instance;
            }
        }
    


        try {





            this->delete_trigger(version, accountId, triggerId, response);
            } catch (Pistache::Http::HttpError &e) {
                response.send(static_cast<Pistache::Http::Code>(e.code()), e.what());
                return;
            } catch (std::exception &e) {
                this->handleOperationException(e, response);
                return;
            }

    } catch (std::exception &e) {
        response.send(Pistache::Http::Code::Internal_Server_Error, e.what());
    }


}

void TriggerApi::get_trigger_handler(const Pistache::Rest::Request& request, Pistache::Http::ResponseWriter response) {
    try {

        // Getting the path params
        auto version = request.param(":version").as<double>();
        
        
        // Getting the query params
        auto accountIdQuery = request.query().get("accountId");
        std::optional<int64_t> accountId;
        if (accountIdQuery.has_value()) {
            int64_t valueQuery_instance;
            if (fromStringValue(accountIdQuery.value(), valueQuery_instance)) {
                accountId = valueQuery_instance;
            }
        }
        auto triggerIdQuery = request.query().get("triggerId");
        std::optional<int64_t> triggerId;
        if (triggerIdQuery.has_value()) {
            int64_t valueQuery_instance;
            if (fromStringValue(triggerIdQuery.value(), valueQuery_instance)) {
                triggerId = valueQuery_instance;
            }
        }
    


        try {





            this->get_trigger(version, accountId, triggerId, response);
            } catch (Pistache::Http::HttpError &e) {
                response.send(static_cast<Pistache::Http::Code>(e.code()), e.what());
                return;
            } catch (std::exception &e) {
                this->handleOperationException(e, response);
                return;
            }

    } catch (std::exception &e) {
        response.send(Pistache::Http::Code::Internal_Server_Error, e.what());
    }


}

void TriggerApi::search_triggers_handler(const Pistache::Rest::Request& request, Pistache::Http::ResponseWriter response) {
    try {

        // Getting the path params
        auto version = request.param(":version").as<double>();
        
        
        // Getting the query params
        auto accountIdQuery = request.query().get("accountId");
        std::optional<int64_t> accountId;
        if (accountIdQuery.has_value()) {
            int64_t valueQuery_instance;
            if (fromStringValue(accountIdQuery.value(), valueQuery_instance)) {
                accountId = valueQuery_instance;
            }
        }
        auto groupingIdQuery = request.query().get("groupingId");
        std::optional<std::string> groupingId;
        if (groupingIdQuery.has_value()) {
            std::string valueQuery_instance;
            if (fromStringValue(groupingIdQuery.value(), valueQuery_instance)) {
                groupingId = valueQuery_instance;
            }
        }
        auto filterQuery = request.query().get("filter");
        std::optional<std::string> filter;
        if (filterQuery.has_value()) {
            std::string valueQuery_instance;
            if (fromStringValue(filterQuery.value(), valueQuery_instance)) {
                filter = valueQuery_instance;
            }
        }
        auto statusesQuery = request.query().get("statuses");
        std::optional<std::string> statuses;
        if (statusesQuery.has_value()) {
            std::string valueQuery_instance;
            if (fromStringValue(statusesQuery.value(), valueQuery_instance)) {
                statuses = valueQuery_instance;
            }
        }
        auto templateTypesQuery = request.query().get("templateTypes");
        std::optional<std::string> templateTypes;
        if (templateTypesQuery.has_value()) {
            std::string valueQuery_instance;
            if (fromStringValue(templateTypesQuery.value(), valueQuery_instance)) {
                templateTypes = valueQuery_instance;
            }
        }
        auto appKeyQuery = request.query().get("appKey");
        std::optional<std::string> appKey;
        if (appKeyQuery.has_value()) {
            std::string valueQuery_instance;
            if (fromStringValue(appKeyQuery.value(), valueQuery_instance)) {
                appKey = valueQuery_instance;
            }
        }
        auto keywordQuery = request.query().get("keyword");
        std::optional<std::string> keyword;
        if (keywordQuery.has_value()) {
            std::string valueQuery_instance;
            if (fromStringValue(keywordQuery.value(), valueQuery_instance)) {
                keyword = valueQuery_instance;
            }
        }
        auto sortFieldQuery = request.query().get("sortField");
        std::optional<std::string> sortField;
        if (sortFieldQuery.has_value()) {
            std::string valueQuery_instance;
            if (fromStringValue(sortFieldQuery.value(), valueQuery_instance)) {
                sortField = valueQuery_instance;
            }
        }
        auto descendingQuery = request.query().get("descending");
        std::optional<bool> descending;
        if (descendingQuery.has_value()) {
            bool valueQuery_instance;
            if (fromStringValue(descendingQuery.value(), valueQuery_instance)) {
                descending = valueQuery_instance;
            }
        }
        auto startQuery = request.query().get("start");
        std::optional<int32_t> start;
        if (startQuery.has_value()) {
            int32_t valueQuery_instance;
            if (fromStringValue(startQuery.value(), valueQuery_instance)) {
                start = valueQuery_instance;
            }
        }
        auto limitQuery = request.query().get("limit");
        std::optional<int32_t> limit;
        if (limitQuery.has_value()) {
            int32_t valueQuery_instance;
            if (fromStringValue(limitQuery.value(), valueQuery_instance)) {
                limit = valueQuery_instance;
            }
        }
        auto activeOnlyQuery = request.query().get("activeOnly");
        std::optional<bool> activeOnly;
        if (activeOnlyQuery.has_value()) {
            bool valueQuery_instance;
            if (fromStringValue(activeOnlyQuery.value(), valueQuery_instance)) {
                activeOnly = valueQuery_instance;
            }
        }
    


        try {





            this->search_triggers(version, accountId, groupingId, filter, statuses, templateTypes, appKey, keyword, sortField, descending, start, limit, activeOnly, response);
            } catch (Pistache::Http::HttpError &e) {
                response.send(static_cast<Pistache::Http::Code>(e.code()), e.what());
                return;
            } catch (std::exception &e) {
                this->handleOperationException(e, response);
                return;
            }

    } catch (std::exception &e) {
        response.send(Pistache::Http::Code::Internal_Server_Error, e.what());
    }


}

void TriggerApi::update_trigger_handler(const Pistache::Rest::Request& request, Pistache::Http::ResponseWriter response) {
    try {

        // Getting the path params
        auto version = request.param(":version").as<double>();
        
        
        // Getting the query params
        auto triggerIdQuery = request.query().get("triggerId");
        std::optional<int64_t> triggerId;
        if (triggerIdQuery.has_value()) {
            int64_t valueQuery_instance;
            if (fromStringValue(triggerIdQuery.value(), valueQuery_instance)) {
                triggerId = valueQuery_instance;
            }
        }
        auto accountIdQuery = request.query().get("accountId");
        std::optional<int64_t> accountId;
        if (accountIdQuery.has_value()) {
            int64_t valueQuery_instance;
            if (fromStringValue(accountIdQuery.value(), valueQuery_instance)) {
                accountId = valueQuery_instance;
            }
        }
        auto nameQuery = request.query().get("name");
        std::optional<std::string> name;
        if (nameQuery.has_value()) {
            std::string valueQuery_instance;
            if (fromStringValue(nameQuery.value(), valueQuery_instance)) {
                name = valueQuery_instance;
            }
        }
        auto appKeyQuery = request.query().get("appKey");
        std::optional<std::string> appKey;
        if (appKeyQuery.has_value()) {
            std::string valueQuery_instance;
            if (fromStringValue(appKeyQuery.value(), valueQuery_instance)) {
                appKey = valueQuery_instance;
            }
        }
        auto groupingIdQuery = request.query().get("groupingId");
        std::optional<std::string> groupingId;
        if (groupingIdQuery.has_value()) {
            std::string valueQuery_instance;
            if (fromStringValue(groupingIdQuery.value(), valueQuery_instance)) {
                groupingId = valueQuery_instance;
            }
        }
        auto endpointURLQuery = request.query().get("endpointURL");
        std::optional<std::string> endpointURL;
        if (endpointURLQuery.has_value()) {
            std::string valueQuery_instance;
            if (fromStringValue(endpointURLQuery.value(), valueQuery_instance)) {
                endpointURL = valueQuery_instance;
            }
        }
        auto payloadQuery = request.query().get("payload");
        std::optional<std::string> payload;
        if (payloadQuery.has_value()) {
            std::string valueQuery_instance;
            if (fromStringValue(payloadQuery.value(), valueQuery_instance)) {
                payload = valueQuery_instance;
            }
        }
        auto scheduledDateQuery = request.query().get("scheduledDate");
        std::optional<int64_t> scheduledDate;
        if (scheduledDateQuery.has_value()) {
            int64_t valueQuery_instance;
            if (fromStringValue(scheduledDateQuery.value(), valueQuery_instance)) {
                scheduledDate = valueQuery_instance;
            }
        }
        auto startDateQuery = request.query().get("startDate");
        std::optional<int64_t> startDate;
        if (startDateQuery.has_value()) {
            int64_t valueQuery_instance;
            if (fromStringValue(startDateQuery.value(), valueQuery_instance)) {
                startDate = valueQuery_instance;
            }
        }
        auto endDateQuery = request.query().get("endDate");
        std::optional<int64_t> endDate;
        if (endDateQuery.has_value()) {
            int64_t valueQuery_instance;
            if (fromStringValue(endDateQuery.value(), valueQuery_instance)) {
                endDate = valueQuery_instance;
            }
        }
        auto cronExpressionQuery = request.query().get("cronExpression");
        std::optional<std::string> cronExpression;
        if (cronExpressionQuery.has_value()) {
            std::string valueQuery_instance;
            if (fromStringValue(cronExpressionQuery.value(), valueQuery_instance)) {
                cronExpression = valueQuery_instance;
            }
        }
        auto conditionalInputQuery = request.query().get("conditionalInput");
        std::optional<std::string> conditionalInput;
        if (conditionalInputQuery.has_value()) {
            std::string valueQuery_instance;
            if (fromStringValue(conditionalInputQuery.value(), valueQuery_instance)) {
                conditionalInput = valueQuery_instance;
            }
        }
        auto visibilityQuery = request.query().get("visibility");
        std::optional<std::string> visibility;
        if (visibilityQuery.has_value()) {
            std::string valueQuery_instance;
            if (fromStringValue(visibilityQuery.value(), valueQuery_instance)) {
                visibility = valueQuery_instance;
            }
        }
        auto activeQuery = request.query().get("active");
        std::optional<bool> active;
        if (activeQuery.has_value()) {
            bool valueQuery_instance;
            if (fromStringValue(activeQuery.value(), valueQuery_instance)) {
                active = valueQuery_instance;
            }
        }
    


        try {





            this->update_trigger(version, triggerId, accountId, name, appKey, groupingId, endpointURL, payload, scheduledDate, startDate, endDate, cronExpression, conditionalInput, visibility, active, response);
            } catch (Pistache::Http::HttpError &e) {
                response.send(static_cast<Pistache::Http::Code>(e.code()), e.what());
                return;
            } catch (std::exception &e) {
                this->handleOperationException(e, response);
                return;
            }

    } catch (std::exception &e) {
        response.send(Pistache::Http::Code::Internal_Server_Error, e.what());
    }


}


void TriggerApi::trigger_api_default_handler(const Pistache::Rest::Request &, Pistache::Http::ResponseWriter response) {
    response.send(Pistache::Http::Code::Not_Found, "The requested method does not exist");
}

} // namespace org::openapitools::server::api

