/*
 * Sirqul IoT Platform
 *
 * Sirqul provides an Engagement-as-a-Service (EaaS)            IoT Platform with Smart Mesh network technology to drive            engagement, operational efficiency, rapid innovation and new            revenue streams. Please visit https://dev.sirqul.com/ for more            documents, examples, and sample applications.<?php $a = htmlspecialchars($_GET['appKey']);$b = htmlspecialchars($_GET['appRestKey']);?>
 *
 * The version of the OpenAPI document: 3.16
 * Contact: info@sirqul.com
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class PersonalProfileResponse : IEquatable<PersonalProfileResponse>
    {
        /// <summary>
        /// Gets or Sets Valid
        /// </summary>
        [DataMember(Name="valid", EmitDefaultValue=false)]
        public bool Valid { get; set; }

        /// <summary>
        /// Gets or Sets Message
        /// </summary>
        [DataMember(Name="message", EmitDefaultValue=false)]
        public string Message { get; set; }

        /// <summary>
        /// Gets or Sets VarVersion
        /// </summary>
        [DataMember(Name="version", EmitDefaultValue=false)]
        public double VarVersion { get; set; }

        /// <summary>
        /// Gets or Sets SerializeNulls
        /// </summary>
        [DataMember(Name="serializeNulls", EmitDefaultValue=false)]
        public bool SerializeNulls { get; set; }

        /// <summary>
        /// Gets or Sets StartTimeLog
        /// </summary>
        [DataMember(Name="startTimeLog", EmitDefaultValue=false)]
        public long StartTimeLog { get; set; }

        /// <summary>
        /// Gets or Sets ErrorCode
        /// </summary>
        [DataMember(Name="errorCode", EmitDefaultValue=false)]
        public string ErrorCode { get; set; }

        /// <summary>
        /// Gets or Sets Request
        /// </summary>
        [DataMember(Name="request", EmitDefaultValue=false)]
        public List<NameStringValueResponse> Request { get; set; }


        /// <summary>
        /// Gets or Sets PreferredGender
        /// </summary>
        [TypeConverter(typeof(CustomEnumConverter<PreferredGenderEnum>))]
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum PreferredGenderEnum
        {
            
            /// <summary>
            /// Enum MALEEnum for MALE
            /// </summary>
            [EnumMember(Value = "MALE")]
            MALEEnum = 1,
            
            /// <summary>
            /// Enum FEMALEEnum for FEMALE
            /// </summary>
            [EnumMember(Value = "FEMALE")]
            FEMALEEnum = 2,
            
            /// <summary>
            /// Enum ANYEnum for ANY
            /// </summary>
            [EnumMember(Value = "ANY")]
            ANYEnum = 3
        }

        /// <summary>
        /// Gets or Sets PreferredGender
        /// </summary>
        [DataMember(Name="preferredGender", EmitDefaultValue=false)]
        public PreferredGenderEnum PreferredGender { get; set; }

        /// <summary>
        /// Gets or Sets PreferredEthnicity
        /// </summary>
        [DataMember(Name="preferredEthnicity", EmitDefaultValue=false)]
        public string PreferredEthnicity { get; set; }

        /// <summary>
        /// Gets or Sets PreferredEducation
        /// </summary>
        [DataMember(Name="preferredEducation", EmitDefaultValue=false)]
        public string PreferredEducation { get; set; }

        /// <summary>
        /// Gets or Sets PreferredEducationIndex
        /// </summary>
        [DataMember(Name="preferredEducationIndex", EmitDefaultValue=false)]
        public int PreferredEducationIndex { get; set; }

        /// <summary>
        /// Gets or Sets PreferredBodyType
        /// </summary>
        [DataMember(Name="preferredBodyType", EmitDefaultValue=false)]
        public string PreferredBodyType { get; set; }

        /// <summary>
        /// Gets or Sets PreferredMinAge
        /// </summary>
        [DataMember(Name="preferredMinAge", EmitDefaultValue=false)]
        public int PreferredMinAge { get; set; }

        /// <summary>
        /// Gets or Sets PreferredMaxAge
        /// </summary>
        [DataMember(Name="preferredMaxAge", EmitDefaultValue=false)]
        public int PreferredMaxAge { get; set; }

        /// <summary>
        /// Gets or Sets PreferredMinHeight
        /// </summary>
        [DataMember(Name="preferredMinHeight", EmitDefaultValue=false)]
        public int PreferredMinHeight { get; set; }

        /// <summary>
        /// Gets or Sets PreferredMaxHeight
        /// </summary>
        [DataMember(Name="preferredMaxHeight", EmitDefaultValue=false)]
        public int PreferredMaxHeight { get; set; }

        /// <summary>
        /// Gets or Sets PreferredLocationRange
        /// </summary>
        [DataMember(Name="preferredLocationRange", EmitDefaultValue=false)]
        public double PreferredLocationRange { get; set; }


        /// <summary>
        /// Gets or Sets Gender
        /// </summary>
        [TypeConverter(typeof(CustomEnumConverter<GenderEnum>))]
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum GenderEnum
        {
            
            /// <summary>
            /// Enum MALEEnum for MALE
            /// </summary>
            [EnumMember(Value = "MALE")]
            MALEEnum = 1,
            
            /// <summary>
            /// Enum FEMALEEnum for FEMALE
            /// </summary>
            [EnumMember(Value = "FEMALE")]
            FEMALEEnum = 2,
            
            /// <summary>
            /// Enum ANYEnum for ANY
            /// </summary>
            [EnumMember(Value = "ANY")]
            ANYEnum = 3
        }

        /// <summary>
        /// Gets or Sets Gender
        /// </summary>
        [DataMember(Name="gender", EmitDefaultValue=false)]
        public GenderEnum Gender { get; set; }

        /// <summary>
        /// Gets or Sets Hometown
        /// </summary>
        [DataMember(Name="hometown", EmitDefaultValue=false)]
        public string Hometown { get; set; }

        /// <summary>
        /// Gets or Sets Height
        /// </summary>
        [DataMember(Name="height", EmitDefaultValue=false)]
        public string Height { get; set; }

        /// <summary>
        /// Gets or Sets HeightIndex
        /// </summary>
        [DataMember(Name="heightIndex", EmitDefaultValue=false)]
        public int HeightIndex { get; set; }

        /// <summary>
        /// Gets or Sets Ethnicity
        /// </summary>
        [DataMember(Name="ethnicity", EmitDefaultValue=false)]
        public string Ethnicity { get; set; }

        /// <summary>
        /// Gets or Sets BodyType
        /// </summary>
        [DataMember(Name="bodyType", EmitDefaultValue=false)]
        public string BodyType { get; set; }

        /// <summary>
        /// Gets or Sets Children
        /// </summary>
        [DataMember(Name="children", EmitDefaultValue=false)]
        public string Children { get; set; }

        /// <summary>
        /// Gets or Sets Companionship
        /// </summary>
        [DataMember(Name="companionship", EmitDefaultValue=false)]
        public string Companionship { get; set; }

        /// <summary>
        /// Gets or Sets CompanionshipIndex
        /// </summary>
        [DataMember(Name="companionshipIndex", EmitDefaultValue=false)]
        public int CompanionshipIndex { get; set; }

        /// <summary>
        /// Gets or Sets Drink
        /// </summary>
        [DataMember(Name="drink", EmitDefaultValue=false)]
        public string Drink { get; set; }

        /// <summary>
        /// Gets or Sets Education
        /// </summary>
        [DataMember(Name="education", EmitDefaultValue=false)]
        public string Education { get; set; }

        /// <summary>
        /// Gets or Sets EducationIndex
        /// </summary>
        [DataMember(Name="educationIndex", EmitDefaultValue=false)]
        public int EducationIndex { get; set; }

        /// <summary>
        /// Gets or Sets MaritalStatus
        /// </summary>
        [DataMember(Name="maritalStatus", EmitDefaultValue=false)]
        public string MaritalStatus { get; set; }

        /// <summary>
        /// Gets or Sets Smoke
        /// </summary>
        [DataMember(Name="smoke", EmitDefaultValue=false)]
        public string Smoke { get; set; }

        /// <summary>
        /// Gets or Sets Religion
        /// </summary>
        [DataMember(Name="religion", EmitDefaultValue=false)]
        public string Religion { get; set; }

        /// <summary>
        /// Gets or Sets Birthday
        /// </summary>
        [DataMember(Name="birthday", EmitDefaultValue=false)]
        public long Birthday { get; set; }

        /// <summary>
        /// Gets or Sets Returning
        /// </summary>
        [DataMember(Name="returning", EmitDefaultValue=false)]
        public string Returning { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PersonalProfileResponse {\n");
            sb.Append("  Valid: ").Append(Valid).Append("\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("  VarVersion: ").Append(VarVersion).Append("\n");
            sb.Append("  SerializeNulls: ").Append(SerializeNulls).Append("\n");
            sb.Append("  StartTimeLog: ").Append(StartTimeLog).Append("\n");
            sb.Append("  ErrorCode: ").Append(ErrorCode).Append("\n");
            sb.Append("  Request: ").Append(Request).Append("\n");
            sb.Append("  PreferredGender: ").Append(PreferredGender).Append("\n");
            sb.Append("  PreferredEthnicity: ").Append(PreferredEthnicity).Append("\n");
            sb.Append("  PreferredEducation: ").Append(PreferredEducation).Append("\n");
            sb.Append("  PreferredEducationIndex: ").Append(PreferredEducationIndex).Append("\n");
            sb.Append("  PreferredBodyType: ").Append(PreferredBodyType).Append("\n");
            sb.Append("  PreferredMinAge: ").Append(PreferredMinAge).Append("\n");
            sb.Append("  PreferredMaxAge: ").Append(PreferredMaxAge).Append("\n");
            sb.Append("  PreferredMinHeight: ").Append(PreferredMinHeight).Append("\n");
            sb.Append("  PreferredMaxHeight: ").Append(PreferredMaxHeight).Append("\n");
            sb.Append("  PreferredLocationRange: ").Append(PreferredLocationRange).Append("\n");
            sb.Append("  Gender: ").Append(Gender).Append("\n");
            sb.Append("  Hometown: ").Append(Hometown).Append("\n");
            sb.Append("  Height: ").Append(Height).Append("\n");
            sb.Append("  HeightIndex: ").Append(HeightIndex).Append("\n");
            sb.Append("  Ethnicity: ").Append(Ethnicity).Append("\n");
            sb.Append("  BodyType: ").Append(BodyType).Append("\n");
            sb.Append("  Children: ").Append(Children).Append("\n");
            sb.Append("  Companionship: ").Append(Companionship).Append("\n");
            sb.Append("  CompanionshipIndex: ").Append(CompanionshipIndex).Append("\n");
            sb.Append("  Drink: ").Append(Drink).Append("\n");
            sb.Append("  Education: ").Append(Education).Append("\n");
            sb.Append("  EducationIndex: ").Append(EducationIndex).Append("\n");
            sb.Append("  MaritalStatus: ").Append(MaritalStatus).Append("\n");
            sb.Append("  Smoke: ").Append(Smoke).Append("\n");
            sb.Append("  Religion: ").Append(Religion).Append("\n");
            sb.Append("  Birthday: ").Append(Birthday).Append("\n");
            sb.Append("  Returning: ").Append(Returning).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((PersonalProfileResponse)obj);
        }

        /// <summary>
        /// Returns true if PersonalProfileResponse instances are equal
        /// </summary>
        /// <param name="other">Instance of PersonalProfileResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PersonalProfileResponse other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Valid == other.Valid ||
                    
                    Valid.Equals(other.Valid)
                ) && 
                (
                    Message == other.Message ||
                    Message != null &&
                    Message.Equals(other.Message)
                ) && 
                (
                    VarVersion == other.VarVersion ||
                    
                    VarVersion.Equals(other.VarVersion)
                ) && 
                (
                    SerializeNulls == other.SerializeNulls ||
                    
                    SerializeNulls.Equals(other.SerializeNulls)
                ) && 
                (
                    StartTimeLog == other.StartTimeLog ||
                    
                    StartTimeLog.Equals(other.StartTimeLog)
                ) && 
                (
                    ErrorCode == other.ErrorCode ||
                    ErrorCode != null &&
                    ErrorCode.Equals(other.ErrorCode)
                ) && 
                (
                    Request == other.Request ||
                    Request != null &&
                    other.Request != null &&
                    Request.SequenceEqual(other.Request)
                ) && 
                (
                    PreferredGender == other.PreferredGender ||
                    
                    PreferredGender.Equals(other.PreferredGender)
                ) && 
                (
                    PreferredEthnicity == other.PreferredEthnicity ||
                    PreferredEthnicity != null &&
                    PreferredEthnicity.Equals(other.PreferredEthnicity)
                ) && 
                (
                    PreferredEducation == other.PreferredEducation ||
                    PreferredEducation != null &&
                    PreferredEducation.Equals(other.PreferredEducation)
                ) && 
                (
                    PreferredEducationIndex == other.PreferredEducationIndex ||
                    
                    PreferredEducationIndex.Equals(other.PreferredEducationIndex)
                ) && 
                (
                    PreferredBodyType == other.PreferredBodyType ||
                    PreferredBodyType != null &&
                    PreferredBodyType.Equals(other.PreferredBodyType)
                ) && 
                (
                    PreferredMinAge == other.PreferredMinAge ||
                    
                    PreferredMinAge.Equals(other.PreferredMinAge)
                ) && 
                (
                    PreferredMaxAge == other.PreferredMaxAge ||
                    
                    PreferredMaxAge.Equals(other.PreferredMaxAge)
                ) && 
                (
                    PreferredMinHeight == other.PreferredMinHeight ||
                    
                    PreferredMinHeight.Equals(other.PreferredMinHeight)
                ) && 
                (
                    PreferredMaxHeight == other.PreferredMaxHeight ||
                    
                    PreferredMaxHeight.Equals(other.PreferredMaxHeight)
                ) && 
                (
                    PreferredLocationRange == other.PreferredLocationRange ||
                    
                    PreferredLocationRange.Equals(other.PreferredLocationRange)
                ) && 
                (
                    Gender == other.Gender ||
                    
                    Gender.Equals(other.Gender)
                ) && 
                (
                    Hometown == other.Hometown ||
                    Hometown != null &&
                    Hometown.Equals(other.Hometown)
                ) && 
                (
                    Height == other.Height ||
                    Height != null &&
                    Height.Equals(other.Height)
                ) && 
                (
                    HeightIndex == other.HeightIndex ||
                    
                    HeightIndex.Equals(other.HeightIndex)
                ) && 
                (
                    Ethnicity == other.Ethnicity ||
                    Ethnicity != null &&
                    Ethnicity.Equals(other.Ethnicity)
                ) && 
                (
                    BodyType == other.BodyType ||
                    BodyType != null &&
                    BodyType.Equals(other.BodyType)
                ) && 
                (
                    Children == other.Children ||
                    Children != null &&
                    Children.Equals(other.Children)
                ) && 
                (
                    Companionship == other.Companionship ||
                    Companionship != null &&
                    Companionship.Equals(other.Companionship)
                ) && 
                (
                    CompanionshipIndex == other.CompanionshipIndex ||
                    
                    CompanionshipIndex.Equals(other.CompanionshipIndex)
                ) && 
                (
                    Drink == other.Drink ||
                    Drink != null &&
                    Drink.Equals(other.Drink)
                ) && 
                (
                    Education == other.Education ||
                    Education != null &&
                    Education.Equals(other.Education)
                ) && 
                (
                    EducationIndex == other.EducationIndex ||
                    
                    EducationIndex.Equals(other.EducationIndex)
                ) && 
                (
                    MaritalStatus == other.MaritalStatus ||
                    MaritalStatus != null &&
                    MaritalStatus.Equals(other.MaritalStatus)
                ) && 
                (
                    Smoke == other.Smoke ||
                    Smoke != null &&
                    Smoke.Equals(other.Smoke)
                ) && 
                (
                    Religion == other.Religion ||
                    Religion != null &&
                    Religion.Equals(other.Religion)
                ) && 
                (
                    Birthday == other.Birthday ||
                    
                    Birthday.Equals(other.Birthday)
                ) && 
                (
                    Returning == other.Returning ||
                    Returning != null &&
                    Returning.Equals(other.Returning)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    
                    hashCode = hashCode * 59 + Valid.GetHashCode();
                    if (Message != null)
                    hashCode = hashCode * 59 + Message.GetHashCode();
                    
                    hashCode = hashCode * 59 + VarVersion.GetHashCode();
                    
                    hashCode = hashCode * 59 + SerializeNulls.GetHashCode();
                    
                    hashCode = hashCode * 59 + StartTimeLog.GetHashCode();
                    if (ErrorCode != null)
                    hashCode = hashCode * 59 + ErrorCode.GetHashCode();
                    if (Request != null)
                    hashCode = hashCode * 59 + Request.GetHashCode();
                    
                    hashCode = hashCode * 59 + PreferredGender.GetHashCode();
                    if (PreferredEthnicity != null)
                    hashCode = hashCode * 59 + PreferredEthnicity.GetHashCode();
                    if (PreferredEducation != null)
                    hashCode = hashCode * 59 + PreferredEducation.GetHashCode();
                    
                    hashCode = hashCode * 59 + PreferredEducationIndex.GetHashCode();
                    if (PreferredBodyType != null)
                    hashCode = hashCode * 59 + PreferredBodyType.GetHashCode();
                    
                    hashCode = hashCode * 59 + PreferredMinAge.GetHashCode();
                    
                    hashCode = hashCode * 59 + PreferredMaxAge.GetHashCode();
                    
                    hashCode = hashCode * 59 + PreferredMinHeight.GetHashCode();
                    
                    hashCode = hashCode * 59 + PreferredMaxHeight.GetHashCode();
                    
                    hashCode = hashCode * 59 + PreferredLocationRange.GetHashCode();
                    
                    hashCode = hashCode * 59 + Gender.GetHashCode();
                    if (Hometown != null)
                    hashCode = hashCode * 59 + Hometown.GetHashCode();
                    if (Height != null)
                    hashCode = hashCode * 59 + Height.GetHashCode();
                    
                    hashCode = hashCode * 59 + HeightIndex.GetHashCode();
                    if (Ethnicity != null)
                    hashCode = hashCode * 59 + Ethnicity.GetHashCode();
                    if (BodyType != null)
                    hashCode = hashCode * 59 + BodyType.GetHashCode();
                    if (Children != null)
                    hashCode = hashCode * 59 + Children.GetHashCode();
                    if (Companionship != null)
                    hashCode = hashCode * 59 + Companionship.GetHashCode();
                    
                    hashCode = hashCode * 59 + CompanionshipIndex.GetHashCode();
                    if (Drink != null)
                    hashCode = hashCode * 59 + Drink.GetHashCode();
                    if (Education != null)
                    hashCode = hashCode * 59 + Education.GetHashCode();
                    
                    hashCode = hashCode * 59 + EducationIndex.GetHashCode();
                    if (MaritalStatus != null)
                    hashCode = hashCode * 59 + MaritalStatus.GetHashCode();
                    if (Smoke != null)
                    hashCode = hashCode * 59 + Smoke.GetHashCode();
                    if (Religion != null)
                    hashCode = hashCode * 59 + Religion.GetHashCode();
                    
                    hashCode = hashCode * 59 + Birthday.GetHashCode();
                    if (Returning != null)
                    hashCode = hashCode * 59 + Returning.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(PersonalProfileResponse left, PersonalProfileResponse right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(PersonalProfileResponse left, PersonalProfileResponse right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
