/*
 * Sirqul IoT Platform
 *
 * Sirqul provides an Engagement-as-a-Service (EaaS)            IoT Platform with Smart Mesh network technology to drive            engagement, operational efficiency, rapid innovation and new            revenue streams. Please visit https://dev.sirqul.com/ for more            documents, examples, and sample applications.<?php $a = htmlspecialchars($_GET['appKey']);$b = htmlspecialchars($_GET['appRestKey']);?>
 *
 * The version of the OpenAPI document: 3.16
 * Contact: info@sirqul.com
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class Stop : IEquatable<Stop>
    {
        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name="id", EmitDefaultValue=false)]
        public long Id { get; set; }

        /// <summary>
        /// Gets or Sets Active
        /// </summary>
        [DataMember(Name="active", EmitDefaultValue=false)]
        public bool Active { get; set; }

        /// <summary>
        /// Gets or Sets Valid
        /// </summary>
        [DataMember(Name="valid", EmitDefaultValue=false)]
        public bool Valid { get; set; }

        /// <summary>
        /// Gets or Sets Latitude
        /// </summary>
        [DataMember(Name="latitude", EmitDefaultValue=false)]
        public double Latitude { get; set; }

        /// <summary>
        /// Gets or Sets Longitude
        /// </summary>
        [DataMember(Name="longitude", EmitDefaultValue=false)]
        public double Longitude { get; set; }

        /// <summary>
        /// Gets or Sets LocationDescription
        /// </summary>
        [DataMember(Name="locationDescription", EmitDefaultValue=false)]
        public string LocationDescription { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Owner
        /// </summary>
        [DataMember(Name="owner", EmitDefaultValue=false)]
        public Account Owner { get; set; }

        /// <summary>
        /// Gets or Sets Location
        /// </summary>
        [DataMember(Name="location", EmitDefaultValue=false)]
        public Location Location { get; set; }

        /// <summary>
        /// Gets or Sets Notes
        /// </summary>
        [DataMember(Name="notes", EmitDefaultValue=false)]
        public List<Note> Notes { get; set; }

        /// <summary>
        /// Gets or Sets NoteCount
        /// </summary>
        [DataMember(Name="noteCount", EmitDefaultValue=false)]
        public long NoteCount { get; set; }


        /// <summary>
        /// Gets or Sets StopType
        /// </summary>
        [TypeConverter(typeof(CustomEnumConverter<StopTypeEnum>))]
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum StopTypeEnum
        {
            
            /// <summary>
            /// Enum PICKUPEnum for PICKUP
            /// </summary>
            [EnumMember(Value = "PICKUP")]
            PICKUPEnum = 1,
            
            /// <summary>
            /// Enum DROPOFFEnum for DROPOFF
            /// </summary>
            [EnumMember(Value = "DROPOFF")]
            DROPOFFEnum = 2,
            
            /// <summary>
            /// Enum STARTEnum for START
            /// </summary>
            [EnumMember(Value = "START")]
            STARTEnum = 3,
            
            /// <summary>
            /// Enum ENDEnum for END
            /// </summary>
            [EnumMember(Value = "END")]
            ENDEnum = 4,
            
            /// <summary>
            /// Enum ROUTINGEnum for ROUTING
            /// </summary>
            [EnumMember(Value = "ROUTING")]
            ROUTINGEnum = 5
        }

        /// <summary>
        /// Gets or Sets StopType
        /// </summary>
        [DataMember(Name="stopType", EmitDefaultValue=false)]
        public StopTypeEnum StopType { get; set; }

        /// <summary>
        /// Gets or Sets OrderIndex
        /// </summary>
        [DataMember(Name="orderIndex", EmitDefaultValue=false)]
        public long OrderIndex { get; set; }

        /// <summary>
        /// Gets or Sets StartTime
        /// </summary>
        [DataMember(Name="startTime", EmitDefaultValue=false)]
        public DateTime StartTime { get; set; }

        /// <summary>
        /// Gets or Sets EndTime
        /// </summary>
        [DataMember(Name="endTime", EmitDefaultValue=false)]
        public DateTime EndTime { get; set; }

        /// <summary>
        /// Gets or Sets EstimatedTime
        /// </summary>
        [DataMember(Name="estimatedTime", EmitDefaultValue=false)]
        public DateTime EstimatedTime { get; set; }

        /// <summary>
        /// Gets or Sets EstimatedArrivalTime
        /// </summary>
        [DataMember(Name="estimatedArrivalTime", EmitDefaultValue=false)]
        public DateTime EstimatedArrivalTime { get; set; }

        /// <summary>
        /// Gets or Sets EstimatedDepartureTime
        /// </summary>
        [DataMember(Name="estimatedDepartureTime", EmitDefaultValue=false)]
        public DateTime EstimatedDepartureTime { get; set; }

        /// <summary>
        /// Gets or Sets ActualTime
        /// </summary>
        [DataMember(Name="actualTime", EmitDefaultValue=false)]
        public DateTime ActualTime { get; set; }

        /// <summary>
        /// Gets or Sets DesiredTime
        /// </summary>
        [DataMember(Name="desiredTime", EmitDefaultValue=false)]
        public DateTime DesiredTime { get; set; }

        /// <summary>
        /// Gets or Sets TimePadding
        /// </summary>
        [DataMember(Name="timePadding", EmitDefaultValue=false)]
        public int TimePadding { get; set; }

        /// <summary>
        /// Gets or Sets Route
        /// </summary>
        [DataMember(Name="route", EmitDefaultValue=false)]
        public Route Route { get; set; }

        /// <summary>
        /// Gets or Sets Shipment
        /// </summary>
        [DataMember(Name="shipment", EmitDefaultValue=false)]
        public Shipment Shipment { get; set; }


        /// <summary>
        /// Gets or Sets ProgressStatus
        /// </summary>
        [TypeConverter(typeof(CustomEnumConverter<ProgressStatusEnum>))]
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum ProgressStatusEnum
        {
            
            /// <summary>
            /// Enum PENDINGEnum for PENDING
            /// </summary>
            [EnumMember(Value = "PENDING")]
            PENDINGEnum = 1,
            
            /// <summary>
            /// Enum COMPLETEEnum for COMPLETE
            /// </summary>
            [EnumMember(Value = "COMPLETE")]
            COMPLETEEnum = 2,
            
            /// <summary>
            /// Enum INVALIDEnum for INVALID
            /// </summary>
            [EnumMember(Value = "INVALID")]
            INVALIDEnum = 3
        }

        /// <summary>
        /// Gets or Sets ProgressStatus
        /// </summary>
        [DataMember(Name="progressStatus", EmitDefaultValue=false)]
        public ProgressStatusEnum ProgressStatus { get; set; }

        /// <summary>
        /// Gets or Sets CompareEstimatedTime
        /// </summary>
        [DataMember(Name="compareEstimatedTime", EmitDefaultValue=false)]
        public DateTime CompareEstimatedTime { get; set; }

        /// <summary>
        /// Gets or Sets CompareEstimatedArrivalTime
        /// </summary>
        [DataMember(Name="compareEstimatedArrivalTime", EmitDefaultValue=false)]
        public DateTime CompareEstimatedArrivalTime { get; set; }

        /// <summary>
        /// Gets or Sets CompareEstimiatedDepartureTime
        /// </summary>
        [DataMember(Name="compareEstimiatedDepartureTime", EmitDefaultValue=false)]
        public DateTime CompareEstimiatedDepartureTime { get; set; }

        /// <summary>
        /// Gets or Sets Polyline
        /// </summary>
        [DataMember(Name="polyline", EmitDefaultValue=false)]
        public string Polyline { get; set; }

        /// <summary>
        /// Gets or Sets Parent
        /// </summary>
        [DataMember(Name="parent", EmitDefaultValue=false)]
        public Stop Parent { get; set; }

        /// <summary>
        /// Gets or Sets LocationDisplay
        /// </summary>
        [DataMember(Name="locationDisplay", EmitDefaultValue=false)]
        public string LocationDisplay { get; set; }

        /// <summary>
        /// Gets or Sets Complete
        /// </summary>
        [DataMember(Name="complete", EmitDefaultValue=false)]
        public bool Complete { get; set; }

        /// <summary>
        /// Gets or Sets ContentName
        /// </summary>
        [DataMember(Name="contentName", EmitDefaultValue=false)]
        public string ContentName { get; set; }

        /// <summary>
        /// Gets or Sets LocationAddress
        /// </summary>
        [DataMember(Name="locationAddress", EmitDefaultValue=false)]
        public string LocationAddress { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Stop {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Active: ").Append(Active).Append("\n");
            sb.Append("  Valid: ").Append(Valid).Append("\n");
            sb.Append("  Latitude: ").Append(Latitude).Append("\n");
            sb.Append("  Longitude: ").Append(Longitude).Append("\n");
            sb.Append("  LocationDescription: ").Append(LocationDescription).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Owner: ").Append(Owner).Append("\n");
            sb.Append("  Location: ").Append(Location).Append("\n");
            sb.Append("  Notes: ").Append(Notes).Append("\n");
            sb.Append("  NoteCount: ").Append(NoteCount).Append("\n");
            sb.Append("  StopType: ").Append(StopType).Append("\n");
            sb.Append("  OrderIndex: ").Append(OrderIndex).Append("\n");
            sb.Append("  StartTime: ").Append(StartTime).Append("\n");
            sb.Append("  EndTime: ").Append(EndTime).Append("\n");
            sb.Append("  EstimatedTime: ").Append(EstimatedTime).Append("\n");
            sb.Append("  EstimatedArrivalTime: ").Append(EstimatedArrivalTime).Append("\n");
            sb.Append("  EstimatedDepartureTime: ").Append(EstimatedDepartureTime).Append("\n");
            sb.Append("  ActualTime: ").Append(ActualTime).Append("\n");
            sb.Append("  DesiredTime: ").Append(DesiredTime).Append("\n");
            sb.Append("  TimePadding: ").Append(TimePadding).Append("\n");
            sb.Append("  Route: ").Append(Route).Append("\n");
            sb.Append("  Shipment: ").Append(Shipment).Append("\n");
            sb.Append("  ProgressStatus: ").Append(ProgressStatus).Append("\n");
            sb.Append("  CompareEstimatedTime: ").Append(CompareEstimatedTime).Append("\n");
            sb.Append("  CompareEstimatedArrivalTime: ").Append(CompareEstimatedArrivalTime).Append("\n");
            sb.Append("  CompareEstimiatedDepartureTime: ").Append(CompareEstimiatedDepartureTime).Append("\n");
            sb.Append("  Polyline: ").Append(Polyline).Append("\n");
            sb.Append("  Parent: ").Append(Parent).Append("\n");
            sb.Append("  LocationDisplay: ").Append(LocationDisplay).Append("\n");
            sb.Append("  Complete: ").Append(Complete).Append("\n");
            sb.Append("  ContentName: ").Append(ContentName).Append("\n");
            sb.Append("  LocationAddress: ").Append(LocationAddress).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((Stop)obj);
        }

        /// <summary>
        /// Returns true if Stop instances are equal
        /// </summary>
        /// <param name="other">Instance of Stop to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Stop other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Id == other.Id ||
                    
                    Id.Equals(other.Id)
                ) && 
                (
                    Active == other.Active ||
                    
                    Active.Equals(other.Active)
                ) && 
                (
                    Valid == other.Valid ||
                    
                    Valid.Equals(other.Valid)
                ) && 
                (
                    Latitude == other.Latitude ||
                    
                    Latitude.Equals(other.Latitude)
                ) && 
                (
                    Longitude == other.Longitude ||
                    
                    Longitude.Equals(other.Longitude)
                ) && 
                (
                    LocationDescription == other.LocationDescription ||
                    LocationDescription != null &&
                    LocationDescription.Equals(other.LocationDescription)
                ) && 
                (
                    Name == other.Name ||
                    Name != null &&
                    Name.Equals(other.Name)
                ) && 
                (
                    Owner == other.Owner ||
                    Owner != null &&
                    Owner.Equals(other.Owner)
                ) && 
                (
                    Location == other.Location ||
                    Location != null &&
                    Location.Equals(other.Location)
                ) && 
                (
                    Notes == other.Notes ||
                    Notes != null &&
                    other.Notes != null &&
                    Notes.SequenceEqual(other.Notes)
                ) && 
                (
                    NoteCount == other.NoteCount ||
                    
                    NoteCount.Equals(other.NoteCount)
                ) && 
                (
                    StopType == other.StopType ||
                    
                    StopType.Equals(other.StopType)
                ) && 
                (
                    OrderIndex == other.OrderIndex ||
                    
                    OrderIndex.Equals(other.OrderIndex)
                ) && 
                (
                    StartTime == other.StartTime ||
                    StartTime != null &&
                    StartTime.Equals(other.StartTime)
                ) && 
                (
                    EndTime == other.EndTime ||
                    EndTime != null &&
                    EndTime.Equals(other.EndTime)
                ) && 
                (
                    EstimatedTime == other.EstimatedTime ||
                    EstimatedTime != null &&
                    EstimatedTime.Equals(other.EstimatedTime)
                ) && 
                (
                    EstimatedArrivalTime == other.EstimatedArrivalTime ||
                    EstimatedArrivalTime != null &&
                    EstimatedArrivalTime.Equals(other.EstimatedArrivalTime)
                ) && 
                (
                    EstimatedDepartureTime == other.EstimatedDepartureTime ||
                    EstimatedDepartureTime != null &&
                    EstimatedDepartureTime.Equals(other.EstimatedDepartureTime)
                ) && 
                (
                    ActualTime == other.ActualTime ||
                    ActualTime != null &&
                    ActualTime.Equals(other.ActualTime)
                ) && 
                (
                    DesiredTime == other.DesiredTime ||
                    DesiredTime != null &&
                    DesiredTime.Equals(other.DesiredTime)
                ) && 
                (
                    TimePadding == other.TimePadding ||
                    
                    TimePadding.Equals(other.TimePadding)
                ) && 
                (
                    Route == other.Route ||
                    Route != null &&
                    Route.Equals(other.Route)
                ) && 
                (
                    Shipment == other.Shipment ||
                    Shipment != null &&
                    Shipment.Equals(other.Shipment)
                ) && 
                (
                    ProgressStatus == other.ProgressStatus ||
                    
                    ProgressStatus.Equals(other.ProgressStatus)
                ) && 
                (
                    CompareEstimatedTime == other.CompareEstimatedTime ||
                    CompareEstimatedTime != null &&
                    CompareEstimatedTime.Equals(other.CompareEstimatedTime)
                ) && 
                (
                    CompareEstimatedArrivalTime == other.CompareEstimatedArrivalTime ||
                    CompareEstimatedArrivalTime != null &&
                    CompareEstimatedArrivalTime.Equals(other.CompareEstimatedArrivalTime)
                ) && 
                (
                    CompareEstimiatedDepartureTime == other.CompareEstimiatedDepartureTime ||
                    CompareEstimiatedDepartureTime != null &&
                    CompareEstimiatedDepartureTime.Equals(other.CompareEstimiatedDepartureTime)
                ) && 
                (
                    Polyline == other.Polyline ||
                    Polyline != null &&
                    Polyline.Equals(other.Polyline)
                ) && 
                (
                    Parent == other.Parent ||
                    Parent != null &&
                    Parent.Equals(other.Parent)
                ) && 
                (
                    LocationDisplay == other.LocationDisplay ||
                    LocationDisplay != null &&
                    LocationDisplay.Equals(other.LocationDisplay)
                ) && 
                (
                    Complete == other.Complete ||
                    
                    Complete.Equals(other.Complete)
                ) && 
                (
                    ContentName == other.ContentName ||
                    ContentName != null &&
                    ContentName.Equals(other.ContentName)
                ) && 
                (
                    LocationAddress == other.LocationAddress ||
                    LocationAddress != null &&
                    LocationAddress.Equals(other.LocationAddress)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    
                    hashCode = hashCode * 59 + Id.GetHashCode();
                    
                    hashCode = hashCode * 59 + Active.GetHashCode();
                    
                    hashCode = hashCode * 59 + Valid.GetHashCode();
                    
                    hashCode = hashCode * 59 + Latitude.GetHashCode();
                    
                    hashCode = hashCode * 59 + Longitude.GetHashCode();
                    if (LocationDescription != null)
                    hashCode = hashCode * 59 + LocationDescription.GetHashCode();
                    if (Name != null)
                    hashCode = hashCode * 59 + Name.GetHashCode();
                    if (Owner != null)
                    hashCode = hashCode * 59 + Owner.GetHashCode();
                    if (Location != null)
                    hashCode = hashCode * 59 + Location.GetHashCode();
                    if (Notes != null)
                    hashCode = hashCode * 59 + Notes.GetHashCode();
                    
                    hashCode = hashCode * 59 + NoteCount.GetHashCode();
                    
                    hashCode = hashCode * 59 + StopType.GetHashCode();
                    
                    hashCode = hashCode * 59 + OrderIndex.GetHashCode();
                    if (StartTime != null)
                    hashCode = hashCode * 59 + StartTime.GetHashCode();
                    if (EndTime != null)
                    hashCode = hashCode * 59 + EndTime.GetHashCode();
                    if (EstimatedTime != null)
                    hashCode = hashCode * 59 + EstimatedTime.GetHashCode();
                    if (EstimatedArrivalTime != null)
                    hashCode = hashCode * 59 + EstimatedArrivalTime.GetHashCode();
                    if (EstimatedDepartureTime != null)
                    hashCode = hashCode * 59 + EstimatedDepartureTime.GetHashCode();
                    if (ActualTime != null)
                    hashCode = hashCode * 59 + ActualTime.GetHashCode();
                    if (DesiredTime != null)
                    hashCode = hashCode * 59 + DesiredTime.GetHashCode();
                    
                    hashCode = hashCode * 59 + TimePadding.GetHashCode();
                    if (Route != null)
                    hashCode = hashCode * 59 + Route.GetHashCode();
                    if (Shipment != null)
                    hashCode = hashCode * 59 + Shipment.GetHashCode();
                    
                    hashCode = hashCode * 59 + ProgressStatus.GetHashCode();
                    if (CompareEstimatedTime != null)
                    hashCode = hashCode * 59 + CompareEstimatedTime.GetHashCode();
                    if (CompareEstimatedArrivalTime != null)
                    hashCode = hashCode * 59 + CompareEstimatedArrivalTime.GetHashCode();
                    if (CompareEstimiatedDepartureTime != null)
                    hashCode = hashCode * 59 + CompareEstimiatedDepartureTime.GetHashCode();
                    if (Polyline != null)
                    hashCode = hashCode * 59 + Polyline.GetHashCode();
                    if (Parent != null)
                    hashCode = hashCode * 59 + Parent.GetHashCode();
                    if (LocationDisplay != null)
                    hashCode = hashCode * 59 + LocationDisplay.GetHashCode();
                    
                    hashCode = hashCode * 59 + Complete.GetHashCode();
                    if (ContentName != null)
                    hashCode = hashCode * 59 + ContentName.GetHashCode();
                    if (LocationAddress != null)
                    hashCode = hashCode * 59 + LocationAddress.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(Stop left, Stop right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(Stop left, Stop right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
