/*
 * Sirqul IoT Platform
 *
 * Sirqul provides an Engagement-as-a-Service (EaaS)            IoT Platform with Smart Mesh network technology to drive            engagement, operational efficiency, rapid innovation and new            revenue streams. Please visit https://dev.sirqul.com/ for more            documents, examples, and sample applications.<?php $a = htmlspecialchars($_GET['appKey']);$b = htmlspecialchars($_GET['appRestKey']);?>
 *
 * The version of the OpenAPI document: 3.16
 * Contact: info@sirqul.com
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class WeatherResponse : IEquatable<WeatherResponse>
    {
        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name="id", EmitDefaultValue=false)]
        public long Id { get; set; }

        /// <summary>
        /// Gets or Sets Cloudcover
        /// </summary>
        [DataMember(Name="cloudcover", EmitDefaultValue=false)]
        public int Cloudcover { get; set; }

        /// <summary>
        /// Gets or Sets Humidity
        /// </summary>
        [DataMember(Name="humidity", EmitDefaultValue=false)]
        public int Humidity { get; set; }

        /// <summary>
        /// Gets or Sets ObservationTime
        /// </summary>
        [DataMember(Name="observationTime", EmitDefaultValue=false)]
        public long ObservationTime { get; set; }

        /// <summary>
        /// Gets or Sets PrecipMM
        /// </summary>
        [DataMember(Name="precipMM", EmitDefaultValue=false)]
        public double PrecipMM { get; set; }

        /// <summary>
        /// Gets or Sets Pressure
        /// </summary>
        [DataMember(Name="pressure", EmitDefaultValue=false)]
        public int Pressure { get; set; }

        /// <summary>
        /// Gets or Sets TempC
        /// </summary>
        [DataMember(Name="temp_C", EmitDefaultValue=false)]
        public int TempC { get; set; }

        /// <summary>
        /// Gets or Sets TempF
        /// </summary>
        [DataMember(Name="temp_F", EmitDefaultValue=false)]
        public int TempF { get; set; }

        /// <summary>
        /// Gets or Sets Visibility
        /// </summary>
        [DataMember(Name="visibility", EmitDefaultValue=false)]
        public int Visibility { get; set; }

        /// <summary>
        /// Gets or Sets WeatherCode
        /// </summary>
        [DataMember(Name="weatherCode", EmitDefaultValue=false)]
        public int WeatherCode { get; set; }

        /// <summary>
        /// Gets or Sets WeatherDesc
        /// </summary>
        [DataMember(Name="weatherDesc", EmitDefaultValue=false)]
        public string WeatherDesc { get; set; }

        /// <summary>
        /// Gets or Sets WeatherIconUrl
        /// </summary>
        [DataMember(Name="weatherIconUrl", EmitDefaultValue=false)]
        public string WeatherIconUrl { get; set; }

        /// <summary>
        /// Gets or Sets Winddir16Point
        /// </summary>
        [DataMember(Name="winddir16Point", EmitDefaultValue=false)]
        public string Winddir16Point { get; set; }

        /// <summary>
        /// Gets or Sets WinddirDegree
        /// </summary>
        [DataMember(Name="winddirDegree", EmitDefaultValue=false)]
        public int WinddirDegree { get; set; }

        /// <summary>
        /// Gets or Sets WindspeedKmph
        /// </summary>
        [DataMember(Name="windspeedKmph", EmitDefaultValue=false)]
        public int WindspeedKmph { get; set; }

        /// <summary>
        /// Gets or Sets WindspeedMiles
        /// </summary>
        [DataMember(Name="windspeedMiles", EmitDefaultValue=false)]
        public int WindspeedMiles { get; set; }

        /// <summary>
        /// Gets or Sets Forecasts
        /// </summary>
        [DataMember(Name="forecasts", EmitDefaultValue=false)]
        public List<WeatherForecastResponse> Forecasts { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class WeatherResponse {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Cloudcover: ").Append(Cloudcover).Append("\n");
            sb.Append("  Humidity: ").Append(Humidity).Append("\n");
            sb.Append("  ObservationTime: ").Append(ObservationTime).Append("\n");
            sb.Append("  PrecipMM: ").Append(PrecipMM).Append("\n");
            sb.Append("  Pressure: ").Append(Pressure).Append("\n");
            sb.Append("  TempC: ").Append(TempC).Append("\n");
            sb.Append("  TempF: ").Append(TempF).Append("\n");
            sb.Append("  Visibility: ").Append(Visibility).Append("\n");
            sb.Append("  WeatherCode: ").Append(WeatherCode).Append("\n");
            sb.Append("  WeatherDesc: ").Append(WeatherDesc).Append("\n");
            sb.Append("  WeatherIconUrl: ").Append(WeatherIconUrl).Append("\n");
            sb.Append("  Winddir16Point: ").Append(Winddir16Point).Append("\n");
            sb.Append("  WinddirDegree: ").Append(WinddirDegree).Append("\n");
            sb.Append("  WindspeedKmph: ").Append(WindspeedKmph).Append("\n");
            sb.Append("  WindspeedMiles: ").Append(WindspeedMiles).Append("\n");
            sb.Append("  Forecasts: ").Append(Forecasts).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((WeatherResponse)obj);
        }

        /// <summary>
        /// Returns true if WeatherResponse instances are equal
        /// </summary>
        /// <param name="other">Instance of WeatherResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(WeatherResponse other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Id == other.Id ||
                    
                    Id.Equals(other.Id)
                ) && 
                (
                    Cloudcover == other.Cloudcover ||
                    
                    Cloudcover.Equals(other.Cloudcover)
                ) && 
                (
                    Humidity == other.Humidity ||
                    
                    Humidity.Equals(other.Humidity)
                ) && 
                (
                    ObservationTime == other.ObservationTime ||
                    
                    ObservationTime.Equals(other.ObservationTime)
                ) && 
                (
                    PrecipMM == other.PrecipMM ||
                    
                    PrecipMM.Equals(other.PrecipMM)
                ) && 
                (
                    Pressure == other.Pressure ||
                    
                    Pressure.Equals(other.Pressure)
                ) && 
                (
                    TempC == other.TempC ||
                    
                    TempC.Equals(other.TempC)
                ) && 
                (
                    TempF == other.TempF ||
                    
                    TempF.Equals(other.TempF)
                ) && 
                (
                    Visibility == other.Visibility ||
                    
                    Visibility.Equals(other.Visibility)
                ) && 
                (
                    WeatherCode == other.WeatherCode ||
                    
                    WeatherCode.Equals(other.WeatherCode)
                ) && 
                (
                    WeatherDesc == other.WeatherDesc ||
                    WeatherDesc != null &&
                    WeatherDesc.Equals(other.WeatherDesc)
                ) && 
                (
                    WeatherIconUrl == other.WeatherIconUrl ||
                    WeatherIconUrl != null &&
                    WeatherIconUrl.Equals(other.WeatherIconUrl)
                ) && 
                (
                    Winddir16Point == other.Winddir16Point ||
                    Winddir16Point != null &&
                    Winddir16Point.Equals(other.Winddir16Point)
                ) && 
                (
                    WinddirDegree == other.WinddirDegree ||
                    
                    WinddirDegree.Equals(other.WinddirDegree)
                ) && 
                (
                    WindspeedKmph == other.WindspeedKmph ||
                    
                    WindspeedKmph.Equals(other.WindspeedKmph)
                ) && 
                (
                    WindspeedMiles == other.WindspeedMiles ||
                    
                    WindspeedMiles.Equals(other.WindspeedMiles)
                ) && 
                (
                    Forecasts == other.Forecasts ||
                    Forecasts != null &&
                    other.Forecasts != null &&
                    Forecasts.SequenceEqual(other.Forecasts)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    
                    hashCode = hashCode * 59 + Id.GetHashCode();
                    
                    hashCode = hashCode * 59 + Cloudcover.GetHashCode();
                    
                    hashCode = hashCode * 59 + Humidity.GetHashCode();
                    
                    hashCode = hashCode * 59 + ObservationTime.GetHashCode();
                    
                    hashCode = hashCode * 59 + PrecipMM.GetHashCode();
                    
                    hashCode = hashCode * 59 + Pressure.GetHashCode();
                    
                    hashCode = hashCode * 59 + TempC.GetHashCode();
                    
                    hashCode = hashCode * 59 + TempF.GetHashCode();
                    
                    hashCode = hashCode * 59 + Visibility.GetHashCode();
                    
                    hashCode = hashCode * 59 + WeatherCode.GetHashCode();
                    if (WeatherDesc != null)
                    hashCode = hashCode * 59 + WeatherDesc.GetHashCode();
                    if (WeatherIconUrl != null)
                    hashCode = hashCode * 59 + WeatherIconUrl.GetHashCode();
                    if (Winddir16Point != null)
                    hashCode = hashCode * 59 + Winddir16Point.GetHashCode();
                    
                    hashCode = hashCode * 59 + WinddirDegree.GetHashCode();
                    
                    hashCode = hashCode * 59 + WindspeedKmph.GetHashCode();
                    
                    hashCode = hashCode * 59 + WindspeedMiles.GetHashCode();
                    if (Forecasts != null)
                    hashCode = hashCode * 59 + Forecasts.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(WeatherResponse left, WeatherResponse right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(WeatherResponse left, WeatherResponse right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
