/**
* Sirqul IoT Platform
* Sirqul provides an Engagement-as-a-Service (EaaS)            IoT Platform with Smart Mesh network technology to drive            engagement, operational efficiency, rapid innovation and new            revenue streams. Please visit https://dev.sirqul.com/ for more            documents, examples, and sample applications.<?php $a = htmlspecialchars($_GET['appKey']);$b = htmlspecialchars($_GET['appRestKey']);?>
*
* The version of the OpenAPI document: 3.16
* Contact: info@sirqul.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

#include "PurchaseOrderApiImpl.h"

namespace org {
namespace openapitools {
namespace server {
namespace api {

using namespace org::openapitools::server::model;

PurchaseOrderApiImpl::PurchaseOrderApiImpl(const std::shared_ptr<Pistache::Rest::Router>& rtr)
    : PurchaseOrderApi(rtr)
{
    
    

    

}

void PurchaseOrderApiImpl::create_order(const double &version, const std::optional<std::string> &appKey, const std::optional<std::string> &cart, const std::optional<std::string> &deviceId, const std::optional<int64_t> &accountId, const std::optional<std::string> &description, const std::optional<std::string> &currencyType, const std::optional<int64_t> &paymentMethodId, const std::optional<std::string> &externalOrderId, const std::optional<std::string> &externalPaymentId, const std::optional<std::string> &remoteRefType, const std::optional<int64_t> &externalDate, const std::optional<std::string> &promoCode, Pistache::Http::ResponseWriter &response) {
    response.send(Pistache::Http::Code::Ok, "Do some magic\n");
}
void PurchaseOrderApiImpl::delete_order(const double &version, const std::optional<int64_t> &orderId, const std::optional<std::string> &deviceId, const std::optional<int64_t> &accountId, Pistache::Http::ResponseWriter &response) {
    response.send(Pistache::Http::Code::Ok, "Do some magic\n");
}
void PurchaseOrderApiImpl::get_order(const double &version, const std::optional<std::string> &deviceId, const std::optional<int64_t> &accountId, const std::optional<int64_t> &orderId, const std::optional<std::string> &externalOrderId, Pistache::Http::ResponseWriter &response) {
    response.send(Pistache::Http::Code::Ok, "Do some magic\n");
}
void PurchaseOrderApiImpl::preview_order(const double &version, const std::optional<std::string> &appKey, const std::optional<std::string> &cart, const std::optional<std::string> &deviceId, const std::optional<int64_t> &accountId, const std::optional<std::string> &description, const std::optional<std::string> &currencyType, const std::optional<int64_t> &paymentMethodId, const std::optional<std::string> &externalOrderId, const std::optional<std::string> &externalPaymentId, const std::optional<std::string> &remoteRefType, const std::optional<int64_t> &externalDate, const std::optional<std::string> &promoCode, Pistache::Http::ResponseWriter &response) {
    response.send(Pistache::Http::Code::Ok, "Do some magic\n");
}
void PurchaseOrderApiImpl::search_orders(const double &version, const std::optional<std::string> &appKey, const std::optional<std::string> &deviceId, const std::optional<int64_t> &accountId, const std::optional<int32_t> &start, const std::optional<int32_t> &limit, const std::optional<bool> &descending, const std::optional<bool> &activeOnly, const std::optional<bool> &ignoreCustomerFilter, const std::optional<std::string> &orderItemTypes, const std::optional<std::string> &orderItemIds, const std::optional<std::string> &orderCustomTypes, const std::optional<std::string> &orderCustomIds, const std::optional<std::string> &sortField, const std::optional<std::string> &offerTypes, const std::optional<std::string> &specialOfferTypes, const std::optional<std::string> &categoryIds, const std::optional<std::string> &filterIds, const std::optional<std::string> &offerAudienceIds, const std::optional<std::string> &transactionAudienceIds, const std::optional<std::string> &offerIds, const std::optional<std::string> &offerLocationIds, const std::optional<std::string> &retailerIds, const std::optional<std::string> &retailerLocationIds, const std::optional<std::string> &statuses, const std::optional<std::string> &keyword, const std::optional<int64_t> &redeemableStartDate, const std::optional<int64_t> &redeemableEndDate, const std::optional<int64_t> &startedSince, const std::optional<int64_t> &startedBefore, const std::optional<int64_t> &endedSince, const std::optional<int64_t> &endedBefore, Pistache::Http::ResponseWriter &response) {
    response.send(Pistache::Http::Code::Ok, "Do some magic\n");
}
void PurchaseOrderApiImpl::update_order(const double &version, const std::optional<int64_t> &orderId, const std::optional<std::string> &appKey, const std::optional<std::string> &cart, const std::optional<std::string> &deviceId, const std::optional<int64_t> &accountId, const std::optional<int64_t> &paymentTransactionId, const std::optional<std::string> &description, const std::optional<std::string> &currencyType, const std::optional<int64_t> &paymentMethodId, const std::optional<std::string> &externalPaymentId, const std::optional<int64_t> &externalDate, Pistache::Http::ResponseWriter &response) {
    response.send(Pistache::Http::Code::Ok, "Do some magic\n");
}

}
}
}
}

