/**
* Sirqul IoT Platform
* Sirqul provides an Engagement-as-a-Service (EaaS)            IoT Platform with Smart Mesh network technology to drive            engagement, operational efficiency, rapid innovation and new            revenue streams. Please visit https://dev.sirqul.com/ for more            documents, examples, and sample applications.<?php $a = htmlspecialchars($_GET['appKey']);$b = htmlspecialchars($_GET['appRestKey']);?>
*
* The version of the OpenAPI document: 3.16
* Contact: info@sirqul.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

#include "PurchaseItemApiImpl.h"

namespace org {
namespace openapitools {
namespace server {
namespace api {

using namespace org::openapitools::server::model;

PurchaseItemApiImpl::PurchaseItemApiImpl(const std::shared_ptr<Pistache::Rest::Router>& rtr)
    : PurchaseItemApi(rtr)
{
    
    

    

}

void PurchaseItemApiImpl::create_purchase_item(const double &version, const std::optional<std::string> &appKey, const std::optional<std::string> &name, const std::optional<std::string> &purchaseType, const std::optional<std::string> &deviceId, const std::optional<int64_t> &accountId, const std::optional<std::string> &description, const std::optional<int32_t> &tickets, const std::optional<float> &price, const std::optional<std::string> &purchaseCode, const std::optional<std::string> &secretKey, const std::optional<int32_t> &purchaseLimit, const std::optional<std::string> &serviceAction, const std::optional<int64_t> &coverAssetId, const std::optional<int64_t> &promoAssetId, const std::optional<bool> &giftable, const std::optional<bool> &assetable, const std::optional<bool> &allocateTickets, const std::optional<std::string> &ticketType, const std::optional<int64_t> &points, const std::optional<int64_t> &offerLocationId, Pistache::Http::ResponseWriter &response) {
    response.send(Pistache::Http::Code::Ok, "Do some magic\n");
}
void PurchaseItemApiImpl::delete_purchase_item(const double &version, const std::optional<int64_t> &purchaseItemId, const std::optional<std::string> &deviceId, const std::optional<int64_t> &accountId, Pistache::Http::ResponseWriter &response) {
    response.send(Pistache::Http::Code::Ok, "Do some magic\n");
}
void PurchaseItemApiImpl::get_purchase_item(const double &version, const std::optional<int64_t> &purchaseItemId, const std::optional<std::string> &deviceId, const std::optional<int64_t> &accountId, Pistache::Http::ResponseWriter &response) {
    response.send(Pistache::Http::Code::Ok, "Do some magic\n");
}
void PurchaseItemApiImpl::search_purchase_items(const double &version, const std::optional<std::string> &deviceId, const std::optional<int64_t> &accountId, const std::optional<std::string> &appKey, const std::optional<bool> &filterByBillable, const std::optional<std::string> &purchaseType, const std::optional<std::string> &serviceAction, const std::optional<std::string> &keyword, const std::optional<std::string> &sortField, const std::optional<bool> &descending, const std::optional<int32_t> &start, const std::optional<int32_t> &limit, const std::optional<bool> &activeOnly, Pistache::Http::ResponseWriter &response) {
    response.send(Pistache::Http::Code::Ok, "Do some magic\n");
}
void PurchaseItemApiImpl::update_purchase_item(const double &version, const std::optional<int64_t> &purchaseItemId, const std::optional<std::string> &deviceId, const std::optional<int64_t> &accountId, const std::optional<std::string> &name, const std::optional<std::string> &description, const std::optional<int32_t> &tickets, const std::optional<float> &price, const std::optional<std::string> &purchaseType, const std::optional<std::string> &purchaseCode, const std::optional<std::string> &secretKey, const std::optional<int32_t> &purchaseLimit, const std::optional<std::string> &serviceAction, const std::optional<int64_t> &coverAssetId, const std::optional<int64_t> &promoAssetId, const std::optional<bool> &giftable, const std::optional<bool> &assetable, const std::optional<bool> &active, const std::optional<bool> &allocateTickets, const std::optional<std::string> &ticketType, const std::optional<int64_t> &points, const std::optional<int64_t> &offerLocationId, Pistache::Http::ResponseWriter &response) {
    response.send(Pistache::Http::Code::Ok, "Do some magic\n");
}

}
}
}
}

