// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Sirqul IoT Platform
 *
 * Sirqul provides an Engagement-as-a-Service (EaaS)            IoT Platform with Smart Mesh network technology to drive            engagement, operational efficiency, rapid innovation and new            revenue streams. Please visit https://dev.sirqul.com/ for more            documents, examples, and sample applications.<?php $a = htmlspecialchars($_GET['appKey']);$b = htmlspecialchars($_GET['appRestKey']);?>
 *
 * API version: 3.16
 * Contact: info@sirqul.com
 */

package openapi

import (
	"context"
	"net/http"
	"errors"
)

// RouteSettingAPIService is a service that implements the logic for the RouteSettingAPIServicer
// This service should implement the business logic for every endpoint for the RouteSettingAPI API.
// Include any external packages or services that will be required by this service.
type RouteSettingAPIService struct {
}

// NewRouteSettingAPIService creates a default api service
func NewRouteSettingAPIService() *RouteSettingAPIService {
	return &RouteSettingAPIService{}
}

// SearchRouteSettings - Search Route Settings
func (s *RouteSettingAPIService) SearchRouteSettings(ctx context.Context, version float32, sortField string, descending bool, start int32, limit int32, activeOnly bool, hubId int64, programId int64, keyword string) (ImplResponse, error) {
	// TODO - update SearchRouteSettings with the required logic for this service method.
	// Add api_route_setting_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, []RouteSettings{}) or use other options such as http.Ok ...
	// return Response(200, []RouteSettings{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("SearchRouteSettings method not implemented")
}

// CreateRouteSettings - Create Route Setting
func (s *RouteSettingAPIService) CreateRouteSettings(ctx context.Context, version float32, body RouteSettings) (ImplResponse, error) {
	// TODO - update CreateRouteSettings with the required logic for this service method.
	// Add api_route_setting_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, RouteSettings{}) or use other options such as http.Ok ...
	// return Response(200, RouteSettings{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("CreateRouteSettings method not implemented")
}

// GetRouteSettings - Get Route Setting
func (s *RouteSettingAPIService) GetRouteSettings(ctx context.Context, version float32, routeSettingsId int64) (ImplResponse, error) {
	// TODO - update GetRouteSettings with the required logic for this service method.
	// Add api_route_setting_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, RouteSettings{}) or use other options such as http.Ok ...
	// return Response(200, RouteSettings{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetRouteSettings method not implemented")
}

// UpdateRouteSettings - Update Route Setting
func (s *RouteSettingAPIService) UpdateRouteSettings(ctx context.Context, version float32, routeSettingsId int64, body RouteSettings) (ImplResponse, error) {
	// TODO - update UpdateRouteSettings with the required logic for this service method.
	// Add api_route_setting_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, RouteSettings{}) or use other options such as http.Ok ...
	// return Response(200, RouteSettings{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("UpdateRouteSettings method not implemented")
}

// DeleteRouteSettings - Delete Route Setting
func (s *RouteSettingAPIService) DeleteRouteSettings(ctx context.Context, version float32, routeSettingsId int64) (ImplResponse, error) {
	// TODO - update DeleteRouteSettings with the required logic for this service method.
	// Add api_route_setting_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, map[string]interface{}{}) or use other options such as http.Ok ...
	// return Response(200, map[string]interface{}{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("DeleteRouteSettings method not implemented")
}
