// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Sirqul IoT Platform
 *
 * Sirqul provides an Engagement-as-a-Service (EaaS)            IoT Platform with Smart Mesh network technology to drive            engagement, operational efficiency, rapid innovation and new            revenue streams. Please visit https://dev.sirqul.com/ for more            documents, examples, and sample applications.<?php $a = htmlspecialchars($_GET['appKey']);$b = htmlspecialchars($_GET['appRestKey']);?>
 *
 * API version: 3.16
 * Contact: info@sirqul.com
 */

package openapi

import (
	"context"
	"net/http"
	"errors"
)

// QuestionAPIService is a service that implements the logic for the QuestionAPIServicer
// This service should implement the business logic for every endpoint for the QuestionAPI API.
// Include any external packages or services that will be required by this service.
type QuestionAPIService struct {
}

// NewQuestionAPIService creates a default api service
func NewQuestionAPIService() *QuestionAPIService {
	return &QuestionAPIService{}
}

// CreateQuestion - Create Question
func (s *QuestionAPIService) CreateQuestion(ctx context.Context, version float32, accountId int64, question string, answers string, active bool, allocateTickets bool, ticketCount int64, tags string, videoURL string, assetId int64, ticketType string, points int64) (ImplResponse, error) {
	// TODO - update CreateQuestion with the required logic for this service method.
	// Add api_question_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, QuestionResponse{}) or use other options such as http.Ok ...
	// return Response(200, QuestionResponse{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("CreateQuestion method not implemented")
}

// DeleteQuestion - Delete Question
func (s *QuestionAPIService) DeleteQuestion(ctx context.Context, version float32, questionId int64, accountId int64) (ImplResponse, error) {
	// TODO - update DeleteQuestion with the required logic for this service method.
	// Add api_question_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, SirqulResponse{}) or use other options such as http.Ok ...
	// return Response(200, SirqulResponse{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("DeleteQuestion method not implemented")
}

// GetQuestion - Get Question
func (s *QuestionAPIService) GetQuestion(ctx context.Context, version float32, questionId int64, accountId int64) (ImplResponse, error) {
	// TODO - update GetQuestion with the required logic for this service method.
	// Add api_question_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, QuestionResponse{}) or use other options such as http.Ok ...
	// return Response(200, QuestionResponse{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetQuestion method not implemented")
}

// SearchQuestions - Search Questions
func (s *QuestionAPIService) SearchQuestions(ctx context.Context, version float32, accountId int64, sortField string, descending bool, activeOnly bool, start int32, limit int32, keyword string) (ImplResponse, error) {
	// TODO - update SearchQuestions with the required logic for this service method.
	// Add api_question_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, []QuestionResponse{}) or use other options such as http.Ok ...
	// return Response(200, []QuestionResponse{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("SearchQuestions method not implemented")
}

// UpdateQuestion - Update Question
func (s *QuestionAPIService) UpdateQuestion(ctx context.Context, version float32, questionId int64, accountId int64, ticketCount int64, question string, answers string, tags string, videoURL string, assetId int64, active bool, allocateTickets bool, ticketType string, points int64) (ImplResponse, error) {
	// TODO - update UpdateQuestion with the required logic for this service method.
	// Add api_question_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, QuestionResponse{}) or use other options such as http.Ok ...
	// return Response(200, QuestionResponse{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("UpdateQuestion method not implemented")
}
