// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Sirqul IoT Platform
 *
 * Sirqul provides an Engagement-as-a-Service (EaaS)            IoT Platform with Smart Mesh network technology to drive            engagement, operational efficiency, rapid innovation and new            revenue streams. Please visit https://dev.sirqul.com/ for more            documents, examples, and sample applications.<?php $a = htmlspecialchars($_GET['appKey']);$b = htmlspecialchars($_GET['appRestKey']);?>
 *
 * API version: 3.16
 * Contact: info@sirqul.com
 */

package openapi

import (
	"net/http"
	"strings"
)

// LikeAPIController binds http requests to an api service and writes the service results to the http response
type LikeAPIController struct {
	service LikeAPIServicer
	errorHandler ErrorHandler
}

// LikeAPIOption for how the controller is set up.
type LikeAPIOption func(*LikeAPIController)

// WithLikeAPIErrorHandler inject ErrorHandler into controller
func WithLikeAPIErrorHandler(h ErrorHandler) LikeAPIOption {
	return func(c *LikeAPIController) {
		c.errorHandler = h
	}
}

// NewLikeAPIController creates a default api controller
func NewLikeAPIController(s LikeAPIServicer, opts ...LikeAPIOption) *LikeAPIController {
	controller := &LikeAPIController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the LikeAPIController
func (c *LikeAPIController) Routes() Routes {
	return Routes{
		"RegisterLike": Route{
			"RegisterLike",
			strings.ToUpper("Post"),
			"/api/3.18/like",
			c.RegisterLike,
		},
		"RemoveLike": Route{
			"RemoveLike",
			strings.ToUpper("Post"),
			"/api/3.18/like/delete",
			c.RemoveLike,
		},
		"SearchLikes": Route{
			"SearchLikes",
			strings.ToUpper("Get"),
			"/api/3.18/like/search",
			c.SearchLikes,
		},
	}
}

// OrderedRoutes returns all the api routes in a deterministic order for the LikeAPIController
func (c *LikeAPIController) OrderedRoutes() []Route {
	return []Route{
		Route{
			"RegisterLike",
			strings.ToUpper("Post"),
			"/api/3.18/like",
			c.RegisterLike,
		},
		Route{
			"RemoveLike",
			strings.ToUpper("Post"),
			"/api/3.18/like/delete",
			c.RemoveLike,
		},
		Route{
			"SearchLikes",
			strings.ToUpper("Get"),
			"/api/3.18/like/search",
			c.SearchLikes,
		},
	}
}



// RegisterLike - Create Like
func (c *LikeAPIController) RegisterLike(w http.ResponseWriter, r *http.Request) {
	query, err := parseQuery(r.URL.RawQuery)
	if err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	var likableTypeParam string
	if query.Has("likableType") {
		param := query.Get("likableType")

		likableTypeParam = param
	} else {
		c.errorHandler(w, r, &RequiredError{Field: "likableType"}, nil)
		return
	}
	var likableIdParam int64
	if query.Has("likableId") {
		param, err := parseNumericParameter[int64](
			query.Get("likableId"),
			WithParse[int64](parseInt64),
		)
		if err != nil {
			c.errorHandler(w, r, &ParsingError{Param: "likableId", Err: err}, nil)
			return
		}

		likableIdParam = param
	} else {
		c.errorHandler(w, r, &RequiredError{Field: "likableId"}, nil)
		return
	}
	var deviceIdParam string
	if query.Has("deviceId") {
		param := query.Get("deviceId")

		deviceIdParam = param
	} else {
	}
	var accountIdParam int64
	if query.Has("accountId") {
		param, err := parseNumericParameter[int64](
			query.Get("accountId"),
			WithParse[int64](parseInt64),
		)
		if err != nil {
			c.errorHandler(w, r, &ParsingError{Param: "accountId", Err: err}, nil)
			return
		}

		accountIdParam = param
	} else {
	}
	var permissionableTypeParam string
	if query.Has("permissionableType") {
		param := query.Get("permissionableType")

		permissionableTypeParam = param
	} else {
	}
	var permissionableIdParam int64
	if query.Has("permissionableId") {
		param, err := parseNumericParameter[int64](
			query.Get("permissionableId"),
			WithParse[int64](parseInt64),
		)
		if err != nil {
			c.errorHandler(w, r, &ParsingError{Param: "permissionableId", Err: err}, nil)
			return
		}

		permissionableIdParam = param
	} else {
	}
	var likeParam bool
	if query.Has("like") {
		param, err := parseBoolParameter(
			query.Get("like"),
			WithParse[bool](parseBool),
		)
		if err != nil {
			c.errorHandler(w, r, &ParsingError{Param: "like", Err: err}, nil)
			return
		}

		likeParam = param
	} else {
	}
	var appParam string
	if query.Has("app") {
		param := query.Get("app")

		appParam = param
	} else {
	}
	var gameTypeParam string
	if query.Has("gameType") {
		param := query.Get("gameType")

		gameTypeParam = param
	} else {
	}
	var appKeyParam string
	if query.Has("appKey") {
		param := query.Get("appKey")

		appKeyParam = param
	} else {
	}
	var latitudeParam float64
	if query.Has("latitude") {
		param, err := parseNumericParameter[float64](
			query.Get("latitude"),
			WithParse[float64](parseFloat64),
		)
		if err != nil {
			c.errorHandler(w, r, &ParsingError{Param: "latitude", Err: err}, nil)
			return
		}

		latitudeParam = param
	} else {
	}
	var longitudeParam float64
	if query.Has("longitude") {
		param, err := parseNumericParameter[float64](
			query.Get("longitude"),
			WithParse[float64](parseFloat64),
		)
		if err != nil {
			c.errorHandler(w, r, &ParsingError{Param: "longitude", Err: err}, nil)
			return
		}

		longitudeParam = param
	} else {
	}
	result, err := c.service.RegisterLike(r.Context(), likableTypeParam, likableIdParam, deviceIdParam, accountIdParam, permissionableTypeParam, permissionableIdParam, likeParam, appParam, gameTypeParam, appKeyParam, latitudeParam, longitudeParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// RemoveLike - Delete Like
func (c *LikeAPIController) RemoveLike(w http.ResponseWriter, r *http.Request) {
	query, err := parseQuery(r.URL.RawQuery)
	if err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	var likableTypeParam string
	if query.Has("likableType") {
		param := query.Get("likableType")

		likableTypeParam = param
	} else {
		c.errorHandler(w, r, &RequiredError{Field: "likableType"}, nil)
		return
	}
	var likableIdParam int64
	if query.Has("likableId") {
		param, err := parseNumericParameter[int64](
			query.Get("likableId"),
			WithParse[int64](parseInt64),
		)
		if err != nil {
			c.errorHandler(w, r, &ParsingError{Param: "likableId", Err: err}, nil)
			return
		}

		likableIdParam = param
	} else {
		c.errorHandler(w, r, &RequiredError{Field: "likableId"}, nil)
		return
	}
	var deviceIdParam string
	if query.Has("deviceId") {
		param := query.Get("deviceId")

		deviceIdParam = param
	} else {
	}
	var accountIdParam int64
	if query.Has("accountId") {
		param, err := parseNumericParameter[int64](
			query.Get("accountId"),
			WithParse[int64](parseInt64),
		)
		if err != nil {
			c.errorHandler(w, r, &ParsingError{Param: "accountId", Err: err}, nil)
			return
		}

		accountIdParam = param
	} else {
	}
	var latitudeParam float64
	if query.Has("latitude") {
		param, err := parseNumericParameter[float64](
			query.Get("latitude"),
			WithParse[float64](parseFloat64),
		)
		if err != nil {
			c.errorHandler(w, r, &ParsingError{Param: "latitude", Err: err}, nil)
			return
		}

		latitudeParam = param
	} else {
	}
	var longitudeParam float64
	if query.Has("longitude") {
		param, err := parseNumericParameter[float64](
			query.Get("longitude"),
			WithParse[float64](parseFloat64),
		)
		if err != nil {
			c.errorHandler(w, r, &ParsingError{Param: "longitude", Err: err}, nil)
			return
		}

		longitudeParam = param
	} else {
	}
	result, err := c.service.RemoveLike(r.Context(), likableTypeParam, likableIdParam, deviceIdParam, accountIdParam, latitudeParam, longitudeParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// SearchLikes - Search Likes
func (c *LikeAPIController) SearchLikes(w http.ResponseWriter, r *http.Request) {
	query, err := parseQuery(r.URL.RawQuery)
	if err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	var likableTypeParam string
	if query.Has("likableType") {
		param := query.Get("likableType")

		likableTypeParam = param
	} else {
		c.errorHandler(w, r, &RequiredError{Field: "likableType"}, nil)
		return
	}
	var likableIdParam int64
	if query.Has("likableId") {
		param, err := parseNumericParameter[int64](
			query.Get("likableId"),
			WithParse[int64](parseInt64),
		)
		if err != nil {
			c.errorHandler(w, r, &ParsingError{Param: "likableId", Err: err}, nil)
			return
		}

		likableIdParam = param
	} else {
		c.errorHandler(w, r, &RequiredError{Field: "likableId"}, nil)
		return
	}
	var deviceIdParam string
	if query.Has("deviceId") {
		param := query.Get("deviceId")

		deviceIdParam = param
	} else {
	}
	var accountIdParam int64
	if query.Has("accountId") {
		param, err := parseNumericParameter[int64](
			query.Get("accountId"),
			WithParse[int64](parseInt64),
		)
		if err != nil {
			c.errorHandler(w, r, &ParsingError{Param: "accountId", Err: err}, nil)
			return
		}

		accountIdParam = param
	} else {
	}
	var connectionAccountIdsParam string
	if query.Has("connectionAccountIds") {
		param := query.Get("connectionAccountIds")

		connectionAccountIdsParam = param
	} else {
	}
	var sortFieldParam string
	if query.Has("sortField") {
		param := query.Get("sortField")

		sortFieldParam = param
	} else {
		param := "ID"
		sortFieldParam = param
	}
	var descendingParam bool
	if query.Has("descending") {
		param, err := parseBoolParameter(
			query.Get("descending"),
			WithParse[bool](parseBool),
		)
		if err != nil {
			c.errorHandler(w, r, &ParsingError{Param: "descending", Err: err}, nil)
			return
		}

		descendingParam = param
	} else {
		var param bool = true
		descendingParam = param
	}
	var updatedSinceParam int64
	if query.Has("updatedSince") {
		param, err := parseNumericParameter[int64](
			query.Get("updatedSince"),
			WithParse[int64](parseInt64),
		)
		if err != nil {
			c.errorHandler(w, r, &ParsingError{Param: "updatedSince", Err: err}, nil)
			return
		}

		updatedSinceParam = param
	} else {
	}
	var updatedBeforeParam int64
	if query.Has("updatedBefore") {
		param, err := parseNumericParameter[int64](
			query.Get("updatedBefore"),
			WithParse[int64](parseInt64),
		)
		if err != nil {
			c.errorHandler(w, r, &ParsingError{Param: "updatedBefore", Err: err}, nil)
			return
		}

		updatedBeforeParam = param
	} else {
	}
	var startParam int32
	if query.Has("start") {
		param, err := parseNumericParameter[int32](
			query.Get("start"),
			WithParse[int32](parseInt32),
		)
		if err != nil {
			c.errorHandler(w, r, &ParsingError{Param: "start", Err: err}, nil)
			return
		}

		startParam = param
	} else {
		var param int32 = 0
		startParam = param
	}
	var limitParam int32
	if query.Has("limit") {
		param, err := parseNumericParameter[int32](
			query.Get("limit"),
			WithParse[int32](parseInt32),
		)
		if err != nil {
			c.errorHandler(w, r, &ParsingError{Param: "limit", Err: err}, nil)
			return
		}

		limitParam = param
	} else {
		var param int32 = 20
		limitParam = param
	}
	result, err := c.service.SearchLikes(r.Context(), likableTypeParam, likableIdParam, deviceIdParam, accountIdParam, connectionAccountIdsParam, sortFieldParam, descendingParam, updatedSinceParam, updatedBeforeParam, startParam, limitParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}
