// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Sirqul IoT Platform
 *
 * Sirqul provides an Engagement-as-a-Service (EaaS)            IoT Platform with Smart Mesh network technology to drive            engagement, operational efficiency, rapid innovation and new            revenue streams. Please visit https://dev.sirqul.com/ for more            documents, examples, and sample applications.<?php $a = htmlspecialchars($_GET['appKey']);$b = htmlspecialchars($_GET['appRestKey']);?>
 *
 * API version: 3.16
 * Contact: info@sirqul.com
 */

package openapi

import (
	"context"
	"net/http"
	"errors"
)

// ScheduledNotificationAPIService is a service that implements the logic for the ScheduledNotificationAPIServicer
// This service should implement the business logic for every endpoint for the ScheduledNotificationAPI API.
// Include any external packages or services that will be required by this service.
type ScheduledNotificationAPIService struct {
}

// NewScheduledNotificationAPIService creates a default api service
func NewScheduledNotificationAPIService() *ScheduledNotificationAPIService {
	return &ScheduledNotificationAPIService{}
}

// CreateScheduledNotification - Create Scheduled Notification
func (s *ScheduledNotificationAPIService) CreateScheduledNotification(ctx context.Context, version float32, accountId int64, name string, type_ string, message string, contentId int64, contentName string, contentType string, parentId int64, parentType string, appKey string, groupingId string, connectionGroupIds string, connectionAccountIds string, audienceId int64, audienceIds string, albumIds string, reportId int64, reportParams string, endpointURL string, payload string, scheduledDate int64, startDate int64, endDate int64, cronExpression string, cronType string, metaData string, conditionalInput string, templateType string, visibility string, active bool, sendNow bool, eventType string, deepLinkURI string, sendToAll bool) (ImplResponse, error) {
	// TODO - update CreateScheduledNotification with the required logic for this service method.
	// Add api_scheduled_notification_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, ScheduledNotificationFullResponse{}) or use other options such as http.Ok ...
	// return Response(200, ScheduledNotificationFullResponse{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("CreateScheduledNotification method not implemented")
}

// DeleteScheduledNotification - Delete Scheduled Notification
func (s *ScheduledNotificationAPIService) DeleteScheduledNotification(ctx context.Context, version float32, accountId int64, scheduledNotificationId int64, deleteByGroupingId bool) (ImplResponse, error) {
	// TODO - update DeleteScheduledNotification with the required logic for this service method.
	// Add api_scheduled_notification_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, ScheduledNotificationFullResponse{}) or use other options such as http.Ok ...
	// return Response(200, ScheduledNotificationFullResponse{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("DeleteScheduledNotification method not implemented")
}

// ScheduleNotificationListings - Generate Schedule Notifications
func (s *ScheduledNotificationAPIService) ScheduleNotificationListings(ctx context.Context, version float32, accountId int64, appKey string, reportName string, message string, offset int32, recipientReportId int64, reportParams string, type_ string) (ImplResponse, error) {
	// TODO - update ScheduleNotificationListings with the required logic for this service method.
	// Add api_scheduled_notification_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, SirqulResponse{}) or use other options such as http.Ok ...
	// return Response(200, SirqulResponse{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ScheduleNotificationListings method not implemented")
}

// GetScheduledNotification - Get Scheduled Notification
func (s *ScheduledNotificationAPIService) GetScheduledNotification(ctx context.Context, version float32, accountId int64, scheduledNotificationId int64) (ImplResponse, error) {
	// TODO - update GetScheduledNotification with the required logic for this service method.
	// Add api_scheduled_notification_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, ScheduledNotificationFullResponse{}) or use other options such as http.Ok ...
	// return Response(200, ScheduledNotificationFullResponse{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetScheduledNotification method not implemented")
}

// SearchScheduledNotifications - Search Scheduled Notifications
func (s *ScheduledNotificationAPIService) SearchScheduledNotifications(ctx context.Context, version float32, accountId int64, groupingId string, audienceId int64, filter string, types string, contentIds string, contentTypes string, parentIds string, parentTypes string, statuses string, templateTypes string, appKey string, keyword string, sortField string, descending bool, start int32, limit int32, activeOnly bool, groupByGroupingId bool, returnAudienceAccountCount bool) (ImplResponse, error) {
	// TODO - update SearchScheduledNotifications with the required logic for this service method.
	// Add api_scheduled_notification_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, ScheduledNotificationFullResponse{}) or use other options such as http.Ok ...
	// return Response(200, ScheduledNotificationFullResponse{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("SearchScheduledNotifications method not implemented")
}

// UpdateScheduledNotification - Update Scheduled Notification
func (s *ScheduledNotificationAPIService) UpdateScheduledNotification(ctx context.Context, version float32, scheduledNotificationId int64, accountId int64, name string, type_ string, message string, payload string, contentId int64, contentName string, contentType string, parentId int64, parentType string, appKey string, groupingId string, connectionGroupIds string, connectionAccountIds string, audienceId int64, audienceIds string, albumIds string, reportId int64, reportParams string, endpointURL string, scheduledDate int64, startDate int64, endDate int64, cronExpression string, cronType string, metaData string, conditionalInput string, templateType string, visibility string, active bool, errorMessage string, status string, updateByGroupingId bool, sendNow bool, eventType string, deepLinkURI string, sendToAll bool) (ImplResponse, error) {
	// TODO - update UpdateScheduledNotification with the required logic for this service method.
	// Add api_scheduled_notification_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, ScheduledNotificationFullResponse{}) or use other options such as http.Ok ...
	// return Response(200, ScheduledNotificationFullResponse{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("UpdateScheduledNotification method not implemented")
}
