// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Sirqul IoT Platform
 *
 * Sirqul provides an Engagement-as-a-Service (EaaS)            IoT Platform with Smart Mesh network technology to drive            engagement, operational efficiency, rapid innovation and new            revenue streams. Please visit https://dev.sirqul.com/ for more            documents, examples, and sample applications.<?php $a = htmlspecialchars($_GET['appKey']);$b = htmlspecialchars($_GET['appRestKey']);?>
 *
 * API version: 3.16
 * Contact: info@sirqul.com
 */

package openapi




type ScheduledNotificationFullResponse struct {

	ScheduledNotificationId int64 `json:"scheduledNotificationId,omitempty"`

	Active bool `json:"active,omitempty"`

	Status string `json:"status,omitempty"`

	Type string `json:"type,omitempty"`

	Name string `json:"name,omitempty"`

	Message string `json:"message,omitempty"`

	GroupingId string `json:"groupingId,omitempty"`

	ScheduledDate int64 `json:"scheduledDate,omitempty"`

	StartDate int64 `json:"startDate,omitempty"`

	EndDate int64 `json:"endDate,omitempty"`

	Owner AccountShortResponse `json:"owner,omitempty"`

	BillableEntity BillableEntityShortResponse `json:"billableEntity,omitempty"`

	ContentId int64 `json:"contentId,omitempty"`

	ContentName string `json:"contentName,omitempty"`

	ContentType string `json:"contentType,omitempty"`

	ParentId int64 `json:"parentId,omitempty"`

	ParentType string `json:"parentType,omitempty"`

	Application ApplicationMiniResponse `json:"application,omitempty"`

	TargetId int64 `json:"targetId,omitempty"`

	TargetName string `json:"targetName,omitempty"`

	TargetType string `json:"targetType,omitempty"`

	TargetParams string `json:"targetParams,omitempty"`

	DeliverEstimate int64 `json:"deliverEstimate,omitempty"`

	DeliverCount int64 `json:"deliverCount,omitempty"`

	DeliverTotal int64 `json:"deliverTotal,omitempty"`

	DeliverFailed int64 `json:"deliverFailed,omitempty"`

	ProcessingTime int64 `json:"processingTime,omitempty"`

	SendingTime int64 `json:"sendingTime,omitempty"`

	Updated int64 `json:"updated,omitempty"`

	Created int64 `json:"created,omitempty"`

	CronExpression string `json:"cronExpression,omitempty"`

	EndpointURL string `json:"endpointURL,omitempty"`

	Payload string `json:"payload,omitempty"`

	ConditionalInput string `json:"conditionalInput,omitempty"`

	ConnectionAccountIds []int64 `json:"connectionAccountIds,omitempty"`

	TemplateType string `json:"templateType,omitempty"`

	GroupedTypes []string `json:"groupedTypes,omitempty"`
}

// AssertScheduledNotificationFullResponseRequired checks if the required fields are not zero-ed
func AssertScheduledNotificationFullResponseRequired(obj ScheduledNotificationFullResponse) error {
	if err := AssertAccountShortResponseRequired(obj.Owner); err != nil {
		return err
	}
	if err := AssertBillableEntityShortResponseRequired(obj.BillableEntity); err != nil {
		return err
	}
	if err := AssertApplicationMiniResponseRequired(obj.Application); err != nil {
		return err
	}
	return nil
}

// AssertScheduledNotificationFullResponseConstraints checks if the values respects the defined constraints
func AssertScheduledNotificationFullResponseConstraints(obj ScheduledNotificationFullResponse) error {
	if err := AssertAccountShortResponseConstraints(obj.Owner); err != nil {
		return err
	}
	if err := AssertBillableEntityShortResponseConstraints(obj.BillableEntity); err != nil {
		return err
	}
	if err := AssertApplicationMiniResponseConstraints(obj.Application); err != nil {
		return err
	}
	return nil
}
