// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Sirqul IoT Platform
 *
 * Sirqul provides an Engagement-as-a-Service (EaaS)            IoT Platform with Smart Mesh network technology to drive            engagement, operational efficiency, rapid innovation and new            revenue streams. Please visit https://dev.sirqul.com/ for more            documents, examples, and sample applications.<?php $a = htmlspecialchars($_GET['appKey']);$b = htmlspecialchars($_GET['appRestKey']);?>
 *
 * API version: 3.16
 * Contact: info@sirqul.com
 */

package openapi




type NoteFullResponse struct {

	Valid bool `json:"valid,omitempty"`

	Message string `json:"message,omitempty"`

	Version float64 `json:"version,omitempty"`

	SerializeNulls bool `json:"serializeNulls,omitempty"`

	StartTimeLog int64 `json:"startTimeLog,omitempty"`

	ErrorCode string `json:"errorCode,omitempty"`

	Request []NameStringValueResponse `json:"request,omitempty"`

	NoteId int64 `json:"noteId,omitempty"`

	Comment string `json:"comment,omitempty"`

	Tags string `json:"tags,omitempty"`

	LikesCount int64 `json:"likesCount,omitempty"`

	DislikesCount int64 `json:"dislikesCount,omitempty"`

	DateCreated int64 `json:"dateCreated,omitempty"`

	CreatedDate int64 `json:"createdDate,omitempty"`

	UpdatedDate int64 `json:"updatedDate,omitempty"`

	Owner AccountShortResponse `json:"owner,omitempty"`

	Latitude float64 `json:"latitude,omitempty"`

	Longitude float64 `json:"longitude,omitempty"`

	LocationDescription string `json:"locationDescription,omitempty"`

	AttachedAssets []AssetShortResponse `json:"attachedAssets,omitempty"`

	Likes []LikeResponse `json:"likes,omitempty"`

	HasLiked bool `json:"hasLiked,omitempty"`

	HasDisliked bool `json:"hasDisliked,omitempty"`

	Returning string `json:"returning,omitempty"`
}

// AssertNoteFullResponseRequired checks if the required fields are not zero-ed
func AssertNoteFullResponseRequired(obj NoteFullResponse) error {
	for _, el := range obj.Request {
		if err := AssertNameStringValueResponseRequired(el); err != nil {
			return err
		}
	}
	if err := AssertAccountShortResponseRequired(obj.Owner); err != nil {
		return err
	}
	for _, el := range obj.AttachedAssets {
		if err := AssertAssetShortResponseRequired(el); err != nil {
			return err
		}
	}
	for _, el := range obj.Likes {
		if err := AssertLikeResponseRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertNoteFullResponseConstraints checks if the values respects the defined constraints
func AssertNoteFullResponseConstraints(obj NoteFullResponse) error {
	for _, el := range obj.Request {
		if err := AssertNameStringValueResponseConstraints(el); err != nil {
			return err
		}
	}
	if err := AssertAccountShortResponseConstraints(obj.Owner); err != nil {
		return err
	}
	for _, el := range obj.AttachedAssets {
		if err := AssertAssetShortResponseConstraints(el); err != nil {
			return err
		}
	}
	for _, el := range obj.Likes {
		if err := AssertLikeResponseConstraints(el); err != nil {
			return err
		}
	}
	return nil
}
