require 'json'


MyApp.add_route('GET', '/api/{version}/analytics/useractivity', {
  "resourcePath" => "/Analytics",
  "summary" => "Get User Activity",
  "nickname" => "activities",
  "responseClass" => "Array<UserActivityResponse>",
  "endpoint" => "/api/{version}/analytics/useractivity",
  "notes" => "Get an activity feed by user.",
  "parameters" => [
    {
      "name" => "start",
      "description" => "The start of the pagination",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "limit",
      "description" => "The limit of the pagination",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "account_id",
      "description" => "the account id of the user",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "version",
      "description" => "",
      "dataType" => "Float",
      "paramType" => "path",
    },
    ]}) do
  cross_origin
  # the guts live here

  {"message" => "yes, it worked"}.to_json
end


MyApp.add_route('GET', '/api/{version}/analytics/aggregatedFilteredUsage', {
  "resourcePath" => "/Analytics",
  "summary" => "Get Aggregated Filtered Usage",
  "nickname" => "aggregated_filtered_usage",
  "responseClass" => "ChartData",
  "endpoint" => "/api/{version}/analytics/aggregatedFilteredUsage",
  "notes" => "Query analytics to get data used for nested graphs and charts",
  "parameters" => [
    {
      "name" => "device_id",
      "description" => "The unique id of the device making the request (deviceId or accountId required)",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "account_id",
      "description" => "The account id of the user (deviceId or accountId required)",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "application_id",
      "description" => "This parameter is deprecated.",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "app_key",
      "description" => "The application key used to filter results by application",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "start_date",
      "description" => "Used to search for results after or equal to this date (UNIX time-stamp in milliseconds)",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "end_date",
      "description" => "Used to search for results before or equal to this date (UNIX time-stamp in milliseconds)",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "device_type",
      "description" => "The device type to filter results by (performs a LIKE search)",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "device",
      "description" => "The device to filter results by (performs a LIKE search)",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "device_os",
      "description" => "The device OS to filter results by (performs a LIKE search)",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "gender",
      "description" => "The gender to filter results by {MALE, FEMALE}",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "age_group",
      "description" => "Comma separated list of age groups to filter by {AGE_0_13, AGE_14_17, AGE_18_22, AGE_23_30, AGE_31_54, AGE_55_PLUS}",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "country",
      "description" => "The country to filter results by (performs a wild-card search)",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "state",
      "description" => "The state to filter results by (performs a wild-card search)",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "city",
      "description" => "The city to filter results by (performs a wild-card search)",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "zip",
      "description" => "The zip to filter results by (performs a wild-card search)",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "model",
      "description" => "The model to filter results by (performs a wild-card search)",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "tag",
      "description" => "The tag to filter results by (performs a wild-card search)",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "user_account_id",
      "description" => "The account id to filter results for a particular user",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "user_account_display",
      "description" => "The user display to filter results by (performs a wild-card search)",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "user_account_username",
      "description" => "The username to filter results by (performs a wild-card search)",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "group_by_root",
      "description" => "Determines how to group results. For example, passing in &#39;CREATED&#39; will return results by date. Passing in &#39;ACCOUNT&#39; will return results by user {TAG, CUSTOM_ID, TOKEN, MODEL, DEVICE_TYPE, DEVICE, DEVICE_OS, IP_ADDRESS, STATE, CITY, ZIP, COUNTRY, ACCOUNT, APPLICATION_ID, APPLICATION_NAME_BY_ID}",
      "dataType" => "String",
      "allowableValues" => "[TAG_COUNT, TAG, TOKEN, MODEL, DEVICE_TYPE, DEVICE, DEVICE_OS, DEVICE_ID, IP_ADDRESS, STATE, CITY, ZIP, COUNTRY, CREATED, UPDATED, LAST_UPDATED, CLIENT_TIME, ACTIVE, CUSTOM_ID, CUSTOM_TYPE, CUSTOM_VALUE, CUSTOM_VALUE2, CUSTOM_LONG, CUSTOM_LONG2, CUSTOM_MESSAGE, CUSTOM_MESSAGE2, ACCOUNT_ID, ACCOUNT_USERNAME, ACCOUNT_DISPLAY, ACCOUNT_CREATED, ACCOUNT_GENDER, ACCOUNT_AGE_GROUP, APPLICATION_ID, APPLICATION_KEY, APPLICATION_NAME]",
      "paramType" => "query",
    },
    {
      "name" => "group_by",
      "description" => "Determines how to group the nested data. {TAG, CUSTOM_ID, TOKEN, MODEL, DEVICE_TYPE, DEVICE, DEVICE_OS, IP_ADDRESS, STATE, CITY, ZIP, COUNTRY, ACCOUNT, APPLICATION_ID, APPLICATION_NAME_BY_ID}",
      "dataType" => "String",
      "allowableValues" => "[TAG_COUNT, TAG, TOKEN, MODEL, DEVICE_TYPE, DEVICE, DEVICE_OS, DEVICE_ID, IP_ADDRESS, STATE, CITY, ZIP, COUNTRY, CREATED, UPDATED, LAST_UPDATED, CLIENT_TIME, ACTIVE, CUSTOM_ID, CUSTOM_TYPE, CUSTOM_VALUE, CUSTOM_VALUE2, CUSTOM_LONG, CUSTOM_LONG2, CUSTOM_MESSAGE, CUSTOM_MESSAGE2, ACCOUNT_ID, ACCOUNT_USERNAME, ACCOUNT_DISPLAY, ACCOUNT_CREATED, ACCOUNT_GENDER, ACCOUNT_AGE_GROUP, APPLICATION_ID, APPLICATION_KEY, APPLICATION_NAME]",
      "paramType" => "query",
    },
    {
      "name" => "distinct_count",
      "description" => "Performs a unique query on the specified column. For example, passing in &#39;ACCOUNT&#39; will return the number of unique users. {TAG, CUSTOM_ID, TOKEN, MODEL, DEVICE_TYPE, DEVICE, DEVICE_OS, IP_ADDRESS, STATE, CITY, ZIP, COUNTRY, ACCOUNT, APPLICATION_ID, NEW_ACCOUNT}",
      "dataType" => "String",
      "allowableValues" => "[TAG_COUNT, TAG, TOKEN, MODEL, DEVICE_TYPE, DEVICE, DEVICE_OS, DEVICE_ID, IP_ADDRESS, STATE, CITY, ZIP, COUNTRY, CREATED, UPDATED, LAST_UPDATED, CLIENT_TIME, ACTIVE, CUSTOM_ID, CUSTOM_TYPE, CUSTOM_VALUE, CUSTOM_VALUE2, CUSTOM_LONG, CUSTOM_LONG2, CUSTOM_MESSAGE, CUSTOM_MESSAGE2, ACCOUNT_ID, ACCOUNT_USERNAME, ACCOUNT_DISPLAY, ACCOUNT_CREATED, ACCOUNT_GENDER, ACCOUNT_AGE_GROUP, APPLICATION_ID, APPLICATION_KEY, APPLICATION_NAME]",
      "paramType" => "query",
    },
    {
      "name" => "sort_field",
      "description" => "Determines whether the results will be sorted by day or by number of hits {CREATED, TAG_COUNT}",
      "dataType" => "String",
      "allowableValues" => "[TAG_COUNT, TAG, TOKEN, MODEL, DEVICE_TYPE, DEVICE, DEVICE_OS, DEVICE_ID, IP_ADDRESS, STATE, CITY, ZIP, COUNTRY, CREATED, UPDATED, LAST_UPDATED, CLIENT_TIME, ACTIVE, CUSTOM_ID, CUSTOM_TYPE, CUSTOM_VALUE, CUSTOM_VALUE2, CUSTOM_LONG, CUSTOM_LONG2, CUSTOM_MESSAGE, CUSTOM_MESSAGE2, ACCOUNT_ID, ACCOUNT_USERNAME, ACCOUNT_DISPLAY, ACCOUNT_CREATED, ACCOUNT_GENDER, ACCOUNT_AGE_GROUP, APPLICATION_ID, APPLICATION_KEY, APPLICATION_NAME]",
      "paramType" => "query",
    },
    {
      "name" => "descending",
      "description" => "Determines whether to return results in descending order",
      "dataType" => "Boolean",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "hide_unknown",
      "description" => "Determines whether to return data that has empty or unknown values",
      "dataType" => "Boolean",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "response_format",
      "description" => "Determines whether to return a JOSN or XML representation of the graph results",
      "dataType" => "String",
      "allowableValues" => "[HTML, XML, JSON, CSV]",
      "paramType" => "query",
    },
    {
      "name" => "_l",
      "description" => "This parameter is deprecated.",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "limit",
      "description" => "Used to limit results to get a cleaner graph. The results that gets filtered out will be combined",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "latitude",
      "description" => "the current latitude of the user",
      "dataType" => "Float",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "longitude",
      "description" => "the current longitude of the user",
      "dataType" => "Float",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "version",
      "description" => "",
      "dataType" => "Float",
      "paramType" => "path",
    },
    ]}) do
  cross_origin
  # the guts live here

  {"message" => "yes, it worked"}.to_json
end


MyApp.add_route('GET', '/api/{version}/analytics/filteredUsage', {
  "resourcePath" => "/Analytics",
  "summary" => "Get Filtered Usage",
  "nickname" => "filtered_usage",
  "responseClass" => "ChartData",
  "endpoint" => "/api/{version}/analytics/filteredUsage",
  "notes" => "Query analytics to get data used for graphs and charts",
  "parameters" => [
    {
      "name" => "device_id",
      "description" => "The unique id of the device making the request (deviceId or accountId required)",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "account_id",
      "description" => "The account id of the user (deviceId or accountId required)",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "application_id",
      "description" => "This parameter is deprecated.",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "app_key",
      "description" => "The application key used to filter results by application",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "start_date",
      "description" => "Used to search for results after or equal to this date (UNIX time-stamp in milliseconds)",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "end_date",
      "description" => "Used to search for results before or equal to this date (UNIX time-stamp in milliseconds)",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "device_type",
      "description" => "The device type to filter results by (performs a LIKE search)",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "device",
      "description" => "The device to filter results by (performs a LIKE search)",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "device_os",
      "description" => "The device OS to filter results by (performs a LIKE search)",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "gender",
      "description" => "The gender to filter results by {MALE, FEMALE}",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "age_group",
      "description" => "Comma separated list of age groups to filter by {AGE_0_13, AGE_14_17, AGE_18_22, AGE_23_30, AGE_31_54, AGE_55_PLUS}",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "country",
      "description" => "The country to filter results by (performs a wild-card search)",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "state",
      "description" => "The state to filter results by (performs a wild-card search)",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "city",
      "description" => "The city to filter results by (performs a wild-card search)",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "zip",
      "description" => "The zip to filter results by (performs a wild-card search)",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "model",
      "description" => "The model to filter results by (performs a wild-card search)",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "tag",
      "description" => "The tag to filter results by (performs a wild-card search)",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "user_account_id",
      "description" => "The account id to filter results for a particular user",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "user_account_display",
      "description" => "The user display to filter results by (performs a wild-card search)",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "user_account_username",
      "description" => "The username to filter results by (performs a wild-card search)",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "custom_id",
      "description" => "The ID for the custom table column",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "custom_type",
      "description" => "The type defined for the custom table column",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "custom_value",
      "description" => "The value for the custom table column",
      "dataType" => "Float",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "custom_value2",
      "description" => "The value for another custom table column",
      "dataType" => "Float",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "custom_long",
      "description" => "The value that supports Longs for custom table column",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "custom_long2",
      "description" => "The value that supports Longs for custom table column",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "custom_message",
      "description" => "The message for the custom table column",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "custom_message2",
      "description" => "The message for the custom table column",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "group_by",
      "description" => "Determines how to group results. For example, passing in &#39;CREATED&#39; will return results by date. Passing in &#39;ACCOUNT&#39; will return results by user {TAG, CUSTOM_ID, TOKEN, MODEL, DEVICE_TYPE, DEVICE, DEVICE_OS, DEVICE_ID, IP_ADDRESS, STATE, CITY, ZIP, COUNTRY, ACCOUNT, APPLICATION_ID}",
      "dataType" => "String",
      "allowableValues" => "[TAG_COUNT, TAG, TOKEN, MODEL, DEVICE_TYPE, DEVICE, DEVICE_OS, DEVICE_ID, IP_ADDRESS, STATE, CITY, ZIP, COUNTRY, CREATED, UPDATED, LAST_UPDATED, CLIENT_TIME, ACTIVE, CUSTOM_ID, CUSTOM_TYPE, CUSTOM_VALUE, CUSTOM_VALUE2, CUSTOM_LONG, CUSTOM_LONG2, CUSTOM_MESSAGE, CUSTOM_MESSAGE2, ACCOUNT_ID, ACCOUNT_USERNAME, ACCOUNT_DISPLAY, ACCOUNT_CREATED, ACCOUNT_GENDER, ACCOUNT_AGE_GROUP, APPLICATION_ID, APPLICATION_KEY, APPLICATION_NAME]",
      "paramType" => "query",
    },
    {
      "name" => "distinct_count",
      "description" => "Performs a unique query on the specified column. For example, passing in &#39;ACCOUNT&#39; will return the number of unique users. {TAG, CUSTOM_ID, TOKEN, MODEL, DEVICE_TYPE, DEVICE, DEVICE_OS, DEVICE_ID, IP_ADDRESS, STATE, CITY, ZIP, COUNTRY, ACCOUNT, APPLICATION_ID}",
      "dataType" => "String",
      "allowableValues" => "[TAG_COUNT, TAG, TOKEN, MODEL, DEVICE_TYPE, DEVICE, DEVICE_OS, DEVICE_ID, IP_ADDRESS, STATE, CITY, ZIP, COUNTRY, CREATED, UPDATED, LAST_UPDATED, CLIENT_TIME, ACTIVE, CUSTOM_ID, CUSTOM_TYPE, CUSTOM_VALUE, CUSTOM_VALUE2, CUSTOM_LONG, CUSTOM_LONG2, CUSTOM_MESSAGE, CUSTOM_MESSAGE2, ACCOUNT_ID, ACCOUNT_USERNAME, ACCOUNT_DISPLAY, ACCOUNT_CREATED, ACCOUNT_GENDER, ACCOUNT_AGE_GROUP, APPLICATION_ID, APPLICATION_KEY, APPLICATION_NAME]",
      "paramType" => "query",
    },
    {
      "name" => "sum_column",
      "description" => "sum of the column values",
      "dataType" => "String",
      "allowableValues" => "[TAG_COUNT, TAG, TOKEN, MODEL, DEVICE_TYPE, DEVICE, DEVICE_OS, DEVICE_ID, IP_ADDRESS, STATE, CITY, ZIP, COUNTRY, CREATED, UPDATED, LAST_UPDATED, CLIENT_TIME, ACTIVE, CUSTOM_ID, CUSTOM_TYPE, CUSTOM_VALUE, CUSTOM_VALUE2, CUSTOM_LONG, CUSTOM_LONG2, CUSTOM_MESSAGE, CUSTOM_MESSAGE2, ACCOUNT_ID, ACCOUNT_USERNAME, ACCOUNT_DISPLAY, ACCOUNT_CREATED, ACCOUNT_GENDER, ACCOUNT_AGE_GROUP, APPLICATION_ID, APPLICATION_KEY, APPLICATION_NAME]",
      "paramType" => "query",
    },
    {
      "name" => "sort_field",
      "description" => "Determines whether the results will be sorted by day or by number of hits {CREATED, TAG_COUNT}",
      "dataType" => "String",
      "allowableValues" => "[TAG_COUNT, TAG, TOKEN, MODEL, DEVICE_TYPE, DEVICE, DEVICE_OS, DEVICE_ID, IP_ADDRESS, STATE, CITY, ZIP, COUNTRY, CREATED, UPDATED, LAST_UPDATED, CLIENT_TIME, ACTIVE, CUSTOM_ID, CUSTOM_TYPE, CUSTOM_VALUE, CUSTOM_VALUE2, CUSTOM_LONG, CUSTOM_LONG2, CUSTOM_MESSAGE, CUSTOM_MESSAGE2, ACCOUNT_ID, ACCOUNT_USERNAME, ACCOUNT_DISPLAY, ACCOUNT_CREATED, ACCOUNT_GENDER, ACCOUNT_AGE_GROUP, APPLICATION_ID, APPLICATION_KEY, APPLICATION_NAME]",
      "paramType" => "query",
    },
    {
      "name" => "descending",
      "description" => "Determines whether to return results in descending order",
      "dataType" => "Boolean",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "hide_unknown",
      "description" => "Determines whether to return data that has empty or unknown values",
      "dataType" => "Boolean",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "response_format",
      "description" => "Determines whether to return a JOSN or XML representation of the graph results",
      "dataType" => "String",
      "allowableValues" => "[HTML, XML, JSON, CSV]",
      "paramType" => "query",
    },
    {
      "name" => "_l",
      "description" => "This parameter is deprecated.",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "limit",
      "description" => "Used to limit results to get a cleaner graph. The results that gets filtered out will be combined",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "latitude",
      "description" => "the current latitude of the user",
      "dataType" => "Float",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "longitude",
      "description" => "the current longitude of the user",
      "dataType" => "Float",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "version",
      "description" => "",
      "dataType" => "Float",
      "paramType" => "path",
    },
    ]}) do
  cross_origin
  # the guts live here

  {"message" => "yes, it worked"}.to_json
end


MyApp.add_route('POST', '/api/{version}/analytics/usage', {
  "resourcePath" => "/Analytics",
  "summary" => "Create Usage Record",
  "nickname" => "usage",
  "responseClass" => "SirqulResponse",
  "endpoint" => "/api/{version}/analytics/usage",
  "notes" => "Record an analytic record for a known state within the application.",
  "parameters" => [
    {
      "name" => "tag",
      "description" => "The tag to apply: the name of the action or thing being logged.",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "device_id",
      "description" => "The client deviceID",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "account_id",
      "description" => "The logged in user ID",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "application_id",
      "description" => "This parameter is deprecated. This is deprecated, use appKey.",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "app_key",
      "description" => "The application key unique to each application.",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "app_version",
      "description" => "The current build version of the application",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "device",
      "description" => "The name of the device being used (iPhone5,1 , HTC Nexus One, x86_64, etc.)",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "device_type",
      "description" => "The type of device (Handheld or Desktop)",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "device_os",
      "description" => "The operating system that the device is using (iPhone OS 5.0, Android OS 2.3.6, Windows 7 Service Pack 1, etc)",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "model",
      "description" => "The model of the device (iPhone5,1 , Nexus One, etc.)",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "latitude",
      "description" => "The current position of the user",
      "dataType" => "Float",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "longitude",
      "description" => "The current position of the user",
      "dataType" => "Float",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "custom_id",
      "description" => "A customId used to associate the usage record with some other record in the system",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "custom_type",
      "description" => "The type of record the customId is recorded for",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "achievement_increment",
      "description" => "This parameter is deprecated. This is deprecated, use \&quot;customValue\&quot;. Determines how many achievement points and/or ranking points the user gets if this analytic is associated with an achievement",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "city",
      "description" => "The current city of the user",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "state",
      "description" => "The current state of the user",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "country",
      "description" => "The current country of the user",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "zip",
      "description" => "The current zip of the user",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "location_description",
      "description" => "The general description of the user&#39;s location",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "client_time",
      "description" => "Timestamp sent from device",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "error_message",
      "description" => "This parameter is deprecated.",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "ip",
      "description" => "the ip address of the client device",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "user_agent",
      "description" => "this is a description of the client (might contain the device&#39;s OS, browser version etc - its a common term)",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "background_event",
      "description" => "This is deprecated.",
      "dataType" => "Boolean",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "custom_message",
      "description" => "a custom message for the usage record",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "custom_message2",
      "description" => "a custom message for the usage record",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "custom_value",
      "description" => "a custom value for the usage record",
      "dataType" => "Float",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "custom_value2",
      "description" => "a custom value for the usage record",
      "dataType" => "Float",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "custom_long",
      "description" => "a custom long value for the usage record",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "custom_long2",
      "description" => "a custom long value for the usage record",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "version",
      "description" => "",
      "dataType" => "Float",
      "paramType" => "path",
    },
    ]}) do
  cross_origin
  # the guts live here

  {"message" => "yes, it worked"}.to_json
end


MyApp.add_route('POST', '/api/{version}/analytics/usage/batch', {
  "resourcePath" => "/Analytics",
  "summary" => "Create Multiple Usage Records",
  "nickname" => "usage_batch",
  "responseClass" => "SirqulResponse",
  "endpoint" => "/api/{version}/analytics/usage/batch",
  "notes" => "Sends multiple analytics. Can be used to send in the user's stored usage when they did not have internet access. Should not include more than 100 items per batch.",
  "parameters" => [
    {
      "name" => "device_id",
      "description" => "The unique id of the device making the request",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "account_id",
      "description" => "The account ID of the logged in user making the request",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "app_key",
      "description" => "The application key unique to each application.",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "app_version",
      "description" => "The current build version of the application",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "device",
      "description" => "The name of the device being used (iPhone5,1 , HTC Nexus One, x86_64, etc.)",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "device_type",
      "description" => "The type of device (Handheld or Desktop)",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "device_os",
      "description" => "The operating system that the device is using (iPhone OS 5.0, Android OS 2.3.6, Windows 7 Service Pack 1, etc.)",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "model",
      "description" => "The model of the device (iPhone5,1 , Nexus One, etc.)",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "data",
      "description" => "The analytic data AnalyticListResponse",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "update_ranking",
      "description" => "Will create a leaderboard if one does not exist for the \&quot;tag\&quot; yet",
      "dataType" => "Boolean",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "return_summary_response",
      "description" => "Returns a summary response of the achievements that have been completed due to the analytics",
      "dataType" => "Boolean",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "version",
      "description" => "",
      "dataType" => "Float",
      "paramType" => "path",
    },
    ]}) do
  cross_origin
  # the guts live here

  {"message" => "yes, it worked"}.to_json
end

