require 'json'


MyApp.add_route('POST', '/api/{version}/application/create', {
  "resourcePath" => "/Application",
  "summary" => "Create Application",
  "nickname" => "create_application",
  "responseClass" => "ApplicationResponse",
  "endpoint" => "/api/{version}/application/create",
  "notes" => "Create an application record and one placement record for that application. You can create more placements for this application by using {@link createApplicationPlacement}.",
  "parameters" => [
    {
      "name" => "device_id",
      "description" => "The unique id of the device making the request (deviceId or accountId required)",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "account_id",
      "description" => "The account id of the user (deviceId or accountId required)",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "app_name",
      "description" => "The name of the application",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "about",
      "description" => "The description of the application",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "bundle_id",
      "description" => "The application bundle identifier (format - com.company.appName)",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "app_icon_asset_id",
      "description" => "The application icon asset id",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "app_logo_asset_id",
      "description" => "The application logo asset id",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "facebook_app_id",
      "description" => "The Facebook application id",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "facebook_app_secret",
      "description" => "The Facebook application secret",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "google_api_key",
      "description" => "This is the either the &#39;server key&#39; or &#39;browser key&#39; generated from google to enable Google Cloud Messaging",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "update_eula_date",
      "description" => "Determines whether to update the EULA date",
      "dataType" => "Boolean",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "eula_version",
      "description" => "The EULA version",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "landing_page_url",
      "description" => "The landing page URL",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "show_in_activities",
      "description" => "Determines whether to show the application in the activity feed",
      "dataType" => "Boolean",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "activity_description",
      "description" => "The description of the application in the activity feed",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "invite_welcome_text",
      "description" => "The text to display on the invite page",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "invite_page_url",
      "description" => "The url to the application invite page",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "url_scheme",
      "description" => "The protocal the app uses to load the app via a browser",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "platforms",
      "description" => "A json object with a list of supported platforms.  &#x60;&#x60;&#x60;json {   \&quot;platforms\&quot;: [     {       \&quot;deviceId\&quot;: 1,       \&quot;minimum\&quot;: 230,       \&quot;maximum\&quot;: 421,       \&quot;downloadUrl\&quot;: \&quot;http://app.store.com/download\&quot;,       \&quot;description\&quot;: \&quot;description and version info\&quot;     }   ] } &#x60;&#x60;&#x60; ",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "download_urls",
      "description" => "Json formatted downloadUrls.  &#x60;&#x60;&#x60;json {   \&quot;ios\&quot;: \&quot;the-url-to-app-store\&quot;,    \&quot;android\&quot;: \&quot;the-url-to-google-play\&quot; } &#x60;&#x60;&#x60;  ",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "category_ids",
      "description" => "List of categories to apply",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "scoring_type",
      "description" => "The type of scoring this application will use {GAME_LEVEL, GAME_OBJECT",
      "dataType" => "String",
      "allowableValues" => "[GAME_LEVEL, GAME_OBJECT]",
      "defaultValue" => "'GAME_LEVEL'",
      "paramType" => "query",
    },
    {
      "name" => "hint_cost",
      "description" => "The cost of hints",
      "dataType" => "Integer",
      "allowableValues" => "",
      "defaultValue" => "11",
      "paramType" => "query",
    },
    {
      "name" => "max_score",
      "description" => "The maximum score that will be possible",
      "dataType" => "Integer",
      "allowableValues" => "",
      "defaultValue" => "125",
      "paramType" => "query",
    },
    {
      "name" => "tickets_per_point",
      "description" => "The point-to-ticket conversion ratio",
      "dataType" => "Float",
      "allowableValues" => "",
      "defaultValue" => "0.037",
      "paramType" => "query",
    },
    {
      "name" => "has_game_data",
      "description" => "Determines whether the application uses services to save custom game objects",
      "dataType" => "Boolean",
      "allowableValues" => "",
      "defaultValue" => "true",
      "paramType" => "query",
    },
    {
      "name" => "public_notifications",
      "description" => "Public Notifications",
      "dataType" => "Boolean",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "use_matching_algorithm",
      "description" => "Use Matching Algorithm",
      "dataType" => "Boolean",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "global_tickets",
      "description" => "Determines whether earned tickets are applied across all applications",
      "dataType" => "Boolean",
      "allowableValues" => "",
      "defaultValue" => "false",
      "paramType" => "query",
    },
    {
      "name" => "build_version",
      "description" => "The current build version of the application",
      "dataType" => "Float",
      "allowableValues" => "",
      "defaultValue" => "1",
      "paramType" => "query",
    },
    {
      "name" => "api_version",
      "description" => "The current API version the application uses",
      "dataType" => "Float",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "placement_name",
      "description" => "The name of the placement",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "placement_description",
      "description" => "The description of the placement",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "placement_size",
      "description" => "The ad placement size {BANNER, LEADERBOARD, SKYSCRAPER, INTERSTITIAL, CUSTOM (this is required if a placements is to be created)",
      "dataType" => "String",
      "allowableValues" => "[CONFIG, BANNER, LEADERBOARD, SKYSCRAPER, VIDEO, ZIP, INTERSTITIAL, CUSTOM1, CUSTOM2, CUSTOM3, CUSTOM4, CUSTOM5, CUSTOM6, CUSTOM7, CUSTOM8, CUSTOM9, CUSTOM10]",
      "paramType" => "query",
    },
    {
      "name" => "placement_height",
      "description" => "The height of a custom ad size",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "placement_width",
      "description" => "The width of a custom ad size",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "placement_refresh_interval",
      "description" => "The refresh interval in seconds",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "create_object_store",
      "description" => "Generate a custom object store to use",
      "dataType" => "Boolean",
      "allowableValues" => "",
      "defaultValue" => "true",
      "paramType" => "query",
    },
    {
      "name" => "public_content_approval",
      "description" => "Determine whether or not public content requires admin approval before it becomes public",
      "dataType" => "Boolean",
      "allowableValues" => "",
      "defaultValue" => "false",
      "paramType" => "query",
    },
    {
      "name" => "production_mode",
      "description" => "Determines whether the application uses production or sandbox services",
      "dataType" => "Boolean",
      "allowableValues" => "",
      "defaultValue" => "false",
      "paramType" => "query",
    },
    {
      "name" => "minimum_session_length",
      "description" => "Minimum Session Length",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "session_gap_length",
      "description" => "Session Gap Length",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "local_ads_enabled",
      "description" => "Local Ads Enabled",
      "dataType" => "Boolean",
      "allowableValues" => "",
      "defaultValue" => "false",
      "paramType" => "query",
    },
    {
      "name" => "sqoot_api_key",
      "description" => "Sqoot Api Key",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "trilat_processing_type",
      "description" => "Determines how to process trilateration data. Possible values include: DEFAULT, FINGERPRINT",
      "dataType" => "String",
      "allowableValues" => "[DEFAULT, FINGERPRINT, FINGERPRINT_V2]",
      "defaultValue" => "'FINGERPRINT'",
      "paramType" => "query",
    },
    {
      "name" => "max_sample_size",
      "description" => "Determines what the maximum sample size during trilateration",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "min_rssi",
      "description" => "Determines what the minimum acceptable RSSI value",
      "dataType" => "Float",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "modules",
      "description" => "List modules allowed to be served by the server, possible values include: COMMON, MEDIA, OFFER, GAME, SOCIAL, CONSUMER_WEBSITE, ALL",
      "dataType" => "String",
      "allowableValues" => "",
      "defaultValue" => "'ALL'",
      "paramType" => "query",
    },
    {
      "name" => "authorized_count",
      "description" => "How many servers the license will support",
      "dataType" => "Integer",
      "allowableValues" => "",
      "defaultValue" => "1",
      "paramType" => "query",
    },
    {
      "name" => "authorized_servers",
      "description" => "The list of ip addresses of servers the license will support, leave null for any server",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "default_timezone",
      "description" => "Sets the default timezone for the app (used for leaderboards and other time specific content)",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "smtp_pass",
      "description" => "SMTP Pass",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "meta_data",
      "description" => "The application meta data. Defined by the client",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "placement_meta_data",
      "description" => "The ad placement meta data. Defined by the client",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "ips_floor",
      "description" => "Create floor tables for Ips",
      "dataType" => "Boolean",
      "allowableValues" => "",
      "defaultValue" => "false",
      "paramType" => "query",
    },
    {
      "name" => "enable_apns_badge",
      "description" => "Enables setting the APNS badge value in the payload",
      "dataType" => "Boolean",
      "allowableValues" => "",
      "defaultValue" => "true",
      "paramType" => "query",
    },
    {
      "name" => "include_in_report",
      "description" => "Enables using the application in session reports",
      "dataType" => "Boolean",
      "allowableValues" => "",
      "defaultValue" => "true",
      "paramType" => "query",
    },
    {
      "name" => "default_app_filter_id",
      "description" => "Sets the default filter to use (if none is passed in) for certain search APIs including Album Search.",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "enable_welcome_email",
      "description" => "Enables whether the default welcome email will be sent for new app users",
      "dataType" => "Boolean",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "apple_app_id",
      "description" => "The Apple Application ID",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "apple_team_id",
      "description" => "The Apple Team ID",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "apple_auth_key_id",
      "description" => "The Apple Auth Key ID",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "apple_auth_key",
      "description" => "The Apple Auth Signin Key (p8) File",
      "dataType" => "File",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "apple_issuer_id",
      "description" => "The Apple Issuer ID",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "app_store_key_id",
      "description" => "The Apple App Store Key ID",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "app_store_key",
      "description" => "The Apple App Store Key (p8) File",
      "dataType" => "File",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "google_private_key_file",
      "description" => "This is the private key file for your Google service account.",
      "dataType" => "File",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "authorize_net_api_key",
      "description" => "Authorize Net Api Key",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "authorize_net_transaction_key",
      "description" => "Authorize Net Transaction Key",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "email_sender",
      "description" => "Email Sender",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "smtp_user",
      "description" => "SMTP User",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "smtp_host",
      "description" => "SMTP Host",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "vatom_business_id",
      "description" => "Vatom Business Id",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "vatom_rest_client_id",
      "description" => "Vatom REST Client Id",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "vatom_rest_secret_key",
      "description" => "Vatom Secret Key",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "twilio_account_sid",
      "description" => "Twilio Account SID",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "twilio_auth_token",
      "description" => "Twilio Auth Token",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "twilio_sender_phone_number",
      "description" => "Twilio Sender Phone Number",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "open_ai_secret_key",
      "description" => "OpenAI Secret API Key",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "version",
      "description" => "",
      "dataType" => "Float",
      "paramType" => "path",
    },
    ]}) do
  cross_origin
  # the guts live here

  {"message" => "yes, it worked"}.to_json
end


MyApp.add_route('POST', '/api/{version}/application/placement/create', {
  "resourcePath" => "/Application",
  "summary" => "Create Ad Placement",
  "nickname" => "create_application_placement",
  "responseClass" => "PlacementResponse",
  "endpoint" => "/api/{version}/application/placement/create",
  "notes" => "Creates a new ad placement for an application.",
  "parameters" => [
    {
      "name" => "device_id",
      "description" => "The unique id of the device making the request (deviceId or accountId required)",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "account_id",
      "description" => "The account id of the user (deviceId or accountId required)",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "app_key",
      "description" => "The appKey of the application the ad placement is for",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "name",
      "description" => "The name of the placement",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "description",
      "description" => "The description of the placement",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "size",
      "description" => "The ad placement size {BANNER, LEADERBOARD, SKYSCRAPER, INTERSTITIAL, CUSTOM",
      "dataType" => "String",
      "allowableValues" => "[CONFIG, BANNER, LEADERBOARD, SKYSCRAPER, VIDEO, ZIP, INTERSTITIAL, CUSTOM1, CUSTOM2, CUSTOM3, CUSTOM4, CUSTOM5, CUSTOM6, CUSTOM7, CUSTOM8, CUSTOM9, CUSTOM10]",
      "paramType" => "query",
    },
    {
      "name" => "height",
      "description" => "The height of a custom ad size",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "width",
      "description" => "The width of a custom ad size",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "refresh_interval",
      "description" => "The refresh interval in seconds",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "default_image_id",
      "description" => "Default Image Id",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "active",
      "description" => "Active",
      "dataType" => "Boolean",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "version",
      "description" => "",
      "dataType" => "Float",
      "paramType" => "path",
    },
    ]}) do
  cross_origin
  # the guts live here

  {"message" => "yes, it worked"}.to_json
end


MyApp.add_route('POST', '/api/{version}/application/delete', {
  "resourcePath" => "/Application",
  "summary" => "Delete Application",
  "nickname" => "delete_application",
  "responseClass" => "SirqulResponse",
  "endpoint" => "/api/{version}/application/delete",
  "notes" => "Set the deleted timestamp to current time. This effectively deletes the application since all queries should ignore any records with a deleted timestamp",
  "parameters" => [
    {
      "name" => "account_id",
      "description" => "The account used to perform the delete, must have rights to edit the application.",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "app_key",
      "description" => "The key of the application to be deleted",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "version",
      "description" => "",
      "dataType" => "Float",
      "paramType" => "path",
    },
    ]}) do
  cross_origin
  # the guts live here

  {"message" => "yes, it worked"}.to_json
end


MyApp.add_route('POST', '/api/{version}/application/placement/delete', {
  "resourcePath" => "/Application",
  "summary" => "Delete Ad Placement",
  "nickname" => "delete_application_placement",
  "responseClass" => "PlacementResponse",
  "endpoint" => "/api/{version}/application/placement/delete",
  "notes" => "Deletes an ad placement for an application.",
  "parameters" => [
    {
      "name" => "device_id",
      "description" => "The unique id of the device making the request (deviceId or accountId required)",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "account_id",
      "description" => "The account id of the user (deviceId or accountId required)",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "placement_id",
      "description" => "The id of the placement to delete, the user must have rights to the application the ad placement is for",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "version",
      "description" => "",
      "dataType" => "Float",
      "paramType" => "path",
    },
    ]}) do
  cross_origin
  # the guts live here

  {"message" => "yes, it worked"}.to_json
end


MyApp.add_route('GET', '/api/{version}/application/get', {
  "resourcePath" => "/Application",
  "summary" => "Get Application",
  "nickname" => "get_application",
  "responseClass" => "ApplicationResponse",
  "endpoint" => "/api/{version}/application/get",
  "notes" => "Get a specific application by appKey",
  "parameters" => [
    {
      "name" => "app_key",
      "description" => "The key of the application",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "application_id",
      "description" => "Application Id",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "version",
      "description" => "",
      "dataType" => "Float",
      "paramType" => "path",
    },
    ]}) do
  cross_origin
  # the guts live here

  {"message" => "yes, it worked"}.to_json
end


MyApp.add_route('GET', '/api/{version}/application/placement/get', {
  "resourcePath" => "/Application",
  "summary" => "Get Ad Placement",
  "nickname" => "get_application_placement",
  "responseClass" => "PlacementResponse",
  "endpoint" => "/api/{version}/application/placement/get",
  "notes" => "Get details of an ad placement",
  "parameters" => [
    {
      "name" => "device_id",
      "description" => "The unique id of the device making the request (deviceId or accountId required)",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "account_id",
      "description" => "The account id of the user (deviceId or accountId required)",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "placement_id",
      "description" => "The id of the placement",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "version",
      "description" => "",
      "dataType" => "Float",
      "paramType" => "path",
    },
    ]}) do
  cross_origin
  # the guts live here

  {"message" => "yes, it worked"}.to_json
end


MyApp.add_route('GET', '/api/{version}/application/versions', {
  "resourcePath" => "/Application",
  "summary" => "Get API versions",
  "nickname" => "get_application_versions",
  "responseClass" => "SirqulResponse",
  "endpoint" => "/api/{version}/application/versions",
  "notes" => "Will return a comma separated list of numbers, newest first. For example: 3.0, 2.2, 2.1, 1.8",
  "parameters" => [
    {
      "name" => "version",
      "description" => "",
      "dataType" => "Float",
      "paramType" => "path",
    },
    ]}) do
  cross_origin
  # the guts live here

  {"message" => "yes, it worked"}.to_json
end


MyApp.add_route('GET', '/api/{version}/application/users', {
  "resourcePath" => "/Application",
  "summary" => "Search Application Users",
  "nickname" => "get_unique_users_by_app",
  "responseClass" => "AccountListResponse",
  "endpoint" => "/api/{version}/application/users",
  "notes" => "Get a list of users per application",
  "parameters" => [
    {
      "name" => "app_key",
      "description" => "The application key",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "q",
      "description" => "Q",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "keyword",
      "description" => "The keyword used to search",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "since",
      "description" => "Return accounts that have been active after this date (UNIX time-stamp in milliseconds)",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "_i",
      "description" => "the start of the index",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "start",
      "description" => "The start of the pagination",
      "dataType" => "Integer",
      "allowableValues" => "",
      "defaultValue" => "0",
      "paramType" => "query",
    },
    {
      "name" => "_l",
      "description" => "the limit of the index",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "limit",
      "description" => "The limit of the pagination",
      "dataType" => "Integer",
      "allowableValues" => "",
      "defaultValue" => "20",
      "paramType" => "query",
    },
    {
      "name" => "version",
      "description" => "",
      "dataType" => "Float",
      "paramType" => "path",
    },
    ]}) do
  cross_origin
  # the guts live here

  {"message" => "yes, it worked"}.to_json
end


MyApp.add_route('GET', '/api/{version}/application/list', {
  "resourcePath" => "/Application",
  "summary" => "List Applications",
  "nickname" => "list_applications",
  "responseClass" => "Array<ApplicationShortResponse>",
  "endpoint" => "/api/{version}/application/list",
  "notes" => "List active applications matching the criteria (as a consumer)",
  "parameters" => [
    {
      "name" => "account_id",
      "description" => "The account id of the application owner/manager",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "q",
      "description" => "Q",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "keyword",
      "description" => "The keyword used to search for title, about, and description fields",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "platforms",
      "description" => "Deprecated, use deviceIds and deviceVersions",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "device_ids",
      "description" => "The list of targeted device ids, comma separated; possible values are retreived via /api/{version/audience/devices com.sirqul.geoapps.common.service.AudienceApi#getDevices getDevices (pass in deviceId values)",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "device_versions",
      "description" => "The list of targeted device version ranges that are aligned  with the provided devices list (see devices param for possible values),  comma separated; examples are: 2.3-X, 0-5.1.4, 4.3.1-6.1.4 where X  is no maximum and 0 is no minimum. ",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "category_ids",
      "description" => "The list of category ids to filter the list by",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "sort_field",
      "description" => "The column to sort the search on, possible values include: UPDATED (default), CREATED, TITLE",
      "dataType" => "String",
      "allowableValues" => "[CREATED, UPDATED, DELETED, SEARCH_TAGS, ACTIVE, HAS_ADVERTISEMENTS, PUBLIC_NOTIFICATIONS, PLACEMENTS, BILLABLE_ENTITY_ID, BILLABLE_ENTITY_NAME, RESPONSIBLE_DISPLAY, TITLE, NAME, ABOUT, DESCRIPTION, APPLICATION_ID, APP_TYPE, GAME_TYPE, BUNDLE_ID, SCORING_TYPE, LANDING_PAGE_URL, EULA_VERSION, BUILD_VERSION, API_VERSION]",
      "defaultValue" => "'UPDATED'",
      "paramType" => "query",
    },
    {
      "name" => "has_ads",
      "description" => "Filter results on whether the application supports ads or not. Ignore this parameter to return all results.",
      "dataType" => "Boolean",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "public_notifications",
      "description" => "Filter results on whether the application is available for public trigger notifications",
      "dataType" => "Boolean",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "filter_billable",
      "description" => "Determines whether to only return applications that the user has access to",
      "dataType" => "Boolean",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "filter_content_admin",
      "description" => "Determines whether to only return applications that the user is a content admin of",
      "dataType" => "Boolean",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "descending",
      "description" => "The order to return the search results",
      "dataType" => "Boolean",
      "allowableValues" => "",
      "defaultValue" => "true",
      "paramType" => "query",
    },
    {
      "name" => "_i",
      "description" => "the start of the index",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "start",
      "description" => "The start of the pagination",
      "dataType" => "Integer",
      "allowableValues" => "",
      "defaultValue" => "0",
      "paramType" => "query",
    },
    {
      "name" => "_l",
      "description" => "The limit of the index",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "limit",
      "description" => "The limit of the pagination",
      "dataType" => "Integer",
      "allowableValues" => "",
      "defaultValue" => "20",
      "paramType" => "query",
    },
    {
      "name" => "application_ids",
      "description" => "The list of application ids, comma separated. If provided will ignore all other params.",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "has_object_store",
      "description" => "Only include applications with a object store (default is false)",
      "dataType" => "Boolean",
      "allowableValues" => "",
      "defaultValue" => "false",
      "paramType" => "query",
    },
    {
      "name" => "active_only",
      "description" => "Return only active results",
      "dataType" => "Boolean",
      "allowableValues" => "",
      "defaultValue" => "true",
      "paramType" => "query",
    },
    {
      "name" => "version",
      "description" => "",
      "dataType" => "Float",
      "paramType" => "path",
    },
    ]}) do
  cross_origin
  # the guts live here

  {"message" => "yes, it worked"}.to_json
end


MyApp.add_route('GET', '/api/{version}/application/placement/search', {
  "resourcePath" => "/Application",
  "summary" => "Search for Ad Placements",
  "nickname" => "search_application_placement",
  "responseClass" => "Array<PlacementResponse>",
  "endpoint" => "/api/{version}/application/placement/search",
  "notes" => "Searches placements for an application.",
  "parameters" => [
    {
      "name" => "device_id",
      "description" => "The unique id of the device making the request (deviceId or accountId required)",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "account_id",
      "description" => "The account id of the user (deviceId or accountId required)",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "app_key",
      "description" => "The key of the application",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "start",
      "description" => "The start of the pagination",
      "dataType" => "Integer",
      "allowableValues" => "",
      "defaultValue" => "0",
      "paramType" => "query",
    },
    {
      "name" => "limit",
      "description" => "The limit of the pagination",
      "dataType" => "Integer",
      "allowableValues" => "",
      "defaultValue" => "100",
      "paramType" => "query",
    },
    {
      "name" => "version",
      "description" => "",
      "dataType" => "Float",
      "paramType" => "path",
    },
    ]}) do
  cross_origin
  # the guts live here

  {"message" => "yes, it worked"}.to_json
end


MyApp.add_route('GET', '/api/{version}/application/settings/search', {
  "resourcePath" => "/Application",
  "summary" => "Search for Application Settings",
  "nickname" => "search_application_settings",
  "responseClass" => "ApplicationSettingsResponse",
  "endpoint" => "/api/{version}/application/settings/search",
  "notes" => "Returns a list of applications that the user has logged into before, and returns specific settings for that application and user",
  "parameters" => [
    {
      "name" => "device_id",
      "description" => "The device id (deviceId or accountId required)",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "account_id",
      "description" => "The account id of the user (deviceId or accountId required)",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "connection_account_id",
      "description" => "The account id used to view another person&#39;s account",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "keyword",
      "description" => "The string to search applications on",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "sort_field",
      "description" => "The column to sort the search on. Possible values include: CREATED, UPDATED, APPLICATION_TITLE",
      "dataType" => "String",
      "allowableValues" => "",
      "defaultValue" => "'APPLICATION_TITLE'",
      "paramType" => "query",
    },
    {
      "name" => "descending",
      "description" => "The order to return the search results",
      "dataType" => "Boolean",
      "allowableValues" => "",
      "defaultValue" => "false",
      "paramType" => "query",
    },
    {
      "name" => "start",
      "description" => "The start index for pagination",
      "dataType" => "Integer",
      "allowableValues" => "",
      "defaultValue" => "0",
      "paramType" => "query",
    },
    {
      "name" => "limit",
      "description" => "The limit per result set for pagination",
      "dataType" => "Integer",
      "allowableValues" => "",
      "defaultValue" => "20",
      "paramType" => "query",
    },
    {
      "name" => "version",
      "description" => "",
      "dataType" => "Float",
      "paramType" => "path",
    },
    ]}) do
  cross_origin
  # the guts live here

  {"message" => "yes, it worked"}.to_json
end


MyApp.add_route('GET', '/api/{version}/application/search', {
  "resourcePath" => "/Application",
  "summary" => "Search Applications",
  "nickname" => "search_applications",
  "responseClass" => "Array<ApplicationResponse>",
  "endpoint" => "/api/{version}/application/search",
  "notes" => "Search for applications matching the criteria that the logged in user has access to",
  "parameters" => [
    {
      "name" => "device_id",
      "description" => "The unique id of the device making the request (deviceId or accountId required)",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "account_id",
      "description" => "The account id of the user (deviceId or accountId required)",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "latitude",
      "description" => "The location of the device",
      "dataType" => "Float",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "longitude",
      "description" => "The location of the device",
      "dataType" => "Float",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "q",
      "description" => "Q",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "keyword",
      "description" => "The keyword used to search",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "q_search_fields",
      "description" => "The columns to applied the keyword search to",
      "dataType" => "String",
      "allowableValues" => "",
      "defaultValue" => "'NAME,ABOUT,BILLABLE_ENTITY_NAME'",
      "paramType" => "query",
    },
    {
      "name" => "sort_field",
      "description" => "The column to sort the search on",
      "dataType" => "String",
      "allowableValues" => "[CREATED, UPDATED, DELETED, SEARCH_TAGS, ACTIVE, HAS_ADVERTISEMENTS, PUBLIC_NOTIFICATIONS, PLACEMENTS, BILLABLE_ENTITY_ID, BILLABLE_ENTITY_NAME, RESPONSIBLE_DISPLAY, TITLE, NAME, ABOUT, DESCRIPTION, APPLICATION_ID, APP_TYPE, GAME_TYPE, BUNDLE_ID, SCORING_TYPE, LANDING_PAGE_URL, EULA_VERSION, BUILD_VERSION, API_VERSION]",
      "defaultValue" => "'APPLICATION_ID'",
      "paramType" => "query",
    },
    {
      "name" => "descending",
      "description" => "The order to return the search results",
      "dataType" => "Boolean",
      "allowableValues" => "",
      "defaultValue" => "false",
      "paramType" => "query",
    },
    {
      "name" => "_i",
      "description" => "the start of the index",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "start",
      "description" => "The start of the pagination",
      "dataType" => "Integer",
      "allowableValues" => "",
      "defaultValue" => "0",
      "paramType" => "query",
    },
    {
      "name" => "_l",
      "description" => "the limit of the index",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "limit",
      "description" => "The limit of the pagination",
      "dataType" => "Integer",
      "allowableValues" => "",
      "defaultValue" => "100",
      "paramType" => "query",
    },
    {
      "name" => "has_ads",
      "description" => "Filter results on whether the application supports ads or not. Ignore this parameter to return all results.",
      "dataType" => "Boolean",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "public_notifications",
      "description" => "Filter results on whether the application is available for public trigger notifications",
      "dataType" => "Boolean",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "active_only",
      "description" => "Return only active results",
      "dataType" => "Boolean",
      "allowableValues" => "",
      "defaultValue" => "false",
      "paramType" => "query",
    },
    {
      "name" => "version",
      "description" => "",
      "dataType" => "Float",
      "paramType" => "path",
    },
    ]}) do
  cross_origin
  # the guts live here

  {"message" => "yes, it worked"}.to_json
end


MyApp.add_route('POST', '/api/{version}/application/update', {
  "resourcePath" => "/Application",
  "summary" => "Update Application",
  "nickname" => "update_application",
  "responseClass" => "ApplicationResponse",
  "endpoint" => "/api/{version}/application/update",
  "notes" => "Update an application record",
  "parameters" => [
    {
      "name" => "device_id",
      "description" => "The unique id of the device making the request (deviceId or accountId required)",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "account_id",
      "description" => "The account id of the user (deviceId or accountId required)",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "app_key",
      "description" => "The application key for updating an existing application",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "app_name",
      "description" => "The name of the application",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "about",
      "description" => "The description of the application",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "bundle_id",
      "description" => "The application bundle identifier (format - com.company.appName)",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "app_icon_asset_id",
      "description" => "The application icon asset id",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "app_logo_asset_id",
      "description" => "The application logo asset id",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "facebook_app_id",
      "description" => "The Facebook application id",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "facebook_app_secret",
      "description" => "The Facebook application secret",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "google_api_key",
      "description" => "This is the either the &#39;server key&#39; or &#39;browser key&#39; generated from google to enable Google Cloud Messaging",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "update_eula_date",
      "description" => "Determines whether to update the EULA date",
      "dataType" => "Boolean",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "eula_version",
      "description" => "The EULA version",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "landing_page_url",
      "description" => "The landing page URL",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "show_in_activities",
      "description" => "Determines whether to show the application in the activity feed",
      "dataType" => "Boolean",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "activity_description",
      "description" => "The description of the application in the activity feed",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "invite_welcome_text",
      "description" => "The text to display on the invite page",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "invite_page_url",
      "description" => "The url to the application invite page",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "url_scheme",
      "description" => "The protocal the app uses to load the app via a browser",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "platforms",
      "description" => "A json object with a list of supported platforms.  &#x60;&#x60;&#x60;json {   \&quot;platforms\&quot;: [     {       \&quot;deviceId\&quot;: 1,       \&quot;minimum\&quot;: 230,       \&quot;maximum\&quot;: 421,       \&quot;downloadUrl\&quot;: \&quot;http://app.store.com/download\&quot;,       \&quot;description\&quot;: \&quot;description and version info\&quot;     }   ] } &#x60;&#x60;&#x60; ",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "download_urls",
      "description" => "Json formatted downloadUrls.  &#x60;&#x60;&#x60;json {   \&quot;ios\&quot;: \&quot;the-url-to-app-store\&quot;,    \&quot;android\&quot;: \&quot;the-url-to-google-play\&quot; } &#x60;&#x60;&#x60;  ",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "category_ids",
      "description" => "List of categories to apply",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "scoring_type",
      "description" => "The type of scoring this application will use {GAME_LEVEL, GAME_OBJECT",
      "dataType" => "String",
      "allowableValues" => "[GAME_LEVEL, GAME_OBJECT]",
      "defaultValue" => "'GAME_LEVEL'",
      "paramType" => "query",
    },
    {
      "name" => "hint_cost",
      "description" => "The cost of hints",
      "dataType" => "Integer",
      "allowableValues" => "",
      "defaultValue" => "11",
      "paramType" => "query",
    },
    {
      "name" => "max_score",
      "description" => "The maximum score that will be possible",
      "dataType" => "Integer",
      "allowableValues" => "",
      "defaultValue" => "125",
      "paramType" => "query",
    },
    {
      "name" => "tickets_per_point",
      "description" => "The point-to-ticket conversion ratio",
      "dataType" => "Float",
      "allowableValues" => "",
      "defaultValue" => "0.037",
      "paramType" => "query",
    },
    {
      "name" => "has_game_data",
      "description" => "Determines whether the application uses services to save custom game objects",
      "dataType" => "Boolean",
      "allowableValues" => "",
      "defaultValue" => "true",
      "paramType" => "query",
    },
    {
      "name" => "public_notifications",
      "description" => "Public Notifications",
      "dataType" => "Boolean",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "use_matching_algorithm",
      "description" => "Use Matching Algorithm",
      "dataType" => "Boolean",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "global_tickets",
      "description" => "Determines whether earned tickets are applied across all applications",
      "dataType" => "Boolean",
      "allowableValues" => "",
      "defaultValue" => "false",
      "paramType" => "query",
    },
    {
      "name" => "build_version",
      "description" => "The current build version of the application",
      "dataType" => "Float",
      "allowableValues" => "",
      "defaultValue" => "1",
      "paramType" => "query",
    },
    {
      "name" => "api_version",
      "description" => "The current API version the application uses",
      "dataType" => "Float",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "placement_name",
      "description" => "The name of the placement",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "placement_description",
      "description" => "The description of the placement",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "placement_size",
      "description" => "The ad placement size {BANNER, LEADERBOARD, SKYSCRAPER, INTERSTITIAL, CUSTOM (this is required if a placements is to be created)",
      "dataType" => "String",
      "allowableValues" => "[CONFIG, BANNER, LEADERBOARD, SKYSCRAPER, VIDEO, ZIP, INTERSTITIAL, CUSTOM1, CUSTOM2, CUSTOM3, CUSTOM4, CUSTOM5, CUSTOM6, CUSTOM7, CUSTOM8, CUSTOM9, CUSTOM10]",
      "paramType" => "query",
    },
    {
      "name" => "placement_height",
      "description" => "The height of a custom ad size",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "placement_width",
      "description" => "The width of a custom ad size",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "placement_refresh_interval",
      "description" => "The refresh interval in seconds",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "create_object_store",
      "description" => "Generate a custom object store to use",
      "dataType" => "Boolean",
      "allowableValues" => "",
      "defaultValue" => "true",
      "paramType" => "query",
    },
    {
      "name" => "public_content_approval",
      "description" => "Determine whether or not public content requires admin approval before it becomes public",
      "dataType" => "Boolean",
      "allowableValues" => "",
      "defaultValue" => "false",
      "paramType" => "query",
    },
    {
      "name" => "production_mode",
      "description" => "Determines whether the application uses production or sandbox services",
      "dataType" => "Boolean",
      "allowableValues" => "",
      "defaultValue" => "false",
      "paramType" => "query",
    },
    {
      "name" => "minimum_session_length",
      "description" => "Minimum Session Length",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "session_gap_length",
      "description" => "Session Gap Length",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "local_ads_enabled",
      "description" => "Local Ads Enabled",
      "dataType" => "Boolean",
      "allowableValues" => "",
      "defaultValue" => "false",
      "paramType" => "query",
    },
    {
      "name" => "sqoot_api_key",
      "description" => "Sqoot Api Key",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "trilat_processing_type",
      "description" => "Determines how to process trilateration data. Possible values include: DEFAULT, FINGERPRINT",
      "dataType" => "String",
      "allowableValues" => "[DEFAULT, FINGERPRINT, FINGERPRINT_V2]",
      "defaultValue" => "'FINGERPRINT'",
      "paramType" => "query",
    },
    {
      "name" => "max_sample_size",
      "description" => "Determines what the maximum sample size during trilateration",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "min_rssi",
      "description" => "Determines what the minimum acceptable RSSI value",
      "dataType" => "Float",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "modules",
      "description" => "List modules allowed to be served by the server, possible values include: COMMON, MEDIA, OFFER, GAME, SOCIAL, CONSUMER_WEBSITE, ALL",
      "dataType" => "String",
      "allowableValues" => "",
      "defaultValue" => "'ALL'",
      "paramType" => "query",
    },
    {
      "name" => "authorized_count",
      "description" => "How many servers the license will support",
      "dataType" => "Integer",
      "allowableValues" => "",
      "defaultValue" => "1",
      "paramType" => "query",
    },
    {
      "name" => "authorized_servers",
      "description" => "The list of ip addresses of servers the license will support, leave null for any server",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "default_timezone",
      "description" => "Sets the default timezone for the app (used for leaderboards and other time specific content)",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "smtp_pass",
      "description" => "SMTP Pass",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "meta_data",
      "description" => "The application meta data. Defined by the client",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "placement_meta_data",
      "description" => "The ad placement meta data. Defined by the client",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "ips_floor",
      "description" => "Create floor tables for Ips",
      "dataType" => "Boolean",
      "allowableValues" => "",
      "defaultValue" => "false",
      "paramType" => "query",
    },
    {
      "name" => "enable_apns_badge",
      "description" => "Enables setting the APNS badge value in the payload",
      "dataType" => "Boolean",
      "allowableValues" => "",
      "defaultValue" => "true",
      "paramType" => "query",
    },
    {
      "name" => "include_in_report",
      "description" => "Enables using the application in session reports",
      "dataType" => "Boolean",
      "allowableValues" => "",
      "defaultValue" => "true",
      "paramType" => "query",
    },
    {
      "name" => "default_app_filter_id",
      "description" => "Sets the default filter to use (if none is passed in) for certain search APIs including Album Search.",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "enable_welcome_email",
      "description" => "Enables whether the default welcome email will be sent for new app users",
      "dataType" => "Boolean",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "apple_app_id",
      "description" => "The Apple Application ID",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "apple_team_id",
      "description" => "The Apple Team ID",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "apple_auth_key_id",
      "description" => "The Apple Auth Key ID",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "apple_auth_key",
      "description" => "The Apple Auth Signin Key (p8) File",
      "dataType" => "File",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "apple_issuer_id",
      "description" => "The Apple Issuer ID",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "app_store_key_id",
      "description" => "The Apple App Store Key ID",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "app_store_key",
      "description" => "The Apple App Store Key (p8) File",
      "dataType" => "File",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "google_private_key_file",
      "description" => "This is the private key file for your Google service account.",
      "dataType" => "File",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "authorize_net_api_key",
      "description" => "Authorize Net Api Key",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "authorize_net_transaction_key",
      "description" => "Authorize Net Transaction Key",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "email_sender",
      "description" => "Email Sender",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "smtp_user",
      "description" => "SMTP User",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "smtp_host",
      "description" => "SMTP Host",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "vatom_business_id",
      "description" => "Vatom Business Id",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "vatom_rest_client_id",
      "description" => "Vatom REST Client Id",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "vatom_rest_secret_key",
      "description" => "Vatom Secret Key",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "twilio_account_sid",
      "description" => "Twilio Account SID",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "twilio_auth_token",
      "description" => "Twilio Auth Token",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "twilio_sender_phone_number",
      "description" => "Twilio Sender Phone Number",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "open_ai_secret_key",
      "description" => "OpenAI Secret API Key",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "version",
      "description" => "",
      "dataType" => "Float",
      "paramType" => "path",
    },
    ]}) do
  cross_origin
  # the guts live here

  {"message" => "yes, it worked"}.to_json
end


MyApp.add_route('POST', '/api/{version}/application/active', {
  "resourcePath" => "/Application",
  "summary" => "Change Appliation Status",
  "nickname" => "update_application_active",
  "responseClass" => "SirqulResponse",
  "endpoint" => "/api/{version}/application/active",
  "notes" => "Set the application's active flag to true/false. This effectively activates or deactivates the application.",
  "parameters" => [
    {
      "name" => "account_id",
      "description" => "The account used to perform the delete, must have rights to edit the application.",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "app_key",
      "description" => "The key of the application to be deleted",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "active",
      "description" => "If true then set to active, false otherwise",
      "dataType" => "Boolean",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "version",
      "description" => "",
      "dataType" => "Float",
      "paramType" => "path",
    },
    ]}) do
  cross_origin
  # the guts live here

  {"message" => "yes, it worked"}.to_json
end


MyApp.add_route('POST', '/api/{version}/application/placement/update', {
  "resourcePath" => "/Application",
  "summary" => "Update Ad Placement",
  "nickname" => "update_application_placement",
  "responseClass" => "PlacementResponse",
  "endpoint" => "/api/{version}/application/placement/update",
  "notes" => "Updates an ad placement for an application.",
  "parameters" => [
    {
      "name" => "device_id",
      "description" => "The unique id of the device making the request (deviceId or accountId required)",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "account_id",
      "description" => "The account id of the user (deviceId or accountId required)",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "placement_id",
      "description" => "The id of the placement to update, the user must have rights to the application the ad placement is for",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "name",
      "description" => "The name of the placement",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "description",
      "description" => "The description of the placement",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "size",
      "description" => "The ad placement size {BANNER, LEADERBOARD, SKYSCRAPER, INTERSTITIAL, CUSTOM",
      "dataType" => "String",
      "allowableValues" => "[CONFIG, BANNER, LEADERBOARD, SKYSCRAPER, VIDEO, ZIP, INTERSTITIAL, CUSTOM1, CUSTOM2, CUSTOM3, CUSTOM4, CUSTOM5, CUSTOM6, CUSTOM7, CUSTOM8, CUSTOM9, CUSTOM10]",
      "paramType" => "query",
    },
    {
      "name" => "height",
      "description" => "The height of a custom ad size",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "width",
      "description" => "The width of a custom ad size",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "refresh_interval",
      "description" => "The refresh interval in seconds",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "default_image_id",
      "description" => "Default Image Id",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "active",
      "description" => "Active",
      "dataType" => "Boolean",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "version",
      "description" => "",
      "dataType" => "Float",
      "paramType" => "path",
    },
    ]}) do
  cross_origin
  # the guts live here

  {"message" => "yes, it worked"}.to_json
end


MyApp.add_route('POST', '/api/{version}/application/certificate/create', {
  "resourcePath" => "/Application",
  "summary" => "Create Application Certificate",
  "nickname" => "upload_application_certificate",
  "responseClass" => "SirqulResponse",
  "endpoint" => "/api/{version}/application/certificate/create",
  "notes" => "Uploads a certificate for an application that the user has access to.",
  "parameters" => [
    {
      "name" => "device_id",
      "description" => "Device Id",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "account_id",
      "description" => "The account used to perform the delete, must have rights to edit the application.",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "app_key",
      "description" => "The key of the application",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "certificate",
      "description" => "Certificate",
      "dataType" => "File",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "version",
      "description" => "",
      "dataType" => "Float",
      "paramType" => "path",
    },
    ]}) do
  cross_origin
  # the guts live here

  {"message" => "yes, it worked"}.to_json
end

