require 'json'


MyApp.add_route('POST', '/api/{version}/media/create', {
  "resourcePath" => "/Media",
  "summary" => "Create Media",
  "nickname" => "create_media",
  "responseClass" => "MediaOfferResponse",
  "endpoint" => "/api/{version}/media/create",
  "notes" => "Create a media offering.",
  "parameters" => [
    {
      "name" => "account_id",
      "description" => "The account id of the logged in user",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "retailer_location_ids",
      "description" => "Comma separated list of retailer location ids. This will assign the offer to these retailer locations.",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "title",
      "description" => "The title (255 char limit)",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "sub_title",
      "description" => "The sub title (255 char limit)",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "details",
      "description" => "The details of the media",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "sub_details",
      "description" => "A string for custom details (255 char limit)",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "fine_print",
      "description" => "The fine print of the media",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "barcode_type",
      "description" => "The bar code type {NONE, UPC, CODE_128, QR, CUSTOM_MEDIA}",
      "dataType" => "String",
      "allowableValues" => "[NONE, UPC, CODE_128, QR, CUSTOM_MEDIA]",
      "paramType" => "query",
    },
    {
      "name" => "barcode_entry",
      "description" => "The bar code entry string",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "external_redeem_options",
      "description" => "An external identifier. What the identifier will be used for and how it is formatted is up to the frontend developer",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "external_url",
      "description" => "The clickUrl of the offer",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "tickets_reward_type",
      "description" => "The type of ticket to reward, null means default type",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "tickets_reward",
      "description" => "Determines how many tickets are awarded",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "activated",
      "description" => "The date of when the offer will be visible to consumers",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "expires",
      "description" => "The date of when the offer expires",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "no_expiration",
      "description" => "Overrides the expiration date so that the offer does not expire",
      "dataType" => "Boolean",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "available_limit",
      "description" => "The limit of how many times the offer can be used by consumers",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "available_limit_per_user",
      "description" => "The limit of how many times a user can used the same offer",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "added_limit",
      "description" => "The limit of how many times the offer can be added to consumer wallets",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "view_limit",
      "description" => "The limit of how many times the offer can be viewed",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "max_prints",
      "description" => "The maximum number of times the offer can be printed",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "ticket_price_type",
      "description" => "the type of ticket needed to buy offer",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "ticket_price",
      "description" => "The cost of the offer in tickets",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "full_price",
      "description" => "The retail/full price cost of the offer in real currency",
      "dataType" => "Float",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "discount_price",
      "description" => "The cost of the offer at a discounted price (what the consumer pays)",
      "dataType" => "Float",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "show_remaining",
      "description" => "show how many of the media is remaining (if there is a limit)",
      "dataType" => "Boolean",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "show_redeemed",
      "description" => "show how many of the media has been redeemed",
      "dataType" => "Boolean",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "replaced",
      "description" => "if the media has been replaced",
      "dataType" => "Boolean",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "featured",
      "description" => "if the media should be featured or not",
      "dataType" => "Boolean",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "special_offer_type",
      "description" => "The special offer type {ALL, REGULAR_OFFER, ACT_NOW, GET_THERE_NOW}",
      "dataType" => "String",
      "allowableValues" => "[ALL, RESERVABLE, REGULAR_OFFER, ACT_NOW, GET_THERE_NOW, SQOOT, TICKETS, YIPIT]",
      "paramType" => "query",
    },
    {
      "name" => "offer_visibility",
      "description" => "The offer visibility {PUBLIC, REWARDABLE, TRIGGERABLE}",
      "dataType" => "String",
      "allowableValues" => "[PUBLIC, LISTABLE, REWARDABLE, TRIGGERABLE, PRIVATE]",
      "paramType" => "query",
    },
    {
      "name" => "category_ids",
      "description" => "Comma separated list of category ids",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "filter_ids",
      "description" => "Comma separated list of filter ids",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "active",
      "description" => "Sets the active flag",
      "dataType" => "Boolean",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "barcode_asset_id",
      "description" => "The id of the barcode asset",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "image_asset_id",
      "description" => "The id of the an offer asset",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "image_asset_id1",
      "description" => "The id of the an offer asset",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "image_asset_id2",
      "description" => "The id of the an offer asset",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "image_asset_id3",
      "description" => "The id of the an offer asset",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "image_asset_id4",
      "description" => "The id of the an offer asset",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "image_asset_id5",
      "description" => "The id of the an offer asset",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "publisher",
      "description" => "The maker of the item.",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "redeemable_start",
      "description" => "The redeemable start date/time of the offer.",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "redeemable_end",
      "description" => "The redeemable start date/time of the offer.",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "condition_type",
      "description" => "The condition type of the media",
      "dataType" => "String",
      "allowableValues" => "[NEW, USED, REFURBISHED, OTHER]",
      "paramType" => "query",
    },
    {
      "name" => "isbn",
      "description" => "The ISBN id",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "asin",
      "description" => "The ASIN id",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "catalog_numbers",
      "description" => "The list of catelog numbers, comma seperated",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "parental_rating",
      "description" => "The parental control rating",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "availability_date",
      "description" => "The date the media is available to use",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "media_type",
      "description" => "the media type",
      "dataType" => "String",
      "allowableValues" => "[APK, APPLICATION, IMAGE, AUDIO, VIDEO, MULTIPART, BAR_CODE, TEXT, OTHER]",
      "paramType" => "query",
    },
    {
      "name" => "duration",
      "description" => "The total playing time of the media item",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "author",
      "description" => "The created/author of the media item",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "release_date",
      "description" => "The date/time of when the media item was originally released",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "collection_ids",
      "description" => "the IDs of the collections this media should be assigned to",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "availability",
      "description" => "ability to assign if this media should active or not",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "availability_summary",
      "description" => "ability to assign when the media expires",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "version",
      "description" => "",
      "dataType" => "Float",
      "paramType" => "path",
    },
    ]}) do
  cross_origin
  # the guts live here

  {"message" => "yes, it worked"}.to_json
end


MyApp.add_route('POST', '/api/{version}/media/delete', {
  "resourcePath" => "/Media",
  "summary" => "Delete Media",
  "nickname" => "delete_media",
  "responseClass" => "SirqulResponse",
  "endpoint" => "/api/{version}/media/delete",
  "notes" => "Delete a media offering that the user has permissions to.",
  "parameters" => [
    {
      "name" => "account_id",
      "description" => "the id of the logged in user",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "media_id",
      "description" => "the ID of the media to delete",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "version",
      "description" => "",
      "dataType" => "Float",
      "paramType" => "path",
    },
    ]}) do
  cross_origin
  # the guts live here

  {"message" => "yes, it worked"}.to_json
end


MyApp.add_route('GET', '/api/{version}/media/get', {
  "resourcePath" => "/Media",
  "summary" => "Media Get",
  "nickname" => "get_media",
  "responseClass" => "MediaOfferResponse",
  "endpoint" => "/api/{version}/media/get",
  "notes" => "Get a media offering.",
  "parameters" => [
    {
      "name" => "account_id",
      "description" => "the id of the logged in user",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "media_id",
      "description" => "the id of the media to get",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "version",
      "description" => "",
      "dataType" => "Float",
      "paramType" => "path",
    },
    ]}) do
  cross_origin
  # the guts live here

  {"message" => "yes, it worked"}.to_json
end


MyApp.add_route('GET', '/api/{version}/media/search', {
  "resourcePath" => "/Media",
  "summary" => "Search Media",
  "nickname" => "search_media",
  "responseClass" => "Array<MediaOfferResponse>",
  "endpoint" => "/api/{version}/media/search",
  "notes" => "Searches on events that the account has access to.",
  "parameters" => [
    {
      "name" => "account_id",
      "description" => "The logged in user.",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "keyword",
      "description" => "The keyword used to search",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "active_only",
      "description" => "Return only active results",
      "dataType" => "Boolean",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "category_ids",
      "description" => "",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "filter_ids",
      "description" => "",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "sort_field",
      "description" => "The column to sort the search on. Possible values include: ID, CREATED, UPDATED, ACTIVE, ACTIVATED, EXPIRES, TITLE, SUBTITLE, DETAILS, OFFER_TYPE, SPECIAL_OFFER_TYPE, OFFER_VISIBILITY, ESTIMATED_VALUE, VOUCHER_PRICE, RETAILER_ID, RETAILER_NAME, RETAILER_LOCATION_ID, RETAILER_LOCATION_NAME, BILLABLE_ENTITY_ID, BILLABLE_ENTITY_NAME, RESPONSIBLE_DISPLAY, AVAILABILITY_DATE, RELEASE_DATE",
      "dataType" => "String",
      "allowableValues" => "[ID, CREATED, UPDATED, DELETED, SEARCH_TAGS, ACTIVE, ACTIVATED, EXPIRES, REDEEMABLE_START, REDEEMABLE_END, TITLE, SUBTITLE, DETAILS, OFFER_TYPE, SPECIAL_OFFER_TYPE, OFFER_VISIBILITY, ESTIMATED_VALUE, VOUCHER_PRICE, VOUCHER_DISCOUNT_PRICE, FULL_PRICE, DICOUNT_PRICE, TICKETS_REWARD, AVAILABILITY_DATE, RELEASE_DATE, RETAILER_ID, RETAILER_NAME, RETAILER_LOCATION_ID, RETAILER_LOCATION_NAME, BILLABLE_ENTITY_ID, BILLABLE_ENTITY_NAME, RESPONSIBLE_DISPLAY]",
      "paramType" => "query",
    },
    {
      "name" => "descending",
      "description" => "The order to return the search results",
      "dataType" => "Boolean",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "start",
      "description" => "The record to begin the return set on",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "limit",
      "description" => "The number of records to return",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "version",
      "description" => "",
      "dataType" => "Float",
      "paramType" => "path",
    },
    ]}) do
  cross_origin
  # the guts live here

  {"message" => "yes, it worked"}.to_json
end


MyApp.add_route('POST', '/api/{version}/media/update', {
  "resourcePath" => "/Media",
  "summary" => "Update Media",
  "nickname" => "update_media",
  "responseClass" => "MediaOfferResponse",
  "endpoint" => "/api/{version}/media/update",
  "notes" => "Update a media offering.",
  "parameters" => [
    {
      "name" => "account_id",
      "description" => "The account used to perform the update, must have rights to edit the offer (deviceId or accountId required)",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "media_id",
      "description" => "",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "retailer_location_ids",
      "description" => "Comma separated list of retailer location ids. This will assign the offer to these retailer locations.",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "offer_locations",
      "description" => "A list of json data that has offer location specific values.",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "title",
      "description" => "The title (255 char limit)",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "sub_title",
      "description" => "The sub title (255 char limit)",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "details",
      "description" => "The details",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "sub_details",
      "description" => "A string for custom details (255 char limit)",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "fine_print",
      "description" => "The fine print",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "barcode_type",
      "description" => "The bar code type {NONE, UPC, CODE_128, QR, CUSTOM_MEDIA}",
      "dataType" => "String",
      "allowableValues" => "[NONE, UPC, CODE_128, QR, CUSTOM_MEDIA]",
      "paramType" => "query",
    },
    {
      "name" => "barcode_entry",
      "description" => "The bar code entry string",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "external_redeem_options",
      "description" => "An external identifier. What the identifier will be used for and how it is formatted is up to the frontend developer.",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "external_url",
      "description" => "The clickUrl of the offer",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "tickets_reward_type",
      "description" => "The type of ticket to reward, null means default type",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "tickets_reward",
      "description" => "Determines how many tickets are awarded",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "activated",
      "description" => "The date of when the offer will be visible to consumers",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "expires",
      "description" => "The date of when the offer expires",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "no_expiration",
      "description" => "Overrides the expiration date so that the offer does not expire",
      "dataType" => "Boolean",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "available_limit",
      "description" => "The limit of how many times the offer can be used by consumers",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "available_limit_per_user",
      "description" => "The limit of how many times a user can used the same offer",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "added_limit",
      "description" => "The limit of how many times the offer can be added to consumer wallets",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "view_limit",
      "description" => "",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "max_prints",
      "description" => "The maximum number of times the offer can be printed",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "ticket_price_type",
      "description" => "the type of ticket needed to buy the offer",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "ticket_price",
      "description" => "The cost of the offer in tickets",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "full_price",
      "description" => "The retail/full price cost of the offer in real currency",
      "dataType" => "Float",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "discount_price",
      "description" => "The cost of the offer at a discounted price (what the consumer pays)",
      "dataType" => "Float",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "show_remaining",
      "description" => "The show remaining",
      "dataType" => "Boolean",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "show_redeemed",
      "description" => "The show redeemed",
      "dataType" => "Boolean",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "replaced",
      "description" => "The replaced",
      "dataType" => "Boolean",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "featured",
      "description" => "The featured",
      "dataType" => "Boolean",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "special_offer_type",
      "description" => "The special offer type {ALL, REGULAR_OFFER, ACT_NOW, GET_THERE_NOW}",
      "dataType" => "String",
      "allowableValues" => "[ALL, RESERVABLE, REGULAR_OFFER, ACT_NOW, GET_THERE_NOW, SQOOT, TICKETS, YIPIT]",
      "paramType" => "query",
    },
    {
      "name" => "offer_visibility",
      "description" => "The offer visibility {PUBLIC, REWARDABLE, TRIGGERABLE}",
      "dataType" => "String",
      "allowableValues" => "[PUBLIC, LISTABLE, REWARDABLE, TRIGGERABLE, PRIVATE]",
      "paramType" => "query",
    },
    {
      "name" => "category_ids",
      "description" => "Comma separated list of category ids",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "filter_ids",
      "description" => "Comma separated list of filter ids",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "active",
      "description" => "Sets the active flag",
      "dataType" => "Boolean",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "barcode_asset_id",
      "description" => "The id of the barcode asset",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "image_asset_id",
      "description" => "The id of the an offer asset",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "image_asset_id1",
      "description" => "The id of the an offer asset",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "image_asset_id2",
      "description" => "The id of the an offer asset",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "image_asset_id3",
      "description" => "The id of the an offer asset",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "image_asset_id4",
      "description" => "The id of the an offer asset",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "image_asset_id5",
      "description" => "The id of the an offer asset",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "publisher",
      "description" => "The maker of the item.",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "redeemable_start",
      "description" => "The redeemable start date/time of the offer.",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "redeemable_end",
      "description" => "The redeemable start date/time of the offer.",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "condition_type",
      "description" => "The condition. OfferType PRODUCT only.",
      "dataType" => "String",
      "allowableValues" => "[NEW, USED, REFURBISHED, OTHER]",
      "paramType" => "query",
    },
    {
      "name" => "isbn",
      "description" => "The ISBN id. OfferType PRODUCT only.",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "asin",
      "description" => "The ASIN id. OfferType PRODUCT only.",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "catalog_numbers",
      "description" => "The list of catelog numbers, comma seperated. OfferType PRODUCT only.",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "availability_date",
      "description" => "The date available. OfferType PRODUCT only.",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "parental_rating",
      "description" => "The parental control rating. OfferType PRODUCT only.",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "media_type",
      "description" => "",
      "dataType" => "String",
      "allowableValues" => "[APK, APPLICATION, IMAGE, AUDIO, VIDEO, MULTIPART, BAR_CODE, TEXT, OTHER]",
      "paramType" => "query",
    },
    {
      "name" => "duration",
      "description" => "The total playing time of the media item. OfferType MEDIA only.",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "author",
      "description" => "The created/author of the media item. OfferType MEDIA only.",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "release_date",
      "description" => "The date/time of when the media item was originally released. OfferType MEDIA only.",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "collection_ids",
      "description" => "",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "availability",
      "description" => "",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "availability_summary",
      "description" => "",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "version",
      "description" => "",
      "dataType" => "Float",
      "paramType" => "path",
    },
    ]}) do
  cross_origin
  # the guts live here

  {"message" => "yes, it worked"}.to_json
end

