require 'json'


MyApp.add_route('POST', '/api/3.18/retailer/offer/location/batchUpdate', {
  "resourcePath" => "/Offer",
  "summary" => "Update Offer Locations",
  "nickname" => "batch_update_offer_locations",
  "responseClass" => "SirqulResponse",
  "endpoint" => "/retailer/offer/location/batchUpdate",
  "notes" => "Batch update offer locations.",
  "parameters" => [
    {
      "name" => "device_id",
      "description" => "The device id (deviceId or accountId required)",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "account_id",
      "description" => "The account id of the user (deviceId or accountId required)",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "data",
      "description" => "JSON string in the following format: &#x60;&#x60;&#x60;json [{   \&quot;offerLocationId\&quot;: 1705,   \&quot;latitude\&quot;: 54.0,   \&quot;longitude\&quot;: -122.0,   \&quot;altitude\&quot;: 1.0,   \&quot;locationDetail\&quot;: \&quot;floor 1\&quot;,   \&quot;locationDescription\&quot;: \&quot;behind the Coke sign\&quot; }, {   \&quot;offerLocationId\&quot;: 1704,   \&quot;latitude\&quot;: 54.1,   \&quot;longitude\&quot;: -122.1 }] &#x60;&#x60;&#x60; ",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    ]}) do
  cross_origin
  # the guts live here

  {"message" => "yes, it worked"}.to_json
end


MyApp.add_route('POST', '/api/3.18/retailer/offer/create', {
  "resourcePath" => "/Offer",
  "summary" => "Create Offer",
  "nickname" => "create_offer",
  "responseClass" => "RetailerOfferResponse",
  "endpoint" => "/retailer/offer/create",
  "notes" => "Create an offer and assign it to the provided retailer locations.",
  "parameters" => [
    {
      "name" => "device_id",
      "description" => "The device id (deviceId or accountId required)",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "account_id",
      "description" => "The account id (deviceId or accountId required)",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "tags",
      "description" => "Custom string field for doing full-text searches",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "parent_offer_id",
      "description" => "the parent offer id",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "include_offer_locations",
      "description" => "If true return all the offer locations associated with the offer",
      "dataType" => "Boolean",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "retailer_location_ids",
      "description" => "Comma separated list of retailer location ids. This will assign the offer to these retailer locations.",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "offer_locations",
      "description" => "A list of json data that has offer location specific values.",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "title",
      "description" => "The title (255 char limit)",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "sub_title",
      "description" => "The sub title (255 char limit)",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "details",
      "description" => "The details",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "sub_details",
      "description" => "A string for custom details (255 char limit)",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "fine_print",
      "description" => "The fine print",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "barcode_type",
      "description" => "The bar code type {NONE, UPC, CODE_128, QR, CUSTOM_MEDIA}",
      "dataType" => "String",
      "allowableValues" => "[NONE, UPC, CODE_128, QR, CUSTOM_MEDIA]",
      "paramType" => "query",
    },
    {
      "name" => "barcode_entry",
      "description" => "The bar code entry string",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "external_redeem_options",
      "description" => "An external identifier. What the identifier will be used for and how it is formatted is up to the frontend developer",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "external_url",
      "description" => "The clickUrl of the offer",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "external_id",
      "description" => "an external identifier. What the identifier will be used for and how it is formatted is up to the frontend developer",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "tickets_reward_type",
      "description" => "The type of ticket to reward, null means default type",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "tickets_reward",
      "description" => "Determines how many tickets are awarded",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "activated",
      "description" => "The date of when the offer will be visible to consumers",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "expires",
      "description" => "The date of when the offer expires",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "no_expiration",
      "description" => "Overrides the expiration date so that the offer does not expire",
      "dataType" => "Boolean",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "available_limit",
      "description" => "The limit of how many times the offer can be used by consumers",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "available_limit_per_user",
      "description" => "The limit of how many times a user can used the same offer",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "added_limit",
      "description" => "The limit of how many times the offer can be added to consumer wallets",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "view_limit",
      "description" => "The limit of how many times the offer can be viewed",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "max_prints",
      "description" => "The maximum number of times the offer can be printed",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "ticket_price_type",
      "description" => "the type of ticket needed to buy offer",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "ticket_price",
      "description" => "The cost of the offer in tickets",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "full_price",
      "description" => "The retail/full price cost of the offer in real currency",
      "dataType" => "Float",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "discount_price",
      "description" => "The cost of the offer at a discounted price (what the consumer pays)",
      "dataType" => "Float",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "show_remaining",
      "description" => "show remaining offers available",
      "dataType" => "Boolean",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "show_redeemed",
      "description" => "show how many offers have been redeemed",
      "dataType" => "Boolean",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "replaced",
      "description" => "",
      "dataType" => "Boolean",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "featured",
      "description" => "flag if offer is featured or not",
      "dataType" => "Boolean",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "offer_type",
      "description" => "The offer type {VOUCHER, COUPON, PRODUCT, EVENT, MEDIA, DEVICE}",
      "dataType" => "String",
      "allowableValues" => "[VOUCHER, COUPON, PRODUCT, MEDIA, EVENT, DEVICE]",
      "paramType" => "query",
    },
    {
      "name" => "special_offer_type",
      "description" => "The special offer type {ALL, REGULAR_OFFER, ACT_NOW, GET_THERE_NOW}",
      "dataType" => "String",
      "allowableValues" => "[ALL, RESERVABLE, REGULAR_OFFER, ACT_NOW, GET_THERE_NOW, SQOOT, TICKETS, YIPIT]",
      "paramType" => "query",
    },
    {
      "name" => "offer_visibility",
      "description" => "The offer visibility {PUBLIC, REWARDABLE, TRIGGERABLE}",
      "dataType" => "String",
      "allowableValues" => "[PUBLIC, LISTABLE, REWARDABLE, TRIGGERABLE, PRIVATE]",
      "paramType" => "query",
    },
    {
      "name" => "category_ids",
      "description" => "Comma separated list of category ids",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "filter_ids",
      "description" => "Comma separated list of filter ids",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "active",
      "description" => "Sets the active flag",
      "dataType" => "Boolean",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "barcode_asset_id",
      "description" => "The id of the barcode asset",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "image_asset_id",
      "description" => "The id of the an offer asset",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "image_asset_id1",
      "description" => "The id of the an offer asset",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "image_asset_id2",
      "description" => "The id of the an offer asset",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "image_asset_id3",
      "description" => "The id of the an offer asset",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "image_asset_id4",
      "description" => "The id of the an offer asset",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "image_asset_id5",
      "description" => "The id of the an offer asset",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "publisher",
      "description" => "The maker of the item.",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "redeemable_start",
      "description" => "The redeemable start date/time of the offer.",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "redeemable_end",
      "description" => "The redeemable start date/time of the offer.",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "brand",
      "description" => "The brand. OfferType PRODUCT only.",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "product_type",
      "description" => "The product type. OfferType PRODUCT only.",
      "dataType" => "String",
      "allowableValues" => "[APPAREL, APPLIANCES, APPS, ARTS_CRAFTS, AUTOMOTIVE, BABY, BEAUTY, BOOKS, CLASSICAL, COLLECTIBLES, DVD, ELECTRONICS, GIFT_CARDS, GOURMET_FOOD, GROCERY, HEALTH_PERSONAL_CARE, HOME_GARDEN, INDUSTRIAL, JEWELRY, KITCHEN, LAWN_GARDEN, MAGAZINES, MISCELLANEOUS, MUSICAL_INSTRUMENTS, OFFICE_PRODUCTS, OTHER, OUTDOOR_LIVING, PC_HARDWARE, PET_SUPPLIES, SHOES, SOFTWARE, SPORTING_GOODS, TOOLS, TOYS, VIDEO_GAMES, WATCHES, WIRELESS, WIRELESS_ACCESSORIES]",
      "paramType" => "query",
    },
    {
      "name" => "condition_type",
      "description" => "The condition. OfferType PRODUCT only.",
      "dataType" => "String",
      "allowableValues" => "[NEW, USED, REFURBISHED, OTHER]",
      "paramType" => "query",
    },
    {
      "name" => "isbn",
      "description" => "The ISBN id. OfferType PRODUCT only.",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "asin",
      "description" => "The ASIN id. OfferType PRODUCT only.",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "catalog_numbers",
      "description" => "The list of catelog numbers, comma seperated. OfferType PRODUCT only.",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "department",
      "description" => "The department name. The OfferType PRODUCT only.",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "features",
      "description" => "The list of features, comma seperated. OfferType PRODUCT only.",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "minimum_price",
      "description" => "The MAP price. OfferType PRODUCT only.",
      "dataType" => "Float",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "width",
      "description" => "The width of the item. OfferType PRODUCT only.",
      "dataType" => "Float",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "height",
      "description" => "The height of the item. OfferType PRODUCT only.",
      "dataType" => "Float",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "depth",
      "description" => "The depth of the item. OfferType PRODUCT only.",
      "dataType" => "Float",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "weight",
      "description" => "The weight of the item. OfferType PRODUCT only.",
      "dataType" => "Float",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "unit",
      "description" => "The unit of measurement. OfferType PRODUCT only.",
      "dataType" => "String",
      "allowableValues" => "[MILIMETER, CENTIMETER, METER, INCH, FOOT, YARD]",
      "paramType" => "query",
    },
    {
      "name" => "studio",
      "description" => "The studio name. OfferType PRODUCT only.",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "parental_rating",
      "description" => "The parental control rating. OfferType PRODUCT only.",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "publish_date",
      "description" => "The date published. OfferType PRODUCT only.",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "availability_date",
      "description" => "The date available. OfferType PRODUCT only.",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "size_id",
      "description" => "",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "listing_id",
      "description" => "The ID of the event listing",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "media_type",
      "description" => "the media type of the offer",
      "dataType" => "String",
      "allowableValues" => "[APK, APPLICATION, IMAGE, AUDIO, VIDEO, MULTIPART, BAR_CODE, TEXT, OTHER]",
      "paramType" => "query",
    },
    {
      "name" => "duration",
      "description" => "The total playing time of the media item. OfferType MEDIA only.",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "author",
      "description" => "The created/author of the media item. OfferType MEDIA only.",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "release_date",
      "description" => "The date/time of when the media item was originally released. OfferType MEDIA only.",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "collection_ids",
      "description" => "",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "reboot_time_hour",
      "description" => "The reboot hour time ranging from 0 to 23",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "reboot_time_minute",
      "description" => "The reboot minute time ranging from 0 to 59",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "idle_timeout_in_second",
      "description" => "If the device is idle for idleTimeoutInSecond then the device should timeout",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "serial_number",
      "description" => "The serial number on the device",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "udid",
      "description" => "The unique device id for the device",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "device_type",
      "description" => "The type of the device, for example: \&quot;Kiosk\&quot;, \&quot;Beacon\&quot;.",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "device_power",
      "description" => "Edysen device power level setting",
      "dataType" => "Float",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "device_interference",
      "description" => "Edysen device inteference setting",
      "dataType" => "Float",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "availability",
      "description" => "",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "availability_summary",
      "description" => "",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    ]}) do
  cross_origin
  # the guts live here

  {"message" => "yes, it worked"}.to_json
end


MyApp.add_route('POST', '/api/3.18/retailer/offer/delete', {
  "resourcePath" => "/Offer",
  "summary" => "Delete Offer",
  "nickname" => "delete_offer",
  "responseClass" => "SirqulResponse",
  "endpoint" => "/retailer/offer/delete",
  "notes" => "Set the deleted timestamp to current time. This effectively deletes the offer since all queries should ignore any records with a deleted time stamp.",
  "parameters" => [
    {
      "name" => "device_id",
      "description" => "The device id (deviceId or accountId required)",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "account_id",
      "description" => "The account used to perform the delete, must have rights to edit the offer.",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "offer_id",
      "description" => "The ID of the offer to be deleted",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    ]}) do
  cross_origin
  # the guts live here

  {"message" => "yes, it worked"}.to_json
end


MyApp.add_route('POST', '/api/3.18/retailer/offer/location/delete', {
  "resourcePath" => "/Offer",
  "summary" => "Delete Offer Location",
  "nickname" => "delete_offer_location",
  "responseClass" => "SirqulResponse",
  "endpoint" => "/retailer/offer/location/delete",
  "notes" => "Set the deleted timestamp to current time. This effectively deletes the offer location since all queries should ignore any records with a deleted time stamp.",
  "parameters" => [
    {
      "name" => "device_id",
      "description" => "The device id (deviceId or accountId required)",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "account_id",
      "description" => "The account used to perform the delete, must have rights to edit the offer location.",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "offer_location_id",
      "description" => "The ID of the offer location to be deleted",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    ]}) do
  cross_origin
  # the guts live here

  {"message" => "yes, it worked"}.to_json
end


MyApp.add_route('GET', '/api/3.18/retailer/offer/get', {
  "resourcePath" => "/Offer",
  "summary" => "Get Offer",
  "nickname" => "get_offer",
  "responseClass" => "RetailerOfferResponse",
  "endpoint" => "/retailer/offer/get",
  "notes" => "Gets the details of an offer that the user has access to.",
  "parameters" => [
    {
      "name" => "device_id",
      "description" => "The device id (deviceId or accountId required)",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "account_id",
      "description" => "The account id (deviceId or accountId required)",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "offer_id",
      "description" => "The id of the offer",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "include_offer_locations",
      "description" => "",
      "dataType" => "Boolean",
      "allowableValues" => "",
      "paramType" => "query",
    },
    ]}) do
  cross_origin
  # the guts live here

  {"message" => "yes, it worked"}.to_json
end


MyApp.add_route('GET', '/api/3.18/offer/get', {
  "resourcePath" => "/Offer",
  "summary" => "Get Offer",
  "nickname" => "get_offer_details",
  "responseClass" => "OfferResponse",
  "endpoint" => "/offer/get",
  "notes" => "Gets offer or offer location details as a consumer.  Will check if it is a favorite if the deviceId/accountId is provided.  If the offerId is provided it will look up the main offer and ignore the the offerLocationId. If no offerId is provided then an offerLocationId must be specified.",
  "parameters" => [
    {
      "name" => "device_id",
      "description" => "The device id for returning account information (i.e. favorites)",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "account_id",
      "description" => "The account id for returning account information (i.e. favorites)",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "offer_id",
      "description" => "The offer id (either offeLocationId or offerId must be provided)",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "offer_location_id",
      "description" => "The offer location id (either offeLocationId or offerId must be provided)",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "distance",
      "description" => "The distance of the offer from the user&#39;s current location (this is returned when the offer is searched)",
      "dataType" => "Float",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "latitude",
      "description" => "The latitude to calculate distance from the offer",
      "dataType" => "Float",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "longitude",
      "description" => "The longitude to calculate distance from the offer",
      "dataType" => "Float",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "include_offer_locations",
      "description" => "Determines whether to return offer locations for the offer",
      "dataType" => "Boolean",
      "allowableValues" => "",
      "defaultValue" => "false",
      "paramType" => "query",
    },
    {
      "name" => "include_retailer_locations",
      "description" => "Determines whether to return the retailer location info for each offer location response (includeOfferLocations must also be true for this to work)",
      "dataType" => "Boolean",
      "allowableValues" => "",
      "defaultValue" => "false",
      "paramType" => "query",
    },
    {
      "name" => "include_child_offers",
      "description" => "Determines whether to include child offers in the response",
      "dataType" => "Boolean",
      "allowableValues" => "",
      "defaultValue" => "false",
      "paramType" => "query",
    },
    ]}) do
  cross_origin
  # the guts live here

  {"message" => "yes, it worked"}.to_json
end


MyApp.add_route('GET', '/api/3.18/offer/lists/count', {
  "resourcePath" => "/Offer",
  "summary" => "Get Offers (Counts)",
  "nickname" => "get_offer_list_counts",
  "responseClass" => "ListCountResponse",
  "endpoint" => "/offer/lists/count",
  "notes" => "Gets the offer list counts.",
  "parameters" => [
    {
      "name" => "latitude",
      "description" => "The latitude of where the search will center at",
      "dataType" => "Float",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "longitude",
      "description" => "The longitude of where the search will center at",
      "dataType" => "Float",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "search_range",
      "description" => "The range of the search",
      "dataType" => "Float",
      "allowableValues" => "",
      "defaultValue" => "5",
      "paramType" => "query",
    },
    {
      "name" => "distance_unit",
      "description" => "The units to use for distance calculations (e.g. MILES, KILOMETERS)",
      "dataType" => "String",
      "allowableValues" => "[MILES, KILOMETERS]",
      "defaultValue" => "'MILES'",
      "paramType" => "query",
    },
    ]}) do
  cross_origin
  # the guts live here

  {"message" => "yes, it worked"}.to_json
end


MyApp.add_route('GET', '/api/3.18/offer/location/get', {
  "resourcePath" => "/Offer",
  "summary" => "Get Offer Location",
  "nickname" => "get_offer_location",
  "responseClass" => "OfferShortResponse",
  "endpoint" => "/offer/location/get",
  "notes" => "Gets the offer location by offer location id or udid (of a device)",
  "parameters" => [
    {
      "name" => "offer_location_id",
      "description" => "the id of the offer location to get",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "udid",
      "description" => "the UDID of the device",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    ]}) do
  cross_origin
  # the guts live here

  {"message" => "yes, it worked"}.to_json
end


MyApp.add_route('GET', '/api/3.18/retailer/offer/location/search', {
  "resourcePath" => "/Offer",
  "summary" => "Search Offer Locations",
  "nickname" => "get_offer_locations_for_retailers",
  "responseClass" => "Array<OfferShortResponse>",
  "endpoint" => "/retailer/offer/location/search",
  "notes" => "Searches on offer locations, which are records that represent an offer that has been assigned to a retailer location. If an offer does not have any locations assigned, then it will NOT be returned.",
  "parameters" => [
    {
      "name" => "device_id",
      "description" => "The device id (deviceId or accountId required)",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "account_id",
      "description" => "The account id of the user (deviceId or accountId required)",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "keyword",
      "description" => "The keyword used to search",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "retailer_id",
      "description" => "Filter results for a specific retailer",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "retailer_location_id",
      "description" => "Filter results for a specific retailer location",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "offer_type",
      "description" => "Filter results to only return COUPON, VOUCHER, PRODUCT, MEDIA, or EVENT offers",
      "dataType" => "String",
      "allowableValues" => "[VOUCHER, COUPON, PRODUCT, MEDIA, EVENT, DEVICE]",
      "paramType" => "query",
    },
    {
      "name" => "special_offer_type",
      "description" => "Filter results to only return REGULAR_OFFER, ACT_NOW, GET_THERE_NOW offer specials",
      "dataType" => "String",
      "allowableValues" => "[ALL, RESERVABLE, REGULAR_OFFER, ACT_NOW, GET_THERE_NOW, SQOOT, TICKETS, YIPIT]",
      "paramType" => "query",
    },
    {
      "name" => "sort_field",
      "description" => "The column to sort the results on. Default is \&quot;TITLE\&quot;, which will sort the results by the offer title. Possible input values: {CREATED, UPDATED, ACTIVE, ACTIVATED, EXPIRES, TITLE, SUBTITLE, DETAILS, OFFER_TYPE, RETAILER_ID,RETAILER_LOCATION_ID, BILLABLE_ENTITY_NAME, RESPONSIBLE_DISPLAY}",
      "dataType" => "String",
      "allowableValues" => "[ID, CREATED, UPDATED, DELETED, SEARCH_TAGS, ACTIVE, OFFER_ID, ACTIVATED, EXPIRES, TITLE, SUBTITLE, DETAILS, OFFER_TYPE, SPECIAL_OFFER_TYPE, OFFER_VISIBILITY, RETAILER_ID, RETAILER_LOCATION_ID, BILLABLE_ENTITY_ID, BILLABLE_ENTITY_NAME, RESPONSIBLE_DISPLAY]",
      "paramType" => "query",
    },
    {
      "name" => "descending",
      "description" => "The order to return the results. Default is false, which will return the results in ascending order.",
      "dataType" => "Boolean",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "start",
      "description" => "The index into the record set to start with. Default is 0.",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "limit",
      "description" => "The total number of records to return. Default is 20.",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "active_only",
      "description" => "Determines whether to return only active results. Default is false.",
      "dataType" => "Boolean",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "include_retailer_location",
      "description" => "",
      "dataType" => "Boolean",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "barcode_type",
      "description" => "",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "barcode_entry",
      "description" => "",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "isbn",
      "description" => "",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "asin",
      "description" => "",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "device_status",
      "description" => "Edysen device status, running, warning, or down",
      "dataType" => "String",
      "allowableValues" => "[RUNNING, WARNING, DOWN]",
      "paramType" => "query",
    },
    {
      "name" => "needs_notification_sent",
      "description" => "",
      "dataType" => "Boolean",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "last_notification_sent",
      "description" => "",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    ]}) do
  cross_origin
  # the guts live here

  {"message" => "yes, it worked"}.to_json
end


MyApp.add_route('GET', '/api/3.18/retailer/offer/search', {
  "resourcePath" => "/Offer",
  "summary" => "Search Offers",
  "nickname" => "get_offers_for_retailers",
  "responseClass" => "Array<OfferResponse>",
  "endpoint" => "/retailer/offer/search",
  "notes" => "Searches on offers that the account has access to.",
  "parameters" => [
    {
      "name" => "device_id",
      "description" => "The device id (deviceId or accountId required)",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "account_id",
      "description" => "The account id of the user (deviceId or accountId required)",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "category_ids",
      "description" => "",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "filter_ids",
      "description" => "",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "q",
      "description" => "This parameter is deprecated.",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "keyword",
      "description" => "The keyword used to search",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "retailer_id",
      "description" => "the id of the retailer",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "retailer_location_id",
      "description" => "the id of the retailer location",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "coupon_type",
      "description" => "This parameter is deprecated.",
      "dataType" => "String",
      "allowableValues" => "[VOUCHER, COUPON, PRODUCT, MEDIA, EVENT, DEVICE]",
      "paramType" => "query",
    },
    {
      "name" => "offer_type",
      "description" => "This parameter is deprecated. Use offer types. Filter results to only return COUPON, VOUCHER, PRODUCT, MEDIA, or EVENT offers",
      "dataType" => "String",
      "allowableValues" => "[VOUCHER, COUPON, PRODUCT, MEDIA, EVENT, DEVICE]",
      "paramType" => "query",
    },
    {
      "name" => "offer_types",
      "description" => "Comma separated list of offer types {COUPON, VOUCHER, PRODUCT, MEDIA, EVENT, DEVICE}",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "special_offer_type",
      "description" => "Filter results to only return REGULAR_OFFER, ACT_NOW, GET_THERE_NOW offer specials",
      "dataType" => "String",
      "allowableValues" => "[ALL, RESERVABLE, REGULAR_OFFER, ACT_NOW, GET_THERE_NOW, SQOOT, TICKETS, YIPIT]",
      "paramType" => "query",
    },
    {
      "name" => "offer_visibility",
      "description" => "",
      "dataType" => "String",
      "allowableValues" => "[PUBLIC, LISTABLE, REWARDABLE, TRIGGERABLE, PRIVATE]",
      "paramType" => "query",
    },
    {
      "name" => "sort_field",
      "description" => "The column to sort the search on. Possible values include: ID, CREATED, UPDATED, ACTIVE, ACTIVATED, EXPIRES, TITLE, SUBTITLE, DETAILS, OFFER_TYPE, SPECIAL_OFFER_TYPE, OFFER_VISIBILITY, ESTIMATED_VALUE, VOUCHER_PRICE, RETAILER_ID, RETAILER_NAME, RETAILER_LOCATION_ID, RETAILER_LOCATION_NAME, BILLABLE_ENTITY_ID, BILLABLE_ENTITY_NAME, RESPONSIBLE_DISPLAY",
      "dataType" => "String",
      "allowableValues" => "[ID, CREATED, UPDATED, DELETED, SEARCH_TAGS, ACTIVE, ACTIVATED, EXPIRES, REDEEMABLE_START, REDEEMABLE_END, TITLE, SUBTITLE, DETAILS, OFFER_TYPE, SPECIAL_OFFER_TYPE, OFFER_VISIBILITY, ESTIMATED_VALUE, VOUCHER_PRICE, VOUCHER_DISCOUNT_PRICE, FULL_PRICE, DICOUNT_PRICE, TICKETS_REWARD, AVAILABILITY_DATE, RELEASE_DATE, RETAILER_ID, RETAILER_NAME, RETAILER_LOCATION_ID, RETAILER_LOCATION_NAME, BILLABLE_ENTITY_ID, BILLABLE_ENTITY_NAME, RESPONSIBLE_DISPLAY]",
      "paramType" => "query",
    },
    {
      "name" => "descending",
      "description" => "The order to return the search results",
      "dataType" => "Boolean",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "_i",
      "description" => "This parameter is deprecated.",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "start",
      "description" => "The record to begin the return set on",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "_l",
      "description" => "This parameter is deprecated.",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "limit",
      "description" => "The number of records to return",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "available_only",
      "description" => "Return only results that are currently being promoted (is activated and not expired)",
      "dataType" => "Boolean",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "active_only",
      "description" => "Return only active results",
      "dataType" => "Boolean",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "include_categories",
      "description" => "",
      "dataType" => "Boolean",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "include_filters",
      "description" => "",
      "dataType" => "Boolean",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "include_offer_locations",
      "description" => "",
      "dataType" => "Boolean",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "barcode_type",
      "description" => "",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "barcode_entry",
      "description" => "",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "isbn",
      "description" => "",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "asin",
      "description" => "",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "device_status",
      "description" => "Edysen device status",
      "dataType" => "String",
      "allowableValues" => "[RUNNING, WARNING, DOWN]",
      "paramType" => "query",
    },
    {
      "name" => "needs_notification_sent",
      "description" => "",
      "dataType" => "Boolean",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "last_notification_sent",
      "description" => "",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    ]}) do
  cross_origin
  # the guts live here

  {"message" => "yes, it worked"}.to_json
end


MyApp.add_route('POST', '/api/3.18/retailer/offer/transaction/update', {
  "resourcePath" => "/Offer",
  "summary" => "Update Offer Transaction",
  "nickname" => "redeem_offer_transaction",
  "responseClass" => "SirqulResponse",
  "endpoint" => "/retailer/offer/transaction/update",
  "notes" => "Redeems an offer.",
  "parameters" => [
    {
      "name" => "device_id",
      "description" => "the device id (deviceId or accountId required)",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "account_id",
      "description" => "the account id of the user (deviceId or accountId required)",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "offer_transaction_id",
      "description" => "the OfferTransaction ID of the transaction being redeemed",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "offer_location_id",
      "description" => "the OfferLocation ID where the offer is being redeemed",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "status",
      "description" => "the status to set the offer transaction to - 1 sets it to redeemable and 2 sets it to redeemed",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    ]}) do
  cross_origin
  # the guts live here

  {"message" => "yes, it worked"}.to_json
end


MyApp.add_route('GET', '/api/3.18/retailer/offer/transaction/search', {
  "resourcePath" => "/Offer",
  "summary" => "Search Offer Transactions",
  "nickname" => "search_offer_transactions_for_retailers",
  "responseClass" => "Array<OfferTransactionResponse>",
  "endpoint" => "/retailer/offer/transaction/search",
  "notes" => "Searches on offer transactions for offers that the account has access to.",
  "parameters" => [
    {
      "name" => "device_id",
      "description" => "The device id (deviceId or accountId required)",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "account_id",
      "description" => "The account id of the user (deviceId or accountId required)",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "q",
      "description" => "This parameter is deprecated.",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "keyword",
      "description" => "The keyword to search for",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "retailer_id",
      "description" => "Filter results for this retailer",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "retailer_location_id",
      "description" => "Filter results for this retailer location",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "offer_id",
      "description" => "Filter results for this offer",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "offer_location_id",
      "description" => "Filter results for this offer location",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "redeemed",
      "description" => "if true return redeemed transactions (status 2), if false return active transactions (status 0 or 1)",
      "dataType" => "Boolean",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "reservations_only",
      "description" => "returns only reservation transactions if true",
      "dataType" => "Boolean",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "coupon_type",
      "description" => "This parameter is deprecated.",
      "dataType" => "String",
      "allowableValues" => "[VOUCHER, COUPON, PRODUCT, MEDIA, EVENT, DEVICE]",
      "paramType" => "query",
    },
    {
      "name" => "offer_type",
      "description" => "Filter results to only return COUPON, VOUCHER, PRODUCT, MEDIA, or EVENT offers",
      "dataType" => "String",
      "allowableValues" => "[VOUCHER, COUPON, PRODUCT, MEDIA, EVENT, DEVICE]",
      "paramType" => "query",
    },
    {
      "name" => "special_offer_type",
      "description" => "Filter results to only return REGULAR_OFFER, ACT_NOW, GET_THERE_NOW offer specials",
      "dataType" => "String",
      "allowableValues" => "[ALL, RESERVABLE, REGULAR_OFFER, ACT_NOW, GET_THERE_NOW, SQOOT, TICKETS, YIPIT]",
      "paramType" => "query",
    },
    {
      "name" => "customer_account_ids",
      "description" => "Filter results by accounts",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "category_ids",
      "description" => "",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "redeemable_start_date",
      "description" => "",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "redeemable_end_date",
      "description" => "",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "sort_field",
      "description" => "Determines what to sort the results by {CREATED, UPDATED, SEARCH_TAGS, ACTIVE, ACTIVATED, EXPIRES, TITLE, SUBTITLE, OFFER_TYPE, SPECIAL_OFFER_TYPE, OFFER_VISIBILITY, CUSTOMER_ID, CUSTOMER_DISPLAY, RETAILER_ID, RETAILER_NAME, RETAILER_LOCATION_ID, RETAILER_LOCATION_NAME, BILLABLE_ENTITY_ID, BILLABLE_ENTITY_NAME, RESPONSIBLE_DISPLAY}",
      "dataType" => "String",
      "allowableValues" => "[ID, CREATED, UPDATED, DELETED, SEARCH_TAGS, ACTIVE, ACTIVATED, EXPIRES, TITLE, SUBTITLE, DETAILS, OFFER_TYPE, SPECIAL_OFFER_TYPE, OFFER_VISIBILITY, REDEEMABLE_START, REDEEMABLE_END, CUSTOMER_ID, CUSTOMER_DISPLAY, RETAILER_ID, RETAILER_NAME, RETAILER_LOCATION_ID, RETAILER_LOCATION_NAME, BILLABLE_ENTITY_ID, BILLABLE_ENTITY_NAME, RESPONSIBLE_DISPLAY]",
      "paramType" => "query",
    },
    {
      "name" => "descending",
      "description" => "Determines whether the results are in descending order",
      "dataType" => "Boolean",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "_i",
      "description" => "This parameter is deprecated.",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "start",
      "description" => "The start index for pagination",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "_l",
      "description" => "This parameter is deprecated.",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "limit",
      "description" => "The limit for pagination",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "active_only",
      "description" => "Determines whether to only return active offer transactions",
      "dataType" => "Boolean",
      "allowableValues" => "",
      "paramType" => "query",
    },
    ]}) do
  cross_origin
  # the guts live here

  {"message" => "yes, it worked"}.to_json
end


MyApp.add_route('GET', '/api/3.18/offer/lists', {
  "resourcePath" => "/Offer",
  "summary" => "Search Offers",
  "nickname" => "search_offers_for_consumer",
  "responseClass" => "OfferListResponse",
  "endpoint" => "/offer/lists",
  "notes" => "Searches for offers as a consumer.",
  "parameters" => [
    {
      "name" => "app_key",
      "description" => "The application key used to identify the application",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "device_id",
      "description" => "The device id for returning account information (i.e. offer transactions made by the user)",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "account_id",
      "description" => "The account id for returning account information (i.e. offer transactions made by the user)",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "latitude",
      "description" => "The latitude of where the search will center at",
      "dataType" => "Float",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "longitude",
      "description" => "The longitude of where the search will center at",
      "dataType" => "Float",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "search_range",
      "description" => "The range of the search",
      "dataType" => "Float",
      "allowableValues" => "",
      "defaultValue" => "5",
      "paramType" => "query",
    },
    {
      "name" => "tags",
      "description" => "Does a full-text search on tags",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "supported_postal_codes",
      "description" => "supported postal codes",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "keyword",
      "description" => "The keyword to filter results by",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "categories",
      "description" => "Comma separate list of category ids",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "filters",
      "description" => "Comma separated list of filter ids",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "offer_types",
      "description" => "Comma separated list of offer types {COUPON, VOUCHER, PRODUCT, MEDIA, EVENT, DEVICE}",
      "dataType" => "String",
      "allowableValues" => "",
      "defaultValue" => "'COUPON, VOUCHER'",
      "paramType" => "query",
    },
    {
      "name" => "type",
      "description" => "The special offer type {ALL, RESERVABLE, REGULAR_OFFER, ACT_NOW, GET_THERE_NOW}",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "sort_field",
      "description" => "The field to sort the result set on:DISTANCE Sort the offers nearest to farthest BUSINESS_NAME Sort the offers alphabetically by location name SHUFFLE Sort the nearest offers randomly USERPREFS accountId must accompany this parameter. Gives the first X recommendations where X equals the parameter maxRecommendations",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "recommend_offer_ids",
      "description" => "Return recommendations based on these offers IDs",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "recommendation_type",
      "description" => "The method to use to gather recommendations: WALLET base relevance on items in users wallets CLICKS base relevance on items users have clicked on BLENDED blend using all methods available",
      "dataType" => "String",
      "allowableValues" => "[WALLET, CLICKS, BLENDED]",
      "paramType" => "query",
    },
    {
      "name" => "location_id",
      "description" => "This parameter is deprecated. The location id",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "retailer_location_ids",
      "description" => "Only return offer locations for the specific retailer locations.",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "offer_id",
      "description" => "Only return offer locations for the specific offer.",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "include_mission",
      "description" => "If true include the mission response as part of the offer. Default is false.",
      "dataType" => "Boolean",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "include_categories",
      "description" => "If true include the category list response as part of the offer. Default is false.",
      "dataType" => "Boolean",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "include_filters",
      "description" => "If true include the filter list response as part of the offer. Default is false.",
      "dataType" => "Boolean",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "include_expired",
      "description" => "If true then ignore the expired dates. Default is false.",
      "dataType" => "Boolean",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "include_favorite",
      "description" => "If true then ignore the favorite. Default is false.",
      "dataType" => "Boolean",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "start",
      "description" => "The start index for pagination",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "limit",
      "description" => "The limit for pagination",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "max_recommendations",
      "description" => "",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "distance_unit",
      "description" => "",
      "dataType" => "String",
      "allowableValues" => "[MILES, KILOMETERS]",
      "paramType" => "query",
    },
    {
      "name" => "closest_offer_only",
      "description" => "This parameter is deprecated. see groupBy. If true then it only returns the offer location for an offer closest to the given lat/lon",
      "dataType" => "Boolean",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "search_expression",
      "description" => "",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "group_by",
      "description" => "groups the results by a certain field. For example, if you want to return the closest offer location of an offer, then pass in groupBy&#x3D;OFFER_ID and sortField&#x3D;DISTANCE (to sort by distance).",
      "dataType" => "String",
      "allowableValues" => "[ID, CREATED, UPDATED, DELETED, SEARCH_TAGS, ACTIVE, OFFER_ID, ACTIVATED, EXPIRES, TITLE, SUBTITLE, DETAILS, OFFER_TYPE, SPECIAL_OFFER_TYPE, OFFER_VISIBILITY, RETAILER_ID, RETAILER_LOCATION_ID, BILLABLE_ENTITY_ID, BILLABLE_ENTITY_NAME, RESPONSIBLE_DISPLAY]",
      "paramType" => "query",
    },
    ]}) do
  cross_origin
  # the guts live here

  {"message" => "yes, it worked"}.to_json
end


MyApp.add_route('GET', '/api/3.18/offer/top', {
  "resourcePath" => "/Offer",
  "summary" => "Get Offers (Top)",
  "nickname" => "top_offer_transactions",
  "responseClass" => "OfferListResponse",
  "endpoint" => "/offer/top",
  "notes" => "Gets the top active offers.",
  "parameters" => [
    {
      "name" => "start",
      "description" => "The index into the record set to start with. Default is 0.",
      "dataType" => "Integer",
      "allowableValues" => "",
      "defaultValue" => "0",
      "paramType" => "query",
    },
    {
      "name" => "limit",
      "description" => "The total number of record to return. Default id 20.",
      "dataType" => "Integer",
      "allowableValues" => "",
      "defaultValue" => "20",
      "paramType" => "query",
    },
    ]}) do
  cross_origin
  # the guts live here

  {"message" => "yes, it worked"}.to_json
end


MyApp.add_route('POST', '/api/3.18/retailer/offer/update', {
  "resourcePath" => "/Offer",
  "summary" => "Update Offer",
  "nickname" => "update_offer",
  "responseClass" => "RetailerOfferResponse",
  "endpoint" => "/retailer/offer/update",
  "notes" => "Update an offer, must provide a current list of retailer locations or the current offer locations will be marked as deleted.",
  "parameters" => [
    {
      "name" => "device_id",
      "description" => "The device id (deviceId or accountId required)",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "account_id",
      "description" => "The account used to perform the update, must have rights to edit the offer (deviceId or accountId required)",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "offer_id",
      "description" => "The offer to update",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "parent_offer_id",
      "description" => "",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "include_offer_locations",
      "description" => "If true return all the offer locations associated with the offer",
      "dataType" => "Boolean",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "retailer_location_ids",
      "description" => "Comma separated list of retailer location ids. This will assign the offer to these retailer locations.",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "offer_locations",
      "description" => "A list of json data that has offer location specific values.",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "tags",
      "description" => "Custom string field for doing full-text searches",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "title",
      "description" => "The title (255 char limit)",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "sub_title",
      "description" => "The sub title (255 char limit)",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "details",
      "description" => "The details",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "sub_details",
      "description" => "A string for custom details (255 char limit)",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "fine_print",
      "description" => "The fine print",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "barcode_type",
      "description" => "The bar code type {NONE, UPC, CODE_128, QR, CUSTOM_MEDIA}",
      "dataType" => "String",
      "allowableValues" => "[NONE, UPC, CODE_128, QR, CUSTOM_MEDIA]",
      "paramType" => "query",
    },
    {
      "name" => "barcode_entry",
      "description" => "The bar code entry string",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "external_redeem_options",
      "description" => "An external identifier. What the identifier will be used for and how it is formatted is up to the frontend developer.",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "external_url",
      "description" => "The clickUrl of the offer",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "external_id",
      "description" => "",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "tickets_reward_type",
      "description" => "The type of ticket to reward, null means default type",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "tickets_reward",
      "description" => "Determines how many tickets are awarded",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "activated",
      "description" => "The date of when the offer will be visible to consumers",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "expires",
      "description" => "The date of when the offer expires",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "no_expiration",
      "description" => "Overrides the expiration date so that the offer does not expire",
      "dataType" => "Boolean",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "available_limit",
      "description" => "The limit of how many times the offer can be used by consumers",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "available_limit_per_user",
      "description" => "The limit of how many times a user can used the same offer",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "added_limit",
      "description" => "The limit of how many times the offer can be added to consumer wallets",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "view_limit",
      "description" => "",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "max_prints",
      "description" => "The maximum number of times the offer can be printed",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "ticket_price_type",
      "description" => "the type of ticket needed to buy the offer",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "ticket_price",
      "description" => "The cost of the offer in tickets",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "full_price",
      "description" => "The retail/full price cost of the offer in real currency",
      "dataType" => "Float",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "discount_price",
      "description" => "The cost of the offer at a discounted price (what the consumer pays)",
      "dataType" => "Float",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "show_remaining",
      "description" => "show remaining offers available",
      "dataType" => "Boolean",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "show_redeemed",
      "description" => "show how many offers have been redeemed",
      "dataType" => "Boolean",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "replaced",
      "description" => "",
      "dataType" => "Boolean",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "featured",
      "description" => "whether the offer is featured or not",
      "dataType" => "Boolean",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "offer_type",
      "description" => "The offer type {VOUCHER, COUPON, PRODUCT, MEDIA, EVENT}",
      "dataType" => "String",
      "allowableValues" => "[VOUCHER, COUPON, PRODUCT, MEDIA, EVENT, DEVICE]",
      "paramType" => "query",
    },
    {
      "name" => "special_offer_type",
      "description" => "The special offer type {ALL, REGULAR_OFFER, ACT_NOW, GET_THERE_NOW}",
      "dataType" => "String",
      "allowableValues" => "[ALL, RESERVABLE, REGULAR_OFFER, ACT_NOW, GET_THERE_NOW, SQOOT, TICKETS, YIPIT]",
      "paramType" => "query",
    },
    {
      "name" => "offer_visibility",
      "description" => "The offer visibility {PUBLIC, REWARDABLE, TRIGGERABLE}",
      "dataType" => "String",
      "allowableValues" => "[PUBLIC, LISTABLE, REWARDABLE, TRIGGERABLE, PRIVATE]",
      "paramType" => "query",
    },
    {
      "name" => "category_ids",
      "description" => "Comma separated list of category ids",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "filter_ids",
      "description" => "Comma separated list of filter ids",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "active",
      "description" => "Sets the active flag",
      "dataType" => "Boolean",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "barcode_asset_id",
      "description" => "The id of the barcode asset",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "image_asset_id",
      "description" => "The id of the an offer asset",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "image_asset_id1",
      "description" => "The id of the an offer asset",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "image_asset_id2",
      "description" => "The id of the an offer asset",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "image_asset_id3",
      "description" => "The id of the an offer asset",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "image_asset_id4",
      "description" => "The id of the an offer asset",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "image_asset_id5",
      "description" => "The id of the an offer asset",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "publisher",
      "description" => "The maker of the item.",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "redeemable_start",
      "description" => "The redeemable start date/time of the offer.",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "redeemable_end",
      "description" => "The redeemable start date/time of the offer.",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "brand",
      "description" => "The brand. OfferType PRODUCT only.",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "product_type",
      "description" => "The product type. OfferType PRODUCT only.",
      "dataType" => "String",
      "allowableValues" => "[APPAREL, APPLIANCES, APPS, ARTS_CRAFTS, AUTOMOTIVE, BABY, BEAUTY, BOOKS, CLASSICAL, COLLECTIBLES, DVD, ELECTRONICS, GIFT_CARDS, GOURMET_FOOD, GROCERY, HEALTH_PERSONAL_CARE, HOME_GARDEN, INDUSTRIAL, JEWELRY, KITCHEN, LAWN_GARDEN, MAGAZINES, MISCELLANEOUS, MUSICAL_INSTRUMENTS, OFFICE_PRODUCTS, OTHER, OUTDOOR_LIVING, PC_HARDWARE, PET_SUPPLIES, SHOES, SOFTWARE, SPORTING_GOODS, TOOLS, TOYS, VIDEO_GAMES, WATCHES, WIRELESS, WIRELESS_ACCESSORIES]",
      "paramType" => "query",
    },
    {
      "name" => "condition_type",
      "description" => "The condition. OfferType PRODUCT only.",
      "dataType" => "String",
      "allowableValues" => "[NEW, USED, REFURBISHED, OTHER]",
      "paramType" => "query",
    },
    {
      "name" => "isbn",
      "description" => "The ISBN id. OfferType PRODUCT only.",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "asin",
      "description" => "The ASIN id. OfferType PRODUCT only.",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "catalog_numbers",
      "description" => "The list of catelog numbers, comma seperated. OfferType PRODUCT only.",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "department",
      "description" => "The department name. The OfferType PRODUCT only.",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "features",
      "description" => "The list of features, comma seperated. OfferType PRODUCT only.",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "minimum_price",
      "description" => "The MAP price. OfferType PRODUCT only.",
      "dataType" => "Float",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "width",
      "description" => "The width of the item. OfferType PRODUCT only.",
      "dataType" => "Float",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "height",
      "description" => "The height of the item. OfferType PRODUCT only.",
      "dataType" => "Float",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "depth",
      "description" => "The depth of the item. OfferType PRODUCT only.",
      "dataType" => "Float",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "weight",
      "description" => "The weight of the item. OfferType PRODUCT only.",
      "dataType" => "Float",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "unit",
      "description" => "The unit of measurement. OfferType PRODUCT only.",
      "dataType" => "String",
      "allowableValues" => "[MILIMETER, CENTIMETER, METER, INCH, FOOT, YARD]",
      "paramType" => "query",
    },
    {
      "name" => "studio",
      "description" => "The studio name. OfferType PRODUCT only.",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "parental_rating",
      "description" => "The parental control rating. OfferType PRODUCT only.",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "publish_date",
      "description" => "The date published. OfferType PRODUCT only.",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "availability_date",
      "description" => "The date available. OfferType PRODUCT only.",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "size_id",
      "description" => "The size Id. OfferType PRODUCT only.",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "listing_id",
      "description" => "The ID of the event listing",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "media_type",
      "description" => "",
      "dataType" => "String",
      "allowableValues" => "[APK, APPLICATION, IMAGE, AUDIO, VIDEO, MULTIPART, BAR_CODE, TEXT, OTHER]",
      "paramType" => "query",
    },
    {
      "name" => "duration",
      "description" => "The total playing time of the media item. OfferType MEDIA only.",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "author",
      "description" => "The created/author of the media item. OfferType MEDIA only.",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "release_date",
      "description" => "The date/time of when the media item was originally released. OfferType MEDIA only.",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "collection_ids",
      "description" => "",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "reboot_time_hour",
      "description" => "The reboot hour time ranging from 0 to 23",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "reboot_time_minute",
      "description" => "The reboot minute time ranging from 0 to 59",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "idle_timeout_in_second",
      "description" => "If the device is idle for idleTimeoutInSecond then the device should timeout",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "serial_number",
      "description" => "The serial number on the device",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "udid",
      "description" => "The unique device id for the device",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "device_type",
      "description" => "The type of the device, for example: \&quot;Kiosk\&quot;, \&quot;Beacon\&quot;.",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "device_power",
      "description" => "RSSI reading at 1 meter from device (-10 to -140)",
      "dataType" => "Float",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "device_interference",
      "description" => "",
      "dataType" => "Float",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "availability",
      "description" => "",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "availability_summary",
      "description" => "",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    ]}) do
  cross_origin
  # the guts live here

  {"message" => "yes, it worked"}.to_json
end


MyApp.add_route('POST', '/api/3.18/retailer/offer/status', {
  "resourcePath" => "/Offer",
  "summary" => "Activate Offer",
  "nickname" => "update_offer_status",
  "responseClass" => "SirqulResponse",
  "endpoint" => "/retailer/offer/status",
  "notes" => "Sets the activated date on offers. This will make offers visible for consumers.",
  "parameters" => [
    {
      "name" => "device_id",
      "description" => "The device id (deviceId or accountId required)",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "account_id",
      "description" => "The account used to perform the activation, must have rights to edit the offer.",
      "dataType" => "Integer",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "offer_ids",
      "description" => "Comma separated list of offer ids",
      "dataType" => "String",
      "allowableValues" => "",
      "paramType" => "query",
    },
    {
      "name" => "active",
      "description" => "Determines whether to make the offer active as well",
      "dataType" => "Boolean",
      "allowableValues" => "",
      "paramType" => "query",
    },
    ]}) do
  cross_origin
  # the guts live here

  {"message" => "yes, it worked"}.to_json
end

