/**
 * 
 * Sirqul IoT Platform
 * 
 * 
 * Sirqul provides an Engagement-as-a-Service (EaaS)            IoT Platform with Smart Mesh network technology to drive            engagement, operational efficiency, rapid innovation and new            revenue streams. Please visit https://dev.sirqul.com/ for more            documents, examples, and sample applications.<?php $a = htmlspecialchars($_GET['appKey']);$b = htmlspecialchars($_GET['appRestKey']);?>
 * 
 * Version: 3.16
 * Contact: info@sirqul.com
 * Generated by OpenAPI Generator: https://openapi-generator.tech
 */

// package openapi3graphql-server

// game_api

export default {
    Query: {

        // @return GameResponse
        GetGame: ($accountId, $gameId, $includeGameData) => {
            return {
                "accountId": "789",
                "gameId": "789",
                "includeGameData": "true"
            };
        },

        // @return GameResponse
        SearchGames: ($accountId, $appKey, $start, $limit, $keyword, $appVersion, $includeGameData, $includeInactive) => {
            return {
                "accountId": "789",
                "appKey": "appKey_example",
                "start": "56",
                "limit": "56",
                "keyword": "keyword_example",
                "appVersion": "appVersion_example",
                "includeGameData": "true",
                "includeInactive": "true"
            };
        },

    },

    Mutation: {

        // @return GameResponse
        CreateGame: ($accountId, $appKey, $title, $description, $metaData, $packIds, $includeGameData) => {
            return {
                "accountId": "789",
                "appKey": "appKey_example",
                "title": "title_example",
                "description": "description_example",
                "metaData": "metaData_example",
                "packIds": "packIds_example",
                "includeGameData": "true"
            };
        },

        // @return SirqulResponse
        DeleteGame: ($accountId, $gameId) => {
            return {
                "accountId": "789",
                "gameId": "789"
            };
        },

        // @return GameResponse
        UpdateGame: ($accountId, $gameId, $appKey, $title, $description, $metaData, $packIds, $includeGameData) => {
            return {
                "accountId": "789",
                "gameId": "789",
                "appKey": "appKey_example",
                "title": "title_example",
                "description": "description_example",
                "metaData": "metaData_example",
                "packIds": "packIds_example",
                "includeGameData": "true"
            };
        },

    }
}