from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.date_time_zone import DateTimeZone
from openapi_server import util

from openapi_server.models.date_time_zone import DateTimeZone  # noqa: E501

class Chronology(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, zone=None):  # noqa: E501
        """Chronology - a model defined in OpenAPI

        :param zone: The zone of this Chronology.  # noqa: E501
        :type zone: DateTimeZone
        """
        self.openapi_types = {
            'zone': DateTimeZone
        }

        self.attribute_map = {
            'zone': 'zone'
        }

        self._zone = zone

    @classmethod
    def from_dict(cls, dikt) -> 'Chronology':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Chronology of this Chronology.  # noqa: E501
        :rtype: Chronology
        """
        return util.deserialize_model(dikt, cls)

    @property
    def zone(self) -> DateTimeZone:
        """Gets the zone of this Chronology.


        :return: The zone of this Chronology.
        :rtype: DateTimeZone
        """
        return self._zone

    @zone.setter
    def zone(self, zone: DateTimeZone):
        """Sets the zone of this Chronology.


        :param zone: The zone of this Chronology.
        :type zone: DateTimeZone
        """

        self._zone = zone
