from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.asset_short_response import AssetShortResponse
from openapi_server import util

from openapi_server.models.asset_short_response import AssetShortResponse  # noqa: E501

class PlacementResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, placement_id=None, name=None, description=None, size=None, height=None, width=None, refresh_interval=None, app_name=None, app_key=None, active=None, default_image=None):  # noqa: E501
        """PlacementResponse - a model defined in OpenAPI

        :param placement_id: The placement_id of this PlacementResponse.  # noqa: E501
        :type placement_id: int
        :param name: The name of this PlacementResponse.  # noqa: E501
        :type name: str
        :param description: The description of this PlacementResponse.  # noqa: E501
        :type description: str
        :param size: The size of this PlacementResponse.  # noqa: E501
        :type size: str
        :param height: The height of this PlacementResponse.  # noqa: E501
        :type height: int
        :param width: The width of this PlacementResponse.  # noqa: E501
        :type width: int
        :param refresh_interval: The refresh_interval of this PlacementResponse.  # noqa: E501
        :type refresh_interval: int
        :param app_name: The app_name of this PlacementResponse.  # noqa: E501
        :type app_name: str
        :param app_key: The app_key of this PlacementResponse.  # noqa: E501
        :type app_key: str
        :param active: The active of this PlacementResponse.  # noqa: E501
        :type active: bool
        :param default_image: The default_image of this PlacementResponse.  # noqa: E501
        :type default_image: AssetShortResponse
        """
        self.openapi_types = {
            'placement_id': int,
            'name': str,
            'description': str,
            'size': str,
            'height': int,
            'width': int,
            'refresh_interval': int,
            'app_name': str,
            'app_key': str,
            'active': bool,
            'default_image': AssetShortResponse
        }

        self.attribute_map = {
            'placement_id': 'placementId',
            'name': 'name',
            'description': 'description',
            'size': 'size',
            'height': 'height',
            'width': 'width',
            'refresh_interval': 'refreshInterval',
            'app_name': 'appName',
            'app_key': 'appKey',
            'active': 'active',
            'default_image': 'defaultImage'
        }

        self._placement_id = placement_id
        self._name = name
        self._description = description
        self._size = size
        self._height = height
        self._width = width
        self._refresh_interval = refresh_interval
        self._app_name = app_name
        self._app_key = app_key
        self._active = active
        self._default_image = default_image

    @classmethod
    def from_dict(cls, dikt) -> 'PlacementResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PlacementResponse of this PlacementResponse.  # noqa: E501
        :rtype: PlacementResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def placement_id(self) -> int:
        """Gets the placement_id of this PlacementResponse.


        :return: The placement_id of this PlacementResponse.
        :rtype: int
        """
        return self._placement_id

    @placement_id.setter
    def placement_id(self, placement_id: int):
        """Sets the placement_id of this PlacementResponse.


        :param placement_id: The placement_id of this PlacementResponse.
        :type placement_id: int
        """

        self._placement_id = placement_id

    @property
    def name(self) -> str:
        """Gets the name of this PlacementResponse.


        :return: The name of this PlacementResponse.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this PlacementResponse.


        :param name: The name of this PlacementResponse.
        :type name: str
        """

        self._name = name

    @property
    def description(self) -> str:
        """Gets the description of this PlacementResponse.


        :return: The description of this PlacementResponse.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this PlacementResponse.


        :param description: The description of this PlacementResponse.
        :type description: str
        """

        self._description = description

    @property
    def size(self) -> str:
        """Gets the size of this PlacementResponse.


        :return: The size of this PlacementResponse.
        :rtype: str
        """
        return self._size

    @size.setter
    def size(self, size: str):
        """Sets the size of this PlacementResponse.


        :param size: The size of this PlacementResponse.
        :type size: str
        """
        allowed_values = ["CONFIG", "BANNER", "LEADERBOARD", "SKYSCRAPER", "VIDEO", "ZIP", "INTERSTITIAL", "CUSTOM1", "CUSTOM2", "CUSTOM3", "CUSTOM4", "CUSTOM5", "CUSTOM6", "CUSTOM7", "CUSTOM8", "CUSTOM9", "CUSTOM10"]  # noqa: E501
        if size not in allowed_values:
            raise ValueError(
                "Invalid value for `size` ({0}), must be one of {1}"
                .format(size, allowed_values)
            )

        self._size = size

    @property
    def height(self) -> int:
        """Gets the height of this PlacementResponse.


        :return: The height of this PlacementResponse.
        :rtype: int
        """
        return self._height

    @height.setter
    def height(self, height: int):
        """Sets the height of this PlacementResponse.


        :param height: The height of this PlacementResponse.
        :type height: int
        """

        self._height = height

    @property
    def width(self) -> int:
        """Gets the width of this PlacementResponse.


        :return: The width of this PlacementResponse.
        :rtype: int
        """
        return self._width

    @width.setter
    def width(self, width: int):
        """Sets the width of this PlacementResponse.


        :param width: The width of this PlacementResponse.
        :type width: int
        """

        self._width = width

    @property
    def refresh_interval(self) -> int:
        """Gets the refresh_interval of this PlacementResponse.


        :return: The refresh_interval of this PlacementResponse.
        :rtype: int
        """
        return self._refresh_interval

    @refresh_interval.setter
    def refresh_interval(self, refresh_interval: int):
        """Sets the refresh_interval of this PlacementResponse.


        :param refresh_interval: The refresh_interval of this PlacementResponse.
        :type refresh_interval: int
        """

        self._refresh_interval = refresh_interval

    @property
    def app_name(self) -> str:
        """Gets the app_name of this PlacementResponse.


        :return: The app_name of this PlacementResponse.
        :rtype: str
        """
        return self._app_name

    @app_name.setter
    def app_name(self, app_name: str):
        """Sets the app_name of this PlacementResponse.


        :param app_name: The app_name of this PlacementResponse.
        :type app_name: str
        """

        self._app_name = app_name

    @property
    def app_key(self) -> str:
        """Gets the app_key of this PlacementResponse.


        :return: The app_key of this PlacementResponse.
        :rtype: str
        """
        return self._app_key

    @app_key.setter
    def app_key(self, app_key: str):
        """Sets the app_key of this PlacementResponse.


        :param app_key: The app_key of this PlacementResponse.
        :type app_key: str
        """

        self._app_key = app_key

    @property
    def active(self) -> bool:
        """Gets the active of this PlacementResponse.


        :return: The active of this PlacementResponse.
        :rtype: bool
        """
        return self._active

    @active.setter
    def active(self, active: bool):
        """Sets the active of this PlacementResponse.


        :param active: The active of this PlacementResponse.
        :type active: bool
        """

        self._active = active

    @property
    def default_image(self) -> AssetShortResponse:
        """Gets the default_image of this PlacementResponse.


        :return: The default_image of this PlacementResponse.
        :rtype: AssetShortResponse
        """
        return self._default_image

    @default_image.setter
    def default_image(self, default_image: AssetShortResponse):
        """Sets the default_image of this PlacementResponse.


        :param default_image: The default_image of this PlacementResponse.
        :type default_image: AssetShortResponse
        """

        self._default_image = default_image
