from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.asset_short_response import AssetShortResponse
from openapi_server.models.contact_info_response import ContactInfoResponse
from openapi_server import util

from openapi_server.models.asset_short_response import AssetShortResponse  # noqa: E501
from openapi_server.models.contact_info_response import ContactInfoResponse  # noqa: E501

class RetailerShortResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, retailer_id=None, name=None, facebook_url=None, twitter_url=None, active=None, contact=None, logo=None, picture1=None, picture2=None, latitude=None, longitude=None, visibility=None):  # noqa: E501
        """RetailerShortResponse - a model defined in OpenAPI

        :param retailer_id: The retailer_id of this RetailerShortResponse.  # noqa: E501
        :type retailer_id: int
        :param name: The name of this RetailerShortResponse.  # noqa: E501
        :type name: str
        :param facebook_url: The facebook_url of this RetailerShortResponse.  # noqa: E501
        :type facebook_url: str
        :param twitter_url: The twitter_url of this RetailerShortResponse.  # noqa: E501
        :type twitter_url: str
        :param active: The active of this RetailerShortResponse.  # noqa: E501
        :type active: bool
        :param contact: The contact of this RetailerShortResponse.  # noqa: E501
        :type contact: ContactInfoResponse
        :param logo: The logo of this RetailerShortResponse.  # noqa: E501
        :type logo: AssetShortResponse
        :param picture1: The picture1 of this RetailerShortResponse.  # noqa: E501
        :type picture1: AssetShortResponse
        :param picture2: The picture2 of this RetailerShortResponse.  # noqa: E501
        :type picture2: AssetShortResponse
        :param latitude: The latitude of this RetailerShortResponse.  # noqa: E501
        :type latitude: float
        :param longitude: The longitude of this RetailerShortResponse.  # noqa: E501
        :type longitude: float
        :param visibility: The visibility of this RetailerShortResponse.  # noqa: E501
        :type visibility: str
        """
        self.openapi_types = {
            'retailer_id': int,
            'name': str,
            'facebook_url': str,
            'twitter_url': str,
            'active': bool,
            'contact': ContactInfoResponse,
            'logo': AssetShortResponse,
            'picture1': AssetShortResponse,
            'picture2': AssetShortResponse,
            'latitude': float,
            'longitude': float,
            'visibility': str
        }

        self.attribute_map = {
            'retailer_id': 'retailerId',
            'name': 'name',
            'facebook_url': 'facebookUrl',
            'twitter_url': 'twitterUrl',
            'active': 'active',
            'contact': 'contact',
            'logo': 'logo',
            'picture1': 'picture1',
            'picture2': 'picture2',
            'latitude': 'latitude',
            'longitude': 'longitude',
            'visibility': 'visibility'
        }

        self._retailer_id = retailer_id
        self._name = name
        self._facebook_url = facebook_url
        self._twitter_url = twitter_url
        self._active = active
        self._contact = contact
        self._logo = logo
        self._picture1 = picture1
        self._picture2 = picture2
        self._latitude = latitude
        self._longitude = longitude
        self._visibility = visibility

    @classmethod
    def from_dict(cls, dikt) -> 'RetailerShortResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RetailerShortResponse of this RetailerShortResponse.  # noqa: E501
        :rtype: RetailerShortResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def retailer_id(self) -> int:
        """Gets the retailer_id of this RetailerShortResponse.


        :return: The retailer_id of this RetailerShortResponse.
        :rtype: int
        """
        return self._retailer_id

    @retailer_id.setter
    def retailer_id(self, retailer_id: int):
        """Sets the retailer_id of this RetailerShortResponse.


        :param retailer_id: The retailer_id of this RetailerShortResponse.
        :type retailer_id: int
        """

        self._retailer_id = retailer_id

    @property
    def name(self) -> str:
        """Gets the name of this RetailerShortResponse.


        :return: The name of this RetailerShortResponse.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this RetailerShortResponse.


        :param name: The name of this RetailerShortResponse.
        :type name: str
        """

        self._name = name

    @property
    def facebook_url(self) -> str:
        """Gets the facebook_url of this RetailerShortResponse.


        :return: The facebook_url of this RetailerShortResponse.
        :rtype: str
        """
        return self._facebook_url

    @facebook_url.setter
    def facebook_url(self, facebook_url: str):
        """Sets the facebook_url of this RetailerShortResponse.


        :param facebook_url: The facebook_url of this RetailerShortResponse.
        :type facebook_url: str
        """

        self._facebook_url = facebook_url

    @property
    def twitter_url(self) -> str:
        """Gets the twitter_url of this RetailerShortResponse.


        :return: The twitter_url of this RetailerShortResponse.
        :rtype: str
        """
        return self._twitter_url

    @twitter_url.setter
    def twitter_url(self, twitter_url: str):
        """Sets the twitter_url of this RetailerShortResponse.


        :param twitter_url: The twitter_url of this RetailerShortResponse.
        :type twitter_url: str
        """

        self._twitter_url = twitter_url

    @property
    def active(self) -> bool:
        """Gets the active of this RetailerShortResponse.


        :return: The active of this RetailerShortResponse.
        :rtype: bool
        """
        return self._active

    @active.setter
    def active(self, active: bool):
        """Sets the active of this RetailerShortResponse.


        :param active: The active of this RetailerShortResponse.
        :type active: bool
        """

        self._active = active

    @property
    def contact(self) -> ContactInfoResponse:
        """Gets the contact of this RetailerShortResponse.


        :return: The contact of this RetailerShortResponse.
        :rtype: ContactInfoResponse
        """
        return self._contact

    @contact.setter
    def contact(self, contact: ContactInfoResponse):
        """Sets the contact of this RetailerShortResponse.


        :param contact: The contact of this RetailerShortResponse.
        :type contact: ContactInfoResponse
        """

        self._contact = contact

    @property
    def logo(self) -> AssetShortResponse:
        """Gets the logo of this RetailerShortResponse.


        :return: The logo of this RetailerShortResponse.
        :rtype: AssetShortResponse
        """
        return self._logo

    @logo.setter
    def logo(self, logo: AssetShortResponse):
        """Sets the logo of this RetailerShortResponse.


        :param logo: The logo of this RetailerShortResponse.
        :type logo: AssetShortResponse
        """

        self._logo = logo

    @property
    def picture1(self) -> AssetShortResponse:
        """Gets the picture1 of this RetailerShortResponse.


        :return: The picture1 of this RetailerShortResponse.
        :rtype: AssetShortResponse
        """
        return self._picture1

    @picture1.setter
    def picture1(self, picture1: AssetShortResponse):
        """Sets the picture1 of this RetailerShortResponse.


        :param picture1: The picture1 of this RetailerShortResponse.
        :type picture1: AssetShortResponse
        """

        self._picture1 = picture1

    @property
    def picture2(self) -> AssetShortResponse:
        """Gets the picture2 of this RetailerShortResponse.


        :return: The picture2 of this RetailerShortResponse.
        :rtype: AssetShortResponse
        """
        return self._picture2

    @picture2.setter
    def picture2(self, picture2: AssetShortResponse):
        """Sets the picture2 of this RetailerShortResponse.


        :param picture2: The picture2 of this RetailerShortResponse.
        :type picture2: AssetShortResponse
        """

        self._picture2 = picture2

    @property
    def latitude(self) -> float:
        """Gets the latitude of this RetailerShortResponse.


        :return: The latitude of this RetailerShortResponse.
        :rtype: float
        """
        return self._latitude

    @latitude.setter
    def latitude(self, latitude: float):
        """Sets the latitude of this RetailerShortResponse.


        :param latitude: The latitude of this RetailerShortResponse.
        :type latitude: float
        """

        self._latitude = latitude

    @property
    def longitude(self) -> float:
        """Gets the longitude of this RetailerShortResponse.


        :return: The longitude of this RetailerShortResponse.
        :rtype: float
        """
        return self._longitude

    @longitude.setter
    def longitude(self, longitude: float):
        """Sets the longitude of this RetailerShortResponse.


        :param longitude: The longitude of this RetailerShortResponse.
        :type longitude: float
        """

        self._longitude = longitude

    @property
    def visibility(self) -> str:
        """Gets the visibility of this RetailerShortResponse.


        :return: The visibility of this RetailerShortResponse.
        :rtype: str
        """
        return self._visibility

    @visibility.setter
    def visibility(self, visibility: str):
        """Sets the visibility of this RetailerShortResponse.


        :param visibility: The visibility of this RetailerShortResponse.
        :type visibility: str
        """

        self._visibility = visibility
