from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.asset import Asset
from openapi_server import util

from openapi_server.models.asset import Asset  # noqa: E501

class Tutorial(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, active=None, valid=None, name=None, description=None, alignment=None, image=None, order_index=None, tutorial_object_type=None):  # noqa: E501
        """Tutorial - a model defined in OpenAPI

        :param id: The id of this Tutorial.  # noqa: E501
        :type id: int
        :param active: The active of this Tutorial.  # noqa: E501
        :type active: bool
        :param valid: The valid of this Tutorial.  # noqa: E501
        :type valid: bool
        :param name: The name of this Tutorial.  # noqa: E501
        :type name: str
        :param description: The description of this Tutorial.  # noqa: E501
        :type description: str
        :param alignment: The alignment of this Tutorial.  # noqa: E501
        :type alignment: str
        :param image: The image of this Tutorial.  # noqa: E501
        :type image: Asset
        :param order_index: The order_index of this Tutorial.  # noqa: E501
        :type order_index: int
        :param tutorial_object_type: The tutorial_object_type of this Tutorial.  # noqa: E501
        :type tutorial_object_type: str
        """
        self.openapi_types = {
            'id': int,
            'active': bool,
            'valid': bool,
            'name': str,
            'description': str,
            'alignment': str,
            'image': Asset,
            'order_index': int,
            'tutorial_object_type': str
        }

        self.attribute_map = {
            'id': 'id',
            'active': 'active',
            'valid': 'valid',
            'name': 'name',
            'description': 'description',
            'alignment': 'alignment',
            'image': 'image',
            'order_index': 'orderIndex',
            'tutorial_object_type': 'tutorialObjectType'
        }

        self._id = id
        self._active = active
        self._valid = valid
        self._name = name
        self._description = description
        self._alignment = alignment
        self._image = image
        self._order_index = order_index
        self._tutorial_object_type = tutorial_object_type

    @classmethod
    def from_dict(cls, dikt) -> 'Tutorial':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Tutorial of this Tutorial.  # noqa: E501
        :rtype: Tutorial
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this Tutorial.


        :return: The id of this Tutorial.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this Tutorial.


        :param id: The id of this Tutorial.
        :type id: int
        """

        self._id = id

    @property
    def active(self) -> bool:
        """Gets the active of this Tutorial.


        :return: The active of this Tutorial.
        :rtype: bool
        """
        return self._active

    @active.setter
    def active(self, active: bool):
        """Sets the active of this Tutorial.


        :param active: The active of this Tutorial.
        :type active: bool
        """

        self._active = active

    @property
    def valid(self) -> bool:
        """Gets the valid of this Tutorial.


        :return: The valid of this Tutorial.
        :rtype: bool
        """
        return self._valid

    @valid.setter
    def valid(self, valid: bool):
        """Sets the valid of this Tutorial.


        :param valid: The valid of this Tutorial.
        :type valid: bool
        """

        self._valid = valid

    @property
    def name(self) -> str:
        """Gets the name of this Tutorial.


        :return: The name of this Tutorial.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Tutorial.


        :param name: The name of this Tutorial.
        :type name: str
        """

        self._name = name

    @property
    def description(self) -> str:
        """Gets the description of this Tutorial.


        :return: The description of this Tutorial.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this Tutorial.


        :param description: The description of this Tutorial.
        :type description: str
        """

        self._description = description

    @property
    def alignment(self) -> str:
        """Gets the alignment of this Tutorial.


        :return: The alignment of this Tutorial.
        :rtype: str
        """
        return self._alignment

    @alignment.setter
    def alignment(self, alignment: str):
        """Sets the alignment of this Tutorial.


        :param alignment: The alignment of this Tutorial.
        :type alignment: str
        """
        allowed_values = ["NONE", "IMAGE_ABOVE", "IMAGE_BELOW", "IMAGE_LEFT", "IMAGE_RIGHT", "IMAGE_ONLY", "TEXT_ONLY"]  # noqa: E501
        if alignment not in allowed_values:
            raise ValueError(
                "Invalid value for `alignment` ({0}), must be one of {1}"
                .format(alignment, allowed_values)
            )

        self._alignment = alignment

    @property
    def image(self) -> Asset:
        """Gets the image of this Tutorial.


        :return: The image of this Tutorial.
        :rtype: Asset
        """
        return self._image

    @image.setter
    def image(self, image: Asset):
        """Sets the image of this Tutorial.


        :param image: The image of this Tutorial.
        :type image: Asset
        """

        self._image = image

    @property
    def order_index(self) -> int:
        """Gets the order_index of this Tutorial.


        :return: The order_index of this Tutorial.
        :rtype: int
        """
        return self._order_index

    @order_index.setter
    def order_index(self, order_index: int):
        """Sets the order_index of this Tutorial.


        :param order_index: The order_index of this Tutorial.
        :type order_index: int
        """

        self._order_index = order_index

    @property
    def tutorial_object_type(self) -> str:
        """Gets the tutorial_object_type of this Tutorial.


        :return: The tutorial_object_type of this Tutorial.
        :rtype: str
        """
        return self._tutorial_object_type

    @tutorial_object_type.setter
    def tutorial_object_type(self, tutorial_object_type: str):
        """Sets the tutorial_object_type of this Tutorial.


        :param tutorial_object_type: The tutorial_object_type of this Tutorial.
        :type tutorial_object_type: str
        """
        allowed_values = ["GAME_OBJECT", "GAME_LEVEL", "PACK", "GAME", "MISSION", "PROFILE", "APPLICATION", "TICKETS", "ASSET", "CUSTOM"]  # noqa: E501
        if tutorial_object_type not in allowed_values:
            raise ValueError(
                "Invalid value for `tutorial_object_type` ({0}), must be one of {1}"
                .format(tutorial_object_type, allowed_values)
            )

        self._tutorial_object_type = tutorial_object_type
