<?php declare(strict_types=1);

/**
 * Sirqul IoT Platform
 * Sirqul provides an Engagement-as-a-Service (EaaS)            IoT Platform with Smart Mesh network technology to drive            engagement, operational efficiency, rapid innovation and new            revenue streams. Please visit https://dev.sirqul.com/ for more            documents, examples, and sample applications.<?php $a = htmlspecialchars($_GET['appKey']);$b = htmlspecialchars($_GET['appRestKey']);?>
 * PHP version 8.1
 *
 * The version of the OpenAPI document: 3.16
 * Contact: info@sirqul.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * Source files are located at:
 *
 * > https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/php-laravel/
 */


namespace OpenAPI\Server\Api;


interface AMQPApiInterface {


    /**
     * Operation consumerCreate
     *
     * Create Consumer
     * @param string $appKey
     * @param string $name
     * @param string $hostname
     * @param string $username
     * @param string $password
     * @param string $dataMapping
     * @param null | string $deviceId
     * @param null | int $accountId
     * @param null | int $port
     * @param null | string $virtualHost
     * @param null | string $exchanger
     * @param null | string $exchangerType
     * @param null | int $workers
     * @param null | bool $useSSL
     * @return \OpenAPI\Server\Model\QueueResponse
     */
    public function consumerCreate(
            string $appKey,
            string $name,
            string $hostname,
            string $username,
            string $password,
            string $dataMapping,
            ?string $deviceId,
            ?int $accountId,
            ?int $port,
            ?string $virtualHost,
            ?string $exchanger,
            ?string $exchangerType,
            ?int $workers,
            ?bool $useSSL,
    ):
        \OpenAPI\Server\Model\QueueResponse
    ;


    /**
     * Operation consumerUpdate
     *
     * Update Consumer
     * @param string $appKey
     * @param int $queueId
     * @param string $dataMapping
     * @param null | string $deviceId
     * @param null | int $accountId
     * @param null | bool $useSSL
     * @return \OpenAPI\Server\Model\QueueResponse
     */
    public function consumerUpdate(
            string $appKey,
            int $queueId,
            string $dataMapping,
            ?string $deviceId,
            ?int $accountId,
            ?bool $useSSL,
    ):
        \OpenAPI\Server\Model\QueueResponse
    ;


    /**
     * Operation queueCreate
     *
     * Create Queue
     * @param string $appKey
     * @param string $name
     * @param null | string $deviceId
     * @param null | int $accountId
     * @param null | int $workers
     * @param null | string $analyticTags
     * @param null | string $hostname
     * @param null | int $port
     * @param null | string $username
     * @param null | string $password
     * @param null | string $virtualHost
     * @param null | bool $useSSL
     * @return \OpenAPI\Server\Model\QueueResponse
     */
    public function queueCreate(
            string $appKey,
            string $name,
            ?string $deviceId,
            ?int $accountId,
            ?int $workers,
            ?string $analyticTags,
            ?string $hostname,
            ?int $port,
            ?string $username,
            ?string $password,
            ?string $virtualHost,
            ?bool $useSSL,
    ):
        \OpenAPI\Server\Model\QueueResponse
    ;


    /**
     * Operation queueDelete
     *
     * Delete Queue
     * @param int $queueId
     * @param null | string $deviceId
     * @param null | int $accountId
     * @return \OpenAPI\Server\Model\SirqulResponse
     */
    public function queueDelete(
            int $queueId,
            ?string $deviceId,
            ?int $accountId,
    ):
        \OpenAPI\Server\Model\SirqulResponse
    ;


    /**
     * Operation queueGet
     *
     * Get Queue
     * @param null | string $deviceId
     * @param null | int $accountId
     * @param null | int $queueId
     * @param null | string $appKey
     * @param null | string $name
     * @param null | string $hostname
     * @param null | string $virtualHost
     * @return \OpenAPI\Server\Model\QueueResponse
     */
    public function queueGet(
            ?string $deviceId,
            ?int $accountId,
            ?int $queueId,
            ?string $appKey,
            ?string $name,
            ?string $hostname,
            ?string $virtualHost,
    ):
        \OpenAPI\Server\Model\QueueResponse
    ;


    /**
     * Operation queuePublish
     *
     * Publish Queue
     * @param string $message
     * @param null | int $queueId
     * @param null | string $appKey
     * @param null | string $name
     * @param null | string $hostname
     * @param null | string $virtualHost
     * @return \OpenAPI\Server\Model\SirqulResponse
     */
    public function queuePublish(
            string $message,
            ?int $queueId,
            ?string $appKey,
            ?string $name,
            ?string $hostname,
            ?string $virtualHost,
    ):
        \OpenAPI\Server\Model\SirqulResponse
    ;


    /**
     * Operation queueSearch
     *
     * Search Queue
     * @param null | int $queueId
     * @param null | string $deviceId
     * @param null | int $accountId
     * @param null | string $name
     * @param null | int $start
     * @param null | int $limit
     * @return \OpenAPI\Server\Model\QueueResponse
     */
    public function queueSearch(
            ?int $queueId,
            ?string $deviceId,
            ?int $accountId,
            ?string $name,
            ?int $start,
            ?int $limit,
    ):
        \OpenAPI\Server\Model\QueueResponse
    ;


    /**
     * Operation queueUpdate
     *
     * Update Queue
     * @param int $queueId
     * @param null | string $deviceId
     * @param null | int $accountId
     * @param null | string $appKey
     * @param null | int $workers
     * @param null | string $analyticTags
     * @param null | string $hostname
     * @param null | int $port
     * @param null | string $username
     * @param null | string $password
     * @param null | string $virtualHost
     * @param null | bool $useSSL
     * @return \OpenAPI\Server\Model\QueueResponse
     */
    public function queueUpdate(
            int $queueId,
            ?string $deviceId,
            ?int $accountId,
            ?string $appKey,
            ?int $workers,
            ?string $analyticTags,
            ?string $hostname,
            ?int $port,
            ?string $username,
            ?string $password,
            ?string $virtualHost,
            ?bool $useSSL,
    ):
        \OpenAPI\Server\Model\QueueResponse
    ;

}
