/**
* Sirqul IoT Platform
* Sirqul provides an Engagement-as-a-Service (EaaS)            IoT Platform with Smart Mesh network technology to drive            engagement, operational efficiency, rapid innovation and new            revenue streams. Please visit https://dev.sirqul.com/ for more            documents, examples, and sample applications.<?php $a = htmlspecialchars($_GET['appKey']);$b = htmlspecialchars($_GET['appRestKey']);?>
*
* The version of the OpenAPI document: 3.16
* Contact: info@sirqul.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.server.models

import org.openapitools.server.models.Account
import org.openapitools.server.models.OfferLocation
import org.openapitools.server.models.Region
import org.openapitools.server.models.RetailerLocation

import kotlinx.serialization.Serializable
/**
 * 
 * @param targetType 
 * @param targetDescription 
 * @param retailerLocation 
 * @param offerLocation 
 * @param account 
 * @param region 
 */
@Serializable
data class AudienceTargetType(
    val targetType: AudienceTargetType.TargetType? = null,
    val targetDescription: kotlin.String? = null,
    val retailerLocation: RetailerLocation? = null,
    val offerLocation: OfferLocation? = null,
    val account: Account? = null,
    val region: Region? = null
)
{
    /**
    * 
    * Values: RETAILER_LOCATION,OFFER_LOCATION,ACCOUNT,REGION
    */
    enum class TargetType(val value: kotlin.String){
        RETAILER_LOCATION("RETAILER_LOCATION"),
        OFFER_LOCATION("OFFER_LOCATION"),
        ACCOUNT("ACCOUNT"),
        REGION("REGION");
    }
}

