/**
* Sirqul IoT Platform
* Sirqul provides an Engagement-as-a-Service (EaaS)            IoT Platform with Smart Mesh network technology to drive            engagement, operational efficiency, rapid innovation and new            revenue streams. Please visit https://dev.sirqul.com/ for more            documents, examples, and sample applications.<?php $a = htmlspecialchars($_GET['appKey']);$b = htmlspecialchars($_GET['appRestKey']);?>
*
* The version of the OpenAPI document: 3.16
* Contact: info@sirqul.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.server.models

import org.openapitools.server.models.Account
import org.openapitools.server.models.Asset
import org.openapitools.server.models.Assignment
import org.openapitools.server.models.Building
import org.openapitools.server.models.Category
import org.openapitools.server.models.Filter
import org.openapitools.server.models.Note
import org.openapitools.server.models.OfferLocation
import org.openapitools.server.models.Region
import org.openapitools.server.models.Retailer
import org.openapitools.server.models.RetailerProfile

import kotlinx.serialization.Serializable
/**
 * 
 * @param id 
 * @param active 
 * @param valid 
 * @param latitude 
 * @param longitude 
 * @param locationDescription 
 * @param categories 
 * @param filters 
 * @param offerLocations 
 * @param logo 
 * @param picture1 
 * @param picture2 
 * @param qrCode 
 * @param name 
 * @param locationId 
 * @param code 
 * @param retailer 
 * @param assignments 
 * @param currentAssignment 
 * @param profile 
 * @param regions 
 * @param offerPrintKeyPrefix 
 * @param administrators 
 * @param sqootId 
 * @param yipitId 
 * @param locationToken 
 * @param building 
 * @param notes 
 * @param noteCount 
 * @param searchIndexUpdated 
 * @param inSearchIndex 
 * @param favoriteCount 
 * @param hasRatings 
 * @param googlePlaceId 
 * @param yelpId 
 * @param display 
 * @param appKey 
 * @param categoryTree 
 * @param filterTree 
 * @param addressDisplay 
 * @param mapQuery 
 * @param sortName 
 * @param fullDisplay 
 * @param hasOffers 
 * @param billableId 
 * @param subType 
 * @param contentName 
 * @param owner 
 * @param secondaryType 
 * @param locationAddress 
 * @param validOfferLocationIds 
 */
@Serializable
data class RetailerLocation(
    val id: kotlin.Long? = null,
    val active: kotlin.Boolean? = null,
    val valid: kotlin.Boolean? = null,
    val latitude: kotlin.Double? = null,
    val longitude: kotlin.Double? = null,
    val locationDescription: kotlin.String? = null,
    val categories: kotlin.collections.List<Category>? = null,
    val filters: kotlin.collections.List<Filter>? = null,
    val offerLocations: kotlin.collections.List<OfferLocation>? = null,
    val logo: Asset? = null,
    val picture1: Asset? = null,
    val picture2: Asset? = null,
    val qrCode: Asset? = null,
    val name: kotlin.String? = null,
    val locationId: kotlin.String? = null,
    val code: kotlin.String? = null,
    val retailer: Retailer? = null,
    val assignments: kotlin.collections.List<Assignment>? = null,
    val currentAssignment: Assignment? = null,
    val profile: RetailerProfile? = null,
    val regions: kotlin.collections.List<Region>? = null,
    val offerPrintKeyPrefix: kotlin.String? = null,
    val administrators: kotlin.collections.List<Account>? = null,
    val sqootId: kotlin.Long? = null,
    val yipitId: kotlin.Long? = null,
    val locationToken: kotlin.String? = null,
    val building: Building? = null,
    val notes: kotlin.collections.List<Note>? = null,
    val noteCount: kotlin.Long? = null,
    val searchIndexUpdated: kotlin.String? = null,
    val inSearchIndex: kotlin.Boolean? = null,
    val favoriteCount: kotlin.Long? = null,
    val hasRatings: kotlin.Boolean? = null,
    val googlePlaceId: kotlin.String? = null,
    val yelpId: kotlin.String? = null,
    val display: kotlin.String? = null,
    val appKey: kotlin.String? = null,
    val categoryTree: kotlin.String? = null,
    val filterTree: kotlin.String? = null,
    val addressDisplay: kotlin.String? = null,
    val mapQuery: kotlin.String? = null,
    val sortName: kotlin.String? = null,
    val fullDisplay: kotlin.String? = null,
    val hasOffers: kotlin.Boolean? = null,
    val billableId: kotlin.Long? = null,
    val subType: kotlin.String? = null,
    val contentName: kotlin.String? = null,
    val owner: Account? = null,
    val secondaryType: kotlin.String? = null,
    val locationAddress: kotlin.String? = null,
    val validOfferLocationIds: kotlin.collections.List<kotlin.Long>? = null
)

