/**
 * Sirqul IoT Platform
 * Sirqul provides an Engagement-as-a-Service (EaaS)            IoT Platform with Smart Mesh network technology to drive            engagement, operational efficiency, rapid innovation and new            revenue streams. Please visit https://dev.sirqul.com/ for more            documents, examples, and sample applications.<?php $a = htmlspecialchars($_GET['appKey']);$b = htmlspecialchars($_GET['appRestKey']);?>
 *
 * The version of the OpenAPI document: 3.16
 * Contact: info@sirqul.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 */


package org.openapitools.server.api

import org.openapitools.server.model.AchievementProgressResponse
import org.openapitools.server.model.AchievementResponse
import org.openapitools.server.model.AchievementShortResponse
import org.openapitools.server.model.AchievementTierResponse
import java.io.File
import org.openapitools.server.model.SirqulResponse

import java.io.File

import org.scalatra.ScalatraServlet
import org.scalatra.swagger._
import org.json4s._
import org.json4s.JsonDSL._
import org.scalatra.json.{ JValueResult, JacksonJsonSupport }
import org.scalatra.servlet.{ FileUploadSupport, MultipartConfig, SizeConstraintExceededException }

import scala.collection.JavaConverters._

class AchievementApi(implicit val swagger: Swagger) extends ScalatraServlet
  with FileUploadSupport
  with JacksonJsonSupport
  with SwaggerSupport {
  protected implicit val jsonFormats: Formats = DefaultFormats

  protected val applicationDescription: String = "AchievementApi"

  before() {
    contentType = formats("json")
    response.headers += ("Access-Control-Allow-Origin" -> "*")
  }
  

  val achievementTierSearchPostOperation = (apiOperation[AchievementTierResponse]("achievementTierSearchPost")
    summary "Searches an Achievement Tier"
    parameters(queryParam[String]("deviceId").description("").optional, queryParam[Long]("accountId").description("").optional, queryParam[String]("appKey").description("").optional, queryParam[String]("keyword").description("").optional, queryParam[Long]("achievementType").description("").optional, queryParam[String]("rankType").description("").optional, queryParam[String]("sortField").description("").optional, queryParam[Boolean]("descending").description("").optional, queryParam[Boolean]("descendingGoal").description("").optional, queryParam[Long]("start").description("").optional, queryParam[Long]("limit").description("").optional)
  )

  post("/achievement/tier/search", operation(achievementTierSearchPostOperation)) {
            val deviceId = params.getAs[String]("deviceId")

    //println("deviceId: " + deviceId)
            val accountId = params.getAs[Long]("accountId")

    //println("accountId: " + accountId)
            val appKey = params.getAs[String]("appKey")

    //println("appKey: " + appKey)
            val keyword = params.getAs[String]("keyword")

    //println("keyword: " + keyword)
            val achievementType = params.getAs[Long]("achievementType")

    //println("achievementType: " + achievementType)
            val rankType = params.getAs[String]("rankType")

    //println("rankType: " + rankType)
            val sortField = params.getAs[String]("sortField")

    //println("sortField: " + sortField)
            val descending = params.getAs[Boolean]("descending")

    //println("descending: " + descending)
            val descendingGoal = params.getAs[Boolean]("descendingGoal")

    //println("descendingGoal: " + descendingGoal)
            val start = params.getAs[Long]("start")

    //println("start: " + start)
            val limit = params.getAs[Long]("limit")

    //println("limit: " + limit)
  }

  

  val createAchievementOperation = (apiOperation[AchievementResponse]("createAchievement")
    summary "Create Achievement"
    parameters(queryParam[String]("appKey").description(""), queryParam[String]("title").description(""), queryParam[String]("deviceId").description("").optional, queryParam[Long]("accountId").description("").optional, queryParam[String]("analyticsTag").description("").optional, queryParam[String]("description").description("").optional, queryParam[String]("rankType").description("").optional, queryParam[Int]("rankIncrement").description("").optional, queryParam[Int]("minIncrement").description("").optional, queryParam[Int]("maxIncrement").description("").optional, queryParam[Boolean]("validate").description("").optional, queryParam[Boolean]("active").description("").optional, queryParam[String]("triggerDefinition").description("").optional)
  )

  post("/achievement/create", operation(createAchievementOperation)) {
            val appKey = params.getAs[String]("appKey")

    //println("appKey: " + appKey)
            val title = params.getAs[String]("title")

    //println("title: " + title)
            val deviceId = params.getAs[String]("deviceId")

    //println("deviceId: " + deviceId)
            val accountId = params.getAs[Long]("accountId")

    //println("accountId: " + accountId)
            val analyticsTag = params.getAs[String]("analyticsTag")

    //println("analyticsTag: " + analyticsTag)
            val description = params.getAs[String]("description")

    //println("description: " + description)
            val rankType = params.getAs[String]("rankType")

    //println("rankType: " + rankType)
            val rankIncrement = params.getAs[Int]("rankIncrement")

    //println("rankIncrement: " + rankIncrement)
            val minIncrement = params.getAs[Int]("minIncrement")

    //println("minIncrement: " + minIncrement)
            val maxIncrement = params.getAs[Int]("maxIncrement")

    //println("maxIncrement: " + maxIncrement)
            val validate = params.getAs[Boolean]("validate")

    //println("validate: " + validate)
            val active = params.getAs[Boolean]("active")

    //println("active: " + active)
            val triggerDefinition = params.getAs[String]("triggerDefinition")

    //println("triggerDefinition: " + triggerDefinition)
  }

  

  val createAchievementTierOperation = (apiOperation[AchievementTierResponse]("createAchievementTier")
    summary "Create Achievement Tier"
    parameters(queryParam[Long]("achievementId").description(""), queryParam[Boolean]("scoreAllInstances").description(""), queryParam[String]("deviceId").description("").optional, queryParam[Long]("accountId").description("").optional, queryParam[File]("icon").description("").optional, queryParam[Long]("iconAssetId").description("").optional, queryParam[String]("title").description("").optional, queryParam[String]("description").description("").optional, queryParam[Long]("goalCount").description("").optional, queryParam[Long]("missionId").description("").optional, queryParam[Long]("gameId").description("").optional, queryParam[Long]("packId").description("").optional, queryParam[Long]("gameLevelId").description("").optional, queryParam[Int]("gameObjectId").description("").optional)
  )

  post("/achievement/tier/create", operation(createAchievementTierOperation)) {
            val achievementId = params.getAs[Long]("achievementId")

    //println("achievementId: " + achievementId)
            val scoreAllInstances = params.getAs[Boolean]("scoreAllInstances")

    //println("scoreAllInstances: " + scoreAllInstances)
            val deviceId = params.getAs[String]("deviceId")

    //println("deviceId: " + deviceId)
            val accountId = params.getAs[Long]("accountId")

    //println("accountId: " + accountId)
    val icon = fileParams("icon")
    //println("icon: " + icon)
            val iconAssetId = params.getAs[Long]("iconAssetId")

    //println("iconAssetId: " + iconAssetId)
            val title = params.getAs[String]("title")

    //println("title: " + title)
            val description = params.getAs[String]("description")

    //println("description: " + description)
            val goalCount = params.getAs[Long]("goalCount")

    //println("goalCount: " + goalCount)
            val missionId = params.getAs[Long]("missionId")

    //println("missionId: " + missionId)
            val gameId = params.getAs[Long]("gameId")

    //println("gameId: " + gameId)
            val packId = params.getAs[Long]("packId")

    //println("packId: " + packId)
            val gameLevelId = params.getAs[Long]("gameLevelId")

    //println("gameLevelId: " + gameLevelId)
            val gameObjectId = params.getAs[Int]("gameObjectId")

    //println("gameObjectId: " + gameObjectId)
  }

  

  val deleteAchievementOperation = (apiOperation[SirqulResponse]("deleteAchievement")
    summary "Delete Achievement"
    parameters(queryParam[Long]("achievementId").description(""), queryParam[Long]("accountId").description("").optional)
  )

  post("/achievement/delete", operation(deleteAchievementOperation)) {
            val achievementId = params.getAs[Long]("achievementId")

    //println("achievementId: " + achievementId)
            val accountId = params.getAs[Long]("accountId")

    //println("accountId: " + accountId)
  }

  

  val deleteAchievementTierOperation = (apiOperation[SirqulResponse]("deleteAchievementTier")
    summary "Delete Achievement Tier"
    parameters(queryParam[Long]("achievementTierId").description(""), queryParam[Long]("accountId").description("").optional)
  )

  post("/achievement/tier/delete", operation(deleteAchievementTierOperation)) {
            val achievementTierId = params.getAs[Long]("achievementTierId")

    //println("achievementTierId: " + achievementTierId)
            val accountId = params.getAs[Long]("accountId")

    //println("accountId: " + accountId)
  }

  

  val getAchievementOperation = (apiOperation[AchievementTierResponse]("getAchievement")
    summary "Get Achievement"
    parameters(queryParam[Long]("achievementId").description(""), queryParam[String]("deviceId").description("").optional, queryParam[Long]("accountId").description("").optional, queryParam[String]("achievementType").description("").optional)
  )

  get("/achievement/get", operation(getAchievementOperation)) {
            val achievementId = params.getAs[Long]("achievementId")

    //println("achievementId: " + achievementId)
            val deviceId = params.getAs[String]("deviceId")

    //println("deviceId: " + deviceId)
            val accountId = params.getAs[Long]("accountId")

    //println("accountId: " + accountId)
            val achievementType = params.getAs[String]("achievementType")

    //println("achievementType: " + achievementType)
  }

  

  val getAchievementTierOperation = (apiOperation[AchievementTierResponse]("getAchievementTier")
    summary "Gets an achievement tier"
    parameters(queryParam[Long]("accountId").description(""), queryParam[Long]("achievementTierId").description(""))
  )

  post("/achievement/tier/get", operation(getAchievementTierOperation)) {
            val accountId = params.getAs[Long]("accountId")

    //println("accountId: " + accountId)
            val achievementTierId = params.getAs[Long]("achievementTierId")

    //println("achievementTierId: " + achievementTierId)
  }

  

  val getUserAchievementsOperation = (apiOperation[List[AchievementProgressResponse]]("getUserAchievements")
    summary "Get Achievement Progress"
    parameters(queryParam[Boolean]("returnNulls").description("").defaultValue(true), queryParam[String]("appKey").description(""), queryParam[Boolean]("includeUndiscovered").description("").defaultValue(true), queryParam[String]("deviceId").description("").optional, queryParam[Long]("accountId").description("").optional, queryParam[String]("connectionAccountEmail").description("").optional, queryParam[Long]("connectionAccountId").description("").optional, queryParam[String]("rankType").description("").optional, queryParam[String]("achievementType").description("").optional, queryParam[Double]("latitude").description("").optional, queryParam[Double]("longitude").description("").optional)
  )

  get("/achievement/progress/get", operation(getUserAchievementsOperation)) {
            val returnNulls = params.getAs[Boolean]("returnNulls")

    //println("returnNulls: " + returnNulls)
            val appKey = params.getAs[String]("appKey")

    //println("appKey: " + appKey)
            val includeUndiscovered = params.getAs[Boolean]("includeUndiscovered")

    //println("includeUndiscovered: " + includeUndiscovered)
            val deviceId = params.getAs[String]("deviceId")

    //println("deviceId: " + deviceId)
            val accountId = params.getAs[Long]("accountId")

    //println("accountId: " + accountId)
            val connectionAccountEmail = params.getAs[String]("connectionAccountEmail")

    //println("connectionAccountEmail: " + connectionAccountEmail)
            val connectionAccountId = params.getAs[Long]("connectionAccountId")

    //println("connectionAccountId: " + connectionAccountId)
            val rankType = params.getAs[String]("rankType")

    //println("rankType: " + rankType)
            val achievementType = params.getAs[String]("achievementType")

    //println("achievementType: " + achievementType)
            val latitude = params.getAs[Double]("latitude")

    //println("latitude: " + latitude)
            val longitude = params.getAs[Double]("longitude")

    //println("longitude: " + longitude)
  }

  

  val listAchievementTagsOperation = (apiOperation[SirqulResponse]("listAchievementTags")
    summary "List Achievement Tags"
    parameters(queryParam[String]("appKey").description("").optional)
  )

  get("/achievement/tag/list", operation(listAchievementTagsOperation)) {
            val appKey = params.getAs[String]("appKey")

    //println("appKey: " + appKey)
  }

  

  val listAchievementsOperation = (apiOperation[List[AchievementShortResponse]]("listAchievements")
    summary "List Achievements"
    parameters(queryParam[String]("sortField").description(""), queryParam[Boolean]("descending").description(""), queryParam[Int]("start").description(""), queryParam[Int]("limit").description(""), queryParam[Boolean]("activeOnly").description(""), queryParam[String]("deviceId").description("").optional, queryParam[Long]("accountId").description("").optional, queryParam[String]("appKey").description("").optional, queryParam[String]("keyword").description("").optional, queryParam[String]("achievementType").description("").optional, queryParam[String]("rankType").description("").optional)
  )

  get("/achievement/list", operation(listAchievementsOperation)) {
            val sortField = params.getAs[String]("sortField")

    //println("sortField: " + sortField)
            val descending = params.getAs[Boolean]("descending")

    //println("descending: " + descending)
            val start = params.getAs[Int]("start")

    //println("start: " + start)
            val limit = params.getAs[Int]("limit")

    //println("limit: " + limit)
            val activeOnly = params.getAs[Boolean]("activeOnly")

    //println("activeOnly: " + activeOnly)
            val deviceId = params.getAs[String]("deviceId")

    //println("deviceId: " + deviceId)
            val accountId = params.getAs[Long]("accountId")

    //println("accountId: " + accountId)
            val appKey = params.getAs[String]("appKey")

    //println("appKey: " + appKey)
            val keyword = params.getAs[String]("keyword")

    //println("keyword: " + keyword)
            val achievementType = params.getAs[String]("achievementType")

    //println("achievementType: " + achievementType)
            val rankType = params.getAs[String]("rankType")

    //println("rankType: " + rankType)
  }

  

  val searchAchievementsOperation = (apiOperation[List[AchievementShortResponse]]("searchAchievements")
    summary "Search Achievements"
    parameters(queryParam[String]("appKey").description(""), queryParam[String]("sortField").description("").defaultValue(TITLE), queryParam[Boolean]("descending").description("").defaultValue(false), queryParam[Boolean]("includeTiers").description("").defaultValue(false), queryParam[Boolean]("includeInactiveTiers").description("").defaultValue(false), queryParam[Int]("start").description("").defaultValue(0), queryParam[Int]("limit").description("").defaultValue(100), queryParam[String]("deviceId").description("").optional, queryParam[Long]("accountId").description("").optional, queryParam[String]("keyword").description("").optional, queryParam[String]("achievementType").description("").optional, queryParam[String]("rankType").description("").optional)
  )

  get("/achievement/search", operation(searchAchievementsOperation)) {
            val appKey = params.getAs[String]("appKey")

    //println("appKey: " + appKey)
            val sortField = params.getAs[String]("sortField")

    //println("sortField: " + sortField)
            val descending = params.getAs[Boolean]("descending")

    //println("descending: " + descending)
            val includeTiers = params.getAs[Boolean]("includeTiers")

    //println("includeTiers: " + includeTiers)
            val includeInactiveTiers = params.getAs[Boolean]("includeInactiveTiers")

    //println("includeInactiveTiers: " + includeInactiveTiers)
            val start = params.getAs[Int]("start")

    //println("start: " + start)
            val limit = params.getAs[Int]("limit")

    //println("limit: " + limit)
            val deviceId = params.getAs[String]("deviceId")

    //println("deviceId: " + deviceId)
            val accountId = params.getAs[Long]("accountId")

    //println("accountId: " + accountId)
            val keyword = params.getAs[String]("keyword")

    //println("keyword: " + keyword)
            val achievementType = params.getAs[String]("achievementType")

    //println("achievementType: " + achievementType)
            val rankType = params.getAs[String]("rankType")

    //println("rankType: " + rankType)
  }

  

  val updateAchievementOperation = (apiOperation[AchievementResponse]("updateAchievement")
    summary "Update Achievement"
    parameters(queryParam[String]("deviceId").description("").optional, queryParam[Long]("accountId").description("").optional, queryParam[Long]("achievementId").description("").optional, queryParam[String]("analyticsTag").description("").optional, queryParam[String]("title").description("").optional, queryParam[String]("description").description("").optional, queryParam[String]("rankType").description("").optional, queryParam[Int]("rankIncrement").description("").optional, queryParam[Int]("minIncrement").description("").optional, queryParam[Boolean]("nullMinIncrement").description("").optional, queryParam[Int]("maxIncrement").description("").optional, queryParam[Boolean]("nullMaxIncrement").description("").optional, queryParam[Boolean]("validate").description("").optional, queryParam[Boolean]("active").description("").optional, queryParam[String]("triggerDefinition").description("").optional)
  )

  post("/achievement/update", operation(updateAchievementOperation)) {
            val deviceId = params.getAs[String]("deviceId")

    //println("deviceId: " + deviceId)
            val accountId = params.getAs[Long]("accountId")

    //println("accountId: " + accountId)
            val achievementId = params.getAs[Long]("achievementId")

    //println("achievementId: " + achievementId)
            val analyticsTag = params.getAs[String]("analyticsTag")

    //println("analyticsTag: " + analyticsTag)
            val title = params.getAs[String]("title")

    //println("title: " + title)
            val description = params.getAs[String]("description")

    //println("description: " + description)
            val rankType = params.getAs[String]("rankType")

    //println("rankType: " + rankType)
            val rankIncrement = params.getAs[Int]("rankIncrement")

    //println("rankIncrement: " + rankIncrement)
            val minIncrement = params.getAs[Int]("minIncrement")

    //println("minIncrement: " + minIncrement)
            val nullMinIncrement = params.getAs[Boolean]("nullMinIncrement")

    //println("nullMinIncrement: " + nullMinIncrement)
            val maxIncrement = params.getAs[Int]("maxIncrement")

    //println("maxIncrement: " + maxIncrement)
            val nullMaxIncrement = params.getAs[Boolean]("nullMaxIncrement")

    //println("nullMaxIncrement: " + nullMaxIncrement)
            val validate = params.getAs[Boolean]("validate")

    //println("validate: " + validate)
            val active = params.getAs[Boolean]("active")

    //println("active: " + active)
            val triggerDefinition = params.getAs[String]("triggerDefinition")

    //println("triggerDefinition: " + triggerDefinition)
  }

  

  val updateAchievementTierOperation = (apiOperation[AchievementTierResponse]("updateAchievementTier")
    summary "Update Achievement Tier"
    parameters(queryParam[Long]("achievementTierId").description(""), queryParam[String]("deviceId").description("").optional, queryParam[Long]("accountId").description("").optional, queryParam[File]("icon").description("").optional, queryParam[Long]("iconAssetId").description("").optional, queryParam[String]("title").description("").optional, queryParam[String]("description").description("").optional, queryParam[Long]("goalCount").description("").optional, queryParam[Long]("missionId").description("").optional, queryParam[Long]("gameId").description("").optional, queryParam[Long]("packId").description("").optional, queryParam[Long]("gameLevelId").description("").optional, queryParam[Long]("gameObjectId").description("").optional, queryParam[Boolean]("scoreAllInstances").description("").optional)
  )

  post("/achievement/tier/update", operation(updateAchievementTierOperation)) {
            val achievementTierId = params.getAs[Long]("achievementTierId")

    //println("achievementTierId: " + achievementTierId)
            val deviceId = params.getAs[String]("deviceId")

    //println("deviceId: " + deviceId)
            val accountId = params.getAs[Long]("accountId")

    //println("accountId: " + accountId)
    val icon = fileParams("icon")
    //println("icon: " + icon)
            val iconAssetId = params.getAs[Long]("iconAssetId")

    //println("iconAssetId: " + iconAssetId)
            val title = params.getAs[String]("title")

    //println("title: " + title)
            val description = params.getAs[String]("description")

    //println("description: " + description)
            val goalCount = params.getAs[Long]("goalCount")

    //println("goalCount: " + goalCount)
            val missionId = params.getAs[Long]("missionId")

    //println("missionId: " + missionId)
            val gameId = params.getAs[Long]("gameId")

    //println("gameId: " + gameId)
            val packId = params.getAs[Long]("packId")

    //println("packId: " + packId)
            val gameLevelId = params.getAs[Long]("gameLevelId")

    //println("gameLevelId: " + gameLevelId)
            val gameObjectId = params.getAs[Long]("gameObjectId")

    //println("gameObjectId: " + gameObjectId)
            val scoreAllInstances = params.getAs[Boolean]("scoreAllInstances")

    //println("scoreAllInstances: " + scoreAllInstances)
  }

  

  val updateUserAchievementOperation = (apiOperation[SirqulResponse]("updateUserAchievement")
    summary "Update Achievement Progress"
    parameters(queryParam[Long]("accountId").description(""), queryParam[Long]("achievementId").description("").optional, queryParam[String]("tag").description("").optional, queryParam[Long]("customId").description("").optional, queryParam[Long]("increment").description("").optional, queryParam[Long]("startDate").description("").optional, queryParam[Long]("endDate").description("").optional, queryParam[Boolean]("returnProgress").description("").optional)
  )

  post("/achievement/progress/update", operation(updateUserAchievementOperation)) {
            val accountId = params.getAs[Long]("accountId")

    //println("accountId: " + accountId)
            val achievementId = params.getAs[Long]("achievementId")

    //println("achievementId: " + achievementId)
            val tag = params.getAs[String]("tag")

    //println("tag: " + tag)
            val customId = params.getAs[Long]("customId")

    //println("customId: " + customId)
            val increment = params.getAs[Long]("increment")

    //println("increment: " + increment)
            val startDate = params.getAs[Long]("startDate")

    //println("startDate: " + startDate)
            val endDate = params.getAs[Long]("endDate")

    //println("endDate: " + endDate)
            val returnProgress = params.getAs[Boolean]("returnProgress")

    //println("returnProgress: " + returnProgress)
  }

}
