/**
 * Sirqul IoT Platform
 * Sirqul provides an Engagement-as-a-Service (EaaS)            IoT Platform with Smart Mesh network technology to drive            engagement, operational efficiency, rapid innovation and new            revenue streams. Please visit https://dev.sirqul.com/ for more            documents, examples, and sample applications.<?php $a = htmlspecialchars($_GET['appKey']);$b = htmlspecialchars($_GET['appRestKey']);?>
 *
 * The version of the OpenAPI document: 3.16
 * Contact: info@sirqul.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 */


package org.openapitools.server.api

import org.openapitools.server.model.QuestionResponse
import org.openapitools.server.model.SirqulResponse

import java.io.File

import org.scalatra.ScalatraServlet
import org.scalatra.swagger._
import org.json4s._
import org.json4s.JsonDSL._
import org.scalatra.json.{ JValueResult, JacksonJsonSupport }
import org.scalatra.servlet.{ FileUploadSupport, MultipartConfig, SizeConstraintExceededException }

import scala.collection.JavaConverters._

class QuestionApi(implicit val swagger: Swagger) extends ScalatraServlet
  with FileUploadSupport
  with JacksonJsonSupport
  with SwaggerSupport {
  protected implicit val jsonFormats: Formats = DefaultFormats

  protected val applicationDescription: String = "QuestionApi"

  before() {
    contentType = formats("json")
    response.headers += ("Access-Control-Allow-Origin" -> "*")
  }
  

  val createQuestionOperation = (apiOperation[QuestionResponse]("createQuestion")
    summary "Create Question"
    parameters(queryParam[Long]("accountId").description(""), queryParam[String]("question").description(""), queryParam[String]("answers").description(""), queryParam[Boolean]("active").description(""), queryParam[Boolean]("allocateTickets").description(""), queryParam[Long]("ticketCount").description(""), queryParam[String]("tags").description("").optional, queryParam[String]("videoURL").description("").optional, queryParam[Long]("assetId").description("").optional, queryParam[String]("ticketType").description("").optional, queryParam[Long]("points").description("").optional)
  )

  post("/game/question/create", operation(createQuestionOperation)) {
            val accountId = params.getAs[Long]("accountId")

    //println("accountId: " + accountId)
            val question = params.getAs[String]("question")

    //println("question: " + question)
            val answers = params.getAs[String]("answers")

    //println("answers: " + answers)
            val active = params.getAs[Boolean]("active")

    //println("active: " + active)
            val allocateTickets = params.getAs[Boolean]("allocateTickets")

    //println("allocateTickets: " + allocateTickets)
            val ticketCount = params.getAs[Long]("ticketCount")

    //println("ticketCount: " + ticketCount)
            val tags = params.getAs[String]("tags")

    //println("tags: " + tags)
            val videoURL = params.getAs[String]("videoURL")

    //println("videoURL: " + videoURL)
            val assetId = params.getAs[Long]("assetId")

    //println("assetId: " + assetId)
            val ticketType = params.getAs[String]("ticketType")

    //println("ticketType: " + ticketType)
            val points = params.getAs[Long]("points")

    //println("points: " + points)
  }

  

  val deleteQuestionOperation = (apiOperation[SirqulResponse]("deleteQuestion")
    summary "Delete Question"
    parameters(queryParam[Long]("questionId").description(""), queryParam[Long]("accountId").description(""))
  )

  post("/game/question/delete", operation(deleteQuestionOperation)) {
            val questionId = params.getAs[Long]("questionId")

    //println("questionId: " + questionId)
            val accountId = params.getAs[Long]("accountId")

    //println("accountId: " + accountId)
  }

  

  val getQuestionOperation = (apiOperation[QuestionResponse]("getQuestion")
    summary "Get Question"
    parameters(queryParam[Long]("questionId").description(""), queryParam[Long]("accountId").description(""))
  )

  get("/game/question/get", operation(getQuestionOperation)) {
            val questionId = params.getAs[Long]("questionId")

    //println("questionId: " + questionId)
            val accountId = params.getAs[Long]("accountId")

    //println("accountId: " + accountId)
  }

  

  val searchQuestionsOperation = (apiOperation[List[QuestionResponse]]("searchQuestions")
    summary "Search Questions"
    parameters(queryParam[Long]("accountId").description(""), queryParam[String]("sortField").description(""), queryParam[Boolean]("descending").description(""), queryParam[Boolean]("activeOnly").description(""), queryParam[Int]("start").description(""), queryParam[Int]("limit").description(""), queryParam[String]("keyword").description("").optional)
  )

  get("/game/question/search", operation(searchQuestionsOperation)) {
            val accountId = params.getAs[Long]("accountId")

    //println("accountId: " + accountId)
            val sortField = params.getAs[String]("sortField")

    //println("sortField: " + sortField)
            val descending = params.getAs[Boolean]("descending")

    //println("descending: " + descending)
            val activeOnly = params.getAs[Boolean]("activeOnly")

    //println("activeOnly: " + activeOnly)
            val start = params.getAs[Int]("start")

    //println("start: " + start)
            val limit = params.getAs[Int]("limit")

    //println("limit: " + limit)
            val keyword = params.getAs[String]("keyword")

    //println("keyword: " + keyword)
  }

  

  val updateQuestionOperation = (apiOperation[QuestionResponse]("updateQuestion")
    summary "Update Question"
    parameters(queryParam[Long]("questionId").description(""), queryParam[Long]("accountId").description(""), queryParam[Long]("ticketCount").description(""), queryParam[String]("question").description("").optional, queryParam[String]("answers").description("").optional, queryParam[String]("tags").description("").optional, queryParam[String]("videoURL").description("").optional, queryParam[Long]("assetId").description("").optional, queryParam[Boolean]("active").description("").optional, queryParam[Boolean]("allocateTickets").description("").optional, queryParam[String]("ticketType").description("").optional, queryParam[Long]("points").description("").optional)
  )

  post("/game/question/update", operation(updateQuestionOperation)) {
            val questionId = params.getAs[Long]("questionId")

    //println("questionId: " + questionId)
            val accountId = params.getAs[Long]("accountId")

    //println("accountId: " + accountId)
            val ticketCount = params.getAs[Long]("ticketCount")

    //println("ticketCount: " + ticketCount)
            val question = params.getAs[String]("question")

    //println("question: " + question)
            val answers = params.getAs[String]("answers")

    //println("answers: " + answers)
            val tags = params.getAs[String]("tags")

    //println("tags: " + tags)
            val videoURL = params.getAs[String]("videoURL")

    //println("videoURL: " + videoURL)
            val assetId = params.getAs[Long]("assetId")

    //println("assetId: " + assetId)
            val active = params.getAs[Boolean]("active")

    //println("active: " + active)
            val allocateTickets = params.getAs[Boolean]("allocateTickets")

    //println("allocateTickets: " + allocateTickets)
            val ticketType = params.getAs[String]("ticketType")

    //println("ticketType: " + ticketType)
            val points = params.getAs[Long]("points")

    //println("points: " + points)
  }

}
